### ISSUE TITLE
settings to run only *.ts tests

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#111]
<b>ctaggart[CodePlex]</b> <br />I really like the TypeScript support and the integration with Test Explorer. The Run All in the Test Explorer is picking up the generated
.js files. I'd like to have it ignore them and only run the .ts files. Web Essentials is installed and creating the .js and .min.js files when I save. As a work-a-round I've configured it not to generate those files for now.

**Comment by pushkin-** [comment]
@mmanela  Looks like the comments were deleted. What setting are you referring to?

**Comment by pushkin-** [comment]
@mmanela Following up, what is the setting that you're referring to that makes chutzpah only run .ts files?

**Comment by mmanela** [comment]
You just need to set the path spec in the Includes setting to look for just *.ts file.
