### ISSUE TITLE
Support for node.js serverside code

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#136]
<b>Aarne[CodePlex]</b> <br />When developing both server-side and client-side code in the same project it will be a great advancement to be able to run jasmine unit tests for both in visual studio.

Currently client-side tests can be executed in VS but the server-side tests need to be executed manually using .\node_modules.bin\jasmine-node .\tests
/// ltreference path=quotjasmine.d.tsquot /gt
/// ltreference path=quotnode.d.tsquot /gt

import http = require('http');

describe(quotHttp status codequot, () =gt {
    it(quot200 is OKquot, () =gt {
        expect(http.STATUS_CODES[200]).toEqual('OK');
    });
});

**Comment by forivall** [comment]
Possible starting point for anyone who would want to write a PR: https://github.com/jgordon615/NodeUnitTestAdapter
