### ISSUE TITLE
Support for HTML template imports

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#138]
<b>mmanela[CodePlex]</b> <br />We use external template files all the time for things like jQuery widgets etc. and needed to add support to include these so that we could test rendering. The code it fairly simple but in a nutshell you include a quotnewquot xml comment type:

/// lttemplate path=quotsome.tmpl.htmlquot/gt 

The contents of that file look like: 

ltscript id=quottemplateIdquot type=quottext/htmlquotgt...lt/scriptgt

Chutspah will then read the contents of some.tmpl.html file and insert into the head before any of the JS Files. this will give you something that looks like:

lt!DOCTYPE htmlgtlthtmlgtltheadgt 
ltscript type=quottext/javascriptquot src=quotfile:///TestFiles/qunit.jsquotgtlt/scriptgt

ltlink rel=quotstylesheetquot type=quottext/cssquot href=quotfile:///TestFiles/qunit.cssquot/gt

ltscript id=quottemplateIdquot type=quottext/htmlquotgt...lt/scriptgt

ltscript type=quottext/javascriptquot src=quotfile:///path/references.jsquotgtlt/scriptgt

ltscript type=quottext/javascriptquot src=quotfile:///path/test.jsquotgtlt/scriptgt

lt/headgt 
ltbodygtltdiv id=quotqunit-fixturequotgtlt/divgtlt/bodygtlt/htmlgt

**Comment by EvanWinstanley** [comment]
Another alternative solution, which replicates what [karma-ng-html2js-preprocessor](https://github.com/karma-runner/karma-ng-html2js-preprocessor). See StackOverflow answer here http://stackoverflow.com/a/28554489/11019

I like this approach as it keeps the test files clean. If you specify all your settings in chutzpah.json it is possible to keep your tests independent of the test-runner being used. I have a set of test files that can be run using either Karma or Chutzpah (or conceivably any other test-runner).
