### ISSUE TITLE
Running tests in IDE fails but in browser it passes. 

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#189]
<b>davidhanson90[CodePlex]</b> <br />I have written some tests in typescript which run fine when I view them in the browser mode but fail inside of the visual studio IDE. The test looks like this

/// ltreference path=quotlibs.jsquot /gt
/// ltreference path=quotScripts/typings/qunit/qunit.d.tsquot /gt
/// ltreference path=quot../AngularJs/app/framework/http/endpointsService.tsquot /gt

test(quotQUnit - Test 2quot, () =gt {

    var endpointService = new Framework.Http.EndpointService();
    var endPoint: Framework.Contracts.IEndpoint;

    endpointService.getEndpointAsync(quotProductsquot)
        .subscribe(result =gt { endPoint = result; });
                    
    ok(endPoint !== null, quotEndpoint should not be nullquot);
    ok(endPoint.url !== null, quotEndpoint should have a url valuequot);
});
The libs.js is all the dependencies I need for my test and looks like this
/// ltreference path=quot../AngularJs/libs/jquery/js/jquery.jsquot /gt
/// ltreference path=quot../AngularJs/libs/rxJs/js/rx-lite.jsquot /gt
/// ltreference path=quot../AngularJs/libs/underscore/js/underscore.jsquot /gt
/// ltreference path=quot../AngularJs/libs/angularJs/js/angular.jsquot /gt
/// ltreference path=quot../AngularJs/libs/angularJs/js/angular-route.jsquot /gt
The error I get in the ide when I run this is the following. 

------ Test started: File: C:\MSDE\TypeScript\AngularJs.Tests\qunit-example-tests.ts ------

Test 'QUnit - Test 2' failed
Died on test #1     at 
at file:/ 'undefined' is not a function (evaluating 'observer.onError.bind(observer)')
in qunit-example-tests.ts (line 9) 

1 passed, 1 failed, 2 total (chutzpah). 

========== Total Tests: 1 passed, 1 failed, 2 total ========== 

its like the IDE tests don't pick up the references correctly.

**Comment by bofirial** [comment]
Anything using Function.prototype.bind is failing for me.  I was able to get it working by including a polyfill in my test. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)

Here are some tests that I created to show the issue:

https://gist.github.com/bofirial/88f8300c8bf62436767b

**Comment by mmanela** [comment]
I just upgraded to Phantom2.0 and that will fix this.

**Comment by mmanela** [comment]
The new version of Phantom will be included in the 4.0 release

**Comment by pachumon** [comment]
i am having this same issue with vanilla javascript test implementation , i fact i tried to execute the test with sample html and js as in quint homepage but still the test runner in visual studio gives the below error 

1.Died on test #1: Unable to get property 'ok' of undefined or null reference - { "description": "Unable to get property 'ok' of undefined or null reference", "number": -2146823281, "stack": "TypeError: Unable to get property 'ok' of undefined or null reference at Anonymous function (http://localhost:55938/Tests.js:12:5) at Test.prototype.run (http://localhost:55938/qunit.js:101:4) at Anonymous function (http://localhost:55938/qunit.js:219:5) at process (http://localhost:55938/qunit.js:831:4) at Anonymous function (http://localhost:55938/qunit.js:395:5)" }

**Comment by Nixen85** [comment]
This should be reopened. I have the same issue like pachumon.

Error: Test 'image_adj exists' failed
	Died on test #1 global code@file:///C: ...: Can't find variable: image_adj Expected: undefined, Actual: null

On browser it passes...
