### ISSUE TITLE
Show output of console.log in VS test adapter as well as context menu runner

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#193]
<b>mthamilton[CodePlex]</b> <br />I saw this discussion: 
https://chutzpah.codeplex.com/discussions/458513 requesting the same thing, but I don't think anything ever came from it. It'd be nice if the VS test adapter as well as the context menu runner could capture console.log messages. The adapter could show it
 in the test result pane and the other runner could show in the Output pane. This feature would significantly cut down on the number of times I need to run tests in the browser, which is a bit more time consuming.

**Comment by rschiefer** [comment]
I see the log output in the Text Output window but not in the Test Explorer details window after clicking on an individual test.  I would like to see the log output for both passing and failed tests.  Is this possible?
