### ISSUE TITLE
Packaging the testadapter dll with chutzpah

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#196]
<b>movereem[CodePlex]</b> <br />The new 3.0.1 download does not include the testadapter.dll pre-build. However, using the new dlls with the old testadapter.dll does not work (tfs build stops finding the tests). Building the testadapter.dll myself solves the issue. Can you package the
 dll along with the others, or provide a separate build for new versions?

**Comment by bdukes** [comment]
See https://github.com/xunit/visualstudio.xunit and https://www.nuget.org/packages/xunit.runner.visualstudio for a method of automatically including the test runner via NuGet.  This makes Visual Studio and, especially, TFS integration much simpler.

**Comment by mmanela** [comment]
It doesn't work with Chutzpah since Chutzpah needs a test container discoverer which is not supported for nuget integration unfortunately.

**Comment by mmanela** [comment]
Also, I do package the test adapter dll now which helps in build support

**Comment by overeemm** [comment]
Thanks :) /cc @johan-gorter
