### ISSUE TITLE
Support for nunit test files

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#206]
<b>middlemarsh29[CodePlex]</b> <br />The Chutzpah console app supports the quot/junitquot option. 

Would be nice to support the output of nunit result files. 

I understand you can publish results using the xunit publisher in jenkins but there are other test framework result formats other than junit.

**Comment by davidroberts63** [comment]
I have a need for this and would like to work on it for you. Do you have any objections or major points that you want me to keep in mind?

I was thinking of just making a SummaryTransformer just like the JUnitXmlTransformer but to output NUnit results files.

I was also thinking of a way to allow for people to provide their own transformers and then dynamically load them (inject dependency) at run time to keep from having to release new Chutzpah versions, but that's a much larger task and I only mention it as something to think about.

**Comment by mmanela** [comment]
1. Sounds great about picking it up. It shouldn't be to hard and you are right to just follow the existing transformers.

2. I have thought about those types of ideas before, not just for this feature but for other user asks. The thing that stopped me was lack of demand. Requests like this come in slow and usually it worked enough to just take a PR and update the product.

**Comment by davidroberts63** [comment]
Excellent. I'm well on the way to it. I will send a PR in a day or two. It's working at the moment but I still need to put in Unit Tests and I'm going to try to make it work with the TestGroups instead of just TestFile -> [TestCase]

https://github.com/davidroberts63/chutzpah/tree/NUnitResults

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.
