### ISSUE TITLE
An exception occurred while invoking executor 'executor://chutzpah-js/': Unable to find headless browser: phantomjs.exe

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#236]
<b>ycrumeyrolle[CodePlex]</b> <br />I have the following error message : 
An exception occurred while invoking executor 'executor://chutzpah-js/': Unable to find headless browser: phantomjs.exe

This occurs when I start a build with Chutzpah test runner from TFS2013. 

If I restart the build controller, it seems to works again.

**Comment by stachu** [comment]
I have the same problem. I'm using TFS 2012 and latest chutzpah. Restarting TFS service helps but after a few builds/days the problem returns.
Any suggestion?

**Comment by mmanela** [comment]
I have no idea currently on this one. I have never been able to repro and don't have an idea why this happens.

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.
