### ISSUE TITLE
Incorrect total of unit-tests

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#243]
<b>Toendra[CodePlex]</b> <br />We had some trouble with running the unit-tests in our Test explorer and our CI server. The test count was each time different. After searching we found out that not all Javascript tests were found or did not run at all.

We have an idea how it can be possible some tests cant be found. When running the tests with PhantomJS the result will be the testname together with a random key based on the expectations. It could be possible that testnames are duplicate and not shown (and
 counted / run) anymore. 
We changed the output of the test result to unique names, after that we have no problems anymore with an incorrect count.

Can this be fixed in Chutzpah too?

**Comment by StacyJCarlos** [comment]
I believe I have encountered the same issue in my solution with two tests that are not in the same file.

1. Created a .spec.js file with a test with contents similar to:
<pre><code>describe('test class A', function () {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;it('duplicate test name', function () {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//some code with expects
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
});
</pre></code>

2. Created another .spec.js file within the same directory as the first with contents similar to:
<pre><code>describe('test class B:', function () {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;it('duplicate test name', function () {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//some code with expects
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
});
</pre></code>

3. Attempted to run the test in the Test Explorer in Visual Studio. (I am using VS2013 if that matters)

The results for me are that both tests appear in the Test Explorer, except whenever class B tests that share a name with a test in class A are run, the class A test will execute instead. Additionally, all references for class B tests that share names with class A tests,  point to locations in the class A .spec file.

I was able to remedy this problem in separate, yet non-ideal ways. The first being to change the name of the tests. This seems like a reasonable solution, however there are several hundred tests that would have to change and names are reused to show comparisons between the tests for out controllers. The second solution was to add <code>localStorage.clear()</code> to a beforeEach for every test class. This also poses a number of issues.

It is also worth noting that these test classes run perfectly fine when run separately outside the Test Explorer via the "Run JS Tests" or "Open in browser" options.

**Comment by mmanela** [comment]
@StacyJCarlos Can you provide me with a git repo that reproduces this issue?

**Comment by StacyJCarlos** [comment]
Sorry for the delay. 

I have made a <a href="https://github.com/StacyJCarlos/ChutzpahBugTester.git">GitHub repo</a> that displays this behavior. It's a rather sloppy repo so I apologize in advance.

**Comment by StacyJCarlos** [comment]
After looking into this further. I have noticed that this only happens with long test names.
