### ISSUE TITLE
Chutzpah not handling nested require.js calls

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#253]
<b>khelmar[CodePlex]</b> <br />When a project has multiple nested require.js calls Chutzpah is not correctly receiving tests results from QUnit.

See discussion thread here: 
https://chutzpah.codeplex.com/discussions/545270#post1261193

The propose solution is for Chutzpah to provide a callback for the user to call to tell when its ready for Chutzpah to start running tests.

**Comment by philipooo** [comment]
The Codeplex discussion link seems to be dead.
Maybe I recently hit the same problem by using the following pattern.

	define([
		"exclusions-test-1" /* Contains require.config map-Section to prevent loading some sort of fakes. */
	], function () {

		require([ "testdependency-1", "testdependency-2" ], function(testdependency1, testdependency2) {

			asyncTest("...", 1, function () {
				
				start();
				
			});

		});

	});

**Comment by mmanela** [comment]
Can you provide me a full repro (upload to github) that I can clone and test with?

**Comment by philipooo** [comment]
I tried to setup a repro. But repro works... so there must be some other issue ;) I let you know.

**Comment by philipooo** [comment]
I set up a repro.
> When removing jquery from dep1.js it works (1 test was found) otherwise (0 test was found)

https://github.com/philipooo/chutzpah_issue

**Comment by mmanela** [comment]
Thanks, 
I can repro and I am still looking if there is a great solution. Ideally, this should just work but the problem is Chutzpah is listening for the QUnit events and Chutzpah finishes when the FileDone event is fired. The problem is when you have nested require calls the FileDone call fires before the test file ever gets loaded. The reason it works in the browser is that the FileDone event finishes but the browser stays open and eventually Qunit detects the next test being registered. 

I am open to ideas but the only one I can think of it to add a hook (as mentioned above) where you tell Chutzpah to WAIT before finishing and require the user to tell Chutzpah deterministically when it should finish. This feels kinda gross and I hate people changing tests specifically for Chutzpah.

Thoughts?

**Comment by mmanela** [comment]
Chutzpah 4.2.2 contains a fix to this issue 

Take a look at https://github.com/mmanela/chutzpah/tree/master/Facts.Integration/JS/Test/ManualAmdStart/Jasmine-ManualStart

Specifically: https://github.com/mmanela/chutzpah/blob/master/Facts.Integration/JS/Test/ManualAmdStart/Jasmine-ManualStart/config.js


You will notice two calls, one to preventAmdAutoStart. You need to call this as early as you can to tell Chutzpah to not run. Then a call to amdStart when you are ready for it to run.

```
window.chutzpah.preventAmdAutoStart();

setTimeout(function() {
  require.config({
      
      paths: {
          hello: 'base/jquery.hello',
      },

      shim: {
          hello: { deps: ["jquery"] },
      }
  });
  
  window.chutzpah.amdStart();
}, 500);
```
