### ISSUE TITLE
Support running multiple test files in same harness

### ISSUE THREAD

**Issue by Pablissimo** [mmanela/chutzpah#281]
It appears as though each test file gets its own harness built and own instance of phantomjs spun up to run its contents, which means that the amount of time running tests is dwarfed by the time spent spinning up and down that infrastructure.

Propose an option in chutzpah.json to include multiple test files per harness, off by default as lack of a fresh environment for each set of tests might break tests that aren't able to clean up after themselves.

Rought perf example on my local machine (4 core/8 thread, Core i7-3632QM @ 2.20GHz), ~800 tests over 78 files:

<table>
<thead><tr><th>Setup</th><th>Test run duration</th></tr></thead>
<tbody>
<tr><td>1 thread, all test JS files bundled into one (simulation of proposed change)</td><td>9s</td></tr>
<tr><td>Max parallelism (8 threads), individual files</td><td>28s</td></tr>
<tr><td>Min parallelism (1 thread), individual files</td><td>1m20s</td></tr>
</tbody>
</table>

Could get more advanced and split test file set by degree of parallelism (i.e. in above case 8 sets of about 10 files each) but this actually runs *slower* than simply firing everything through one thread.

Anecdotally, above 1-big-test-file runs at about 15% CPU on one core while max-parallelism lots-of-test-files maxes out all cores.

(nb will look at creating a pull request for this when I find time!)

Thanks for the hard work on Chutzpah!

**Comment by mmanela** [comment]
As of Chutzpah 4, you can use the EnableTestFileBatching setting in chutzpah.json file to batch all files that settings file consumes.
