### ISSUE TITLE
Setup automated build step in TeamCity

### ISSUE THREAD

**Issue by SuneRadich** [mmanela/chutzpah#291]
I can read in blog posts and the documentation, that Chutzpah supports building and reporting via TeamCity. I however cant find any information on how to set this up.

Bare with me, I am quite new to .NET, Visual Studio and TeamCity, Im a frontender :)

I have tried to manually add the package in packages.config in my Web project

```
  <package id="Chutzpah" version="3.2.5" targetFramework="net451" />
```

And by doing this, I would have imagined that TeamCity would install the package and enable me to use a commandline build step to run a command line 

```
chutzpah.console.exe ./Test/tests
```

Running this command in Visual Studio runs all my tests fine. But when I look at the TeamCity build log. I can see that it fails on this step, with a 

```
[Step 3/6] Starting: C:\Windows\system32\cmd.exe /c chutzpah.console.exe ./Test/tests
[15:50:34][Step 3/6] in directory: E:\Build\Web\Test
[15:50:34][Step 3/6] 'chutzpah.console.exe' is not recognized as an internal or external command,
[15:50:34][Step 3/6] operable program or batch file.
[15:50:34][Step 3/6] Process exited with code 1
```

This seems to me that the commandline tool is not installed automatically. How can I make sure the command line tool is installed on my TeamCity build agent?

Am I going about this in the right way, is there an easier way to enable Chutzpah in my TeamCity build?

**Comment by saroj08** [comment]
Hi,
i read the above blogs but didn't find any way to run my tests through command.
can you please suggest me the steps to execute my tests through command prompt.chutzpah installed in my visual studio2015 and there it running fine but i want it from command and also with ms build process.
Regards

**Comment by Zelig880** [comment]
Hi Saroj,

I have actually just finished to implement Chutzpah on team city and I am
happy to share my knowledge with you.

To be able to run Chutzpah from the console, you need to know the
installation path and the location of the chutzpah.console.exe file.

When you have a way to find it, you can run the following command:

*Example POWERSHELL*

& ".\CHUTZPAH INSTALLATION\chutzpah.console.exe" ".\folder, file or
chutzpah.json location"

*Example **COMMAND LINE*

CHUTZPAH INSTALLATION\chutzpah.console "folder, file or chutzpah.json
location"

A full list of command line helper can be found here:
https://github.com/mmanela/chutzpah/wiki/command-line-options

I hope the above helps.

Simone Cuomo
www.zelig880.com

**Comment by saroj08** [comment]
Thanks for your valuable time and suggestion.
