### ISSUE TITLE
IncludeInTestHarness:false does not work for html files included via regex pattern

### ISSUE THREAD

**Issue by russplaysguitar** [mmanela/chutzpah#292]
I have the following bit in `Chutzpah.json`:

```
...
"References": [
		{"Path": "../", "Include": "*template**/*.html", "IncludeInTestHarness": "false" }
],
...
```

But my html template files are included in the test harness even though `IncludeInTestHarness` is `false`. 

Note: 
I think this is caused by the following line, which sets `IncludeInTestHarness` to `true` for any files matching `RegexPatterns.JsTemplatePathRegex`: https://github.com/mmanela/chutzpah/blob/360a23f199f2ba8c08167986d20a54344ee13a1d/Chutzpah/ReferenceProcessor.cs#L189

**Comment by mmanela** [comment]
It has been months since asking for a repro. closing for now
