### ISSUE TITLE
Exclude multiple file patterns in reference path of chutzpah.json

### ISSUE THREAD

**Issue by gonglei** [mmanela/chutzpah#294]
I did not see a way to exclude multiple file patterns in a reference path of chutzpah.json. For example, I added a reference { "Path": "Scripts", "Include": "*.js", "Exclude": "*.min.js" }, while I'd like to exclude another pattern: "*.intellisense.js", I tried many ways without success.
It is using wildcard matching, I'd like to know is it possible to support regular expression here.

**Comment by awbergs** [comment]
I think supporting an array of inclusions / exclusions would be a good way to go on this.

**Comment by gurumusch** [comment]
I think both options would work just fine for us. Using a Regex seems a bit more elegant to me.

**Comment by tlycken** [comment]
This seems to be fixed in 93f3d8e759e0abdf08f377d5ae8d91e50673b01c - is that assumption correct?

**Comment by mmanela** [comment]
Yes

**Comment by mmanela** [comment]
This will be released in version 4.0
