### ISSUE TITLE
Inject code coverage result into TFS 

### ISSUE THREAD

**Issue by ycrumeyrolle** [mmanela/chutzpah#300]
Today, when we run JS unit tests with Chutzaph test runner on TFS, the number of tests failed/succeed/... is stored into TFS, but not the code coverage :
![chutzpah_tfs_summary](https://cloud.githubusercontent.com/assets/1958836/5227955/af77e128-7703-11e4-8b44-9f624955944e.png)

Is it possible to have the code coverage from JS like with the C# code ?

It wiil be great to have the same behavior between C# & JS code.

**Comment by mmanela** [comment]
This is not possible with out changes to the Test Adapter framework.
