### ISSUE TITLE
Code Coverage - Timeout

### ISSUE THREAD

**Issue by IPWright83** [mmanela/chutzpah#302]
I'm getting a timeout when trying to run the code coverage on my tests:

>Log Message: waiting for blanket... from C:\Source\MooDEdge\MooD16\MooD.Visualizations\Tests\mood.dx.chart.spec.js
>Error: Timeout occurred when executing test file
>While Running:C:\Source\MooDEdge\MooD16\MooD.Visualizations\Tests\mood.dx.chart.spec.js

**Comment by lijunle** [comment]
I encounter a similar problem, when running with code coverage, Chutzpah get a very bad performance. After remove code coverage, things run good!

Chutzpah settings file:

```
{
  "Framework": "mocha",
  "TestFileTimeout": "600000", // <-- avoid Timeout error
  "EnableCodeCoverage": true, // <-- get a bad performance if true
  "References": [
    { ... }
  ],
  "Tests": [
    { ... }
  ]
}

```

My result with code coverage:

> Tests complete: 46
> === 46 total, 0 failed, took 28.38 seconds ===

Result without code coverage;

> Tests complete: 46
> === 46 total, 0 failed, took 6.01 seconds ===

**Comment by mmanela** [comment]
Chutzpah uses [Blanket.js](https://github.com/alex-seville/blanket) for code coverage. Can you build a sample without Chutzpah that uses blanket directly to see if this is a problem with Blanket.js itself. If so you should file a bug on their github page.
