### ISSUE TITLE
Upgrade to Jasmine 2.1

### ISSUE THREAD

**Issue by IPWright83** [mmanela/chutzpah#303]
tl;dr; Please allow the use of Jasmine 2.1

I've recently started using chutzpah and what I want is the speed to run tests incredibly quickly. Unfortunately Jasmine 2.0 doesn't always allow this (if specs have significant setup/teardown), they've added a `beforeAll` and `afterAll` into version 2.1 which will significantly help in these sorts of problems, but at the moment I can't use these with the NuGet'd chutzpah.

I do want to add btw - after 2 days use these seems a great library!

**Comment by mmanela** [comment]
Committed the upgrade to Jasmine 2.1.3 (789405011369d65b0b18de13b2f2766b01fb77c7).
