### ISSUE TITLE
Use of typescript class declarations

### ISSUE THREAD

**Issue by teamzone** [mmanela/chutzpah#304]
Hi,

There are quite a few examples of mocha tests written in typescript.  They use a very limited set of typescript capabilities.  How about being able to use a class declaration which would then enable inheritance and use of utilities and command test code in a base class.

I tried it, suspecting that I may be pushing the limits.  I'm also putting my basic knowledge of Javascript to the test as well.  

To get the typescript compiler to create some javascript I created a typescript file as follows and compiled it with the --module commonjs switch

```javascript
/// <reference path='../../typings/tsd.d.ts' />
/// <reference path="../../typings/mocha/mocha.d.ts" />
/// <reference path="../../typings/assert/assert.d.ts" />

import assert = require('assert'); 

class TestClassEx {
  
  constructor() {
    console.log('Test constructor');
  }
  
  describe = ("User Management Service Login Unit Tests", () => {
  
    beforeEach(() => {
      console.log('Before Each');
    });
  
    afterEach(() => {
      console.log('After Each');
    });
    
    it("Test 1", (done) => {
      assert(true);
      done();
    });
  
    it("Test 2", (done) => {
      assert(false);
      done();
    });
  
  });
  
}
```

When compiled you get what looks like a nodejs module.  This is something that mocha cannot run as it's a shape it's not familiar with and maybe it's not even possible - I don't know.  mocha will report 0 passing when run on the command line.

So am I barking up the wrong tree?  

```javascript
/// <reference path='../../typings/tsd.d.ts' />
/// <reference path="../../typings/mocha/mocha.d.ts" />
/// <reference path="../../typings/assert/assert.d.ts" />
var assert = require('assert');

var TestClassEx = (function () {
    function TestClassEx() {
        this.describe = ("User Management Service Login Unit Tests", function () {
            beforeEach(function () {
                console.log('Before Each');
            });

            afterEach(function () {
                console.log('After Each');
            });

            it("Test 1", function (done) {
                assert(true);
                done();
            });

            it("Test 2", function (done) {
                assert(false);
                done();
            });
        });
        console.log('Test constructor');
    }
    return TestClassEx;
})();
```

**Comment by mmanela** [comment]
You should not be relying on Chutzpah to do the compilation for you anymore, that is a legacy feature. The new way is for you to own how it compiles by either telling Chutzpah what command to run or telling Chutzpah to assume that some external process already did the compilation.

Please look at this section on our wiki: https://github.com/mmanela/chutzpah/wiki/Compile-Setting

If you still have questions/issues after that please provide a small repro.

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.
