### ISSUE TITLE
Update to QUnit 1.16.0

### ISSUE THREAD

**Issue by ellismichael** [mmanela/chutzpah#305]
QUnit recently released a new version, 1.16.0, which begins the deprecation process for a number of core functions. This issue is for updating Chutzpah to utilize and include this new version of QUnit.

Also be aware that with this version, QUnit has begun the upgrade process to versions 2.0 and 2.1 which will fully deprecate, then remove, certain functionality. Chutzpah should consider this in the solution design and plan for these future transitions.

**Comment by mmanela** [comment]
I committed the change to update QUnit to 1.16: e4b2413.
