### ISSUE TITLE
QUnit 1.16.0 assert.async() is failing

### ISSUE THREAD

**Issue by dedogs** [mmanela/chutzpah#306]
Visual Studio 2013

Receiving error: 'undefined' is not a function (evaluating 'assert.async()') 

 Failing when setting var done = assert.async(); 

 I have striped out the my actual test implementation and ran test below. This fails? 

 QUnit.module("group async Even"); 
 QUnit.test("Is async working passing 1 task", function (assert) {
var done = assert.async();

assert.ok(true, "Passed one task");

});

When running test through QUnit JavaScript unit testing framework, test is successful. Error occurs only when running test from context menu Run Js Tests.

 I have other tests, which don't include assert.async(), are testing successful.

**Comment by mmanela** [comment]
I committed the change to update QUnit to 1.16: e4b2413.
