### ISSUE TITLE
File path is missing directories when using with TypeScript and RequireJS

### ISSUE THREAD

**Issue by nmehlei** [mmanela/chutzpah#307]
Full description can be seen in this SO post: http://stackoverflow.com/questions/27237091/failing-to-set-up-basic-unit-test-solution-with-chutzpah-typescript-and-require , primarily the Supplement at the bottom.

It seems like that Chutzpah is somehow generating an invalid path when invoking tests. In my case, two directories are missing and thus chutzpah is failing because it can't find the file (obviously). I do not understand how (or rather based on what) Chutzpah is generating this path so I don't really know which further steps I could try to correct this, but an example project is located here: http://tinyurl.com/lg67nxt

**Comment by nmehlei** [comment]
Is there anything I can do to further help in investigating this? This issue is blocking me and my company from using chutzpah.

**Comment by mmanela** [comment]
I think your chutzpah.json is configured wrong. In your sample if you just remove the AMDBasePath setting it will run. That setting is intended to be used in combination with a requireJS base path settings.

Take a look at this sample for reference: https://github.com/mmanela/chutzpah/tree/360a23f199f2ba8c08167986d20a54344ee13a1d/Samples/RequireJS/CustomBaseUrl

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.
