### ISSUE TITLE
Chutzpah does not execute the new module() methods in Qunit

### ISSUE THREAD

**Issue by isterkebab** [mmanela/chutzpah#317]
Is there any way to setup what Qunit version chutzpah uses? I just downloaded the latest version of chutzpah, but it doesn't seem to support the latest module methods. However, the old one works.

To elaborate, "setup" and "teardown" works, but they are deprecated and have been replaced by "beforeEach" and "afterEach", which never gets called when running tests through chutzpah.

http://api.qunitjs.com/QUnit.module/

Edit: It seems that the current release is using QUnit 1.14, and the methods were introduced in 1.16. Just updating the file results in a timeout when running a test.

**Comment by mmanela** [comment]
I committed the change to update QUnit to 1.16: e4b2413994e2f78fd19e7d50514f323401a882ab.

**Comment by isterkebab** [comment]
Thank you!
