### ISSUE TITLE
A discovery request is already in progress

### ISSUE THREAD

**Issue by ariovistus** [mmanela/chutzpah#321]
In VS 2013, I am (coworkers too) occasionally getting 

------ Discover test started ------
------ Discover test started ------
A discovery request is already in progress. Only one active discovery request is supported.
========== Discover test finished: 0 found (0:00:00.127809) ==========

at which point Run Tests is disabled in visual studio until I close and restart it. It seems to be triggered upon save of coffeescript files, but not consistently. We all have have web essentials installed, if that's relevant.

**Comment by mmanela** [comment]
Could you give me more information. 
Version of chutzpah?
Which chutzpah plugins?
Sample project?
OS?
VS Extensions?

**Comment by ariovistus** [comment]
Chutzpah Test Adapter for the Test Explorer 3.2.6
Chutzpah Test Runner Context Menu Extension 3.2.6
win7
Web Essentials 2013 for Update 4 (2.5.3)

I'll see about a sample project.

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed or once they provide a repro.

**Comment by PrestonII** [comment]
hi @mmanela - I'm actually getting the same issue when attempting to run both Jasmine and Mocha tests. 

At the moment, I'm using `Chutzpah 4.3.3` to handle the Client tests which are written in `Jasmine` and `Visual Studio 2015`'s internal testing to handle the server tests which are written in `Mocha` (long story). 

Here's a link to my repo that you can fork to see the project: https://github.com/PrestonII/Portfolio/tree/feature/projects

Please let me know if I can pass on any other information - thanks!

`Windows 10`
`Visual Studio 2015`
`Chutzpah Test Adapter for The Test Explorer 4.3.3`
`Jasmine`
`Karma`
`Mocha`
`Chai`
`NodeJS`

**Comment by mmanela** [comment]
@PrestonII Thanks for the info, Let me try locally and see. Can you tell me what steps you do?

**Comment by PrestonII** [comment]
Sure @mmanela, thanks for looking into it!

My goal was basically to automate the entire process, hence, the whole thing is set to run tests on build, just like with any other VS project. To be honest, there's not much being done on my end in terms of say grunt tasks or the like. 

So, right after build, all tests should populate in the Test Explorer (should be 20+ tests in there)

What I've found though is that if I try to compile any of the tests in the "tests/server" folder to the Mocha framework, it jams the whole process up. No test discovery can be done by either framework. I've been meaning to look into the chutzpah.json file to see if there was any way to manually run it's test discovery process but I've been on a bit of a deadline and intended to check on it later.
