### ISSUE TITLE
Troubleshooting Code Coverage

### ISSUE THREAD

**Issue by jimblanchard** [mmanela/chutzpah#323]
I have the following:
If I run my tests, they always work fine.
If I run code coverage and allow blanket to instrument my specs, everything also works fine.
If I run code coverage and instruct blanket via the chutzpah.json file to ignore the specs, I get lots of reference errors.
I'm assuming this has something to do with how the dependencies are resolved for blanket, and I can probably figure it out, but I can't seem to see any artifacts of the blanket execution to see what it did in terms of what files it included and when. 

How do I peek in on this?

**Comment by mmanela** [comment]
Using the command line version of chutzpah you have come options.

1. Run chutzpah.console.exe /opentestinbrowser, this will open the generated html and you can inspect what it is doing

2. Run chutzpah.console.exe /trace, this will generate a chutzpah.log trace file with details on what chutzpah did

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.
