### ISSUE TITLE
Question: TS1008 and 1005 error on Typescript file

### ISSUE THREAD

**Issue by DaClan008** [mmanela/chutzpah#325]
I'm not sure if this is a bug, or if I'm doing something wrong, but I get a TS1008 and TS1005 error right through my document when trying to test my Typescript using Chutzpah and jasmine.

You can reproduce the error by using a protected method in the main file being tested.  The error occurs from that point forward.

Question:  1.  Is this a bug, or am I missing something?  Here is my json file extract:
"Framework": "jasmine",

        "TestHarnessLocationMode": "SettingsFileAdjacent",
        "TypeScriptCodeGenTarget": "ES5",
        "RootReferencePathMode": "SettingsFileDirectory",
        "References": [ {"Path": "../Functions/Ts", "Include": "*T.ts"}]

As you probably notice from the above the my testing takes place in a separate project (not that this will make any difference).  The test project has also been setup for ECMA5, which should allow protected functions?

Question 2:  Is there a workaround.  I have tried [without success yet] to setup a compile option to use msbuild and to use the bat file option.  This also gave Chutzpah Error: ChutzpahCompilationFailedException - while running c:\...... json.  My json for that is as follows:

    {
        "Compile": {
            "Extensions": [ ".ts" ],
            "ExtensionsWithNoOutput": [ ".d.ts" ],
            "Executable": "%msbuildexe%",
            "Arguments": "/t:CompileTS ",
            "OutDirectory": "out"
        },
        "References": [
            { "Path": "../Functions/Ts", "Include": "*T.ts" }
        ],
        "Tests": [ 
            {"Include": "*/Tests/*test.ts"}
        ]
    }
with compile file being: 
```
       <?xml version="1.0" encoding="utf-8"?>
        <Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
          <PropertyGroup>
                 <TscExe>tsc</TscExe>
          </PropertyGroup>
          <Target Name="CompileTS">
                 <Exec Command="$(TscExe) ../Functions/Ts/T.ts Tests/test.ts --declaration --sourcemap --outdir out" />
          </Target>
        </Project>
```
If I use the above compile option the out folder remain empty.  However somehow I got the files to compile using the .bat file, but the same error message appeared.  What else can I try, or what am I missing?

For completion here is the Typescript file being tested (T.ts) [ps this is just to repro the error]
```
module PT {
    "use strict";
    export class Tester {
        public value: string;
        protected val(): string {
            return this.value;
        }
        constructor() { }
    }
} 
```
And here is my test file (Tests/Test.ts)
```
/// <reference path="../Scripts/typings/jasmine/jasmine.d.ts" />

describe("AnIntroductory", () => {

    it("DummyTest", () => {
        // Fixture setup
        var sut = 1;
        // Exercise system                
        var expectedNumber = sut;
        // Verify outcome
        expect(1).toBe(expectedNumber);
        // Teardown        
    });
    it("realTest",() => {
        var s: PT.Tester = new PT.Tester();
        s.value = "hello";
        expect(s.value).toBe("hello");
    });
});
```

**Comment by mmanela** [comment]
Your first attempt was wrong since it is using the deprecated functionality where chutzpah compile for you. The second configuration you used looks correct since it is using the compile setting where you own how files are compiled. Nothing jumps out at me as blatantly wrong. Looking at the code, it will throw the exception you see if the bat file or msbuild executable return an exit code of > 1. Are you sure that is not happening?

**Comment by DaClan008** [comment]
I did some more trouble shooting and found the exact same error message "not using Chutzpah". I got the exact same error message (TS1008 and 1005 error) when I ran ----  tsc Ts/T.ts... through windows cmd.  error (first TS1008) starts appearing on the first protected method.  This is very strange to me:
1.  I thought protected was 100% supported in ECMA 5 and should work with typescript v 1.4.
2.  Compiling the projects normally works 100% ok -> projects compile without errors;  protected accessor works as it's suppose to in typescript;  and in javascript it is just another normal prototype "method" which is added to the object (which I guess is fine).
3.  It is only when running tsc where the error shows up [I'm not sure what the difference is between the normal typescript compilation of a project and tsc method of compiling typescript files, but the one 'ignores' the error the other don't]
I think a quick solution (though however frustrating it might be) is to change protected accesors to public.

I know a too little about compilation too get 100% to the bottom of this, but at the end it seems not to be a Chutzpah issue, but more typescript, if I am not mistaken.  Thanks for getting back though!!

**Comment by DaClan008** [comment]
I'm not sure if this is the correct way of doing things, but I have managed to make my test project tests work.  Here is the code that I used.  There might be shortcuts to this, but as mentioned running tsc alone cause TS1008 & TS 1005 errors on the output files.  My json file looks like this now.
```
{
    "Compile": { 
        "Extensions": [".ts"],
        "ExtensionsWithNoOutput": [".d.ts"],
        "Executable": "%msbuildexe%",
        "OutDirectory": "myOut"
    },
    "References": [
        { "Path": "myOut", "Include": "*.js" }
    ]
}
```

and my compilation file (compile.proj) looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" />
  <PropertyGroup>
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptIncludeComments>true</TypeScriptIncludeComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
    <TypeScriptModuleKind>AMD</TypeScriptModuleKind>
    <TypeScriptCompileOnSaveEnabled>true</TypeScriptCompileOnSaveEnabled>
    <TypeScriptToolsVersion>1.4</TypeScriptToolsVersion>
    <TypeScriptOutDir>myOut</TypeScriptOutDir>
  </PropertyGroup>
  <ItemGroup>
    <TypeScriptCompile Include="..\Functions\Ts\T.ts" />
    <TypeScriptCompile Include="Tests\Test.ts" />
  </ItemGroup>
  <Target Name="Build" DependsOnTargets="CompileTypeScript">
  </Target>

  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" />
  </Project>
```
I guess one could reduce this file a bit more by excluding the Tests\Test.ts file.  This at the end is already compiling on save through the normal project build operations.  but this offcourse will mean that the references should include a reference to the folder that the test file resides in.

if there is a better way.  Let me know, otherwise, I managed to get passed the errors and on this specific file 2 tests were picked up and ran as expected.

Thanks again :)

**Comment by mmanela** [comment]
Great that you got it to work. You should be able though to only reference the .ts file and let Chutzpah figure out where they are. The key is to making sure the source directory is correctly set to be above where all your files are. So in the attempt below (did not try since I do not have a repro for you) I make the source dir ../ to go up one level and be above the Functions folder.

```
{
    "Compile": { 
        "Extensions": [".ts"],
        "ExtensionsWithNoOutput": [".d.ts"],
        "Executable": "%msbuildexe%",
        "OutDirectory": "myOut",
        "SourceDirectory": "../"
    },
    "References": [
        { "Path": "../Functions/Ts", "Include": "*T.ts" }
    ],
    "Tests": [ 
        {"Include": "*/Tests/*test.ts"}
    ]
}
```

**Comment by DaClan008** [comment]
Thanks mmanela, I will try that out, in the mean time, I will mark this issue as closed.
