### ISSUE TITLE
Support for async() in QUnit v1.17.1

### ISSUE THREAD

**Issue by docHologram** [mmanela/chutzpah#326]
Are there plans for updating QUnit testing to support v1.17.1, notably the changes made concerning async testing. http://api.qunitjs.com/category/async-control/

**Comment by mmanela** [comment]
Does Chutzpah not work with the assert.async?

**Comment by docHologram** [comment]
The few async tests I was runnning were throwing an error because
assert.async() was undefined. Once I refactored my tests based on QUnit
v1.15.0 and used QUnit.start() and QUnit.stop() instead, it worked fine.
Not a big deal, but definitely food for thought as the different unit
testing frameworks make changes to their APIs over time.

Thanks for getting back to me.

-Dave

**Comment by mmanela** [comment]
Ah yes, I committed a change 10 days ago to upgrade to newest QUnit but I have yet to release it.

**Comment by mmanela** [comment]
This will be included in the 4.0 release
