### ISSUE TITLE
Tests in nested folder

### ISSUE THREAD

**Issue by NN---** [mmanela/chutzpah#327]
Chutzpa doesn't scan test files in the nested folders.
So I have to do ugly hack with naming nested_nested2_a.ts.

**Comment by mmanela** [comment]
Can you please provide a repro or at least a more detailed example of what you are trying?

**Comment by NN---** [comment]
Everything works :)
Just put in chutzpa.json this line

"CodeCoverageIncludes": [ "*.js" ]

Thanks for great tool!
