### ISSUE TITLE
global strict mode via configuration

### ISSUE THREAD

**Issue by NN---** [mmanela/chutzpah#328]
Add option to chutzpa.json for putting automatically 'use strict' in all testing files.

```json
{
    "UseStrict": true
}
```

**Comment by mmanela** [comment]
What is the reason for this? Why wouldn't you just put this in your files yourself?

**Comment by NN---** [comment]
If I put 'use strict' in one file, doesn't it affect all other files ?

**Comment by mmanela** [comment]
Should just affect that file

**Comment by NN---** [comment]
Ok, thanks.
