### ISSUE TITLE
Error Opening UnitTest.js.  The system cannot find the path Specified.

### ISSUE THREAD

**Issue by wiscow** [mmanela/chutzpah#333]
I am running into an issue when running the chutzpah on TeamCity.  Specifically i am getting an error that a file cannot be found.  This is the error:

`[11:01:27]#_#Error#_# {"type":"Error","error":{"message":"Error opening c:/teamcity/buildagent/work/roydan.web/Client/Consumer/Phones/phoneListUnitTests.js: The system cannot find the path specified."}}
[11:01:27]Error: Error opening c:/teamcity/buildagent/work/roydan.web/Client/Consumer/Phones/phoneListUnitTests.js: The system cannot find the path specified.
[11:01:27]While Running:c:\teamcity\buildagent\work\c20e96cc79bc863c\roydan.web\Client\Consumer\Phones\phoneListUnitTests.js`

The issue seems to be that the project folder c20e96cc79bc863c is being excluded when the test is looking for the file. However, the path is correct in the "Running" statement at the bottom.  

Here is my chutzpah config:

````json
{
    "TestHarnessReferenceMode": "AMD",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "AMDBasePath": "./Client/",
    "Framework": "jasmine",
    "RootReferencePathMode": "SettingsFileDirectory",
    "CodeCoverageIncludes": [ "*.js" ],
    "CodeCoverageExcludes": [ "*Tests.js", "**/lib/*.js", "node_modules/**/*.js" ],
    "References": [
        { "Path": "Client/Assets/lib/require.js" },
        { "Path": "Client/requireConfig.js" }
    ],
    "Tests": [
        { "Path": "", "Include": "*UnitTests.js", "Exclude": "node_modules/**/*.js" }
    ]
}
````

and here is the execution piece in team city:

%teamcity.build.checkoutDir%\packages\Chutzpah.3.3.1\tools\chutzpah.console.exe

"%teamcity.build.checkoutDir%\Roydan.Web\chutzpah.json" /coverage /teamcity

Any Ideas as to what would be causing this?  The results are never consistent.  The file that cannot be found will be different each time the build runs.  However, there is always at least one file that cannot be found.

Thanks,
Kyle

**Comment by mmanela** [comment]
The error seems not to be complaining about the c20e96cc79bc863c folder but the c:/teamcity/buildagent/work/roydan.web/Client/Consumer/Phones/phoneListUnitTests.js path. Are you sure the file is there? Can you produce a repro at all that I can run locally?

**Comment by wiscow** [comment]
No there is no file located at c:/teamcity/buildagent/work/roydan.web/Client/Consumer/Phones/phoneListUnitTests.js.  But the file is located at c:/teamcity/buildagent/work/c20e96cc79bc863c/roydan.web/Client/Consumer/Phones/phoneListUnitTests.js .  I guess i am not sure why the "c20e96cc79bc863c" part of the path is getting stripped out.  I at first thought it might have been a relative path issue, but it the chutzpah.json config is rooted at the "roydan.web" folder.  Ill take a stab at getting a repo that you could run locally.

**Comment by mmanela** [comment]
Yes please do. This seems very strange.

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed or once they provide a repro.
