### ISSUE TITLE
Test Adapter doesn't work without full Visual Studio install

### ISSUE THREAD

**Issue by dreaburn** [mmanela/chutzpah#336]
On a machine with just the [Agents for Microsoft Visual Studio](http://www.microsoft.com/en-us/download/details.aspx?id=40750) installed, the chutzpah test adapter cannot be loaded. Agents for Microsoft Visual Studio is used to run tests in a lab environment without the full Visual Studio installation.

This problem is occurring because the test adapter dll has a dependency on Microsoft.VisualStudio.TestWindow.Interfaces.dll, which is not present in the Agents install. To fix this, Visual Studio UI dependencies will have to be taken out of the TestAdapter dll.

**Comment by mmanela** [comment]
Thanks for reporting this. It will take some serious refactoring to fix this. I will start to investigate.

**Comment by mmanela** [comment]
I pushed an initial set of changes to address this. Would you be able to help validate?

**Comment by dreaburn** [comment]
Sure! I'll take a look.

**Comment by dreaburn** [comment]
I can confirm it works with Agents for Visual Studio 2013. Thank you!

FYI, I ran into a problem building the test adapter, it looks like the Newtonsoft.Json and SourceMapDotNet NuGet expansions are missing from .\packages.
