### ISSUE TITLE
Typescript 1.4 / Jasmine 2.2 tests not found using chutzpah.json

### ISSUE THREAD

**Issue by alex2074** [mmanela/chutzpah#337]
Hello
I am using Visual Studio 2013, TypeScript 1.4 and Jasmine 2.2.
A few days ago I have migrated my ES5 scripts to typescript. Using ES5 the tests were executed without problems. I use a chutzpah.json config file in order to avoid having all references in the test files.
 
Now I have migrated all my code including the Jasmine tests to typescript 1.4 and the tests are not found anymore in the Visual Studio 2013 Test Explorer or in TFS. 

However the tests can be executed without problems using the command line tool chutzpah.console.exe or the Chutzpah Test Runner Context Menu Extension. But no tests are found in the Test Explorer or in TFS.

chutzpah.json:
{
    "Framework": "jasmine",
    "RootReferencePathMode": "SettingsFileDirectory",
    "TypeScriptCodeGenTarget": "ES5",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ]
    },
    "Tests": [
        { "Path":  "app", "Include":  "test.spec.ts" }
    ]
}

test.spec.js:
describe('test', () => {
    it('should exist', () => {
        expect('foo').toBe('foo');
    });
}); 

Can you please tell me what is wrong in the chutzpah.json?
Thanks,
Alexandra

**Comment by mmanela** [comment]
There is an old setting I have been meaning to remove that you can find in Tools->Options->Chutzpah->Unit Test Explorer->Testing Mode

And make sure it is set to TypeScript or AllExceptHTML

**Comment by alex2074** [comment]
Thanks mmanela. The tests are now found in Visual Studio Test Explorer.

But still the tests are not found on our TFS, it shows "No test found. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.". As I mentioned above the tests were executed on the TFS without problems before we rewrote our ES5 code in TypeScript.

Any advice?

**Comment by mmanela** [comment]
You need to provide a .runsettings file with a similar setting that you just set in VS. See [this page](https://github.com/mmanela/chutzpah/wiki/Running-Unit-Tests-in-a-TFS-Build). But in short:


```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
 <ChutzpahAdapterSettings>
   <TestingMode>All</TestingMode>
 </ChutzpahAdapterSettings>
</RunSettings>
```


This has tripped up a lot of people (you are not alone) so I plan to remove this testingMode setting in the next version.

**Comment by alex2074** [comment]
OK. Now I am a step further but it is still not working. 
The jasmine tests are now found on TFS but while running the tests, I get lots of TSLint errors in jQuery.d.ts like
xxx/jquery.d.ts(281,59): error TS1005: ',' expected.
While Running: C:\xxx\bin\_PublishedWebsites\xxx\test1.spec.js

Any idea how to exclude the TypeScript typing files from the TSLint analysis?

**Comment by mmanela** [comment]
Are the errors happening in Chutzpah or tslint?

**Comment by alex2074** [comment]
Well I'm not sure. The only thing I can say is that the errors happen while running the tests and seems to be TSLint errors. 
Is there a chutzpah log where I could see more details about the errors?

Thanks, Alexandra

**Comment by mmanela** [comment]
Can you provide a small sample that repros this issue?

**Comment by alex2074** [comment]
Hello Matthew,
here is a sample reproducing the problem (using TypeScript 1.4, jasmine 2.2).
While building in TFS I get this message:C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(281,59): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(281,73): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(281,76): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(300,41): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(300,63): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(300,117): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(300,139): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(300,147): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(317,56): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(317,78): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(317,140): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(317,162): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(317,170): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(324,50): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(324,72): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(324,127): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(324,149): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(324,155): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(331,52): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(331,74): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(331,134): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(331,156): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(331,164): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(337,60): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(337,82): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(337,145): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(337,167): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(337,175): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(357,56): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(357,78): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(357,140): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(357,162): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(357,170): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(364,50): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(364,72): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(364,127): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(364,149): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(364,155): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(371,52): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(371,74): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(371,134): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(371,156): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(371,164): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(377,60): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(377,82): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(377,145): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(377,167): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(377,175): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(662,35): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(677,39): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(707,36): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(729,41): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(793,34): error TS1005: '>' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(793,48): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(793,77): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(793,78): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1187,36): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1228,46): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1235,78): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1284,45): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1284,52): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1356,22): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1356,29): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1377,44): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1384,78): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1401,25): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1407,59): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1419,31): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1431,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1462,31): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1476,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1514,24): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1520,57): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1588,50): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1597,50): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1620,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1628,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1642,30): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1650,30): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1665,28): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1674,28): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1682,33): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1690,33): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1711,27): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1719,27): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1733,27): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1741,27): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1755,32): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1763,32): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1777,34): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1785,34): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1799,30): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1807,30): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1837,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(1845,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2437,55): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2444,62): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2557,27): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2557,31): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2563,56): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2563,64): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2571,28): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2571,32): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2577,57): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2577,65): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2584,28): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2584,32): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2592,28): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2592,32): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2598,57): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2598,65): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2625,31): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2625,35): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2632,32): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2632,36): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2640,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2640,33): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2646,58): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2646,66): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2653,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2653,33): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2667,30): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2667,34): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2674,35): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2674,39): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2680,36): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2691,22): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2691,29): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2714,33): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2714,41): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2720,41): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2727,36): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2727,44): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2735,38): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2735,46): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2770,27): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/jquery/jquery.d.ts(2770,34): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(877,50): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(877,57): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(877,64): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(964,35): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(979,82): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(979,91): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(979,100): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(984,74): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(984,83): error TS1005: '=' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(984,92): error TS1003: Identifier expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(1288,99): error TS1005: ',' expected.C:/Builds/2/xxxx/Build_CI/bin/Scripts/typings/angularjs/angular.d.ts(1471,33): error TS1005: ';' expected.While Running:C:\Builds\2\Build_CI\bin\_PublishedWebsites\Web\app\test1.spec.js
I have updated the jquery and angular typings but I still get those errors.
Kind regardsAlexandra 


     Le Lundi 6 avril 2015 0h27, Matthew Manela <notifications@github.com> a écrit :
   

 Can you provide a small sample that repros this issue?—

**Comment by jdenekat** [comment]
I'm having the exact same problem reported by alex2074.  Has there been any progress on this issue?

**Comment by mmanela** [comment]
Can you please provide a full repro?

**Comment by jdenekat** [comment]
Yes, but it may be a while before I can get to it.

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.

**Comment by mikestolpa** [comment]
I'm having the same exact issue. How was this resolved?

**Comment by mmanela** [comment]
I resolved it since the original poster was never able to provide me with a repro. If you have a repro you can share I can re-open

**Comment by mikestolpa** [comment]
Sorry, I'm not able to provide a repro, but, I was able to get this to work
- we are on 3.3.1 and I just needed to put all my classes in our
TestingIncludes.ts file - for some reason the chutzpah.json was not finding
them. We are looking into updating to 4.1.0 to see what happens.

Thanks,

**Comment by goleafs** [comment]
I am having these same errors

**Comment by mmanela** [comment]
@goleafs Can you provide a repro

**Comment by goleafs** [comment]
It's a large solution but I'll see if I can narrow down for the purposes of repo.

The tests run fine local both on my local machine and the build server (when running through VS).

However the automated build is failing when running the same tests...

Sample of errors...

Chutzpah console test runner (64-bit .NET 4.0.30319.42000) Version 3.2.3.0 Copyright (C) 2013 Matthew Manela (http://matthewmanela.com). chutzpah.dll: Version 3.2.3.0 Error: Error in [JavaScript runtime error]: data.service.ts(1,11): error TS1005: ';' expected. data.service.ts(1,29): error TS1005: ';' expected. data.service.ts(5,5): error TS1008: Unexpected token; 'statement' expected. data.service.ts(5,21): error TS1005: ';' expected. data.service.ts(11,23): error TS1005: '=' expected. data.service.ts(11,32): error TS1005: ',' expected. data.service.ts(11,36): error TS1005: ',' expected. data.service.ts(11,45): error TS1005: ',' expected. data.service.ts(20,18): error TS1005: '=' expected. data.service.ts(20,26): error TS1005: ';' expected. data.service.ts(24,1): error TS1008: Unexpected token; 'module, class, interface, enum, import or statement' expected. service.ts(2,11): error TS1005: ';' expected. service.ts(2,24): error TS1005: ';' expected. service.ts(6,5): error TS1008: Unexpected token; 'statement'

**Comment by mmanela** [comment]
You are using an old version of Chutzpah that is doing the compilation of TS for you. Please upgrade to the newer version. I am not supporting the built in TS compile

**Comment by goleafs** [comment]
yes, that could be it - the latest version of typescript (1.6) and chutzpah (4.1) are installed on VS2015 but the build seems to be doing its own thing (chutzpah.console.exe).  Any reference on how to update that?

**Comment by mmanela** [comment]
I am not sure about your situation. Your code is someone explicitly using an old version of Chutzpah.

**Comment by goleafs** [comment]
We are using TFS Build
Correct - unless we use VS manually the old version is being picked up from source... so how to get the latest chutzpah.console.exe and any other supporting files?  Does not look like it was included in the nuget package.  Just pull from your source and build it?

**Comment by goleafs** [comment]
nevermind - found the download - sorry to bother you with this.

**Comment by em-rkumar** [comment]
I am not able to set with TFS 2015 build
