### ISSUE TITLE
Typescript 1.4 upgrade / run inside VS2013

### ISSUE THREAD

**Issue by iBaryo** [mmanela/chutzpah#338]
After upgrading my projects to typescript 1.4, when I try to run Chutzpah inside VS2013 I get errors relevant to the old version of the TSC.
How can I define Chutzpah which TSC version to use?

**Comment by mmanela** [comment]
You should not use the legacy compilation support in Chutzpah. Please use the [compile setting](https://github.com/mmanela/chutzpah/wiki/Compile-Setting). This lets you specify how to compile your files

**Comment by iBaryo** [comment]
Thanks. 
It returned to work when I've created a chutzpah.json file in the root folder of my projects, with a "compile" property.
The thing is that I'm obliged to give an executable to it for it to compile the source files. I don't need it because I want Chutzpah to use the .js files that are automatically created by VS. So it ends up my executable .bat file is pretty much empty and useless.
Is there a cleaner way for this?

**Comment by mmanela** [comment]
What you want is the External compile mode: https://github.com/mmanela/chutzpah/wiki/Compile-Setting#integration-with-compilation-tooling

See a sample here: https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation/ExternalCompile

**Comment by iBaryo** [comment]
Oh wow, thank you!
Sorry for the bother!

**Comment by mmanela** [comment]
I have seen people miss this before, can you tell me how I can update the docks to make this clearer?

**Comment by iBaryo** [comment]
Maybe also reference it in the Visual Studio Extension one.
