### ISSUE TITLE
Please provide NuGet package of Visual studio Test Adapter for VSO deployments

### ISSUE THREAD

**Issue by jessehouwing** [mmanela/chutzpah#339]
Since Visual Studio 2012.1 it has become possible to install test runners through NuGet instead of an Extension. This makes it a lot easier to run tests on platforms like Visual Studio Online and for Git repositories, as it no longer needs the binaries to be checked into source control.

https://msdn.microsoft.com/en-us/library/vstudio/ms253138%28v=vs.110%29.aspx#ThirdParty

**Comment by mmanela** [comment]
I plan to do this for the next release.

**Comment by mmanela** [comment]
I included the needed files in the nuget package. You should be able to consume these once the 4.0 version is released.
