### ISSUE TITLE
Bad JSON escape sequence: \l. Path 'Transforms[0].Path', line 3, position 45.

### ISSUE THREAD

**Issue by ryan9018** [mmanela/chutzpah#343]
I'm using VS 2013 Professional. I'm seeing the above error in the output window when trying to run the tests. I have this in my chutzpah.json file:

{ 
    "Transforms": [
        { "Name": "lcov", "Path": "C:\temp\lcov.dat" },
        { "Name": "junit", "Path": "C:\temp\junit.xml" },
        { "Name": "trx", "Path": "C:\temp\trx.trx" }
    ]

}

**Comment by mmanela** [comment]
If you use a backslash you must escape it with a extra backslash 

```
{ 
"Transforms": [
{ "Name": "lcov", "Path": "C:\\temp\\lcov.dat" },
{ "Name": "junit", "Path": "C:\\temp\\junit.xml" },
{ "Name": "trx", "Path": "C:\\temp\\trx.trx" }
]

}
```

Alternatively you can also use forward slashes.

**Comment by Pablissimo** [comment]
That's my bad with the docs for the Transforms setting - the wiki's code sample's got single backslashes which I think probably worked with the old JSON parser but not with the new'un?
