### ISSUE TITLE
Error installing 4.0 Context Menu Extensions within VS2012

### ISSUE THREAD

**Issue by jimithing277** [mmanela/chutzpah#344]
After installing the 4.0 Context Menu Extensions package I received the attached errors upon restarting Visual Studio.  Also, when going to Tools -> Options -> Chutzpah the "Settings" node shows me "An error occurred loading this property page".

It appears that the packages are attempting to look for a VS2013 DLL based on the following errors from the ActivityLog.xml when it should have been referencing the VS2012 DLL (version 11)

<entry>
    <record>495</record>
    <time>2015/04/09 12:43:06.711</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [ChutzpahPackage]</description>
    <guid>{0A3DA9D8-A5B6-4FB9-B423-EF87FF203628}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>496</record>
    <time>2015/04/09 12:43:06.711</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [ChutzpahPackage]</description>
    <guid>{0A3DA9D8-A5B6-4FB9-B423-EF87FF203628}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
</activity>

![chutzpaherror](https://cloud.githubusercontent.com/assets/4098730/7067358/9a4b4fd6-de98-11e4-9239-11f0ae83cde9.png)

**Comment by mmanela** [comment]
Thanks for the comment. I did a bunch of refactoring on that extension so this definitely is possible. Can you confirm if the the other extension also is failing (the test adapter one)?

**Comment by jimithing277** [comment]
Test adapter seems to be installing fine.  I believe this is isolated to just the context menu extensions.  I appreciate your prompt help and all the work you've done on this amazing tool!

**Comment by AlistairSH** [comment]
I'm seeing the same error, also for the context menu extension.

Thanks.

**Comment by mmanela** [comment]
I just published an update to the context menu extension that should fix this. Please test it out.

**Comment by AlistairSH** [comment]
That was quick!  Looks like the problem is resolved.  Thanks!

**Comment by jimithing277** [comment]
Thanks for fixing this so promptly, it is much appreciated by the community!  Keep up the great work

**Comment by GaryMalk** [comment]
I have the opposite problem.  The Context Menu installed fine (likely due to your fix, above) but the Test Adaptor is failing on VS 2013: "The 'ChutzpahVS2012Package' package did not load correctly."

See attached activity log entry: Expected 1 export(s) with contract name "Chutzpah.VS2012.TestAdapter.IChutzpahSettingsMapper" but found 0 after applying applicable constraints.

[ActivityLog entry.txt](https://github.com/mmanela/chutzpah/files/79256/ActivityLog.entry.txt)

**Comment by mmanela** [comment]
@GaryMalk Can you try to uninstall, clear extension cache and reinstall extension?

**Comment by GaryMalk** [comment]
I uninstalled it.  C:\Users\{User}\AppData\Local\Temp\VWDWebCache was already empty.  After reinstall it appears to work without errors.  Thanks!
