### ISSUE TITLE
Previously successful tests showing as failed only in VS Text Explorer after upgrade to 4.0

### ISSUE THREAD

**Issue by jimithing277** [mmanela/chutzpah#345]
After upgrading the VS 2012 Test Adapter to 4.0 I'm now noticing that several tests which were previously passing are now showing as failed.

The strange part is when I choose "Open in Browser" from the context menu extension the tests then all show as successful.

I'm using mocha as my testing framework with "bdd" style.  The tests that were previously passing before upgrading and now failing all seem to have one thing in common which is that they involve a spy on a global method (i.e. var spy = sinon.spy(window, "globalMethodNameHere" );)

Anyone else experiencing this issue?  It's almost like the VS parser isn't interpreting the results?  I'm not sure how to debug this.

@mmanela - I have two chutzpah.log files which may be of use here.  Is there a way I can privately share these to you?  I'd prefer not to publicly post them if possible.

Also, is there anyway to download the previous version?  I'd like to get back to a stable build until I can get this issue resolved.  Thanks in advance.

**Comment by mmanela** [comment]
Chutzpah 4.0 did upgrade to a new version of Phantom and its plausible that has an impact. In addition to the logs it would be great if you could create a minimal repro of the issue. You can send both to my alias @gmail.com.

**Comment by jimithing277** [comment]
E-mail sent, thank you for the help.

**Comment by jimithing277** [comment]
@mmanela It appears that this indeed is related to the upgrade of Phantom but it is not an issue as far as Chutzpah is concerned.  Tthe latest version of sinon.js does not seem to play nicely with Phantom.  Reverting to version 1.13 of sinon.js corrects the issue.  Closing this case and appreciate all your help.
