### ISSUE TITLE
Update chutzpah.json schema on schemastore.org to v4.0

### ISSUE THREAD

**Issue by kimsk** [mmanela/chutzpah#347]
The existing json schema for Chutzpah is [here](http://json.schemastore.org/chutzpah)

And I think we could send a PR to [here](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/chutzpah.json).

**Comment by mmanela** [comment]
Sounds good, I am about to make one more schema change and after that we can update it

**Comment by mmanela** [comment]
Done
