### ISSUE TITLE
The openinbrowser is not working when the default app for html file is not set to a browser

### ISSUE THREAD

**Issue by dvdguo** [mmanela/chutzpah#351]
When The chutzpah.console.exe has a /openInBrowser parameter, it will open the test case in a browser. However if the default app used to open html file is set to non-browser app, such as notepad, the test page will be opened in notepad instead. 

It would be nice if Chutzpah could load the browser properly when the default app for html file is not set to a browser.

**Comment by mmanela** [comment]
Ah makes perfect sense. Chutzpah just tells the shell to launch the HTML file. But in your case that is not good enough.

**Comment by mmanela** [comment]
Chutzpah will now choose the default installed browser.
