### ISSUE TITLE
Chutzpah try to find generated js files ignoring OutDirectory option in compile setting in chutzpah.json

### ISSUE THREAD

**Issue by sanjeet1827** [mmanela/chutzpah#352]
Hi,

I have seen a strange thing while trying to run my jasmine test case with Chutzpah Testcase Adapter.

Please get the below detail.

I am using Typescript+RequireJS and jasmine for my test cases 
.
Refere the below image for solution structure.

![solution](https://cloud.githubusercontent.com/assets/12337278/7536218/84faa404-f5ab-11e4-9067-f734c5282a47.PNG)

Below is chutzpah.json located at root folder

{
    "TestHarnessReferenceMode": "AMD",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "TypeScriptModuleKind": "AMD",
    "References": [
        { "Path": "defs/qunit.d.ts", "IncludeInTestHarness": "false" },
        { "Path": "defs/require.d.ts", "IncludeInTestHarness": "false" },
        { "Path": "lib/require.js" }
    ],
    "Tests": [
        { "Path": "tests/unit", "Includes": [ "*.js" ], "Exclude": "*.d.ts" }

    ],
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ],
        "SourceDirectory": "js",
        "OutDirectory": "js"
    }
}

below is test case file 

/// <reference path="../../defs/jasmine.d.ts" />
/// <reference path="../../defs/require.d.ts" />

import ClassA = require("../../js/ClassA");

describe("Jasmine - test case", () => {

    it("Jasmine - Class A object should be defined", () => {
        expect(ClassA.ClassA.ClassAObject).toBeDefined();
    })

});

ClassA.ts
==================
import ClassB = require('ClassB');

export class ClassA {

    public static ClassAObject: string = ClassB.ClassB.obj;
    

}

ClassB.ts
==================
export class ClassB {

    public static obj:string = "object assigned";

}

You may notice that I have refered ClassA via require which internally uses ClassB via requireJS.

But when I try to run or discover test cases it does not it as mentioned in test case file.
I saw the chutzpah.log and saw that Chutzpah find ClassB.js file at the right location below

/<Project>/js/ClassB.js

But it also again try to find same file at wrong location (on the root location) as below

/<Project>

I guess it can be the issue because I am having an timeout error while see in output window.
And, When I Put ClassB.ts file at root location It works fine.

Please suggest what I am doing wrong here.

**Comment by mmanela** [comment]
Can you provide a working repro so I can download an run?

**Comment by sanjeet1827** [comment]
Thanks for reply,
You download the repo from below path

https://github.com/sanjeet1827/ChutzpahRequireJS/

**Comment by sanjeet1827** [comment]
Hi mmanela,

Did you find the issue , which is occurring in provided sample ?

Please let me know about the same.

**Comment by mmanela** [comment]
I fixed your issues, you can see all the details in the PR (https://github.com/sanjeet1827/ChutzpahRequireJS/pull/1)

Main Changes:
1. Main problem is incorrect AMD paths in the .ts files
2. Removed unneded lines from Chutzpah.json (this wasnt an issue but keeps it simpler)

**Comment by sanjeet1827** [comment]
Oh! path was an issue , I got confused that if ClassA and ClassB both are in same folder theny why to give path like "js/ClassB" with require statement.

I will have to look now in my main project.
But anyway thanks a lot, Issue is resolved now.
