### ISSUE TITLE
Chutzpah cannot find jasmine tests

### ISSUE THREAD

**Issue by cidthecoatrack** [mmanela/chutzpah#354]
I have recently begun using Chutzpah to run my jasmine/karma tests, so that I can integrate with the Visual Studio test explorer.  All my tests work fine if I run them via karma from the command line.  However, when I tell Chutzpah to run (whether via the test explorer, command line, or the right-click menu), while it will find my spec files and recognize them as test files, it will not run any tests within them.

Example output:

    ------ Test started: File: C:\Users\Andrew Wiggin\Documents\Programming\Projects\BTTiggerWebApp\Tests\Unit\Scripts\app\failure\failureSpec.js ------
    0 passed, 0 failed, 0 total (chutzpah).

    ------ Test started: File: C:\Users\Andrew Wiggin\Documents\Programming\Projects\BTTiggerWebApp\Tests\Unit\Scripts\app\passengerCount\passengerCountSpec.js ------
    0 passed, 0 failed, 0 total (chutzpah).

    ------ Test started: File: C:\Users\Andrew Wiggin\Documents\Programming\Projects\BTTiggerWebApp\Tests\Unit\Scripts\app\dispatch\dispatchSpec.js ------
    0 passed, 0 failed, 0 total (chutzpah).

    ------ Test started: File: C:\Users\Andrew Wiggin\Documents\Programming\Projects\BTTiggerWebApp\Tests\Unit\Scripts\app\mileage\mileageSpec.js ------
    0 passed, 0 failed, 0 total (chutzpah).

    ------ Test started: File: C:\Users\Andrew Wiggin\Documents\Programming\Projects\BTTiggerWebApp\Tests\Unit\Scripts\app\flagDay\flagDaySpec.js ------
    0 passed, 0 failed, 0 total (chutzpah).

    ========== Total Tests: 0 passed, 0 failed, 0 total ==========

Chutzpah configuration:

    {
        "Framework": "jasmine",
        "RootReferencePathMode":"SettingsFileDirectory"
    }

Example test file:

    'use strict'

    /// <reference path="../../../../../_references.js" />

    describe('the PassengerCountController', function () {
    var vm;
    var q;
    var scope;

    beforeEach(module('app.passengerCount'));

    beforeEach(inject(function ($rootScope, $controller, $q) {
        q = $q;
        scope = $rootScope.$new();

        vm = $controller('PassengerCount as vm', {
            $scope: scope
        });
    }));

    it('has initial unknown values', function () {
        expect(vm.driverId).toBe(-1);
        expect(vm.vehicle.Id).toBe(-1);
        expect(vm.vehicle.Name).toBe('Unknown');
        expect(vm.shift.Id).toBe(-1);
        expect(vm.shift.Name).toBe('');
        expect(vm.trip.Trip.Id).toBe(-1);
        expect(vm.trip.Trip.Name).toBe('');
        expect(vm.route.Id).toBe(-1);
        expect(vm.route.RunId).toBe(-1);
        expect(vm.route.TripId).toBe(-1);
        expect(vm.shifts.length).toBe(0);
        expect(vm.trips.length).toBe(0);
        expect(vm.stops.length).toBe(0);
    });

    it('has yesterday as initial scheduled date', function () {
        var today = new Date();
        var yesterday = new Date();
        yesterday.setDate(today.getDate() - 1);

        expect(vm.scheduledDate.getFullYear()).toBe(yesterday.getFullYear());
        expect(vm.scheduledDate.getMonth()).toBe(yesterday.getMonth());
        expect(vm.scheduledDate.getDate()).toBe(yesterday.getDate());
    });

    it('has the initial state of the date picker popover', function () {
        expect(vm.opened).toBeFalsy();
    });

    it('has no alerts on load', function () {
        expect(vm.alerts.length).toBe(0);
    });
    })

(this is a simplified version, but hopefully you get the idea)

What have I configured wrong?  I have jasmine 2.2 installed, which is what Chutzpah defaults to.

It may or may not be related - I assume it is - but when the solution first loads, it takes FOREVER (15+ minutes) for the test explorer to find tests.  And, when it's done, it lists no javascript tests (which makes sense, since it can't find them in any context).  I hope this is just a configuration issue that I can mend.

**Comment by mmanela** [comment]
Sounds like a configuration issue. Please provide a full working repro that I can test with.

**Comment by cidthecoatrack** [comment]
Sure thing.  You can use this branch of this repository:

https://github.com/cidthecoatrack/DNDGenSite/pull/18

**Comment by mmanela** [comment]
I recommend you run chutzpah with the openinbrowser option and debug the generated HTML page to see what it is doing.

**Comment by cidthecoatrack** [comment]
I am having trouble getting the command line option to work.  I try to run `chutzpah /openinbrowser`, but it says that the command is not found.  I have also tried `chutzpah.console`, `chutzpah.console.exe`, and `.\chutzpah.console.exe`.  Is there some other dependency that I need to set up before being able to use this command in the console?

**Comment by mmanela** [comment]
Where did you download the .exe from?

**Comment by cidthecoatrack** [comment]
I have not downloaded it.  I assumed it came when I installed the Visual
Studio add-in.  Was that an incorrect assumption?

**Comment by mmanela** [comment]
No, you need to download it. It is in the releases on github or on nuget

**Comment by cidthecoatrack** [comment]
Im' sorry, I know this is annoying that I keep having to message you, but I can't seem to run the command even after downloading it.

1. I downloaded the 4.0.1 release from GitHub
2. I placed the unzipped folder in the same folder where my solution resides.
3. In GitBash, I go to the Chutzpah.4.0.1 folder
4. I try to run `chutzpah.console.exe /openinbrowser`, but it says `command not found`.  This is also true if I try `chutzpah.console.exe` (without the open in browser option).

Is there some other configuration?installation I need to do before this will run, and I can actually do the debugging you requested?

**Comment by mmanela** [comment]
I am not sure, This is just a plain exe so as long as your are giving the
right path it should run. Can you try ./chutzpah.console.exe

**Comment by cidthecoatrack** [comment]
sweet jeebus that worked - thank you.  You are very responsive in your repo, and I cannot tell you how much I appreciate that.  I can now run it.  However, even with the `/openinbrowser` option, the browser does not open, and the exe does not find any tests.  Here is my Karma configuration file:

    // Karma configuration
    // Generated on Wed Oct 08 2014 13:34:17 GMT-0400 (Eastern Daylight Time)

    module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',


        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine'],


        // list of files / patterns to load in the browser
        files: [
            'DNDGenSite/Scripts/Angular/angular.min.js',
            'DNDGenSite/Scripts/Angular/angular-mocks.js',
            'DNDGenSite/Scripts/app/**/*.module.js',
            'DNDGenSite/Scripts/app/**/*.js',
            'Tests/Unit/Scripts/**'
        ],


        // list of files to exclude
        exclude: [
        ],


        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
        },        

        // web server port
        port: 9876,


        // enable / disable colors in the output (reporters and logs)
        colors: true,


        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,


        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,

        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['PhantomJS', 'Chrome'],

        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: true,
        reporters: ['progress', 'junit'],
        junitReporter: {
            outputFile: 'unit-specs.xml',
            suite: 'unit'
        }
    });
    };

I have looked in the folder where the command runs, and there is not HTML file that has been generated.  Here is the output from the console:

    Chutzpah console test runner (64-bit .NET 4.0.30319.34209
    Version 4.0.1.0
    Copyright (C) 2015 Matthew Manela (http://matthewmanela.com).
    
    === 0 total, 0 failed, took 0.03 seconds ===

Any idea where to go from here?

**Comment by mmanela** [comment]
Chutzpah does not use a karma config file, it has its own called chutzpah.json

-----Original Message-----

**Comment by cidthecoatrack** [comment]
Then I am certainly confused.  Why has the default browser not opened? (Mine is set to Chrome).  Is it because it isn't finding any tests?  Considering it can find the specs, I find it very peculiar.

**Comment by mmanela** [comment]
Because chutzpah was unable to figure out and find your test files. Run chutzpah with /trace and it will print a log file of what it tried to do

**Comment by cidthecoatrack** [comment]
No luck, no `chutzpah.log` file is outputted.

**Comment by mmanela** [comment]
How about this, start with one of the many samples in the chutzpah repo and prove that works for you. Then start to convert to your code. Maybe start with this one https://github.com/mmanela/chutzpah/blob/master/Samples/Basic/Jasmine/basic-jasmine.js

**Comment by cidthecoatrack** [comment]
WHEW, figured it out!  So apparently, when specifying the resource paths at the top of the file, they have to be relative to Chutzpah, NOT to the test file.  For instance, a test file 5 levels deep had `/// <reference path="../../../../../_resources.js" />`.  Then, it found no tests.  However, if I used `/// <reference path="_resources.js" />`, it worked - because that is the location relative to the harndess/`chutzpah.json`, not to where the test file is.

Now there are different issues (namely that it seems to not be loading Angularjs correctly, but that is not this issue, and I can fix that on my own.  Thank you so much for your patience and help - this really is a great add-on.
