### ISSUE TITLE
Add ability to reach PhantomJS host object through window.callPhantom

### ISSUE THREAD

**Issue by zrajnai** [mmanela/chutzpah#355]
It would be great if you could include the following piece in chutzpahRunner.js

page.onCallback = function(data) {
   eval(data);
}

This would open up the door to changing the host's settings or creating sceenshots etc.

**Comment by zrajnai** [comment]
We found that by default phantomJS uses a window size of 400x300.
We had to modify the beforementioned onCallback, to be able to set the page's viewport to our desired size from our test. 
Running:
 window.callPhantom(" page.viewportSize = {  width: 1280, height: 1024 };"); 
before the first beforeEach works, but modification of chutzpahRunner.js is needed to be able to process 'window.callPhantom' on the PhantomJS host side.

**Comment by mmanela** [comment]
Thanks for filing this. That is an interesting idea. Can you submit a PR?

**Comment by mmanela** [comment]
Also, is there any potential drawbacks to exposing this? Is page.onCallback only called when you run window.callPhantom?

**Comment by zrajnai** [comment]
According to PhantomJS' documentation (http://phantomjs.org/api/webpage/handler/on-callback.html)

"...This callback is invoked when there is a JavaScript window.callPhantom call made on the web page. The only argument passed to the callback is a data object.

Note: window.callPhantom is still an experimental API. In the near future, it will be likely replaced with a message-based solution which will still provide the same functionality.

Although there are many possible use cases for this inversion of control, the primary one so far is to prevent the need for a PhantomJS script to be continually polling for some variable on the web page."

In my example, the data object would simply be a script to be evaluated on the phantomJS host side.

**Comment by mmanela** [comment]
Released in 4.0.2
