### ISSUE TITLE
Add ability to hide jasmine_html-reporter when running in phantomjs

### ISSUE THREAD

**Issue by zrajnai** [mmanela/chutzpah#356]
I was surprised to see that the div ".jasmine_html-reporter" is 'visible' when running inside phantomjs.

Would it be possible to set its style to display:none when not running explicitly with /openinbrowser?
It would be even better if it was not included in the DOM at all (but given that I don't know how chutzpah works, this might not be possible).

**Comment by mmanela** [comment]
Chutzpah is just using the default style and always includes that html reporter. What is the issue with having it included and visible?

**Comment by zrajnai** [comment]
We are doing UI tests where we have div-s with position absolute, that need to be in a known position in client-space.

Currently we call:
$(".jasmine_html-reporter").css("display", "none");
before the first describe(...)
So this limitation can be overcome.

(Yes, we know there other - possibly better - tools for UI testing, but this method fits well into our current infrastructure...)

**Comment by mmanela** [comment]
The odd thing here is a user expects that their tests should pass/fail the same if the run headless vs in the browser. So it seems odd for Chutzpah to act differently there

**Comment by zrajnai** [comment]
You are right. The problem was not with the html-reporter but that the window size of the PhantomJS environment was so small (400x300) that our UI tests stopped working :).

We also use openInBrowser to debug the tests (and having the test reporter there also complicates matters somehwhat...

Anyways having a command line option would be a nice-to-have since this 'problem' can easily overcome.

**Comment by mmanela** [comment]
Would this be solved by the change you proposed in your other issue where Chutzpah could let you set the size?

**Comment by zrajnai** [comment]
Yes.
