### ISSUE TITLE
Code coverage problem since 4.0.2 when the path to _Chutzpah.coverage.html contain a space.

### ISSUE THREAD

**Issue by Trysior** [mmanela/chutzpah#366]
There's a bug in 4.0.2 release when the browser open after the execution of code coverage in visual studio 2013 with the "Chutzpah Test Adapter for Test Explorer".

The bug occur when the _Chutzpah.coverage.html is located in a folder where the path contain a space.

Before 4.0.2 you could use any default browser and it worked all fine. But since the 4.0.2 it only work in Internet Explorer. In other browsers there's two tabs opening; one with the part before the space and one with the part after the space. (In 4.0.1 the path was formatted with %20 for the space but it is no longer this way in 4.0.2)

I tested in 4.0.1 and this bug is not occuring.

**Comment by mmanela** [comment]
Thanks for the comment. I will investigate

**Comment by mmanela** [comment]
Fixed and released in 4.0.3

**Comment by Trysior** [comment]
Thank you for the quick fix! It works.
