### ISSUE TITLE
No test found with TypeScript file

### ISSUE THREAD

**Issue by masselot-guillaume-ext** [mmanela/chutzpah#367]
Hello,
I would like to run a very basic typescript test with Jasmine but I can't get it work.
I'm using Visual Studio 2013 and the chutzpah extension.

the file is typescript.spec.ts :
```javascript
/// <reference path="../scripts/typings/jasmine/jasmine.d.ts" /> 
describe("ts unit test", function () {

    it("should be true", function () {
        expect(2).toBe(2); 
    }); 
});
```

This is what is reported in the Visual Studio Tests Output :
```javascript
------ Discover test started ------

========== Discover test finished: 0 found (0:00:00,5343273) ==========
```

I currently have no more chutzpah.json since none of the settings I tried worked so far.

NB : All tests are discovered and work fine when I write them in a .js file directly but I really need to make them work with typescript files.

If you could help me find out what is the problem it would be appreciated (a lot).
I'm sure it's all about this compile setting but I didn't really understand how it works in my scenario (basic) when I read the doc.

EDIT : 
I have tried to compile/run your MsBuild TypeScript sample and it works. I can't make it work replacing qunit files/references with jasmine ones tho (0 test found)
If i press manually Run JS Test i get a 
Chutzpah Error: ChutzpahCompilationFailedException - 
 While Running:C:\Users\MASSELGU\documents\visual studio 2013\Projects\TypeScriptHTMLApp2\TypeScriptHTMLApp2\chutzpah.json

Could you provide a basic working example just like you did in the samples with Jasmine instead of QUnit? (and eventually the angular.d.ts which i noticed has the same problem as Jasmines one)

EDIT2 : YES !
I did it !
First I had an old typescript version in my PATH environment variable. I had 1.3 before 1.4 so I had to remove the 1.3 ref.
Then I took the chutzpah.config you gave in another topic :
```
{
  "Compile": {
    "Mode": "External",
    "Extensions": [".ts"],
    "ExtensionsWithNoOutput": [".d.ts"]
   },
  "References": [
    {"Include": "app.ts", "Exclude": "app.d.ts" },
    {"Include": "*/src/*.ts", "Exclude": "*/src/*.d.ts" }
  ],
  "Tests": [
    { "Include": "*/test/*.ts", "Exclude": "*/test/*.d.ts" }
  ]
}
```
And it worked !!!!!!!!!
I hope it can help people if they run into the same problem.

Other problem :
I get a reference error : can't find variable: module or angular even tho I include
```
/// <reference path="../scripts/typings/angularjs/angular.d.ts" />
/// <reference path="../scripts/typings/angularjs/angular-mocks.d.ts" />
```
It seems like the test can't find the associated .js files. Did I miss something in the process ?

Plus, is there a difference between the References field in chutzpah.json and the reference in a .ts file ? Do you need one of them ? Both ?

EDIT : I managed to make it work adding the .js (not .ts or .d.ts !) in my chutzpah.json. Is it the right way ?

Guillaume

**Comment by mmanela** [comment]
You need to include a reference to angular itself (and not just the .d.ts file) in your .json file to ensure it is loaded in the harness

**Comment by mmanela** [comment]
I have not heard back about this. I am closing for now but please re-open if the issue still persists.
