### ISSUE TITLE
TFS automated test run with chutzpah.json file

### ISSUE THREAD

**Issue by bgoerdt** [mmanela/chutzpah#368]
I had to create a chutzpah.json file in order for Chutzpah to find all of my tests and run them successfully in Visual Studio 2013. I am trying to get these tests to run during a Gated Check-in with an automated test run, but it doesn't seem to use the chutzpah.json file I created. Only a few of the tests are found and they all fail. Is the chutzpah.json file supported when running an automated build?

**Comment by mmanela** [comment]
It is supported but you need to make sure it is copied with your source files to the folder where the build is running chutzpah from.

**Comment by mmanela** [comment]
Closing since I have heard nothing back. Please re-open if you still have an issue.
