### ISSUE TITLE
Nice to have: config setting to control name of  coverage report file.

### ISSUE THREAD

**Issue by davebrewer** [mmanela/chutzpah#369]
Was trying to tie in different Projects, Coverage Reports into a single Reporting Tab in TeamCity CI. Thus would be great to output the coverage report so that it would output to something which I can control and make common, like: "/coverage/index.html". Currently it's got a fixed name.

Small but nice.
Thanks again,
Dave

**Comment by mmanela** [comment]
Sure, that sounds reasonable.

**Comment by mmanela** [comment]
Fixed in cd15704b14dd1080777ac861339e721931af4cb6. 
When released you will be able to use the Transforms section in the chutzpah json file to specify the "coveragehtml" transform and tell it where to place the file
