### ISSUE TITLE
Is is possible to use an External Compile Setting and have separate Test and Code Projects?

### ISSUE THREAD

**Issue by HintonBR** [mmanela/chutzpah#370]
I have to believe this is possible and I just can't figure out how to make it work.  My Chutzpah.json file is below and is set to use External Compile because we have a Visual Studio solution with an ASP.NET MVC project and a separate Javascript Unit Test project.  The error I get is when it tries to find the following reference which is in the MVC project source.  It then tries to look in the Test project directory for the .js output.  The .js output will generally be right where the .ts file is at - but I can't figure out how to tell Chutzpah to just look in that same location

```/// <reference path="../../../../Atlas/Areas/EdwConsole/AppContent/Scripts/BindingHandlers/JQueryUI.ts" />```

Can't find location for generated path on C:\source\Workspaces\CAP Trunk\Atlas\MVCAtlas\MVCAtlas\Atlas\Areas\EdwConsole\AppContent\Scripts\BindingHandlers\JQueryUI.ts since it is not inside of configured source dir C:\source\Workspaces\CAP Trunk\Atlas\MVCAtlas\MVCAtlas\Catalyst.Apps.Atlas.JavaScriptTests

chutzpah.json
```{
	"Framework": "qunit",

	"TestFileTimeout": "10000",

	"CodeCoverageIncludes": [ ],

	"CodeCoverageExcludes": [ "jquery*.js", "knockout*.js", "ZeroClipboard*.js" ],

	"TestHarnessLocationMode": "Custom",

	"TestHarnessDirectory": "ChutzpahTestRun",

	"RootReferencePathMode": "SettingsFileDirectory",

	"TypeScriptCodeGenTarget":  "ES3",

	"Tests": [ { "Path": "Tests", "Includes": [ "*.ts" ] } ],

	"References": [
		{ "Path": "Scripts", "Includes": [ "*.js" ], "Excludes": [ "*.d.ts" ] }
	],

	"Compile": {
    "Mode": "External",
    "Extensions": [".ts"],
		"ExtensionsWithNoOutput": [ ".d.ts" ],
   }
}```

**Comment by mmanela** [comment]
You should not need the references comments (///). You can do it all with your chutzpah.json file, which it looks like you are trying to do. The one issue I see is in the references section you are includes *.js files but I think you should be doing *.ts like:

```

"References": [
    { "Path": "Scripts", "Includes": [ "*.ts" ], "Excludes": [ "*.d.ts" ] }
],
```
