### ISSUE TITLE
Typescript Breakpoints Fail 

### ISSUE THREAD

**Issue by gravidThoughts** [mmanela/chutzpah#372]
Per `Compile` configuration element.

`This setting lets you describe in the Chutzpah.json file how to execute a command which can compile your source files to .js files. You tell Chutzpah what to execute and some information about what your executable does (like where to find the generated .js files). Then after running the executable Chutzpah can associate each source file with each output file to still give the nice behavior of mapping tests back to their original files.`

I interpret this to mean that the js.map files are utilized properly and therefore breakpoints in the original TS source should work.

Everything else is working properly.

When I place a breakpoint in a Typescript unit test, it fails to break when `Test->Debug->All Tests`.

It also fails to break when right clicking and selecting the Chutzpah menu item to `Open in Browser`.

**Comment by mmanela** [comment]
Chutzpah does not support the VS debugger.
