### ISSUE TITLE
Include external template with extension other than html.

### ISSUE THREAD

**Issue by sirrocco** [mmanela/chutzpah#373]
Hi,

It seems that I can't include a template like : 

    /// <template path="../../Views/myPlan/x.cshtml" />

If I change the extension to `.html` instead of `.cshtml` then it works correctly and the template is included. Am I doing something wrong or is this not supported ?

Thanks.

**Comment by mmanela** [comment]
I think it is not supported currently, but shouldn't be hard to add.

**Comment by sirrocco** [comment]
I'm guessing it's not going to be your top priority :) - can you point me in the general direction of where this fix should be made ?

**Comment by mmanela** [comment]
I *think* the only spot to be changed is here: https://github.com/mmanela/chutzpah/blob/master/Chutzpah/TestHarness.cs#L160

**Comment by sirrocco** [comment]
Thanks much !

**Comment by sirrocco** [comment]
Hi Matthew,

So I fixed the issue locally by adding a `CSHtmlScriptExtension` to the `Constants` class and updating https://github.com/mmanela/chutzpah/blob/master/Chutzpah/TestHarness.cs#L160 and https://github.com/mmanela/chutzpah/blob/master/Chutzpah/TestHarness.cs#L196 .

Now I wanted to submit a pull request but I'm thinking you want this fixed on a more generic level. (or not?) - maybe if we reach the last else, if the file has an extension assume it's an html file or any other text file that the user wants to import.

What do you think ? Should I just submit the pull request for cshtml ?

Thanks.

**Comment by mmanela** [comment]
I was thinking the same thing but wasn't sure the right approach. I think the simplest is just hardcode cshtml for now. I am not sure I like assuming anything referenced is ok to embed into the HTML page

**Comment by jongunter** [comment]
If I have variables/bundles in the cshtml that need to be evaluated, will it render those before chutzpah reads the test harness file?
