### ISSUE TITLE
Default Timeout in chutzpah.json

### ISSUE THREAD

**Issue by mt406** [mmanela/chutzpah#375]
Hi ,

I have below two queries very basic as I have just started and trying to use this tool : 

1)What is default timeout to load test src files ? I am getting timeout error when discovering tests .

2)What we should give in references and path keys of .JSON file ?

Thanks 

Regards
Manish

**Comment by mmanela** [comment]
1. I think the default is 10 seconds to run your test file
2. See https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File

**Comment by mt406** [comment]
For 1) - If we want to wait for endless and make sure all scripts lodaded . What should be given in "TestFileTimeout": "<Timeout in milliseconds>" ? 
I tried setting it 0 but then it was not discovering the test cases and if I do not set it chutzpah loads only 57 of 312 test cases.

On our karma test runner setup we are able to find all 312 test cases .


One more thing : Some test cases are very deep inside folder hierarchy and we used "Include : *.js" but chutzpah was not able to discover any test case then .

What I would be missing in above ?

**Comment by mt406** [comment]
Thanks for the initial reply.. :)
Also need some help regarding three issues I am facing:-
1) I am using VS 2013 with installed chutzpah test adapter and runner. When I build my project the test explorer does not discover the test cases. I have to everytime use "Run All" in test explorer to see the test cases. Also note that I am using require.js in my application and test cases.
2) Some where in my files I am using jquery for DOM manipulation. How do I create DOM elements for the test cases
3) When I run my test cases I am getting "Test adapter sent back a result for an unknown test case. Ignoring result for ..." error and this file test cases are not loaded in test explorer.

Kindly help. thanks in advance ..
Regards
Manish

**Comment by mmanela** [comment]
1. You need to turn on the setting that tells it to discover tests on save or after build. There is a button the the test explorer dialog for this.

2. You have two options. One is two reference an HTML file. Chutzpah will inject that into the page for you. The other option is to manually create the elements as part of a JS file

3. Please give me a repro for #3 and I can check it out.

**Comment by mmanela** [comment]
Closing until user re-opens or provides a repro.
