### ISSUE TITLE
QUnit skipped tests show as passed in Visual Studio

### ISSUE THREAD

**Issue by tjhleeds** [mmanela/chutzpah#378]
I am using Chutzpah to run QUnit tests in Visual Studio Test Explorer. QUnit has a skip function for incomplete tests (https://api.qunitjs.com/QUnit.skip/) and the Visual Studio Test Explorer has a section for Skipped Tests, but tests which are skipped in QUnit show up as Passed in Visual Studio.

**Comment by mmanela** [comment]
Thanks for reporting this. Chutzpah doesn't yet support the skip function. I will look at adding it.

**Comment by mmanela** [comment]
Fixed in fc63f671cb5cc05ffa1451c8fe46645db79e7b1a
