### ISSUE TITLE
Jasmine test fails when run in Chutzpah but not in browser

### ISSUE THREAD

**Issue by troylelandshields** [mmanela/chutzpah#379]
Maybe there is some aspect of this I am not understanding, but I have a test that passes perfectly when I open it in the browser but fails miserably when I run it in Visual Studio. 

Here is a link to [my stackoverflow question](http://stackoverflow.com/questions/31443109/jasmine-test-fails-when-run-in-chutzpah-but-not-in-browser/31443260#31443260) on the subject.

Example code that breaks test:
```javascript
var nameLowerCase = person.PersonName.toLowerCase();
var searchLowerCase= search.toLowerCase();
return (nameLowerCase.includes(searchLowerCase));
```

Error output: 

> Message: TypeError: undefined is not a constructor (evaluating 'nameLowerCase.includes(searchLowerCase)') ...

I solved the issue by using a Regex instead, but thought I'd post it here in case (a) it is a bug or (b) you guys can tell me something I'm doing wrong.

**Comment by mmanela** [comment]
The JS engine which PhantomJS uses does not support the includes method yet.
