### ISSUE TITLE
Chutzpah needs an NPM package!

### ISSUE THREAD

**Issue by lilred** [mmanela/chutzpah#380]
I try not to depend on NuGet for my web projects, especially for SPAs. It would be great if I could use NPM to get Chutzpah!

**Comment by kube** [comment]
+1

**Comment by mmanela** [comment]
You want NPM to just drop the Chutzpah exe?

**Comment by kube** [comment]
Something awesome would be to port your executable for OS X and Linux if there's not too much dependencies to Windows modules.

**Comment by mmanela** [comment]
That sounds interesting, I know of one windows dependency that could be fixed but besides that it should be doable.

**Comment by aersamkull** [comment]
Linux support is very important for me as well as I have a Linux Build server. Is there a way to get it running on Linux?

**Comment by mmanela** [comment]
It is probably possible but will take time to prove out. I know a couple features Chutzpah has that will need to be changed to work on Linux. A couple that I can think of off the top of my head

1. Usage of the native windows method for GLOB patterns. Need to convert the glob to regex instead.
2. The way Chutzpah invokes phantom.exe needs to change to be smart about how to do it on Linux vs windows.
3. Ensure all libraries Chutzpah reference work on Linux.
