### ISSUE TITLE
Doesnt build without VS2012 installed

### ISSUE THREAD

**Issue by tyson-benson** [mmanela/chutzpah#385]
I tried to clone and build (by running build.bat) but it complained about not having the Visual studio 2012 SDK (...VisualStudio/11.0/VSSDK... was missing). Any plans to get this working for dev machines without 2012+2012-SDK installed?

**Comment by tyson-benson** [comment]
Even after i installed VS2012 plus the SDK I receive errors on compilation.

Error	3	'Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase' does not contain a definition for 'Traits' and no extension method 'Traits' accepting a first argument of type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase' could be found (are you missing a using directive or an assembly reference?)	c:\users\tbenson\documents\github\chutzpah\vs2012.testadapter\chutzpahextensionmethods.cs	20	22	VS2012.TestAdapter

Error	2	'Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext' does not contain a definition for 'SolutionDirectory' and no extension method 'SolutionDirectory' accepting a first argument of type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext' could be found (are you missing a using directive or an assembly reference?)	C:\Users\tbenson\Documents\GitHub\chutzpah\VS2012.TestAdapter\ExecutionCallback.cs	90	48	VS2012.TestAdapter

**Comment by tyson-benson** [comment]
Note that I'm running Windows 8.1 Enterprise, now with VS 2012+2013+2015 and the sdk installed for each of them.

**Comment by mmanela** [comment]
You need the most recent update for VS2012. 
I think you can run it without VS2012 but building form the command line won't work.  I will look into if it is easy to make this better.

**Comment by mmanela** [comment]
I pushed a new Solution file Chutzpah.NoVS.sln and changed the default command line build command to use that. This should make it easier for people without the VS sdk installed to be able to build. See b85eaf4b7591da679e0edd6f3cafdc39e3f134e7.

Please try this out and let me know if it worked.
