### ISSUE TITLE
TypeScript and VS 2015 community.

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#388]
I'm not sure if there is an answer as I couldn't make it work.
I did the following:
1. add Chutzpah nuget tools (both).
2. Create a project of type class library
3. removed all references to C#.
4. added jasmine definitely typed from nuget.
4. added a single file called test.ts:
```js
describe("Test", () => {
    it("should be the same", () => {
        expect(2).toBe(2);
    });
});
```
with the following chutzpah.json
```
{
  "Framework": "jasmine",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "Tests": [
    { "Include": "test.ts" }
  ]
}
```
no tests are found in test explorer thus nothing runs...
What am I doing wrong?

**Comment by mmanela** [comment]
Did you install Chutzpah using nuget? The Chutzpah VS integration requires the VSIX install.

**Comment by HarelM** [comment]
Yes, I did. When I added JasmineTest nuget package I was able to see the 5 sample tests (written in js) before adding the json configuration file.

**Comment by mmanela** [comment]
Try changing your tests setting to this:
"Tests": [
    { "Include": "*test.ts" }
  ]

**Comment by HarelM** [comment]
Tired that too, didn't help. Which test framework will be the easiest to setup? Qunit?

**Comment by mmanela** [comment]
Did you build the .ts file and ensure a .js file got generated by VS?

**Comment by HarelM** [comment]
I'm not in front of the PC right now, I'll check later, but I see no reason it should not generate those files. Should I include js files and not ts file in the json?

**Comment by mmanela** [comment]
No you do not need to but I have seen people have issues where the files were not generated

-----Original Message-----

**Comment by mmanela** [comment]
If you confim the .js files are being generated can you create a repo that I can clone that reproduces the issue.

**Comment by HarelM** [comment]
Looks like there was an issue with js file generation. I created another project and VS started generating js file. after some playing around the tests appeared. Thanks for your help!
Is there a way to debug those tests in VS?

**Comment by mmanela** [comment]
The next version of Chutzpah is adding integrated VS debugging support.

**Comment by HarelM** [comment]
Great, keep up the good work! Good luck!

**Comment by HarelM** [comment]
BTW, The reason for this is that I created a unit test project. this project does not create js files for typescript.
here is the link on how to fix this.
http://bartwullems.blogspot.co.il/2014/01/typescript-typescript-files-inside.html

basically adding 
```
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" />
``` 
to the csproj file.
