### ISSUE TITLE
Jasmine-Matchers

### ISSUE THREAD

**Issue by Shavindra** [mmanela/chutzpah#391]
I am trying to add [jasmine matchers](https://github.com/JamieMason/Jasmine-Matchers)  ... but I am not sure how... they are simply not working/referenced?

in my specfile.js I have this
````javascript
   /// <reference path="../../Lib/jasmine/jasmine.matchers.custom.js" />
   /// <reference path="../../Lib/jasmine/jasmine-matchers" />
   /// <reference path="../../Lib/jasmine/matchers/tothrow.js" />
   /// <reference path="../../Lib/jasmine/matchers/tobe.js" />
   /// <reference path="../../Lib/jasmine/matchers/tocontain.js" />

````

**Comment by mmanela** [comment]
Please provide a repo that contains a full repro of this issue.

**Comment by mmanela** [comment]
@Shavindra  ping

**Comment by Shavindra** [comment]
This is while ago. I can't remember the specifics.
