### ISSUE TITLE
Change location of chutzpah.log during tfs build

### ISSUE THREAD

**Issue by arch-imp** [mmanela/chutzpah#392]
I'm trying to diagnose some random failures of qunit tests during our tfs (2013) builds. By turning on tracing, I can get chutzpah (4.0.3) to generate a log file in %TEMP%.

However, our build agents could have multiple instances executing and I'm concerned about multiple runs of Chutzpah writing to the same log file. Is there a configuration option for each instance to write to a different log file?

In addition, is there a way to configure the build to automatically copy the log file to the tfs drop location?

**Comment by mmanela** [comment]
There is not a way to do this right now but I can look into it for a future release
