### ISSUE TITLE
Parallelism setting when running Chutzpah under a TFS build

### ISSUE THREAD

**Issue by arch-imp** [mmanela/chutzpah#393]
We have our TFS (2013) build configured to run javascript qunit tests under Chutzpah (4.0.3) by following [this post](http://blogs.msdn.com/b/visualstudioalm/archive/2012/07/09/javascript-unit-tests-on-team-foundation-service-with-chutzpah.aspx). By default, Chutzpah is executing with a parallelism set to 2 (according to the chutzpah.log generated during a build).

Is there a way to adjust the amount of parallelism? I'd like to set it to 1 to help diagnose some random failures.

**Comment by mmanela** [comment]
You need to set the MaxDegreeOfParallelism property in the .runsettings file:

    <?xml version="1.0" encoding="utf-8"?>
    <RunSettings>
     <ChutzpahAdapterSettings>
       <MaxDegreeOfParallelism>2</MaxDegreeOfParallelism>
     </ChutzpahAdapterSettings>
    </RunSettings>

See https://github.com/mmanela/chutzpah/wiki/Running-Unit-Tests-in-a-TFS-Build

**Comment by arch-imp** [comment]
That works, thanks!
