### ISSUE TITLE
Can't get code coverage

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#394]
Hi,
Thanks a lot for helping me before with my issue, your help is greatly appreciated.
I'm working on the following project:
https://github.com/IsraelHikingMap/Site
I have managed to add my first 4 unit tests and wanted to check out the code coverage.
I'm pretty sure I'm configuring something wrong but I'm not sure what.
there are currently two project in the above repository, one with code and the other with one test class, which checks one service class.
I was able to run the tests and they pass but when I configure the code coverage I either get timeout or that no files where covered.
Can you please take a look?
below is the config json just in case, I tried many inputs for the exclude and include of the code coverage but non helped, this is the final version I used which still doesn't work.
```
{
  "Framework": "jasmine",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [],
  "Tests": [
    { "Include": "*/*tests.ts" }
  ],
  "EnableCodeCoverage": true,
  "CodeCoverageIncludes": ["..\\isrealhiking.web\\services\\heightservice.*"]
}
```

**Comment by mmanela** [comment]
Two things

1. EnableCodeCoverage is a badly named property which I plan to change. Setting EnableCodeCoverage to true means ALWAYS run code coverage. While leaving it out means only run code coverage when you tell chutzpah to (through command line /coverage flag or ide menu)

2. Try to change to

  "CodeCoverageIncludes": ["*\\isrealhiking.web\\services\\heightservice.*"]

**Comment by HarelM** [comment]
1. Yes I figured that much, but it didn't seem to do anything without it, not even open the browser with empty jasmine coverage results, so I left it hoping it would help...
2. Thanks, this seems to fix it, the whole / and \\ is very confusing. I can swear I have tried this version in one of my attempts (probably not since this did make it work and my attempts didn't).

You can close this issue, but I would advise a less fragile mechanism, it seems like every little change cause this harness to break and I couldn't find any logs in VS to indicate what went wrong.
You are free to use my project/copy from it as an answer to developer like me to show how to test Chutzpah + Angular + TypeScript.

Keep up the good work!

**Comment by mmanela** [comment]
Thanks for the feedback. Both / and \ would work the issue is that you either need to know the full relative path prefix or put the wildcard at front. But I do agree it is hard to get right.

I would love more feedback about "every little change causes this harness to break". That concerns me and want to understand more what you mean.

**Comment by HarelM** [comment]
Please don't get me wrong, I Think that what you are doing is very important and is appreciated.
I'll try and explain my thought and feelings hoping it will make this project better and not insult you in any way.
I'm a very seasoned developer and from time to time I take a project in a language I'm not familiar with in order to better understand it for my personal career and also my enjoyment (I truly love developing).
So trying new thing is in my nature and I can say that I'm stubborn enough to make things work most of the time.
When adding to my project Chutzpah I was sure it will be a matter of a few minutes, an hour top, to make it work but that was not the case.
I tend to try-out a lot of things in order to make things work (writing an issue here is my last resort), but in this case It didn't feel like my attempt are getting me somewhere.
I did get a lot of "time out" from the test discovery when things are not defined correctly.
When I added all the js references file I got some error which are probably related to the order the files are referenced.
When adding the references in the config I wasn't sure relative to what and so I ended up adding the references in the tests itself...
If there is a problem in the beforeEach code the discovery fails.
I can probably blame myself for most of the issues, but still, the feeling I got is that I need to "behave" in order to make the tests available and runnable, I would expect the harness to allow me to do foolish stuff and let me know about it when I try and run the relevant tests.
That's my two cents...

**Comment by mmanela** [comment]
I think you mistook by tone. I am happy to get any feedback. It is great when someone takes the time to give good constructive feedback, I totally appreciate it. I love to work with the people who have these issues fresh in their mind to try to figure out how can we make the product better and more intuitive. 

Addressing some of your points

1. The relative path issue can be confusing. Chutzpah tries to do a lot to make it just work. In most cases just assume paths are relative to the location of the Chutzpah.json file BUT chutzpah will try to go logic internally to resolve based on multiple paths it is aware of. 

2. The feedback about errors just taking the whole test harness down is one I deal with a lot. I am trying to find a way to make this less difficult but there is a fundamental problem. Chutzpah is relying on the user to be able to set up all the reference enough so the HTML file can even run. If that is not done then it will error out fast and Chutzpah can't give results. Maybe Chutzpah can do a much better job in reporting the errors. What kind of errors would have made it easier for you?

**Comment by HarelM** [comment]
When trying to run/discover the test my main window was the VS output window.
Errors that would've help me (I think) could've been letting me know what happened. for example "Chutzpah is looking for reference files in <folder name>" - assuming I added reference path/file to the list - this way I can know it is not looking in the right place and change the reference accordingly.
"Timeout was caused due to <some reason the user can do something about>".
In general error messages that can help the user know better what went wrong.
Or "There were error discovering the test, Please look in the log file at <some location> for more information".
Remove errors that do not help the user, for example an error I have encountered while writing these lines (my 4 tests are showing and everything is OK yet I got this error):
```
------ Discover test started ------
Error: TypeError: Attempted to assign to readonly property.
in file:///c:/develop/github/israelhikingmapsite/isrealhiking.web/scripts/angular-mocks.js (line 17)
While Running:c:\develop\github\israelhikingmapsite\isrealhiking.web\scripts\angular-mocks.js
```
I know this is not so constructive and I don't really have good ideas, but as I user I would like to know in what stage failed, what could have caused it and what property in the json file I should be looking at in order to try and fix it.

**Comment by laxmiakntkalkote** [comment]
Hello , 
I am also not able to run code coverage giving following error:

Error: Error: Line 510: Duplicate data property in object literal not allowed in strict mode

Error: Error: error loading source script..

and my chutzpa.js is:

{
    "TestFileTimeout": 120000,
   

    "CodeCoverageExcludes": [ "*\\*.min.js", "*\\*mocks.js", "*\\*Test.js", "*\\*bundle*.js"],
    "References": [
        {
            "Path": "../Common/CommonUI/scripts/jquery-2.1.4.min.js"
        },
        {
            "Path": "../Common/CommonUI/scripts/angular-bundle.js"
        },
        {
            "Path": "../Common/CommonUI/scripts/angular-ui-bundle.min.js"
        },
        {
            "Path": "../Common/CommonUI/scripts/lodash.min.js"
        },
        {
            "Path": "../Common/CommonUI/Scripts/angular-mocks.js"
        },
        {
            "Path": "../Common/CommonUI/scripts/kendo-bundle.min.js"
        },
        {
            "Path": "../Common/CommonUI/Modules",
            "Include": "*.js",
            "Exclude": "*Directive*" // We don't write unit tests against directives.
        },
        {
            "Path": "../Aclara.iiDEAS.UI/Modules",
            "Include": "*.js",
            "Exclude": "*Directive*" // We don't write unit tests against directives.
        }
    ]
}

i am facing this problem since last 2 days.

2 days before code coverage was working properly.

could u please check and let me know ?

Thanks in advance...

**Comment by mmanela** [comment]
Can you provide a full repro?
