### ISSUE TITLE
Extension point to replace phantomJs

### ISSUE THREAD

**Issue by ts46235** [mmanela/chutzpah#397]
Hello, we have been using Chutzpah for over a year and have come up with limitations with phantomJS. We need to execute tests in diff browsers instead of headless phantomJS. Is there any extension point available to replace that with execution in a particular browser (chrome, FF, IE, etc) like we can with Karma? Any plans for this feature or recommendations in the meantime?

Thanks!

**Comment by mmanela** [comment]
I have had this request before but have not had time to implement it. Chutzpah is currently hard-wired to only run with PhantomJS. If you are interested I would love to work with you on making this change.

**Comment by rposener** [comment]
+1 any reason we couldn't use node to execute tests instead of phantomjs?

**Comment by EfrainReyes** [comment]
FYI the Phantom JS maintainer is stepping down https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

**Comment by aaron00401** [comment]
Does the Phantom JS maintainer stepping down going to have any effect on the development path of Chutzpah?

**Comment by mmanela** [comment]
Yep, Chutzpah will need to adopt the headless chrome. I have not yet looked at the scope of that work but it is not small. I am hoping someone in the C# community can bridge the gap with a library to make using Headless chrome as easy. But I have not seen this yet.
