### ISSUE TITLE
Include files for code coverage but exclude from summary

### ISSUE THREAD

**Issue by stogle** [mmanela/chutzpah#404]
I would like to exclude my test files and mocks from code coverage, but when I add them to CodeCoverageExcludes in chutzpah.json, my tests fail as in Issue #264 because the file load order changes. The only reason I care to exclude these files is that they inflate the "Average Coverage" number that Chutzpah outputs at the top of its Code Coverage results.

I know it sounds like a bit of a Kluge, but would it be possible to add the option to exclude files not from blanket.js but from the Code Coverage *results* created by Chutzpah (including the all import "Average Coverage" number). This would give me correct output without having to worry about dependencies.

**Comment by miparnisari** [comment]
Will this issue be fixed soon?
