### ISSUE TITLE
Chutzpah references are included twice

### ISSUE THREAD

**Issue by danicomas** [mmanela/chutzpah#405]
Could exist a variable in chutzpah.config to discard the ///references previously added and could it work together with ExpandReferenceComments=true? @mmanela @provegard @hallipr

**Comment by mmanela** [comment]
I am not sure I follow what you mean. Could you give me an example of the issue you are hitting?

**Comment by mmanela** [comment]
Closing since I have not heard back. Can reopen if response comes.
