### ISSUE TITLE
Chutzpah includeOnlyFirstLevelOfChilds attribute

### ISSUE THREAD

**Issue by danicomas** [mmanela/chutzpah#406]
A good way would be to make an attribute includeOnlyFirstLevelOfChilds this attribute only would import the child references but only this level 
///<reference path="x.js" includeOnlyFirstLevelOfChilds="true"

x.js:
///<reference path="a.js"
///<reference path="b.js"

a.js
///<reference path="ab.js"

Imported in head: x, a, b
omitted: ab.js

**Comment by mmanela** [comment]
I am generally encouraging people to use the chutzpah.json to manage references instead of reference comments. Does that not work for your scenario?

**Comment by mmanela** [comment]
Have not heard any response for months. Closing ...
