### ISSUE TITLE
Tests are throwing exception when running through TFS Continuous Integration. 

### ISSUE THREAD

**Issue by muralinit** [mmanela/chutzpah#408]
Hi Manela,

Thank you so much for the wonderful framework. It is really helping a lot of people to achieve TDD. I am facing an issue while executing my unittests in tfs build. This is the below exception message.

Error: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.File.ReadAllText(String path)
   at Chutzpah.Wrappers.FileSystemWrapper.RetryT
   at Chutzpah.TestHarnessBuilder.CreateTestHarness(TestContext testContext, TestOptions options)
   at Chutzpah.TestRunner.<>c__DisplayClassc.<ExecuteTestContexts>b__b(TestContext testContext)
While Running:d:\a\bin\_PublishedWebsites\WebApp\Angular.Tests\testAngular.js

If you can help me in resolving this issue, it would help me a lot. I need to demo this to my team to get approval that we can integrate Chutzpah in TFS. 

Thanks & Regards,
N.Murali Krishna.

**Comment by mmanela** [comment]
Can you please provide a small repro that demonstrates this error?

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
