### ISSUE TITLE
Open in Windows Edge browser not working

### ISSUE THREAD

**Issue by vkomphasouk** [mmanela/chutzpah#413]
I have Chutzpah installed on Windows 10 and Visual Studio 2015. Since my default browser is Edge, when I run 'Open in browser', Edge opens up a blank page. I can however, copy the link into IE or Chrome and it runs perfectly fine. Anyone else having this issue?

**Comment by mmanela** [comment]
Yes, Edge does not render the local webpage currently. I am investigating if there is anything Chutzpah can do to fix this or if this is a Edge bug.

**Comment by mmanela** [comment]
In the next version Chutzpah will support server webpages which will resolve this issue.
