### ISSUE TITLE
Erroneous chutzpah.json Samples

### ISSUE THREAD

**Issue by teetotum** [mmanela/chutzpah#415]
Just wanted to let you know about some samples I found here today in the documentation that do not match their corresponding *"table of supported settings"*:

**Chutzpah.json Settings File**
https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File
One example contains the line `"TypeScriptCodeGenTarget" : "ES5",`, but the property *TypeScriptCodeGenTarget* is not listed among the supported properties at the beginning of the article.

**Compile Setting**
https://github.com/mmanela/chutzpah/wiki/compile-setting
All examples in that article contain settings for *References* and *Tests* in the form of:
```
"References": [
   {"Include": "**/src/**.ts", "Exclude": "**/src/**.d.ts" }
 ],
 "Tests": [
   { "Include": "**/test/**.ts", "Exclude": "**/test/**.d.ts" }
```
But according to the tables of supported properties in the respective articles for *References* and *Tests* the `Include` / `Exclude` must actually be `Includes` / `Excludes`.

**Comment by mmanela** [comment]
Thanks, I will update those samples
