### ISSUE TITLE
Specify Url parameter

### ISSUE THREAD

**Issue by yarkul** [mmanela/chutzpah#417]
Add possibility to set Url parameter. Would be great for UI tests. Question added here:
http://stackoverflow.com/questions/33016477/how-to-run-ui-tests-in-visual-studio-with-phantomjs-qunit-and-chutzpah

**Comment by mmanela** [comment]
Chutzpah already support running on a url. See [running on a remote url](https://github.com/mmanela/chutzpah/wiki/Running-against-a-remote-url).

Does that work for what you want?
