### ISSUE TITLE
Compile Setting For PowerShell Script - Doesn't Seem to Attempt to run

### ISSUE THREAD

**Issue by jeremye416** [mmanela/chutzpah#419]
I'm attempting to compile my angular templates via a powershell script executed from Chutzpah. It doesn't seem like the powershell script is even attempting to run (no errors, no entries in the log output). I'm using Visual Studio 2015 with Chutzpah 4.1.0. The javascript tests do run.

Could you help tell me what I may be missing?

Here are the contents of my Chutzpah.json:

{
  "Framework": "jasmine",
  "CodeCoverageIncludes": ["*/Application/*"],
  "CodeCoverageExcludes": [ "*/requireConfig.js", "*/Assets/*", "*/JavaScript.Tests/*" ],
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "TestFileAdjacent",
  "EnableCodeCoverage": "",
  "AMDBasePath": "../../WebSite/Scripts",
  "Compile": {
    "Mode": "Executable",
    "SkipIfUnchanged": false,
    "Extensions": [ ".html" ],
    "ExtensionsWithNoOutput": [ ".html.js" ],
    "SourceDirectory": "../../WebSite/Templates",
    "OutDirectory": "../../WebSite/Templates",
    "Executable": "%powershellexe% ",
    "Arguments": "-NoProfile %chutzpahsettingsdir%\\compile-template.ps1"
  },
  "References": [
    { "Path": "requireConfig.js" },
    {
      "Path": "../../WebSite/Templates/",
      "Include": "*.html.js"
    }
  ],
  "Tests": [
    { "Path": ".", "Include": "*Spec.js" }
  ],
  "TestFileTimeout": 10000
}

**Comment by mmanela** [comment]
Can you give me a working repo that I can clone and run to test?

**Comment by jeremye416** [comment]
I can't send you the actual repo. It's for a client under a NDA.

I could send you elements of the source code that could help. JavaScript
source code? Unit test source code? Maybe log files?

One other interesting piece is that the tests/chutzpah runs in a visual
studio project. The template that I'm attempting to compile (and all the
javascript I'm testing) is in a separate MVC web project.

Any pieces, other than the actual repo, that would help?

**Comment by mmanela** [comment]
Could you build a repro that captures the essence of the issue?

**Comment by jeremye416** [comment]
I'll attempt to. First, I'm going to download the source code and debug it
in visual studio to try to figure out what's going on.

The environment is complex, so I'm not sure what the underlying issue may
be.

I mainly wanted to see if there was anything obviously wrong with the
configuration file.

**Comment by jeremye416** [comment]
I've resolved the problem. I had to remove the "Include": "*.html.js" from the References. Because the powershell script was going to compile the html file, it would never get picked up. Once I removed the Include parameter, the script was executed.

BEFORE: 
"References": [
        { "Path": "./path/to/templates/", "Include": "*.html.js" },
    ],

AFTER: 
"References": [
        { "Path": "./path/to/templates/" },
    ],
