### ISSUE TITLE
Support tagged template strings

### ISSUE THREAD

**Issue by styfle** [mmanela/chutzpah#423]
I wrote a unit test for a new ES6 feature called [tagged template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings) however it appears that this syntax is not supported.

```js
QUnit.test("Common.sanitize", function (assert) {
    var world = 'Earth';
    var output = Common.sanitize `Hello ${world}`; // backticks
    assert.equal(output, 'Hello Earth');
});
```

The entire module fails to run with the following error:
```
Error: SyntaxError: Invalid character: '`'
```

[Chrome](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings?hl=en) supports this feature already so presumably Chutzpah is built on top of chrome and can update, correct?
Please add support :smiley:

**Comment by mmanela** [comment]
Chutzpah it built on top of [PhantomJS](http://phantomjs.org/) so it is bound by that that program supports. Please file a request on the PhantomJS github page.

**Comment by styfle** [comment]
@mmanela Thanks for the quick reply. I'll poke the PhantomJS team to see where they are at with ES6.
