### ISSUE TITLE
No _Chutzpah.coverage.json after upgrading to 4.1.0

### ISSUE THREAD

**Issue by eilefh** [mmanela/chutzpah#424]
When I used the /coverage option in version 3.2.5 it produced both a _Chutzpah.coverage.html and _Chutzpah.coverage.json file.
After upgrading to 4.1.0 only _Chutzpah.coverage.html is produced
Is there a way to get Chutzpah 4.1.0 to generate the .json file too?

**Comment by mmanela** [comment]
I had removed that in favor of the chutzpah transforms which support the more standard LCOV format (https://github.com/mmanela/chutzpah/wiki/Transforming-Output). However, if you feel strongly about the chutzpah json format I can add it back

**Comment by eilefh** [comment]
OK, It would be of great benefit to me at least if json was an option for the transform, but definitely not a showstopper.
I used the json output to put the result of a CI build into a data warehouse regularly so that we can monitor the coverage history. I can change my analyzer to use another transform if necessary.

**Comment by alaney** [comment]
My team also uses the json output to parse coverage. If I can get the same thing from the trx format that would be fine...but I don't see the coverage information there.

**Comment by ffMathy** [comment]
I find this to be pretty important as well. JSON is a much more universal and easy-to-parse format.

**Comment by mmanela** [comment]
Thanks everyone for the feedback. I will make sure to add back the json format in the next release. It will be another transform option in the transform config.

**Comment by mmanela** [comment]
Fixed and will be part of next release. I added back the JSON but it is not part of the Transforms config. So you can add to your chutzpah.json file a transform section like:


```
{
    "Transforms": [
        { "Name":  "coveragejson", "Path":  "myCoverage.json" }
    ]
}
```

To output the coverage json file.
