### ISSUE TITLE
Code coverage html showing compiled JavaScript code instead of TypeScript files

### ISSUE THREAD

**Issue by halybee** [mmanela/chutzpah#425]
Hi,  

I execute the test coverage feature like so:
chutzpah.console.exe /coverage /path ../../../chutzpahtest/appTest.ts

When I open the coverage report, and click on a .ts file, the compiled JavaScript is shown instead. Is there a way of seeing the original TypeScript code?

Thanks!

**Comment by mmanela** [comment]
There is a UseSourceMaps setting listed here: https://github.com/mmanela/chutzpah/wiki/Compile-Setting
