### ISSUE TITLE
TFS 2015 test publish of trx - namespace issue

### ISSUE THREAD

**Issue by wtjones** [mmanela/chutzpah#426]
I am able to publish the chutzpah trx files via MSTest just fine. We are trying to use the "Publish Test Results" step in the new TFS build system (https://msdn.microsoft.com/en-us/Library/vs/alm/Build/feature-overview), but get this error:

```
Failed to publish test results: 'ns' is an undeclared prefix. Line 2, position 10.
```

The normal VS test runner creates trx files with this in the <TestRun> attributes:

```
xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010"
```

Chutzpah, in addition, puts this:

```
 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
```
If we manually remove these attributes, it works fine. I'm not sure why the new TFS build complains about this. A flag to exclude these declarations (or just exclude by default) should resolve the issue.

**Comment by mmanela** [comment]
Is there any issue always excluding them?

**Comment by Bebo2345** [comment]
I'd vote for always excluding them! :-)

**Comment by wtjones** [comment]
I can't think of any issues.

**Comment by mmanela** [comment]
Fixed, will include in next release.

**Comment by carlin-q-scott** [comment]
This issue pops up in case of test failures. If needed I can attach a trx showing the issue.

**Comment by mcnallys** [comment]
I have the same issue as @carlin-q-scott 
<Message xmlns:q2="http://www.w3.org/2001/XMLSchema" d6p1:type="q2:string" xmlns:d6p1="http://www.w3.org/2001/XMLSchema-instance">

should just be
<Message>

**Comment by ClydeDz** [comment]
+1

Have updated to 4.4.2 and the .trx file doesn't publish to the test results pane. Any specific configurations required?

![image](https://user-images.githubusercontent.com/13506613/46897988-7b380600-cee2-11e8-8ea4-4998c74d1c5e.png)

**Comment by mmanela** [comment]
Nothing has changed in the XML generation here in a long time. The original issue here was that the NS was missing. @mcnallys , you are saying that is not needed?

I am not an expert on this so I would love someone to validate what the right change here is and propose it :)
