### ISSUE TITLE
Using chutzpah when compiling multiple .ts files to a single .js

### ISSUE THREAD

**Issue by halybee** [mmanela/chutzpah#427]
Hi,

I have a VS solution with multiple projects and each project compiles to a single .js file.
I read here https://github.com/mmanela/chutzpah/issues/313#issuecomment-73417856 that Chutzpah doesn't fully support this.

Have there been any changes/updates/fixes since February (time of the post) allowing to use Chutzpah with this kind of setup?

Thanks!

**Comment by mmanela** [comment]
I have not done anything yet but plan to look at this for the next release. If you have a sample project to ensure I hit your scenario with my fix, that would be greatly appreciated.

**Comment by mmanela** [comment]
@halybee I am looking into improvements here. Can you share a repo showing what you are doing so I can ensure I am covering that use case?

**Comment by mmanela** [comment]
I committed a change that lets you have multiple files combine to one. Take a look at the following sample: https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation/TypeScriptToSingleFile But in short the next release will support the following chutzpah.json:

```
{
  // Batching is required to make this work if you are included your test files in the 
  // merged js file. Otherwise, Chutzpah will double count tests
  "EnableTestFileBatching": true,
  "Compile": {
    "Extensions": [".ts"],
    "ExtensionsWithNoOutput": [".d.ts"],
    "Executable": "compile.bat",
    "UseSourceMaps": true,
    "Paths" : [

      // Map all source files to the single merged output file
      { "OutputPath": "_out/merged.js" }
    ]
   },
  "References": [
    {"Includes": ["*/src/*.ts"], "Excludes": ["*/src/*.d.ts"] }
  ],
  "Tests": [
    { "Includes": ["*/test/*.ts"], "Excludes": ["*/test/*.d.ts"] }
  ]
}
```
