### ISSUE TITLE
Test discovery fails if JS tests reside in project with .js. in name

### ISSUE THREAD

**Issue by objarni** [mmanela/chutzpah#428]
It seems the Discovery process of Chutzpah fails if the project containing the JS test has a name with "JS" (or possibly ".JS.") in it.

Here is the output in Output/Tests window of VS2015:

````
----- Discover test started ------
Error: Timeout occurred when executing test file
While Running:c:\CENSORED\development-branches\dev-vs15-olof\src\projects\CENSORED.web.ui.js.test\tests\testchutzpah.js

========== Discover test finished: 0 found (0:00:12,206) ==========
```
Note path of project: **CENSORED.web.ui.js.test**.

Relevant section of **%temp%\chutzpah.log:**

```
vstest.discoveryengine.x86.exe Information: 0 : Time:16:34:18.6252807; Thread:11; Message:Phantom Log - onPageLoaded
vstest.discoveryengine.x86.exe Error: 0 : Time:16:34:18.6332807; Thread:11; Message:Eror recieved from Phantom Error opening c:/CENSORED/development-branches/dev-vs15-olof/src/projects/CENSORED.web.ui.test/tests/testchutzpah.js: The system cannot find the path specified.
```

Notice how the project name, **CENSORED.web.ui.test** does not contain ".js" anymore!

My guess is that something inside of Chutzpah/Test adapter (or possibly the Visual Studio test discovery subsystem) assumes Visual Studio project names do not contain ".js" in them - maybe even doing some "string".replace(".js", "") hack somewhere? :)

Workaround
==========
Rename test project to something that does not contain ".js." in the name, both project name and physical path.

**Comment by mmanela** [comment]
I tried to repro but could not. Here is the project I used: https://github.com/mmanela/repro_chutzpahDottedPath

**Comment by objarni** [comment]
Thanks for trying to reproduce. I could try to narrow down later today and attach the chutzpah.json I'm using.

Hunch: AMD path/mode is used in the config (aswell as reference to require js). Might the be some path rename/replace magic with regard to amd mode?

**Comment by mmanela** [comment]
Maybe, please try to create a minimal repro for me.

**Comment by objarni** [comment]
Yes I will try. I got it today using jasmine amdbasepath and some more settings but will try to minimise things tomorrow.

**Comment by objarni** [comment]
I forked your repo and reproduced problem by using Jasmine + AMD test harness loading.

https://github.com/objarni/repro_chutzpahDottedPath

However, I'm not 100% this the same problem as I had in real solution. I looked around in the Chutzpah source, and found this function in part of the jasmine test loader functionality:

```javascript
        collectPageScripts: function(){
            var toArray = Array.prototype.slice;
            var scripts = toArray.call(document.scripts);
            var selectedScripts=[],scriptNames=[];
            var filter = _blanket.options("filter");
            if(filter != null){
                //global filter in place, data-cover-only
                var antimatch = _blanket.options("antifilter");
                selectedScripts = toArray.call(document.scripts)
                                .filter(function(s){
                                    return toArray.call(s.attributes).filter(function(sn){
                                        return sn.nodeName === "src" && _blanket.utils.matchPatternAttribute(sn.nodeValue,filter) &&
                                            (typeof antimatch === "undefined" || !_blanket.utils.matchPatternAttribute(sn.nodeValue,antimatch));
                                    }).length === 1;
                                });
            }else{
                selectedScripts = toArray.call(document.querySelectorAll("script[data-cover]"));
            }
            scriptNames = selectedScripts.map(function(s){
                                    return _blanket.utils.qualifyURL(
                                        toArray.call(s.attributes).filter(
                                            function(sn){
                                                return sn.nodeName === "src";
                                            })[0].nodeValue).replace(".js","");
                                    });
            if (!filter){
                _blanket.options("filter","['"+scriptNames.join("','")+"']");
            }
            return scriptNames;
        },
```

There is a replace(".js", "") in there - would it not replace all parts of a path, e.g. if '.js' was part of a folder name?

**Comment by mmanela** [comment]
That is in the code coverage plugin I use, Do you see this issue only when using code coverage?

**Comment by mmanela** [comment]
@objarni ping

**Comment by objarni** [comment]
I never tried the code coverage tool. Note the replace was found in more than one place I just copied first I found.

**Comment by mmanela** [comment]
I am still unable to repro. The sample you gave me does not work regardless of .js in the path. In order to try to repro with requirejs I took this sample (https://github.com/mmanela/chutzpah/tree/master/Samples/RequireJS/Jasmine) and renamed Jasmine folder to Jasmine.js and it worked fine.

**Comment by objarni** [comment]
Hi,

OK, I'm not involved in the project where this was a problem, where renaming a .JS (Note: capital letters) folder name to .JavaScript was a workaround.

IIRC the name of the folder was along the line of

CompanyName.Component.Web.JS.Tests
(or possibly .Test)

Did you try capital letters (JS) in your attempt to reproduce?

**Comment by mmanela** [comment]
Yea and that works too

**Comment by objarni** [comment]
Ok - I guess it might have been something in that projects environment then. 

I think enough time has been spent trying to reproduce this so closing ticket would be OK with me.

**Comment by mmanela** [comment]
Ok thanks you for being so responsive. Let me know if you hit any other issues.
