### ISSUE TITLE
VS2015 Task Running Explorer fails with permission error when Text Explorer extension is enabled

### ISSUE THREAD

**Issue by pcavacas** [mmanela/chutzpah#429]
In VS 2015 when the Test Explorer extension is enabled with Chutzpah tests in them then running a clean job (which deletes files) fails with a permissions or file in use error.

error message below
[13:11:02] Error: EPERM, unlink 'C:\Projects\CustomerMaintenance\src\CustomerMaintenance\wwwroot\app\directives\CustomerDetails'

I can run the same job before the Test Explorer window loads and it works fine.  Also I can run the same job as many times as I want with the "Chutzpah Test Adapter for the Test Explorer" disabled without issue.

I can use the right click to run the tests all of the time without issue.  My guess is that the Test Explorer extension is holding a reference to a file and the "clean" job is trying to delete that file.  The clean job is using rimraf to remove all files and folders from a directory.

**Comment by mmanela** [comment]
I am confused about your scenario? What does chutzpah have to do with your job?

**Comment by pcavacas** [comment]
The error only happens when I have the "Chutzpah Test Adapter for the Test Explorer" enabled.  If the Adapter is enabled then the error happens, if I disable it then there is no problems.

**Comment by mmanela** [comment]
Can you please provide a repro?

**Comment by pcavacas** [comment]
Here is the ASP.NET 5 VS2015 project that I'm using.  I have stripped out the bower_components and node_modules, so that it would be smaller, but they should be able to be pulled in automatically by VS.  If you build the project when it first opens you can see that the Task Explorer run fine without issues.  If you then use the Test Explorer Window to run the various chutzpah tests those will run as well.  Now if you go and build the project again you will see that you get the EPERM error in the Task Explorer window.  Now if you go in and disabled the Chutzpah Test Explorer extension for VS then build the project you will see that the Task Running window works without issue.

It won't let me attach a ZIP file to this issue, so how would you like me to send this to you.

**Comment by mmanela** [comment]
Create a github repo and link to it please

**Comment by mmanela** [comment]
Any update on the repro?

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
