### ISSUE TITLE
Chutzpah fails build with tests marked "xit"

### ISSUE THREAD

**Issue by bluerv** [mmanela/chutzpah#430]
This is probably easy, but, I did a search and came up empty.  We have been using the Chutzpah integration in Visual Studio for a while, and it works great.  We just got Chutzpah installed and running on the server, and it almost works.  If all tests pass, we're good, if all tests fail, we're good (i.e. it tells us exactly what failed... perfect).

But... if any of the tests are marked "xit" which, based on the jasmine documentation should disable the tests, the build fails with this message:

Error: Spec 'spec name here' has no expectations.
at specDone in file:///C:/<path here>/packages/Chutzpah.4.1.0/tools/TestFiles/jasmine/v2/jasmine-html.js (line 105)
While Running:...

These tests are, as expected, marked as ignore when we execute them locally.

This should be super easy, I'm sure, but, we don't see a switch for this.

Help?

Details:
Visual Studio 2013
TFS 2012
AngularJS 1.4.3
Jasmine 2.2.0

We are using typescript (latest version... 1.5 I think), but, the tests are running fully under javascript so I don't believe that to be the issue or related.  (I.e. the js files are checked into the solution).

**Comment by mmanela** [comment]
I am not sure. I made a simple test with XIT and chutzpah worked correctly:

```
describe("Skipped Tests", function () {
    xit("Skipped", function () {
        expect(false).toBeTruthy();
    });

```

And this was the output:

```
------ Test started: File: C:\Dev\chutzpah\Facts.Integration\JS\Test\Skipped\skippedJasmine.js ------
0 passed, 0 failed, 1 skipped, 1 total (chutzpah).

========== Total Tests: 0 passed, 0 failed, 1 skipped, 1 total ==========
```


Could you build a repro that I can download and run to see your issue?

**Comment by bluerv** [comment]
Probably... how complete do you want the repro?  Just the jasmine test?  or, an entire visual studio project?  Or something else?

Just to restate:  locally, this works exactly right, it's just on the server that it's behaving weirdly.

------ Test started: File: d:\2012Devel\AccessExpress\branches\dev\AccessExpressPoC\Tests\Account\controllers\AccountInfoSetupSpec.js ------
------ Test started: File: d:\2012Devel\AccessExpress\branches\dev\AccessExpressPoC\Tests\Account\controllers\AccountInfoSetupSpec.ts ------
------ Test started: File: d:\2012Devel\AccessExpress\branches\dev\AccessExpressPoC\Tests\Account\controllers\AccountInfoSetupSpec.d.ts ------
0 passed, 0 failed, 0 total (chutzpah).

0 passed, 0 failed, 0 total (chutzpah).

10 passed, 0 failed, 1 skipped, 11 total (chutzpah).

========== Total Tests: 10 passed, 0 failed, 1 skipped, 11 total ==========

**Comment by mmanela** [comment]
Oh, you probably have an older Chutzpah version on the build server

**Comment by bluerv** [comment]
In looking at what I posted earlier, I think we are using the latest version?
file:///C://packages/Chutzpah.4.1.0/tools

Is 4.1.0 not the latest?

(Or, maybe, how do I know what version is on the server?  I'm assuming that path tells me, but, maybe I need to check something else?)

**Comment by bluerv** [comment]
I apologize.  I'm going to close this.  The issue is completely different than what I thought.  There is an issue (a difference between the server and the client) but it's unrelated to "xit".  I need some time to work on a sample for you for this.  (And the issue is not as severe I wouldn't think... just... an anomaly.)
