### ISSUE TITLE
Does Chutzpah support the Team Build Test Filter syntax?

### ISSUE THREAD

**Issue by jessehouwing** [mmanela/chutzpah#432]
I know that I can configure Chutzpah to run multiple times by pointing it to different chutzpah.json files containing the test configuration.

I wonder whether Chutzpah supports the Test Filter syntax which NUnit and MsTest support. I've written a blog post about this in the past and have been trying to make it work for other frameworks. I understand that certain attributes may translate badly, but others should be no problem.

More information:
- http://blog.jessehouwing.nl/2015/01/staged-execution-of-unit-tests-on-team.html

**Comment by mmanela** [comment]
What would an attribute map to in Javascript and mocha/qunit/jasmine?

**Comment by jessehouwing** [comment]
At least file name, test name, name space (nested functions?) could be supported easily.

Attributes could map to decorators? https://github.com/cmartin81/decorator-wrap

Or /// style comments

```
/// <category>critical</category>
/// <priority>critical</priority>
```

This would all be something on top of what these frameworks support out of the box and be specific to Chutpah to support these features of Visual Studio and TFS and the commandline test runner.

**Comment by mmanela** [comment]
I like the decorator idea but I am not sure if they are supported in PhantomJs 2.0. 
The comment approach is probably safer since this is a chutzpah specific feature. That would be doable. 

Are you interested in contributing this to Chutzpah? I can help guide you if you need help?

**Comment by jessehouwing** [comment]
I do not have the time on my hands at the moment to commit to something like that, sorry. Backproblems, 14 week old baby daughter and a normal dayjob are not the ideal situation to pick up another opensource venture.
