### ISSUE TITLE
Test Suites in NUnit format have wrong "success" attribute

### ISSUE THREAD

**Issue by molnarm** [mmanela/chutzpah#433]
The NUnit 2 output format puts the count of passed test cases in the `success` attribute of `test-suite` tags, but according to [the official documentation](https://github.com/nunit/nunit/wiki/XML-Formats), it should be a string value, `True` or `False`. The problem is in [this line](https://github.com/mmanela/chutzpah/blob/b85eaf4b7591da679e0edd6f3cafdc39e3f134e7/Chutzpah/Transformers/NUnitXmlTransformer.cs#L98).

**Comment by mmanela** [comment]
Cool. Care to make a PR? That would expedite the fix.

Otherwise I can look at in when I get some time

**Comment by molnarm** [comment]
Sure, I will in a few days.
