### ISSUE TITLE
Angular2 SystemJs TypeScript Integration

### ISSUE THREAD

**Issue by meriturva** [mmanela/chutzpah#434]
I'm trying to integrate tests for an Angular2 application using SystemJs module loader.
I started to customize chutzpah.json file without success:

```
{
  "Framework": "jasmine",
  "References": [
    { "Path": "node_modules/traceur/bin/traceur-runtime.js" },
    { "Path": "node_modules/traceur/bin/traceur.js" },
    { "Path": "node_modules/systemjs/dist/system.src.js" },
    { "Path": "node_modules/systemjs/dist/system-polyfills.js" },
    { "Path": "node_modules/angular2/bundles/angular2.js" },
    { "Path": "node_modules/angular2/bundles/testing.js"  }
  ],
    "Tests": [
      {
        "Path": "wwwroot/src",
        "Include": "*.spec.js"
      }
    ]
  }
```

But i receive:

```
Error: TypeError: Unexpected anonymous System.register call.
```

Have you never tried this kind of configuration?

**Comment by mmanela** [comment]
Can you provide me a working repro of this that I can download an run?

**Comment by meriturva** [comment]
Hi Matthew,
i have created a really simple project with Angular2 quickstart instruction in Visual Studio 2015 Update 1 with DNX RC1 (so you have also to update Asp.Net as suggested by VS Update dialog).

https://github.com/meriturva/Chutzpah-434

Note that you have to change the file: Startup.cs file and to put your absolute path to "node_modules" folder.

As you can see there is no chutzpah json configuration file....and i have the error:

```
Error: ReferenceError: Can't find variable: System
```

Tell me if you need more information, i will be really happy to help you making adapter working with System.js

**Comment by meriturva** [comment]
Hi Matthew,
have you checked my sample project?

**Comment by mmanela** [comment]
Not yet, will do once I have some time

**Comment by mmanela** [comment]
I took a look and I probably don't understand enough about how system.js works to give a good answer. One thing I recommend you do is tell Chutzpah to open your test in the browser and then examine what the HTML file is doing. If you can tell me what is it doing wrong I can help you more change the JSON or fix Chutzpah if it is missing a feature.

**Comment by monkeylumps** [comment]
I think I have cracked this one as I was having the same issue, I'll give more info once I am sure but its to do with the order that the js files load in. system should be first and it looks like the order is based off folders in alphabetical order.

Once error Error: TypeError: Unexpected anonymous System.register call.

goes away then there are two others cross orgin errors that I am working on fixing.

XMLHttpRequest cannot load file:///C:/Git/Jasmine/src/Jasmine/wwwroot/app/app.component.spec. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ system.src.js:1049(anonymous function) @ system.src.js:1555lib$es6$promise$$internal$$initializePromise @ angular2-polyfills.js:1558lib$es6$promise$promise$$Promise @ angular2-polyfills.js:1849(anonymous function) @ system.src.js:1554(anonymous function) @ system.src.js:2446(anonymous function) @ system.src.js:3011(anonymous function) @ system.src.js:3244(anonymous function) @ system.src.js:3840(anonymous function) @ system.src.js:4031(anonymous function) @ system.src.js:4277(anonymous function) @ system.src.js:326run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2-polyfills.js:138 Error: XHR error loading file:///C:/Git/Jasmine/src/Jasmine/wwwroot/app/app.component.spec(…)run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:1444(anonymous function) @ angular2-polyfills.js:243run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305


The short term fix is to move the .html file that is generated next to the js file that I am testing down to the wwwroot folder.

I'll work more on this tomorrow.

**Comment by monkeylumps** [comment]
Once you have the .js files loadning into the html in the correct order then you will also need to make sure that the file does not referance the spec test, to do this use the command :-1: 

"TestHarnessReferenceMode": "AMD",


Once you have this you need to make sure that the .html file is not generated next to the .js file you are testing. To do this use this command

  "TestHarnessLocationMode": "SettingsFileAdjacent",

**Comment by linal** [comment]
@munkeylumps can we sort out a working sample repo tomorrow from the angular2 demo code for other people to use as reference

**Comment by mmanela** [comment]
If you have a working repro I can incorporate into the project as an official sample

**Comment by monkeylumps** [comment]
Once I have a working example I will post a report and update here. 

I Currently have an issue running the js tests by themselves but the in browser stuff works

**Comment by bravemav** [comment]
@monkeylumps do you have an update on how to resolve this issue? 

I am getting the same error on VS2015, Chuzpah extension, Angular2, and system.js configuration.

**Comment by meriturva** [comment]
I think that now with Angular 2 more "stable" (we are on beta 3) and System.js more frequently used this issue is gona be really important to fix.....i don't know now the compatibility also with Jspm....anyway if you need a "test" project just tell me.....i already provided https://github.com/meriturva/Chutzpah-434
but i really don't know how to help :)

**Comment by monkeylumps** [comment]
I got past the error that your reported @meriturva  but hit another issue that I did spend a day on but unfortunately I have not had time to go back and look at it. 

I will upload my repo and post how to bypass the original error and give details on the new error at lunch today.

**Comment by monkeylumps** [comment]
Here is my project with that gets past the system.reg call error. 

https://github.com/monkeylumps/TprAngular/tree/NewRelic/Jasmine/src/Jasmine

it does have its own issues though - if you run the spec in browser they work but running as a js test failed with the following error.

Error: Error: undefined is not a constructor (evaluating 'new exports.Map()')
	Error loading file:///C:/Git/Jasmine/src/Jasmine/wwwroot/app/app.component.spec.js
at error  (line 0)
While Running:C:\Git\Jasmine\src\Jasmine\wwwroot\app\app.component.spec.ts

So far I can't work out why this is happening.

 But to fix the sys.reg error you need to change the load order of the js files into the test so that system,js is loaded first then angualr 2 and the last file is the system.js setup config.

To do this I moved my js files into folders called 1,2,3,4.... and loaded in these files - chutzpa loads the js files in alphabetical order of the folder name - it would be nice if this where not the case or we could control the load order without having to use folders called 1,2,3,4.

Aslo I had to use 

  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",

To make sure that the HTML file that is generated it not next to the specs but at the same level as the chutzpa config file - trying to run next to the spec files fails.

I'll will get free to work on the new issue soon and will update once I fix it.

**Comment by og-neth** [comment]
@meriturva I don't see a chutzpah.json file in your .sln on github. I am also working on running tests with chutzpah and systemjs. I get the runner to run, but it doesn't see my tests. It throws no errors, but I am wondering if the location of my chutzpah.json file is the problem.

**Comment by monkeylumps** [comment]
The cutzpah.json file is under the wwwroot - i moved it there at it would not work elsewhere in my case.

https://github.com/monkeylumps/TprAngular/tree/NewRelic/Jasmine/src/Jasmine/wwwroot

**Comment by meriturva** [comment]
Hi @og-neth the project was just a start point...i have to test all again with all latest versions (angular/chitzpah...)..plus JSPM loader... The main problem i see in general is that that we are so dependent to too fast technologies in this crazy moment :)

**Comment by og-neth** [comment]
Hi @meriturva yeah, I am establishing better module patterns at work for the rest of my team, and one of our frameworks (kendo UI) prefers SystemJS, Webpack or Browserify over RequireJS now...  so I had to look into it and thus adapt to SystemJS. I am close to getting this to work... I'll keep trying and let you all know what I find.

**Comment by og-neth** [comment]
@meriturva @monkeylumps @mmanela so I didn't get this to work with SystemJS, I decided to just use requirejs in my .Tests project, but I am using SystemJS in my .Web project in my solution. I got it to work, so I am thinking I will try to just replace systemjs for requirejs in my chutzpah.json, as below. But here it is for reference if you guys want to take a look. 

`{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "Tests": [
    {
      "Path": "Scripts/app"    }
  ],
  "References": [
    {
      "Path": "../Myherbalife3.Crm.AdminTool.Web/Scripts/vendors/jquery-1.10.2.min.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "../Myherbalife3.Crm.AdminTool.Web/Scripts/vendors/kendo/kendo.all.min.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "require-2.1.22.min.js",
      "IsTestFrameworkFile": true
    }
  ]
}
`

Hopefully it can help. @mmanela let me know if I can contribute to your project and help get chutzpah to support systemjs.

**Comment by bravemav** [comment]
I finally got it to work!

I can run unit tests in VS2015 with the chutzpah extension using the chutzpah.json file below. Thanks to everyone in this thread who gave their input and sample config files!

`{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "Tests": [
    {
      "Path": "scripts/main.component.spec.js"
    }
  ],
  "References": [
    { "Path": "scripts/es6-shim.js" },
    { "Path": "scripts/system-polyfills.src.js" },
    { "Path": "scripts/angular2-polyfills.js" },
    { "Path": "scripts/system.src.js" },
    { "Path": "scripts/Rx.js" },
    { "Path": "scripts/angular2.dev.js" },
    { "Path": "scripts/system-config.js" }
  ]
}
`

and here is the content of my test-config.js file which configures systemJS

`System.config({
    packages: {
        scripts: {
            format: 'register',
            defaultExtension: 'js'
        }
    }
});
System.import('scripts/main.component.spec');`

**Comment by bravemav** [comment]
I finally got it to work!

I can run unit tests in VS2015 with the chutzpah extension using the chutzpah.json file below. Thanks to everyone in this thread who gave their input and sample config files!

```
{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "Tests": [
    {
      "Path": "scripts/main.component.spec.js"
    }
  ],
  "References": [
    { "Path": "scripts/es6-shim.js" },
    { "Path": "scripts/system-polyfills.src.js" },
    { "Path": "scripts/angular2-polyfills.js" },
    { "Path": "scripts/system.src.js" },
    { "Path": "scripts/Rx.js" },
    { "Path": "scripts/angular2.dev.js" },
    { "Path": "scripts/system-config.js" }
  ]
}
```


and here is the content of my system-config.js file (referenced in the chutzpah.json file) which configures systemJS.

```
System.config({
    packages: {
        scripts: {
            format: 'register',
            defaultExtension: 'js'
        }
    }
});
System.import('scripts/main.component.spec');
```

**Comment by mmanela** [comment]
Can you give me a sample of this that I can run. I recently started playing with this and started adding some initial baked in support for system.js  (dabe25f830c90069c0ee9539969a12699762470f) but seeing what you did can help me finish it so you don't even need the system-config file

**Comment by bravemav** [comment]
I have added the sample project below:

https://github.com/bravemav/Chutzpah-Angular2-SystemJS

**Comment by og-neth** [comment]
@mmanela looking forward to that baked in support for systemjs!!!

**Comment by mmanela** [comment]
Thanks, I am hitting one issue in my initial test where it fails to work because system.js is hitting issues with the fact that Chutzpah is using file (file:///) references. Require.js does not have an issue with this so maybe I am misconfiguring systemjs?

**Comment by abdurrachman-habibi** [comment]
Hi. is there any update on this ? I encountered similar issues with @mmanela. The system.js tries to xhr a local file which is not allowed in chrome when I run it using "open in browser" mode. It just says "0 passed, 0 failed, 0 total" when running in Visual Studio

**Comment by fl-int** [comment]
I have same issues with XHR local files. Any updates on this?

**Comment by mmanela** [comment]
Unless someone finds a better solution the thing I am thinking of is have Chutzpah support running a local webserver to serve your files. This is a large change in Chutzpah that I will not have time to do in the near term. So I am open to contributions or other solutions...

**Comment by angDakila** [comment]
I am also experiencing XHR local file issues...

**Comment by mmanela** [comment]
Thanks, I am working on a solution. It is a bit large but I am adding a long awaited server mode for Chutzpah. When in this mode Chutzpah will run using a embedded web server and it should resolve some of the oddities Chutzpah can cause when running using the local file system

**Comment by angDakila** [comment]
@mmanela thanks! Can't wait for the next release. I am really using Chutzpah on all of my Angular  1.x and 2 projects.

**Comment by siddharth-pandey** [comment]
Hi, do we have any workaround or update related to this issue? Please share. Thanks

**Comment by GeorgDangl** [comment]
You could use Chrome with a flag to allow local file XHR, [see this StackOverflow answer](http://stackoverflow.com/questions/4819060/allow-google-chrome-to-use-xmlhttprequest-to-load-a-url-from-a-local-file#answer-18137280), if you need to run tests with your Browser.

**Comment by siddharth-pandey** [comment]
@GeorgDangl As stated above, I'm already using following in my chutzpah.json file. But I don't think that is helping as I see chrome's standard error msg in the console that "cross origin requests are only supported for protocol schemes..."

```
 "BrowserArguments": {
        "chrome": "--allow-file-access-from-files"
    }
```

**Comment by GeorgDangl** [comment]
Oh, didn't see your edit there.
However, it should work if you manually start the chrome.exe process with the argument and open the generated Html file from Chutzpah (it does for me), so I guess there's something not working with the `BrowserArguments` in Chutzpah.

**Comment by mmanela** [comment]
@GeorgDangl Does that work if you manually start chrome with that setting?

**Comment by GeorgDangl** [comment]
Yes, when I manually start Chrome with this argument I'm able to run the tests from local files.

**Comment by mmanela** [comment]
I added better support for Angular2 in the 4.3.0 release. Please take a look at the [Angular2 sample](https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic) and see if it helps.

Will close for now but re-open if this doesn't solve the problem.
