### ISSUE TITLE
Run All Tests within one Mult-Project Solution (Visual Studio)

### ISSUE THREAD

**Issue by FrithjofMatthiasSchaefer** [mmanela/chutzpah#436]
It would be wonderful, if one had the option to run all Tests within one Visual Studio Solution,

If you right click on a Visual Studio Project, I can see an Action "Run JS Tests".

It would be awesome if one could also run ALL tests within one Mulit-Project Solution, thus run the "Run JS Test" for all Projects inside the right-clicked Visual Studio Solution

**Comment by mmanela** [comment]
Thanks for filing this. This sounds like a nice feature to add

**Comment by FrithjofMatthiasSchaefer** [comment]
yeps. i already forked your repo but unfortunately my VS Version is 2013 so
i first need to install 2015. If you want i can possibly implememt that
feature.
Am 17.12.2015 17:15 schrieb "Matthew Manela" <notifications@github.com>:

**Comment by miparnisari** [comment]
I think I can take on this task.
