### ISSUE TITLE
nested xdescribe causes timeout error

### ISSUE THREAD

**Issue by lavahot** [mmanela/chutzpah#437]
Took me forever to pin this down. I have found that this works for suites of any length. If you have a suite like this: 
```
-Describe
  -Describe
    -xDescribe
```
Or any arrangement with an `xDescribe` further nested than 3 deep, Chutzpah will timeout every time, even with a longer timeout window. Here's the debug text:
```
Exception was thrown at line 617, column 7 in file:///C:/Users/<my user name>/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/3j2tetj0.hod/TestFiles/jasmine/v2/jasmine.js
0x800a138f - JavaScript runtime error: Unable to get property 'spies' of undefined or null reference
```

Normal describes at this depth work fine. xIts at this depth work fine.

**Comment by mmanela** [comment]
That is interesting. Does this work fine if you open it in a browser?

**Comment by lavahot** [comment]
Nope. Same problem if I run it in the browser.

**Comment by mmanela** [comment]
Then that might be a bug with Jasmine itself

**Comment by mmanela** [comment]
Can you try to craft a vanilla Jasmine test with this structure and see if it errors? If so, please file a bug on them

**Comment by lavahot** [comment]
It looks like there might be more to it. 
This code works:
```
describe('top layer', function () {
  beforeEach(function () {
    spyOn(console, 'error');
    spyOn(console, 'log');
  });
  describe('second layer', function () {
    xdescribe('third layer', function () {
      it('should not display this test', function () {
        expect(true).toEqual(true);
      })
    });
  });
});
```
but this code doesn't:
```
describe('top layer', function () {
  beforeEach(function () {
    spyOn(console, 'error');
    spyOn(console, 'log');
  });
  describe('second layer', function () {
    xdescribe('third layer', function () {
      it('should not display this test', function () {
        expect(true).toEqual(true);
      })
    });
    describe('other third layer', function () {
      it('should not display this test', function () {
        expect(true).toEqual(true);
      })
    });
  });
});
```
And yet this code works:
```
describe('top layer', function () {
  beforeEach(function () {
    spyOn(console, 'error');
    spyOn(console, 'log');
  });
  describe('second layer', function () {
    xdescribe('third layer', function () {
      it('should not display this test', function () {
        expect(true).toEqual(true);
      })
    });
    xdescribe('other third layer', function () {
      it('should not display this test', function () {
        expect(true).toEqual(true);
      })
    });
    describe('nother third layer', function () {
      it('should not display this test', function () {
        expect(true).toEqual(true);
      })
    });
  });
});
```

Try it for yourself and see. This is quite disturbing.

**Comment by lavahot** [comment]
Oh, this might be related, it looks like the extension contains and calls an older version of jasmine, 2.1.3.

**Comment by mmanela** [comment]
I can upgrade to a newer version soon if that helps

**Comment by lavahot** [comment]
I don't really know if it will help, but IIRC there were several syntax changes and bug fixes between then and 2.4.x, so it might be worth trying, at least experimentally. Were you able to reproduce my results with the code I posted?

**Comment by mmanela** [comment]
I have not tried yet. Will experiment and see if the upgrade works

**Comment by mmanela** [comment]
I upgraded to newest jasmine and it resolves the issue
