### ISSUE TITLE
Reading xml file

### ISSUE THREAD

**Issue by Aghlara** [mmanela/chutzpah#438]
Hi,

How do I read an XML file in a test? There are multiple xml files in project (website) folder we need to read and run test against them.

I tried to use the relative path like what I had as reference and use JQuery but was not able to and got "access denied" probably because of domain-site-origin issue.

Thanks for the help.

Regards,

**Comment by mmanela** [comment]
Cant you mock out the call to the xml file and test it that way?

**Comment by Aghlara** [comment]
That's not much about mocking call. I have them on local folder in the project. I want to read them from js test file instead of make all of them as a string content in another js file.

**Comment by mmanela** [comment]
Chutzpah does support embedded HTML in to your test harness. This feature might work for XML but I have never tried this

**Comment by Aghlara** [comment]
Well, the files I am talking about are actually XML files, how do I read them?

**Comment by mmanela** [comment]
Not sure of a simple way to make that work for you currently.

**Comment by mmanela** [comment]
This is not a chutzpah issue so closing. Please re-open if you disagree.
