### ISSUE TITLE
Running Chutzpah on a custom CI system

### ISSUE THREAD

**Issue by yaakov-h** [mmanela/chutzpah#440]
Hi,

I'm looking into running Chutzpah on a custom CI system.

One feature in particular I need is the ability to discover tests, and then the ability to run just a certain subset of tests.

There don't appear to be any command-line options on `chutzpah.console.exe` to do this, but `Chutzpah.TestRunner`/`Chutzpah.ITestRunner`'s API looks promising.

Is this supported public API, or are these internals of Chutzpah?

Thanks.

**Comment by mmanela** [comment]
Most people when using a CI system just run Chutzpah.console.exe on a particular chutzpah.json file which describes which set of tests to run on. 

Does this work for you?

**Comment by yaakov-h** [comment]
This may be workable if there is a command-line option to discover tests without executing them, but I cannot find any such option in the `/?` help.

**Comment by mmanela** [comment]
Why do you want to discover without executing from a CI?

**Comment by yaakov-h** [comment]
Distributed testing - I need to be able to gather a list of tests (without executing), then hand parts of that list off to different test machines to execute their part of the list and return results.

**Comment by mmanela** [comment]
So there is a way to do this but it will not be efficient. Chutzpah can generate just the list of tests BUT in order to do this it still pretty much executes the test files with the test bodies stubbed out. I would advise you to figure a static way to partition tests (maybe by folder) instead.

**Comment by yaakov-h** [comment]
I'm fine with that - we do a similar thing with NUnit and it's `[TestCaseSource]` already.

I assume this is the same method the Visual Studio extension uses?

How would I go about doing this?

**Comment by mmanela** [comment]
I am not sure I follow you. If you organize your tests in a hierarchy of folders you can just farm a whole folder out to a different machine.

**Comment by yaakov-h** [comment]
The system is a bit more advanced than that, but I can't publicly share the specifics here.

**Comment by mmanela** [comment]
Well, if you want you can email me and we can talk further.

**Comment by yaakov-h** [comment]
I can do that, if I could find a published email address... :smile:

**Comment by mmanela** [comment]
My github name at gmail.
