### ISSUE TITLE
Urgent! An exception occurred while invoking executor 'executor://chutzpah-js/': Unable to find headless browser: phantomjs.exe

### ISSUE THREAD

**Issue by akj627** [mmanela/chutzpah#443]
Please read my previous issue : https://github.com/mmanela/chutzpah/issues/402

Couple pointers :
1. This happens every 10-15 days or so after we fix it temporarily using one of the below solutions
2. I see that this error goes away when I somehow build a new version of chutzpah.dll after pulling the repo on my local.
3. It also goes away when the build controller is restarted.

Please let me know what you want me to do to reproduce it.
Also, I was not able to generate a log file. After I added a .runsettings file using this 
https://chutzpah.codeplex.com/wikipage?title=tfsbuild

```
<RunSettings>
 <ChutzpahAdapterSettings>
   <EnabledTracing>True</EnabledTracing>
 </ChutzpahAdapterSettings>
</RunSettings>
```

and added it to the Build Controllers custom option/settings file, it properly errored out saying this :
     An exception occurred while invoking executor 'executor://chutzpah-js/': An error occurred while initializing the settings provider named 'ChutzpahAdapterSettings'. Error: There is an error in XML document (4, 5). There is an error in XML document (4, 5). The string 'True' is not a valid Boolean value. See [http://go.microsoft.com/fwlink/?LinkId=254169](http://go.microsoft.com/fwlink/?LinkId=254169)

But when I fixed it by changing True to 'true', it still didn't give me any log file and started giving me the same headless error :(

I see the error is happening in TestRunner.cs line 163
https://github.com/mmanela/chutzpah/blob/master/Chutzpah/TestRunner.cs

**Comment by mmanela** [comment]
This sounds like phantom.exe is missing somehow. Did you validate its location and that it is not locked or anything?

**Comment by akj627** [comment]
It is not missing obviously as it continues to work for 10-15 days. How can I enable the logs ? I can't get it to work using the .runsettings file. I can send you the logs if I start getting it. Also, the issue I have mentioned is in TFS, FYI, if I was not clear in my starting thread.

**Comment by mmanela** [comment]
Did you look in the %temp% directory for the log file?

**Comment by akj627** [comment]
Ok. I found the log file now. It was sitting in the temp dir of the user account TFS was running into.
I will send you the log next time I experience an error.
I have added more diagnostic logging in TestRunner and FileProbe to peek into all the details.
Also, have added logs to show DateTime instead of time only

**Comment by akj627** [comment]
Thanks for being with me throughout this issue.
This happened again. So, as you can see it's after 13 days
I have masked the logs to hide company info. 
As I said, I modified the chutzpah code to add additional logging so that I could know where its looking for the phantomjs.exe
The 1st two sections of the attached log indicate the error scenario and the path as probed by the code was
```    C:\Users\*tfsid*\AppData\Local\Temp\BuildAgent\2\Assemblies\phantomjs.exe  ```
As the log clearly says, ```   phantomjs.exe ``` was not present in that location.
After I restarted the build controller, the same path started to have it and that's why it goes to success.
One observation is, in the error scenario, the probed folder contains only *.dll files and no other files. 
I have a feeling it's related to the TFS-Chutzpah integration

Check the images and the log file attached

##### Build Agent folder content when erroring out :
![foldercontentsaterror](https://cloud.githubusercontent.com/assets/4824153/12424596/eae3c6a8-be9e-11e5-869a-c728e5e6f7f2.JPG)
##### Build Agent folder content after build controller is started and the build is a success :
![foldercontentsatsuccess](https://cloud.githubusercontent.com/assets/4824153/12424601/ee454290-be9e-11e5-98d7-58f141e9192a.JPG)

[chutzpah log file.txt](https://github.com/mmanela/chutzpah/files/96213/chutzpah.log.file.txt)

**Comment by mmanela** [comment]
This is odd. I think whatever is happening here seems out of the control of Chutzpah. Chutzpah gets copied by the TFS-XAML-Build framework and expects it is completely copied. Chutzpah doesn't control how that happens. 

I might be worth it to file a connect bug against the TFS Build feature and see if they can comment on the issue. I will try to dig in more myself but this seems very odd. 


Thanks a lot for the thorough analysis.

**Comment by mmanela** [comment]
@akj627 Do you still have this issue?

**Comment by mmanela** [comment]
Closing since have not heard back in a long time. Please re-open if issue persists.

**Comment by roopkt** [comment]
Hi I am still getting this issue once I upgraded my Chutzpah to 4.3.3. When it was 3.3 version then it was working fine. I am not able to run test cases in via build definition. When I downgrade to 3.3 it works. Kindly respond.

![bd](https://cloud.githubusercontent.com/assets/330383/22621633/14544f9c-eaf6-11e6-8140-e94e01a957b8.PNG)

An exception occurred while invoking executor 'executor://chutzpah-js/': Exception has been thrown by the target of an invocation.
The type initializer for 'Chutzpah.ChutzpahContainer' threw an exception.
Unable to load libuv.dll

**Comment by roopkt** [comment]
Hi after restarting build controller it resolved and now working. Thanks !
