### ISSUE TITLE
Chutzpah module dependencies injection not working

### ISSUE THREAD

**Issue by octav84** [mmanela/chutzpah#444]
Hi Mr Manela,
I installed Chutzpah for Visual Studio and it worked fine for testing a module without any dependencies. 
But when I tried to run tests for a module that had a list of dependencies, my test crashed.
I tried injecting the dependencies in various ways.

At first, I did this:  

       beforeEach(module('app', ['ngRoute', 'ngSanitize', '7minWorkout', 'WorkoutBuilder', 'mediaPlayer', 'ui.bootstrap', 'LocalStorageModule', 'ngAnimate', 'ngMessages', 'ngResource']));    

Of course, I added references to all the files containing these modules.

Then, after searching a bit on the web, I tried to do this:

            module('ngRoute', []);
            module('ngSanitize', []);
            module('WorkoutBuilder', []);
            module('mediaPlayer', []);
            module('ui.bootstrap', []);
            module('LocalStorageModule', []);
            module('ngAnimate', []);
            module('ngMessages', []);
            module('ngResource', []);
            module('7minWorkout', []);
            module('app');

And even this :
 
            angular.mock.module('ngRoute', []);
            angular.mock.module('ngSanitize', []);
            angular.mock.module('WorkoutBuilder', []);
            angular.mock.module('mediaPlayer', []);
            angular.mock.module('ui.bootstrap', []);
            angular.mock.module('LocalStorageModule', []);
            angular.mock.module('ngAnimate', []);
            angular.mock.module('ngMessages', []);
            angular.mock.module('ngResource', []);
            angular.mock.module('7minWorkout', []);

Every time, the output when running the test was:

          Error: Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=app
in file:///c:/users/octaviane.cvuintelligence/documents/visual%20studio%202013/Projects/PersonalTrainer/PersonalTrainer/Scripts/angular.js (line 2007)
at ensure in file:///c:/users/octaviane.cvuintelligence/documents/visual%20studio%202013/Projects/PersonalTrainer/PersonalTrainer/Scripts/angular.js (line 1929)
at module in ......  
....
<long error text>

I uploaded the jasmine test spec file here:
[workout.spec.docx](https://github.com/mmanela/chutzpah/files/79599/workout.spec.docx)

and also the full error text in a doc file here:
[Error.docx](https://github.com/mmanela/chutzpah/files/79601/Error.docx)

**Comment by mmanela** [comment]
Can you upload a full repro that I can download and run?

**Comment by mmanela** [comment]
@octav84 PING

**Comment by og-neth** [comment]
@mmanela Hi Matt, I am following your steps on AMD unit tests with RequireJS, but I am using SystemJS as my module loader. I am able to run the tests but the runner isn't picking up my test, it says 0 passed 0 failed 0 total in my output window. Let me know if you want me to open up a separate issue for this and we can discuss and I can send some files over.

**Comment by mmanela** [comment]
@octav84 You closed this issue? Did you resolve it?

**Comment by octav84** [comment]
No, but this was a personal attempt and had no implications in a real project. It's not solved, but I am working on a different project with a different technology and I consider the issue obsolete.
