### ISSUE TITLE
Ability to use wildcard* characters in references

### ISSUE THREAD

**Issue by jongunter** [mmanela/chutzpah#446]
Forgive me as I'm pretty new to JS unit testing and Chutzpah, but coming from an npm/gulp-based testing/build environment, I'd be really cool if we could use `*`'s in Chutzpah references as wildcard characters. Is this a possible feature to build?

I understand that I can load entire folders in my references, but sometimes I have very specific types of files I want included that are in a folder, such as all files that end in `.module.js` (or, more often, I want these files loaded before any other `.js` files.

**Comment by mmanela** [comment]
Please take a look at the [Reference Setting](https://github.com/mmanela/chutzpah/wiki/References-Setting) documentation. 

```
{
    "References": [
        { "Path": "src/Code", "Includes": ["*.js"], "Excludes": ["*Resource*"] }
    ]
}
```

**Comment by mmanela** [comment]
Have no heard back. Closing issue, re-open if not resolved.
