### ISSUE TITLE
Version of QUnit is outdated

### ISSUE THREAD

**Issue by rachelppierson** [mmanela/chutzpah#447]
At present, the version of Qunit that is installed alongside Chutzpah is 1.18.0 (released 03 April 2015). The most recent version of QUnit is 1.20.0 (27 October 2015). Could it be updated, please? 

My understanding is that this is intended to be configurable via the Chutzpah.json settings file (https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File). Though my understanding also is that this only works for Jasmine at present. 

An example of tests that are breaking invalidly because the version of QUnit is too old is provided here:

    http://jsfiddle.net/v82zr0ap/2/

An example of those same tests passing with the more recent version of QUnit is provided here:

    http://jsfiddle.net/v82zr0ap/1/

**Comment by mmanela** [comment]
Thanks, I will update this soon.

**Comment by rachelppierson** [comment]
Thank, Matthew. 

Thanks for providing a great tool to the development community.

R.

t: 01698 357455, sk: rachel.p.pierson


Date: Sat, 9 Jan 2016 21:12:22 -0800

**Comment by rachelppierson** [comment]
Thanks for your reply. And thanks for providing such a useful tool to the developer community.

**Comment by mmanela** [comment]
Commit the update to the last version.

**Comment by victor175** [comment]
Hello,

Is it possible for you to update the version of qunit once again to the latest (2.4.0)?
Some major changes to the API were introduced and it would be very helpful if you can do that, so we can benefit from them.

I already did some tests, just replacing the qunit files with the newest ones and everything seem to work without any problems, so it looks compatible (should be a straightforward replacement).
