### ISSUE TITLE
Tests are culture-dependent

### ISSUE THREAD

**Issue by molnarm** [mmanela/chutzpah#450]
I have my regional settings set to Hungarian, which uses comma as a decimal separator. However, some tests (at least `NUnit2XmlTransformerFacts.Will_generate_testsuite_for_each_file` and `JUnitXmlTransformerFacts.Will_generate_junit_xml` contain hardcoded numbers in the expected output with dot as separator, therefore they fail when the application is run with a culture which has a different setting ([of which there are quite a lot](https://en.wikipedia.org/wiki/Decimal_mark#Hindu.E2.80.93Arabic_numeral_system)).

About the tests mentioned above: (NUnit [uses a simple ToString()](https://github.com/nunit/nunit/blob/master/src/NUnitEngine/Addins/nunit-v2-result-writer/NUnit2XmlResultWriter.cs#L245) to output numbers (=the separator depends on CurrentCulture), I haven't checked JUnit.) There might be other tests having this problem, but I don't have all the tools installed to run e.g. integrations tests.

**Comment by mmanela** [comment]
@molnarm What is the correct behavior? Should the XML contain only 1.5 or should it contain 1,5 given locale?

I want to know whether the test is wrong OR the xml serialization is wrong.

**Comment by molnarm** [comment]
@mmanela The test is wrong. The serialization result depends on the current culture (as in NUnit), but the test expectations don't. So the solution is to replace the hardcoded numbers in tests with ToString or String.Format calls.

For example, `Assert.Equal("1.5", suites["path1"].Attribute("time").Value);` ([here](https://github.com/mmanela/chutzpah/blob/master/Facts/Library/Transformers/NUnit2XmlTransformerFacts.cs#L107)) should become `Assert.Equal(1.5.ToString(), suites["path1"].Attribute("time").Value);`

**Comment by mmanela** [comment]
Cool, that is what I thought just wanted to double check
