### ISSUE TITLE
PhantomJS authentication options not passed properly

### ISSUE THREAD

**Issue by Gergues** [mmanela/chutzpah#451]
According the Chutzpah.json file
the options passes there should be passed down to the PhantomJS.exe engine , but it looks like the http authentication is not passed properly.

Using the PhantomJS options json object setting for http authentication.

{ 
     "userName ":"myUser@dev.local",
     "password":"MySecretPassword"
}

When running the chutzpah.console.exe against a remote html file using the local .json settings are ignored.

Chutzpath tries to download the html file for local parsing and that causes 401 authentication failures.

Thank you ..
---
Here is the exception:
_________________________________

Error: System.Net.WebException: The remote server returned an error: (401) Unaut
horized.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request
)
   at System.Net.WebClient.DownloadString(Uri address)
   at Chutzpah.TestContextBuilder.<>c__DisplayClass3d.<TryDetectFramework>b__32(
) in c:\Dev\chutzpah\Chutzpah\TestContextBuilder.cs:line 444
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Chutzpah.TestContextBuilder.<>c__DisplayClass3d.<TryDetectFramework>b__36(
IFrameworkDefinition x) in c:\Dev\chutzpah\Chutzpah\TestContextBuilder.cs:line 4
61
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`
2 predicate)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`
2 predicate)
   at Chutzpah.TestContextBuilder.TryDetectFramework(PathInfo path, ChutzpahTest
SettingsFile chutzpahTestSettings, IFrameworkDefinition& definition) in c:\Dev\c
hutzpah\Chutzpah\TestContextBuilder.cs:line 467
   at Chutzpah.TestContextBuilder.BuildContext(IEnumerable`1 files, TestOptions
options) in c:\Dev\chutzpah\Chutzpah\TestContextBuilder.cs:line 133
   at Chutzpah.TestContextBuilder.TryBuildContext(IEnumerable`1 files, TestOptio
ns options, TestContext& context) in c:\Dev\chutzpah\Chutzpah\TestContextBuilder
.cs:line 202
   at Chutzpah.TestRunner.<>c__DisplayClass12.<BuildTestContexts>b__f(List`1 tes
tFiles) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 414

**Comment by mmanela** [comment]
How are you telling Phantom to use authentication?

**Comment by Gergues** [comment]
Well I have tried the following three options:

1- Passing the user name and password in the URL  http://user:pass@url  this would work with PhantomJS , but Chutzpah will not accept it as the .NET library does not parse it as a valid Url.

2- Adding the user name and password elements in the chutzpah.json settings file as follows

{
"userName ":"myUser@dev.local",
"password":"MySecretPassword"
}
or

{
"settings.userName ":"myUser@dev.local",
"settings.password":"MySecretPassword"
}

nor
{
"page.settings.userName ":"myUser@dev.local",
"page.settings.password":"MySecretPassword"
}
as this actually should work with PhantomJS as a phontomJS option

Thanks.

**Comment by Gergues** [comment]
PS: this might be a PhantomJS Issue 
Read more here 
https://github.com/ariya/phantomjs/issues/13262

**Comment by mmanela** [comment]
Ok, Chutzpah does understand passing those settings in the chutzpah.json file. If you want to set Phantom.js properties you can invoke them from inside your test files this way:

```
window.callPhantom(
{
  Type:"Eval",
  Data: "phantom.pagesize(100,200);"
});
```

**Comment by Gergues** [comment]
That is the dilemma :) 
The scripts and the html setup file are all remote. 

To get to the file -> need to authenticate.

I will attempt to rewrite all test scripts for that project as it does not  look like a good way to test anyways.

Thanks

**Comment by mmanela** [comment]
Closing as it does not seem to be a chutzpah issue
