### ISSUE TITLE
Running Chutzpah in Windows8/WinJS project using Visual Studio 2013

### ISSUE THREAD

**Issue by smilealdway** [mmanela/chutzpah#453]
My WinJS project uses JQuery to send ajax requests. I want to use QUnit to test my ajax requests. In this environment the requests are successfully made from within the app. However, since the Chutzpah uses head-less browser to run tests, the AJAX requests fails because of CORS (Cross-Origin Resource Sharing i.e. cross domain request). Is there anyway to seamlessly make AJAX request and not hitting into this issue?

**Comment by smilealdway** [comment]
is there anyway to disable OPTIONS request - pre-flight requests in Cross-origin resource sharing ?

**Comment by smilealdway** [comment]
It seems Chutzpah already disables all XSS checks. https://github.com/mmanela/chutzpah/issues/41. 

I guess I facing this problem because debugger (Chutzpah for VS2013) uses IE for debugging the tests while phantomjs to run the tests.

**Comment by smilealdway** [comment]
I delved further and realized from the errors from running tests directly, I am facing troubles from RequireJS (yes that too is in mix). RequireJS module loads dependencies just fine when in debugging a Test but then it runs into CORS issue later (the one I mentioned earlier). So my conclusion is that IE (in debug VS debug environment) is able to run RequireJS just fine but phantomJS isn't. Any ideas?

**Comment by mmanela** [comment]
I am a bit confused on what you are trying and what does/doesn't work.

1. Does it work when running a test directly from VS using Chutzpah?
2. Does it work when you have Chutzpah open that test in a browser?

**Comment by smilealdway** [comment]
I am sorry for the confusion and thank you for promptly replying to my queries.

1. My test executes fine (apart from CORS issue which I mentioned earlier) if I use "Debug Selected Tests" option to run my test.
2. My test fails if I use "Run Selected Tests" option. The exception stack trace has following information towards the end :
`onScriptLoad (file:///c:/users/abc/documents/visual%20studio%202013/projects/chutzpahpoc01/chutzpahpoc01/js/Common/Lib/require.js:1679:41): Can't find variable: Debug Expected: undefined, Actual: null
Result StackTrace:	at test Get in c:\users\abc\documents\visual studio 2013\projects\chutzpahpoc01\chutzpahpoc01\js\unittests\testrepository.js:line 2`

This is the reason why I think RequireJS module runs fine in IE (which I believe Chutzpah uses in debug environment) but fails in PhantomJS (which of course is its headless browser)

My environment - 
1. Visual Studio Chutzpah Adapter 
2. Visual Studio 2013
3. Windows 8 Store App using WinJS, RequireJS and AngularJS

**Comment by smilealdway** [comment]
I should have tried proving my hypothesis before posting the question above. Chutpah ran fine using "Run Selected Tests" option once I eliminated call to jquery AJAX from my test. I wonder why I was getting this weird exception in stack trace then. 

Any case, I am back to original problem -

Is there anyway to tell jquery/phantomjs to disable OPTIONS request - pre-flight requests in Cross-origin resource sharing?

**Comment by mmanela** [comment]
Honestly, I do not know. Chutzpah is just using Phantom if Phantom exposes this as a setting I can make it available.

**Comment by smilealdway** [comment]
Thank you mmanela for prompt responses. Looks like I'm the first one trying to use Chutzpah for a Windows 8 Store App using WinJS. 

From my investigations, following are my open question and not an issue per se with Chutzpah

1. Does Chutzpah use IE instead of PhantomJS when we use "Debug Selected Test" option?
2. Is there any way to configure PhantomJS to not make a pre-flight OPTIONS request to the server in cross-domain context? I believe this question is more relevant in PhantomJS git hub and I have asked it back there - https://github.com/ariya/phantomjs/issues/10028#issuecomment-172634290

**Comment by mmanela** [comment]
1. Correct, if you to the debug mode in Visual Studio IE is used.
2. I think contact PhantomJS is the best option.
