### ISSUE TITLE
Chutzpah should run tests off of a localhost server instead of the file:// protocol

### ISSUE THREAD

**Issue by rjgotten** [mmanela/chutzpah#461]
Chutzpah-generated test harnesses currently use the `file://` protocol.

The biggest issue currently is that this breaks `XmlHttpRequest`. However, it also breaks quite a few other things. Almost everything that involves same-origin policies: `@font-face` web fonts, the web storage API  (`window.localStorage` and `window.sessionStorage`) etc. And in the future, new browser features that will be HTTPS-only may have problems as well.

The status-quo is to either hand-build your own test-runner HTML file to launch (in which case you're basically discarding half of what makes Chutzpah great; autodiscovering all your tests based on a glob match) or to exclusively rely on PhantomJS which had its web-security flags explicitly switched off to disable same-origin protections, etc.

Why not spin up a simple server that is capable of serving static files for both the test adapter and the context-menu integrated launchers?

**Comment by mmanela** [comment]
Thanks for the feedback. I have heard this before and I think it makes sense and would simplify things. I just have never had the time to make this change. It is definitely on my list of things to do.

**Comment by rjgotten** [comment]
In that case; may I suggest going with a stock micro web-server package like Nancy in combination with OWIN self-hosting directly inside the Visual Studio extension?

After all; the only thing the server has to do is route a few file requests from disk and generate one HTML file with a few template tags filled out. Nancy or similar packages should have that covered easily.

Self-hosting the server in the extension means you'd have excellent control over when to launch and stop it and you circumvent some other things like negotiating which listening port is being used: the process that selects the listening port for the server and the one that opens PhantomJS or the browser would be one and the same.

**Comment by Deracination** [comment]
This will be great, as then we can debug indexdb from visual studio too. IE10+ only permits IndexedDB on http/https urls

**Comment by mmanela** [comment]
Thanks, I will look into it. Nancy looks very promising since I can self-host in a console application. I need to decide if this work it will be the only options or if it should be configurable with file based still being default.

**Comment by gsmeets** [comment]
I'd just make it configurable. I can imagine you start out with making it default to filesystem at the start, but as a path forward it makes much more sense to go self-hosting as default. Right now I'm running into this as well (actually, just a few weeks before I pointed @rjgotten to take a look at chutzpah). Not only with regular ajax requests that don't work, but also with my view templates which are pulled in with ajax requests.

**Comment by gsmeets** [comment]
I see you've done some work on getting this working. I'm willing to finish it. Can you fill me in on the status of your WebServer branch?

**Comment by mmanela** [comment]
I have it mostly working. The remaining work is:

1. Fix the last two broken integration tests (they are edge cases and I am trying to figure out why they fails)

2. Test Angualr2 project with it and make sure these now work in WebServer mode

3. Decide if this should become default or not. I am leaning to making webserver mode optional for the 4.3 release to get feedback and then make it default in 5.0. This could be a big breaking change but I think webserver mode is the *right* mode going forward. I would love feedback on this approach...

4. More testing :) I have some large projects I want to test on and make sure it works.

**Comment by gsmeets** [comment]
I've tried your branc,h, but had to comment out some code (had to do with viewing the code coverage reports) to get it working. I guess you haven't pushed all your changes from local to Github yet?

I don't use Angular, so I can't really help on point 2. Point 3 I already commented on in this thread, I'd make the default not use it in 4.3, and swap the default in 5.0, as you suggested yourself.

Point 4 I could help with in my own projects of course. ;)

One other small thing, I built the branch and it works in my vs2015 , but not in my vs2013, I get this error:

```
1) Could not finishing composing object of type 'Chutzpah.VS2012.TestAdapter.ChutzpahTestContainerDiscoverer'. The import '
	ContractName	Microsoft.VisualStudio.Shell.SVsServiceProvider
	RequiredTypeIdentity	Microsoft.VisualStudio.Shell.SVsServiceProvider' was not satisfied.
```

Might have to do with the versions of the dll's I'm using?

**Comment by mmanela** [comment]
Can you give me more details on the code coverage issue you are hitting. Most of my tests are passing for coverage so if you are hitting an issue it may be some situation I am not covering. 

As for the VS issue, can you try to uninstall and re-install the extension and clear extension cache?

**Comment by rjgotten** [comment]
> @gsmeets 
> Might have to do with the versions of the dll's I'm using?

Odds are you're working off of a revision that has an explicit `[Import(typeof(SVsServiceProvider)]` attribute marking the `IServiceProvider` parameter of the importing constructor.

You're not supposed to hardcode the concrete type. You're supposed to just import and use whatever `IServiceProvider` Visual Studio's shell extension framework gives you from its composition container.

**Comment by mmanela** [comment]
Oh, interesting. You are right the code is doing that in three places. Thanks!

![image](https://cloud.githubusercontent.com/assets/304410/17333452/532ecf32-5887-11e6-82c6-a7fc46485446.png)

**Comment by mmanela** [comment]
@gsmeets I fixed the VS issue and pushed some more changes. I have all my integration tests now passing. So please try again and let me know if you hit any new issues.

**Comment by mmanela** [comment]
Oops, I still have some failing tests. Had a bug that was hiding this. More work to do then :)

**Comment by mmanela** [comment]
Ok, the changes are all in. Doing some final testing and then will publish a new release

**Comment by mmanela** [comment]
These changes are now deployed in 4.3.0
