### ISSUE TITLE
When using a malformed Chutzpah.json config file, the test runner should immediately die and give a message indicating such.

### ISSUE THREAD

**Issue by rickwebiii** [mmanela/chutzpah#462]
My Chutzpah.json file contained the following. Note the lack of a comma after the first reference, making this file invalid json. I would expect Chutzpah to complain that my json is invalid (ideally, with line and column number). Instead, it silently continues, creates a test runner, no tests run because it didn't add any references or tests, and I get errors that are cryptic and indicate something is wrong with my tests.

Adding the comma fixed my issue.

{
    "Framework": "qunit",
    "TestFileTimeout": 10000,
    "TestHarnessReferenceMode": "AMD",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "References": [
        { "Path": "./Q.js" }
        { "Path": "./Knockout.js" },
        { "Path": "./JQuery.js" },
        { "Path": "./require.js" }
    ],
    "Tests": [
        { "Path": "./Tests.js" }
    ]
}

**Comment by mmanela** [comment]
Thanks for reporting this. I will take a look why it silently continued

**Comment by mmanela** [comment]
Does not repro in most recent version
