### ISSUE TITLE
VS2015 Disconnected Context Exception when trying to debug

### ISSUE THREAD

**Issue by mattmackay76** [mmanela/chutzpah#463]
in VS2015 using Chutzpah extension 4.1.0 I get the following exception when trying to debug. I also get intermittent issues with tests appearing, disappearing or no tests being discovered at all.

Temporarily I went back to 4.0.3 and things appear to be working again.
Here is the Exception Text:

DisconnectedContext occurred
Message: Managed Debugging Assistant 'DisconnectedContext' has detected a problem in 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\te.processhost.managed.exe'.
Additional information: Transition into COM context 0x7625f8 for this RuntimeCallableWrapper failed with the following error: The object invoked has disconnected from its clients. (Exception from HRESULT: 0x80010108 (RPC_E_DISCONNECTED)). This is typically because the COM context 0x7625f8 where this RuntimeCallableWrapper was created has been disconnected or it is busy doing something else. Releasing the interfaces from the current COM context (COM context 0x762488). This may cause corruption or data loss. To avoid this problem, please ensure that all COM contexts/apartments/threads stay alive and are available for context transition, until the application is completely done with the RuntimeCallableWrappers that represents COM components that live inside them.

**Comment by mmanela** [comment]
I have never see this error before. Can you give me more such as
1. Is this VS 2015 Update 1?
2. Exact version of VS?
3. What other extensions are installed.
4. Does it always repro?
5. Can you uninstall chutzpah, clear extension cache and re-install?

Given this info I can file bug in the team who builds the Test adapter.

**Comment by Eric75015** [comment]
Same problem for me! During unit testing.

**Comment by koljada** [comment]
I also have this problem. My version on VS is 14.0.24720.00 Update 1 and I'm not using Chutzpah.

**Comment by joel100** [comment]
+1 Using Update 2 testing log4net LogicalThreadContext.Properties

Occurs after the end of the test method

**Comment by mmanela** [comment]
@koljada Interesting, so you think this has nothing to do with Chutzpah?

**Comment by mmanela** [comment]
Closing as it seems to not be a chutzpah issue
