### ISSUE TITLE
Reset the referenced template before running each test

### ISSUE THREAD

**Issue by adeel41** [mmanela/chutzpah#464]
Is it possible to update/reset the DOM as it was before running the test. The problem I am having is that in some of my tests, I update few DOM elements but in my other tests (which are in the same file) I am expecting it to be at initial state which is before I ran my first test. Let me give me an example to explain it better

Added a template reference
`/// <template path="Index.html" />`

which will be loaded before running any tests. fine.

now in one of my tests, I updated the DOM (e.g. added some data attributes)

now when I run my second test, It is not expecting that data attributes but it found it because of earlier test.

Now the question is that is it possible to reset the content of loaded template?

**Comment by mmanela** [comment]
That is an interesting idea. Chutzpah typically would try to leave that up to the test framework itself but the way Chutzpah did the injection did make that hard. In the next version the template functionality will have the ability to wrap it in a script tag for you and then you could more easily manage when to add/remove from the dom.
