### ISSUE TITLE
Is there any way to make ReSharper-like file reference comment syntax (~/ for current project dir) work in Chutzpah?

### ISSUE THREAD

**Issue by saravanaj** [mmanela/chutzpah#467]
ReSharper's test runner parses file references that start with `~/` as files starting from the current project root directory:

```
/// <reference path="~/App/Code.js" />
/// <reference path="~/Scripts/jasmine/jasmine.js" />
```

Currently Chutzpah does not understand `~/`. Is there any way to configure this?

**Comment by mmanela** [comment]
If you have a chutzpah.json file you can configure how chutzpah roots your references. There is a setting called **RootReferencePathMode** that determines what it will do. Please see https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File
