### ISSUE TITLE
Chutzpah doesn't execute tests when choosing a folder with large amount of files

### ISSUE THREAD

**Issue by nivik** [mmanela/chutzpah#468]
After upgrading to 4.2.0 version, Chutzpah couldn't execute tests when choosing a folder with large amount of files. It did work on previous versions.

I'm running Visual Studio 2015 Update 1 and trying to run tests from a folder within my project that contains 10+ typescript files with tests. When I select the folder and click on "Run JS Tests", nothing happens. It does run tests when I'm choosing one file at a time. After rollback to 4.1.0 All works fine.

Same issue happens when I'm trying to run all the tests of a project by clicking on the project and then on "Run JS Tests". Nothing happens and I don't see an error or an exception.

I couldn't find a log file.

**Comment by dzonatan** [comment]
+1

**Comment by mmanela** [comment]
Does it work with a folder with 2 typescript files? Can you provide a project that repro's this issue?

I will try on my own box but in case here is something I am missing it might help for you to provide a project you know has the issue.

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
