### ISSUE TITLE
Chutzpah Test Adapter duplicates tests if spec file is referenced in _references.js

### ISSUE THREAD

**Issue by saravanaj** [mmanela/chutzpah#469]
Project structure:
```
├── Scripts
|   ├── _references.js
├── App
|   ├── Code.js
├── Test
|   ├── Code-Spec.js
└── Web.config
```

If I reference the `Code-Spec.js` file in `_references.js`, the test methods in the test explorer are getting duplicated.

**Comment by mmanela** [comment]
Why would you reference your test file in the _references.js file?

**Comment by saravanaj** [comment]
It gets added automatically if you have autosync enabled in _references.js file.

**Comment by mmanela** [comment]
Ok so you have a couple options.

1. Use a chutzpah.json file instead to reference what test / reference files you need.
2. Add a chutzpah-exclude=true attribute on the references you do not want chutzpah to look at

**Comment by mmanela** [comment]
Ping.. Have my options helped?

**Comment by saravanaj** [comment]
Yes, thanks.
