### ISSUE TITLE
PhantomJs crashes intermittently during initialization; running chutzpah+qunit with vstest

### ISSUE THREAD

**Issue by thorhayek** [mmanela/chutzpah#470]
On executing Chutzpah tests in TFS( also reproduced the failure locally) we came across the following error : 
        
> Unknown error occurred when executing test file. Received exit code of -1073741819

On investigating the chutzpah.log file I found that 
The phantomJs browser crashes intermittently during initialization while running unit tests. We are running our tests using  qunit framework + chutzpah plugin. The test run fine in visual studio i.e this failure happens only when we use the vstest.console.exe on the command line

Full Error : 
> vstest.executionengine.x86.exe Information: 0 : Time:17:28:51.5986255; Thread:16; Message:Invoking headless browser on test harness 'C:\Users\test\AppData\Local\Temp\39f8576a-fd84-4dfe-9b6d-cbc9eeda2705\WebSdk\Tests\obj\amd64\Tests\Scripts\_Chutzpah.b9105282e406d18e459eb27fe2e8df15.test.html' for file 'C:\Users\test\AppData\Local\Temp\39f8576a-fd84-4dfe-9b6d-cbc9eeda2705\WebSdk\Tests\obj\amd64\Tests\Scripts\dapmsn-tests.js'

> vstest.executionengine.x86.exe Information: 0 : Time:17:28:51.6206473; Thread:16; Message:Started headless browser: C:\Users\test\AppData\Local\Temp\39f8576a-fd84-4dfe-9b6d-cbc9eeda2705\VsTest\Extensions\phantomjs.exe with PID: 37728 using args: --ignore-ssl-errors=true --proxy-type=none "C:\Users\test\AppData\Local\Temp\39f8576a-fd84-4dfe-9b6d-cbc9eeda2705\VsTest\Extensions\JSRunners\qunitRunner.js" "file:///C:/Users/test/AppData/Local/Temp/39f8576a-fd84-4dfe-9b6d-cbc9eeda2705/WebSdk/Tests/obj/amd64/Tests/Scripts/_Chutzpah.b9105282e406d18e459eb27fe2e8df15.test.html" execution 30000 True 

> vstest.executionengine.x86.exe Information: 0 : Time:17:28:52.3369878; Thread:16; Message:Finished reading stream from test file 'C:\Users\test\AppData\Local\Temp\39f8576a-fd84-4dfe-9b6d-cbc9eeda2705\WebSdk\Tests\obj\amd64\Tests\Scripts\dapmsn-tests.js'

> vstest.executionengine.x86.exe Information: 0 : Time:17:28:52.3489978; Thread:16; Message:Ended headless browser: C:\Users\test\AppData\Local\Temp\39f8576a-fd84-4dfe-9b6d-cbc9eeda2705\VsTest\Extensions\phantomjs.exe with PID: 37728 using args: --ignore-ssl-errors=true --proxy-type=none "C:\Users\test\AppData\Local\Temp\39f8576a-fd84-4dfe-9b6d-cbc9eeda2705\VsTest\Extensions\JSRunners\qunitRunner.js" "file:///C:/Users/test/AppData/Local/Temp/39f8576a-fd84-4dfe-9b6d-cbc9eeda2705/WebSdk/Tests/obj/amd64/Tests/Scripts/_Chutzpah.b9105282e406d18e459eb27fe2e8df15.test.html" execution 30000 True 

> vstest.executionengine.x86.exe Error: 0 : Time:17:28:52.3760202; Thread:16; Message:Headless browser returned with an error: Unknown error occurred when executing test file. Received exit code of -1073741819

Let me know if you need more information to help investigate this. 
Chutzpah version: 4.1
phantomJs version: 2.0
vstest.console.exe :  Microsoft (R) Test Execution Command Line Tool Version 12.0.30723.0
Os : windows 10

**Comment by mmanela** [comment]
Looks to be this issue: https://github.com/ariya/phantomjs/issues/11073

Can you add your comments to that thread

**Comment by thorhayek** [comment]
opened a new thread here https://github.com/ariya/phantomjs/issues/14302 .  thanks

**Comment by mmanela** [comment]
Closing since nothing for Chutzpah to do here besides wait for PhantomJs to address
