### ISSUE TITLE
Cannot Debug Unit Tests

### ISSUE THREAD

**Issue by DaBeSoft** [mmanela/chutzpah#476]
Hi,

I am using VS 2015 Update 1 on Windows 10 x64.

I can run my Javascript/Typescript Tests just fine via VS Test Explorer, Resharper Test Explorer or Context Menu -> "Run JS Tests" (using either QUint or Jasmine, tried both)

But when i try to debug them (via any of the before mentioned was), Internet Explorer opens (White Screen) and i always get the following error in the Output window:

> Error: System.Runtime.InteropServices.COMException (0x8971001E): Exception from HRESULT: 0x8971001E
>    at EnvDTE80.Process2.Attach2(Object Engines)
>    at Chutzpah.VS.Common.DteHelpers.DebugAttachToProcess(Int32 subjectProcessId, String debugEngine)
>    at Chutzpah.VS.Common.VsDebuggerTestLauncher.LaunchTest(TestContext testContext)
>    at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext)
> While Running:[...]\file1.ts

Sadly i this Error message isn't quiet helpful for me... but it states that the error happens somewhere Chutzpah related.

this happens on both - JavaScript and Typescript tests. What's tested doesn't matter, even a simple test like this can't be debugged:
```
QUnit.module("QUnit Test - ");

test("Can add", () => {
    // Arrange
    var x = 0;
    // Act
    x++;
 
    // Assert
    equal(x, 1);
});
```

I hope you can help me, thanks in advance
Daniel

**Comment by mmanela** [comment]
Looks like chutzpah is unable to attach to IE on your box. Are you able to manually have VS attach to IE?

**Comment by DaBeSoft** [comment]
Debugging my TypeScript Code in VS via Internet Explorer Works just fine

**Comment by mmanela** [comment]
@turquoiseowl, Do you have any what this issue might be?

**Comment by turquoiseowl** [comment]
@mmanela  Do we know whether the Debug feature works in VS2015? I'm using it daily on VS2013/Win7x64 and it works well (although still using my build and not the official one).

@DaBeSoft Googling for the error code 0x8971001E suggests it *may* be something to do with trying to attach the debugger to a process that is already being debugged. Just to rule that out, is there any chance this is happening in your case?

**Comment by DaBeSoft** [comment]
@turquoiseowl I don't think that there is already a Debugger attched - at least not by my doing. To rule it out i started VS on my freshly booted PC and tried starting Debugging a TypeScript unit test right away (before opening any other debug sessions or Browsers) and it still happens. 

is there any way to find out if VS tries to attach a second Debugger - by Chutzpahs doing or not? any log files that could help?

I'll try the same Scenario on my similary configured secondary tommorow and Report back. Maybe the Installation on my Primary PC is faulted...

**Comment by mmanela** [comment]
@turquoiseowl I have used it and confirmed it works in 2015.

**Comment by mmanela** [comment]
@DaBeSoft Any update on this, do you still have the issue?

**Comment by DaBeSoft** [comment]
@mmanela I am so sorry i forgot to Report back

I just retried debugging the typescript tests and it works now. I freshly installed my PC in the meantime, maybe something was messed up with my previous installation....

Thank you for your help and patience!
