### ISSUE TITLE
Putting a Path in references for my TypeScript files to test breaks Chutzpah

### ISSUE THREAD

**Issue by Ric43** [mmanela/chutzpah#480]
I have a folder structure under Scripts for tests called Tests and one for my ViewModels called ViewModels. If I place my chutzpah.json file in the Tests folder and set it up thusly:

{
    "Framework": "qunit",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ]
    },
    "References": [
        { "Path": "../jquery-1.10.2.js" },
        { "Path": "../knockout-3.4.0.js" },
        { "Path": "../ViewModels/", "Includes": [ "*.ts" ] }
    ],
    "EnableTracing": true,
    "TraceFilePath": "c:/logs/chutzpah.log"

}

Test explorer doesn't show any tests, and if I run the test from the context menu, it seems to hang. The trace file includes this line:
c:\dev\solution\trunk\source\webclient\scripts\tests\HomeTests.js
devenv.exe Error: 0 : Time:22:06:39.5445581; Thread:77; Message:Couldn't find generated path for c:\dev\solution\trunk\source\webclient\scripts\ViewModels\Home\IndexVm.ts at 

That is the last entry in the file.

If I put the chutzpah.json file into the scripts folder and modify it as such:

{
    "Framework": "qunit",
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ]
    },
    "References": [
        { "Path": "./jquery-1.10.2.js" },
        { "Path": "./knockout-3.4.0.js" },
        { "Include":  "*/ViewModels/*.ts" }
    ],
    "EnableTracing": true,
    "TraceFilePath": "c:/logs/chutzpah.log"
}

Then it works correctly and my tests get discovered by test explorer. The way chutzpah seems to die silently bothers me.

**Comment by Ric43** [comment]
Also seeing this in the output window:
An exception occurred while test discoverer 'ChutzpahTestDiscoverer' was loading tests. Exception: Couldn't find generated path for c:\dev\solution\trunk\source\webclient\scripts\ViewModels\Home\IndexVm.ts at

**Comment by mmanela** [comment]
Can you give me a full repro that I can run locally?

**Comment by Ric43** [comment]
Will try and create one with sample code. Will probably be only next week. Little bit swamped at present. Thanks for the reply.
RegardsRichard Chown

Date: Thu, 3 Mar 2016 22:13:06 -0800

**Comment by esskar** [comment]
I get the same error. I have

`MyModule\Scripts\` where i have the typescript files i want to test.
`MyModule.Tests\Tests\` with all my tests.
and `MyModule.Tests\chutzpah.json` 

```
{
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ]
    },
    "References": [
        {
            "Path": "../MyModule/Scripts",
            "Includes": [ "**.ts" ],
            "Excludes": [ "**.d.ts" ]
        }
    ],
    "Tests": [
        { "Includes": [ "*/Tests/*.ts" ], "Excludes": [ "*/Tests/*.d.ts" ] }
    ]
}
```

any idea?

**Comment by mmanela** [comment]
@esskar Can you give a full repro that I can run locally?

**Comment by Ric43** [comment]
Sorry, I simply don't have time to do this right now. The description of the problem I described shows a way of reliably replicating the issue. If you have done that and you cannot get the issue, then let me know. Alternatively, I believe there was another user with this issue. They may be able to help you with a repro.
RegardsRichard Chown

Date: Wed, 6 Apr 2016 10:39:41 -0700

**Comment by KerryRitter** [comment]
I am also seeing this problem.

**Comment by mmanela** [comment]
@esskar I was able to repro your issue and it is an unfornutate complicated part of the configuration. If you use the following JSON it will work:

```
{
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ],
         "Paths" : [
          { "SourcePath": "../", "OutputPath": "../" }
        ]
    },
    "References": [
        {
            "Path": "../MyModule/Scripts",
            "Includes": [ "**.ts" ],
            "Excludes": [ "**.d.ts" ]
        }
    ],
    "Tests": [
        { "Includes": [ "*/Tests/*.ts" ], "Excludes": [ "*/Tests/*.d.ts" ] }
    ]
}
```

What I had to add was the *Paths* section which tells Chutzpah where your source and output files are relative to. By default it assumes all are relative to your chutzpah.json file but since that file is not above the directory of all your ts files you need to configure it.

You can read more here: https://github.com/mmanela/chutzpah/wiki/Compile-Setting


@everyone else, please tell me if this resolves your issues

**Comment by mmanela** [comment]
In Chutzpah 4.2.3 you should be able to do this:

```
{
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ]
    },
    "References": [
        {
            "Path": "../MyModule/Scripts",
            "Includes": [ "**.ts" ],
            "Excludes": [ "**.d.ts" ]
        }
    ],
    "Tests": [
        { "Includes": [ "*/Tests/*.ts" ], "Excludes": [ "*/Tests/*.d.ts" ] }
    ]
}
```
