### ISSUE TITLE
Object reference not set to an instance of an object. at Chutzpah.TestHarness.BuildTags(IEnumerable`1 referencedFilePaths)

### ISSUE THREAD

**Issue by fjut1945** [mmanela/chutzpah#481]
I am posting the issue I encountered here as a reference for anyone trying to setup Chutzpah as a part of a TFS build configuration. The error i encountered was:

Error: System.NullReferenceException: Object reference not set to an instance of an object. 
at Chutzpah.TestHarness.BuildTags(IEnumerable`1 referencedFilePaths) 
at Chutzpah.TestHarnessBuilder.CreateTestHarness(TestContext testContext, TestOptions options) 
at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext) 
While Running:C:\Builds\1\appname\Main_Compile+UnitTest\bin_PublishedWebsites\WebClient\test\unit\formattingServiceTest.js 

The problem was caused by missing references. Here is a excerpt from my test file:

  `describe('Authentication Service Tests', function ()`
  `{`
    `beforeEach(function()`
   ` {`
        `module('appname.enums');`
       ` module('appname.constants');`
      `  module('appname.services');`
    `});`

    it('Given user with no roles HasRoleLRR returns false', inject([
        'AuthenticationService', function (authenticationService) {
            var testUser = {
                id: 1,
                identityKey: 'test.user',
                label: 'test user',
                roles: []
            };

            expect(authenticationService.getRoleInfo(testUser).hasRoleLRR).toBeFalsy();
        }
    ]));`

Once i added references to the top of the file, everything was ok:

 `/// <reference path="../../app/components/angular/angular.js" /> `
 `/// <reference path="../../app/components/angular-mocks/angular-mocks.js" /> `
 `/// <reference path="../../app/components/underscore/underscore.js" />  `
 `/// <reference path="../../app/scripts/modules.js" /> `
 `/// <reference path="../../app/scripts/config/config.js" /> `
 `/// <reference path="../../app/scripts/config/enums.js" /> `
 `/// <reference path="../../app/scripts/factory/authenticationService.js" /> `

Thanks,
Ognjen

**Comment by mmanela** [comment]
Ok great, glad this is resolved
