### ISSUE TITLE
How to tell Chutpah the order of the files / Reduce reference maintenance

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#483]
Hi,
I have an issue when writing with TypeScript and using a base class - the base class file might get referenced after the derived which makes the derived class to not be initialized.
assuming I have a folder called `parsers` with typescript files I tried the following in the `chutzpah.json` file but it didn't work:

``` json
{ "Path": "isrealhiking.web\\services\\parsers\\", "Includes": ["Base1.ts", "Base2.ts"]},
{ "Path": "isrealhiking.web\\services\\parsers\\", "Includes": ["*.ts"]},
```

but they were still referenced alphabetically.
the following did work but the json file starts to look bad and the maintenance for this is high.

``` json
{ "Path": "isrealhiking.web\\services\\parsers\\Base1.ts"}
{ "Path": "isrealhiking.web\\services\\parsers\\Base2.ts"}
{ "Path": "isrealhiking.web\\services\\parsers\\", "Includes": ["*.ts"]},
```

Is there a better way to reference all the files I need in order to test my code?
I'm already doing it in the index.html file, is there a way to take it from there?

**Comment by mmanela** [comment]
Typically I just recommend ordering explicitly in the chutzpah.json file. You can also let chutzpah traverse your dependencies using reference comments although this has its own maintenance problems but does work for some people.

**Comment by HarelM** [comment]
Since SPA is growing stronger as far as I can tell, would it be possible in the future to tell Chutzpah where is the index.html file is located and that Chutzpah will reference all the scripts entries from there? I think that in terms of maintenance it will be the easiest as I need to update my index.html file anyway in order to make things work...

**Comment by mmanela** [comment]
It is fair, my concern is how generalizable that is. Many application dynamically generate their HTML using some other process. However, if you are interested in prototyping this I would not be against it. I could see this as a special entry in the chutzpah.json reference list where you give it an HTML file but indicate to use it for reference parsing.

**Comment by HarelM** [comment]
I'd like that very much. wouldn't mind "QA" it for you...
