### ISSUE TITLE
Duplicate test name causes issues in coverage report

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#484]
I accidentally copy-paste a test in jasmine and ran a code coverage on the entire project. The report then came out weird with duplication in all files. I know that it is my mistake but I should probably get a warning somewhere...?

**Comment by mmanela** [comment]
That is odd. What do you mean duplication in all files?

**Comment by HarelM** [comment]
By duplicate in all files I meant that in the coverage report every file had two rows instead of one describing the coverage.

**Comment by mmanela** [comment]
Ok, and to repro just copy one file verbatim again?

**Comment by HarelM** [comment]
Haven't tried to reproduce it yet, but the original scenario was when I just copy-paste inside the same file a test in jasmine (the code for  the test of course).

**Comment by mmanela** [comment]
I think I need more info for a repro. I tried a basic thing of taking a test file and duplicating one test and these are my results before and after


__Before__
![image](https://cloud.githubusercontent.com/assets/304410/13767368/b53ba24c-ea26-11e5-91fe-e5a425102dbf.png)


__After__
![image](https://cloud.githubusercontent.com/assets/304410/13767363/a99522ba-ea26-11e5-964b-7d5dc279e79e.png)

**Comment by HarelM** [comment]
I can't reproduce either, might have been a more complex scenario that caused it... you are free to close the issue.
