### ISSUE TITLE
Guidance for dnx based projects

### ISSUE THREAD

**Issue by dazinator** [mmanela/chutzpah#487]
Firstly, thanks for making Chutzpah.

Unfortunately, I have spent a long time trying to get Chutzpah to work for my project, and have failed! 

I am using VS2015
My project is a new Dnx based project, targeting dnx451.

I am assuming the reason I am struggling is because this sort of setup is either unsupported or not yet fully tested / documented yet.

Firstly, adding the Chutzpah NuGet package didn't appear to do anything for me. I added it to the project.json file, it seemingly installs,  but then I can't find anything in the packages directory, no chutzpah console exe etc.

So I moved on to using the test adaptor which to be honest is my preferred way of running tests anyway.

My existing project looks like this:

- Project A 
    - wwwroot
        - lib
            - (bower dependencies installed here)
        - modules
            - (compiled typescript output here as AMD modules)
        - require.config.js
    - typings
        - (tsd's installed here) 
    - Scripts
        - tsconfig.json (typescript project settings file)
        - typescriptOne.ts
        - typescriptTwo.ts

I like to keep my tests in a seperate project, so I created a new project to contain the tests for the above project, i.e:

- Project A 
- Project A.Tests

The tests projects adheres to the same structure as the first.

Try as I might, I couldn't get the test adaptor to work, and I am sure it must be something to with my Chutzpah settings file.

Each time it tried to discover my tests it hit problems which were shown in the output window. For example:

```
------ Discover test started ------
Error: Timeout occurred when executing test file
While Running:e:\src\projectA\wwwroot\test2.js

```

The problem for me is, the output isn't helpful to me in identifying whats wrong. I have been tweaking the Chutzpah file, and each time it would usually lead to a different exception in the output window. Sadly, because the test harness html file is deleted by the test adaptor each time, I can't easily see what impact my tweaks to the chutzpah config file is making to the test harness. I also can't open the test harness html file manually to try and see what the problem is and why thye test adaptor might be reporting an exception - because it only exists for a very short period of time on disk.

I've decided that for now, I can't afford to waste anymore time figuring out what is wrong, but if there are any brave souls out there that can demonstrate some sample, showing Chutzpah being used in a new Dnx project, AND testing typescript files that live in a seperate project, I'd find that really really helpful.

**Comment by mmanela** [comment]
Can you give me a sample of what you are trying? Chutzpah should work fine and have nothing to do with it being DNX or not.

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
