### ISSUE TITLE
Tests duplicated within Test Explorer Window

### ISSUE THREAD

**Issue by pratesim** [mmanela/chutzpah#492]
This is my project structure in VS:

```
|- src/
  |- srcFile1.ts
  |- srcFile2.ts
|- Chutzpah.json
|- tests/
  |- testFile1.ts
  |- testFile2.ts
  |- testFile3.ts
```

Currently testFile1.ts contains testA and testB, while testFile2.ts contains testC and testD, so 4 tests in total, but the Test Explorer window is showing 12 tests.

The testA appears 3 time with the sources: testFile1.ts, testFile2.ts, testFile3.ts;
the same for testB, testC, and testD.

I want to see the testA only 1 time (the one with the source testFile1.ts), how can I achieve this?

My Chutzpah.json file is like that:

```
{
    "Framework": "jasmine",
    "References": [
         { "Path": "test/", "Includes": [ "*.js" ] }
    ],
    "Tests": [
        { "Path": "test", "Excludes": [ "*.js" ] }
    ]
}
```

**Comment by pratesim** [comment]
I resolved removing the references part. But now if I run all the tests from VS the results are visible in three different tabs of my browser. Is it possible to have the tests results in only one tab?

**Comment by mmanela** [comment]
Try setting EnableTestFileBatching to true which you can read about [here](https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File)

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
