### ISSUE TITLE
error loading source script when running chutzpah with code coverage and jasmine

### ISSUE THREAD

**Issue by T-rav** [mmanela/chutzpah#493]
I am having the same issue mentioned in ticket https://github.com/mmanela/chutzpah/issues/340, now closed, where I encounter an error loading source files with code coverage enabled.

I have the latest version of the Chutzpah VSIX installed on my TFS 2015 server in VS 2015 Enterprise. Every time the server does a CI build I get this error. It was an internment issue until today when it became such a problem only 1 in 20 builds was passing. Yet all local test runs on developer machines always pass.

I did some digging and found that the error is caused by the fact that there is a default 180 ms timeout as per _blanket.options("timeout") when loading source files in the attachScript method ( line 5141 ) of the blanket_jasmine_v2.js file.
I hard coded this value to 10000 ms and my problem is solved, all TFS CI test runs are green again.

Can you please provide documentation on how to override this value in the chutzpah.json configuration? And adjust the default passed into blanket when enabling code coverage to a more sensible value like 3000 or 5000 ms. I imagine anyone with a large number of test on a busy server will be impacted by this problem.

**Comment by mmanela** [comment]
I can bump the value up but I looked at it seems the default is 3000ms and not 180. 

```
 attachScript: function(options,cb){
           var timeout = _blanket.options("timeout") || 3000;
           setTimeout(function(){
                if (!_blanket.utils.cache[options.url].loaded){
                    throw new Error("error loading source script");
                }
           },timeout);
           _blanket.utils.getFile(
                options.url,
                cb, 
                function(){ throw new Error("error loading source script");}
            );
        },
```

**Comment by mmanela** [comment]
I just released version 4.2.1 and I bumped it from 3000 ms to 5000ms to be safe :)

**Comment by arch-imp** [comment]
I am encountering this issue on our TFS build agents with QUnit. I have searched the github repository and don't see any change to 5000ms.  All the runners seem to still be set to 3000ms.

It would be really ideal if we could adjust this value via chutzpah.json and/or command-line.

**Comment by mmanela** [comment]
I set the default to 5000 [here](https://github.com/mmanela/chutzpah/blob/e73f549776c3c6b7259dddf30e324c477176eb41/Chutzpah/Coverage/BlanketJsCoverageEngine.cs#L106). And I agree configurable would be nice, will look at doing that in future release.

Just to confirm, we are talking about the code coverage timeout when it waits for an asynchronous file right?

**Comment by arch-imp** [comment]
Ah, I see.  I was looking in [these files](https://github.com/mmanela/chutzpah/tree/e73f549776c3c6b7259dddf30e324c477176eb41/Chutzpah/TestFiles/Coverage)

The error I am getting is "error loading source script". The only place I can find that message is in those files.

**Comment by mmanela** [comment]
And if you turn coverage off it works fine?

**Comment by arch-imp** [comment]
That is correct.  The only time I ever see this message is when code coverage is enabled.
