### ISSUE TITLE
Chutzpah does not work with the latest version of chai.js

### ISSUE THREAD

**Issue by MeltingMosaic** [mmanela/chutzpah#494]
I'm getting errors when I try to use Chutzpah to run my Mocha unit tests with chai - I think the version of Mocha is out of date.

**Comment by mmanela** [comment]
I am working on updating Mocha right now. Next release which will be out soon should resolve this

**Comment by mmanela** [comment]
I published version 4.2.1 which has an updated version of Mocha that should work fine with latest Chai.
