### ISSUE TITLE
Chutzpah showing duplicate tests in Test Explorer (Visual Studio 2015)

### ISSUE THREAD

**Issue by ICTechnology** [mmanela/chutzpah#496]
I'm using QUnit with a HTML test harness for my JavaScript testing, I've imported it in to visual studio and have installed this addon, the problem is, it picks up duplicate tests. So it reads tests from the HTML test harness, and then picks them up again in the actual test files. I only want to show my test harness tests inside test explorer, is there anyway I can do this ?

**Comment by mmanela** [comment]
Update your chutzphah.json file to exclude *.js files and include only your .html test harness file.

**Comment by ICTechnology** [comment]
Would you be able to give me an example of the structure for that please? I can see a "CodeCoverageExcludes" and Includes, but I can't seem to find the specific wording for ExcludingFiles from being picked up in the test explorer?

**Comment by mmanela** [comment]
See this [documentations](https://github.com/mmanela/chutzpah/wiki/tests-setting)
