### ISSUE TITLE
Chutzpah not building - 183 Errors.

### ISSUE THREAD

**Issue by ICTechnology** [mmanela/chutzpah#497]
I'm trying to get the repository, I'm using Visual Studio 2015 Update 1, I have the 2015 SDK installed, but I'm receiving a lot of build errors. 183. This is a fresh get from the master branch.

I've tried this on two separate machines now, and neither are able to build Chutzpah. Specifically it's the VS integration projects that are missing a bunch of dependencies, even though I have the SDK installed.

**Comment by miparnisari** [comment]
I'm having issues too. Using VS 2015, I did a clean clone and get the following:

![errors](https://cloud.githubusercontent.com/assets/5374887/14224020/b180f8f0-f863-11e5-8a5d-482633475f9c.png)

**Comment by ICTechnology** [comment]
I've tried a variety of things, I've installed SDK 2013, SDK 2015, but I am still missing loads of references, and therefore the solution just doesn't build. I have managed to get it down to 134 errors. Any help would be great, I would like to contribute to this project, but currently I am unable to. The errors are all to do with the VS Extension projects

**Comment by ICTechnology** [comment]
Ok I've managed to actually get it working with a bit of faffing about.

So what was missing?

Remove Microsoft.VisualStudio.Shell.11.0 and use a later version like 14.0
Downloaded Microsoft.VisualStudio.TestPlatform.ObjectModel from: https://github.com/machine-visualstudio/machine.vstestadapter/tree/master/Source/Microsoft.VisualStudio.TestPlatform.ObjectModel%20Binaries/VS14Update1 and referenced that
Downloaded Microsoft.VisualStudio.TestWindow.Interfaces.dll from http://www.zhaodll.co/m/20141203/242366.html#.VwI4-vkrJhE use these .dll's at your own risk.

**Comment by mmanela** [comment]
Thanks so much for figuring it out. I can try to write an updating documentation but it would help if you could just list all the files you needed and the steps you did .

**Comment by ICTechnology** [comment]
Unfortunately I had a problem trying to run it inside Visual Studio to test my change. It got stuck hitting the same exception and looping back in to it. I believe that was an issue in the VisualStudio.Shell.14.0. I'll see if I can get it fully working.

**Comment by mmanela** [comment]
Can you try to use the Chutzpah.NoVS.sln and see if it works. That excludes all VS integration projects.

**Comment by mmanela** [comment]
@ICTechnology Any update?

**Comment by mmanela** [comment]
Closing as I have not heard back in a long time. Please re-open if needed.
