### ISSUE TITLE
Error: Timeout occurred when executing test file

### ISSUE THREAD

**Issue by HadyAllam** [mmanela/chutzpah#498]
I installed Chutzpah Menu Context. i tried to run test cases but i got an error 

Log Message: suiteSetup from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: setup from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: first from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: teardown from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: setup from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: inner setup from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: second from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: inner teardown from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: teardown from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Log Message: suiteTeardown from D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
Error: Timeout occurred when executing test file
While Running:D:\Samples\TestBuild\TestBuild.Tests\JsTest\Tdd.tests.js
========== Total Tests: 0 passed, 0 failed, 0 total ==========

Chutzpah.Json

`
{
    "Framework": "mocha",
    "MochaInterface": "tdd",
	 "TestHarnessLocationMode": "Custom",
	"TestHarnessDirectory": "JsTest",
	"CustomTestHarnessPath": "JsTest\\index.html"	
}

`

I have another issue

I installed test runner but nothing appears in test explorer
![image](https://cloud.githubusercontent.com/assets/15063220/14231985/37d12a58-f998-11e5-8dd9-49832c7f669f.png)

Thank you for your help

**Comment by mmanela** [comment]
Your setup seems non-typical. I am not sure why you are using a customTestHarnessPath. I think you should have a simpler setup that looks more like: https://github.com/mmanela/chutzpah/tree/master/Samples/Settings/Batching

**Comment by HadyAllam** [comment]
Thank you time out problem is solved now. but i have another problem now. i am using mocha as my Framework. test cases failed because Chutzpah cannot find chai. i added it in my references 

`
{
    "Framework": "mocha",
    "MochaInterface": "tdd",
	"TestHarnessLocationMode": "SettingsFileAdjacent",
	"EnableTestFileBatching": true,
	"References": [
        { 
		"Path":"chai.js",
		"Path":"Code.js"
		}
    ],
	"Tests": [
        { "Path": "JsTest", "Includes": ["*.tests.js"]}
    ]
	
}
`

**Comment by HadyAllam** [comment]
I found the error. i have to adjust references section

`

"References": [
        { 
		"Path":"Lib\\chai.js", "IsTestFrameworkFile": "true" 
		},
		 { 
		"Path":"JsTest\\Code.js"
		}
    ]

`

thank you
