### ISSUE TITLE
Chutzpah cannot run tests in Travis CI

### ISSUE THREAD

**Issue by cidthecoatrack** [mmanela/chutzpah#499]
When I try to run Chutzpah javascript tests on Travis CI, I get the following output:

```
$ mono ./packages/Chutzpah.4.2.1/tools/chutzpah.console.exe ./Tests/Unit/Scripts
Chutzpah console test runner  (64-bit .NET 4.0.30319.17020)
Version 4.2.1.0
Copyright (C) 2015 Matthew Manela (http://matthewmanela.com).
.IO.FileNotFoundException: Unable to find test runner base js file: JSRunners\chutzpahRunner.js
  at Chutzpah.TestRunner.ProcessTestPaths (IEnumerable`1 testPaths, Chutzpah.TestOptions options, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback) <0x4196de30 + 0x0086e> in <filename unknown>:0 
  at Chutzpah.TestRunner.RunTests (IEnumerable`1 testPaths, Chutzpah.TestOptions options, ITestMethodRunnerCallback callback) <0x4196dc90 + 0x00077> in <filename unknown>:0 
  at Chutzpah.Program.RunTests (Chutzpah.CommandLine commandLine) <0x41911810 + 0x00ad8> in <filename unknown>:0 
  at Chutzpah.Program.Main (System.String[] args) <0x4190bd80 + 0x00162> in <filename unknown>:0 
The command "mono ./packages/Chutzpah.4.2.1/tools/chutzpah.console.exe ./Tests/Unit/Scripts" exited with 1.
```

However, if I run the same command-line argument on my local machine, the tests run fine.  I am not sure what is different about the Travis CI environment that causes it to not find the `chutzpahRunner.js` file.

Here is my `.travis.yml`:

```
language: csharp
solution: DNDGenSite.sln
install:
  - nuget restore DNDGenSite.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild DNDGenSite.sln /p:TargetFrameworkVersion="v4.5.1" /p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Tests/bin/Release/DNDGenSite.Tests.dll
  - mono ./packages/Chutzpah.4.2.1/tools/chutzpah.console.exe ./Tests/Unit/Scripts
```

I will say, I recently encountered an issue with NUnit where referencing properties on a dynamic object was fine locally, but threw a hissy-fit on Travis CI, and so I had to find a way around that (referencing a different pointer that was not a property on the dynamic object).  I wonder if something similar is occurring within the Chutzpah codebase...

**Comment by mmanela** [comment]
I have never tried chutzpah in Travis CI so I honestly don't know. And I see you are running it using Mono and I am not sure Chutzpah will even run in Mono, that is another thing I have never tested. So, you are treading into uncharted territory here :)

**Comment by cidthecoatrack** [comment]
Travis builds on virtual linux servers, so I'm pretty sure mono is required to run standard C# exe's.  Unless you know of a way to run chutzpah in a linux environment...

I have also toyed with using `wine` instead of `mono`, and am currently looking at how one would gete that set up in Travis CI

**Comment by mmanela** [comment]
So I am not sure if Chutzpah will run on Mono without source code changes. I have been interested in this before but never had time to pursue it.

**Comment by cidthecoatrack** [comment]
Well, here is a workaround: use `wine` instead.  It works very well (although for Travis, it has to do a lot of extra install stuff, so if we can eventually get `mono` support, that will certainly be faster)

Here is my modified config file for Travis:

```
language: csharp
solution: DNDGenSite.sln
before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install wine1.7 -y
install:
  - nuget restore DNDGenSite.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  - xbuild DNDGenSite.sln /p:TargetFrameworkVersion="v4.5.1" /p:Configuration=Release
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Tests/bin/Release/DNDGenSite.Tests.dll
  - wine ./packages/Chutzpah.4.2.1/tools/chutzpah.console.exe ./Tests/Unit/Scripts
```

**Comment by mmanela** [comment]
Interesting, awesome that wine works. Congrats to be the first person I know of to do this :)
