### ISSUE TITLE
VS2015.2 - TypeScript compilation not working

### ISSUE THREAD

**Issue by KerryRitter** [mmanela/chutzpah#502]
chutzpah.json:

```
{
    "Framework": "jasmine",
    "AMDBaseUrl": "out/MyProject.Tests/",
    "AMDAppDirectory": "./",
  "Compile": {
    "Mode": "Executable",
    "Executable": "compile.bat"
    //"Extensions": [ ".ts" ],
    //"ExtensionsWithNoOutput": [ ".d.ts" ],
    //"Timeout": 5000
  },
    "TestHarnessReferenceMode": "AMD",
    "References": [
        {
            "Includes": [
                "*/node_modules/requirejs/require.js"
            ]
        }
    ],
    "Tests": [
        {
            "Includes": [
                "*/Scripts/**/*.ts"
            ]
        }
    ]
}
```

compile.bat:
```
@echo off
node node_modules/typescript/bin/tsc
```

tsconfig.json: 
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true, 
    "outDir": "out"
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

For some reason, the compilation is not actually running when I run the tests in the solution. When I run compile.bat manually, I can then run the tests and they work as expected. Otherwise, I get 'file not found' exceptions and no tests run.

Additionally, when I uncomment the options I commented out in the chutzpah.json, the testing starts but never exits (successfully nor with errors).

Any help is appreciated.

**Comment by KerryRitter** [comment]
I created a repo that can reproduce this problem: https://github.com/KerryRitter/TypeScriptAngular

**Comment by KerryRitter** [comment]
For anyone needing a workaround, the following gulp build re-compiles the out/ folder for me in a watch, which lets me run tests. 

```
var gulp = require("gulp");
var exec = require("child_process").exec;

gulp.task("compile:ts", function () {
    exec("compile.bat");
});

gulp.task("watch:ts", function () {
    gulp.watch("./Scripts/**/*.ts", ["compile:ts"]);
});
```

**Comment by lennykean** [comment]
I was able to get this working by changing the compile section as follows: 
```
 "Compile": {
    "Mode": "Executable",
    "Executable": "compile.bat",
    "Extensions": [ ".ts" ],
    "Paths": [
        { "OutputPath": "out/TypeScriptAngular.Tests/" }
    ]
  }, 
```

I think the issue here is that if you get the config even slightly wrong, it fails silently. I was getting a null reference exception, in which case the chutzpah process dies silently and you need to restart VS before it will work again.

I was using the console runner to debug it, and I was getting the failure [here](https://github.com/mmanela/chutzpah/blob/master/ConsoleRunner/Program.cs#L186)

testResultsSummary was null when it was trying to access FailedCount

**Comment by mmanela** [comment]
I will investigate to see why it was failing so oddly. I am glad you found a work around

**Comment by mmanela** [comment]
The config you shown is correct but when I am playing with your repro I cannot get that null ref exception you showed. Can you show me the config I need to get that?

**Comment by KerryRitter** [comment]
That config is the same one we used. We are experiencing this problem consistently with this config on multiple machines.

**Comment by mmanela** [comment]
I took your repro, uncommented the section in the json, fixed this missing comma and I got a different error

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
