### ISSUE TITLE
Code coverage using sourcemaps does not apply to asynchronously loaded files.

### ISSUE THREAD

**Issue by dufrannea** [mmanela/chutzpah#503]
Hi,

I am using chutzpah for my typescript project, and recently added coverage.
I use requirejs, jasmine, external (Visual Studio) compilation, and "UseSourceMaps" option is set to true in my chutzpah.json file. I have been unable so far to get coverage for the source _.ts_ files, I get it only for the generated _.js_ files (ie the coverage html file mentions only _.js_ files).

I had a look at [this issue](https://github.com/mmanela/chutzpah/issues/308) and the associated (wonderful) PR, and it seems to me that me mapping between generated and source files is done only for "referenced files", which asynchronously loaded files are not. From my understanding, the mapping is reused to decide whether a coverage result for a javascript file should be remapped to the source file once coverage is done.

I created this small project for easier reproduction, this should make it easier for you to tell me if I missed something : 
https://github.com/dufrannea/ChutzpahTypescriptCoverage

I tested with [those changes](https://github.com/dufrannea/chutzpah/commit/f988e73f5978209dcda7c60c39b743c463c537c2) and I properly get coverage for my typescript source files. What my changes do is to  opportunistically find sources and source maps once coverage is done. The way to identify sources is clearly not how it should be done, but hopefully it illustrates my point.

Can you tell me if I am missing something here ? 

Cheers !

**Comment by mmanela** [comment]
Thanks for the comment, I think it is a good catch that the sourcemap is not working on the dynamic files.

Couple questions
1. Why did you move  @@ReferencedJSFiles@@ higher in the test harness?
2. Your solution to adhoc find the source maps seems interesting. Basically, you are saying if Chutzpah doesn't know about this file BUT we see that is has a souremap just dynamically make the reference look like wefound it earlier? Seems to make sense.


Also, there is a way currently to make chutzpah work for this. You can reference *all* your TS files in the "references" section in the json. And you can include the property: IncludeInTestHarness as false. This should work but I think what you are proposing sounds better.

If you clean it up a bit please send a PR

**Comment by gregveres** [comment]
Hi @dufrannea 

Are you able to create a PR for this change? I have just switched over to using AMD to load my modules and I am running into this. 

Thanks
Greg

**Comment by gregveres** [comment]
Hi @mmanela 

I am looking at his changes. I think they are incomplete but right now I am not able to build the solution. I cloned the repo from github and when I try to build I get these two errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'ChutzpahUTESettings.ResetSettings()': no suitable method found to override	VS.Common	C:\Users\gregv\Documents\GitHub\chutzpah\VS.Common\Settings\ChutzpahUTESettings.cs	55	Active
Error	CS0246	The type or namespace name 'DialogPage' could not be found (are you missing a using directive or an assembly reference?)	VS.Common	C:\Users\gregv\Documents\GitHub\chutzpah\VS.Common\Settings\ChutzpahUTESettings.cs	15	Active

```

Any quick suggestion what I might be doing wrong? 
I opened the Solution Chutzpah.VS.sln. The chutzpah project is selected as the default project. And as the error indicates it is having trouble compiling VS.Common.

Thanks
Greg

**Comment by mmanela** [comment]
Couple things. First from command line run

./build install

This sets up chutzpah's dependencies.

Second, try the .novs solution and see if that works.

**Comment by gregveres** [comment]
@mmanela 

after doing the build step and using the .novs solution, I am able to build the command runner and the dll. 

Now I am trying to figure out where to put them so that they get run so I can test them out. I would have thought that I would replace chutzpah.console.exe and chutzpah.dll that are found in my extensions directory: 
C:\Users\gregv\.nuget\packages\Chutzpah\4.2.3\tools


But looking at that packages directory, I see a chutzpah.console.vshost.exe. I am wondering if that is the one that is being run when I right click inside my chutzpah.json file and select Run Chutzpah with coverage. 

Maybe I should be running chutzpah.console.exe from the command line against my project's files? I will look around to see if I can figure out what the command line should be. 


BTW, with the .novs sln loaded, running the tests (ctrl-r, a) I get a lot of failures. For  instance 6 of the mathLib tests in the ConsoleRunner section fail.

**Comment by gregveres** [comment]
@mmanela 

You can ignore the previous message for a few minutes. I just found this link:
https://github.com/mmanela/chutzpah/wiki/building-and-running-the-code

and I am following those instructions first.

**Comment by gregveres** [comment]
Ok I installed the SDK but the .vs.sln still shows Microsoft.VisualStudio.Shell.11.0 as not found in the solution explorer and symbols from it are not found during compilation so I must have done something wrong. 

I am moving on to trying to figure out the command line flags to use to see if the changes do what we think they should.

**Comment by gregveres** [comment]
I have the debugger running on chutzpah.console.exe now with this command line:

Tests\App\FrontDesk\AddMemberToLeagueViewModelTests.ts /openInBrowser FireFox /coverage
and the appropriate working directory. 

I am getting the test results loaded in firefox with the coverage listed below. But the coverage is still showing JS files not TS files. 

By setting break points I can see that the main function that @dufrannea  changed isn't getting called. He made changes to DeserializeCoverageObject but that isn't getting called at all. So I am not sure where the coverage is being dealt with. I will keep looking, but I think at this point it is safe to say that @dufrannea's changes don't do what I expected them to do. 

Is there a different execution path when you do "run chutzpah with ... coverage" in the VS extension?

**Comment by mmanela** [comment]
That should be called as long as the browser successfully returned coverage results.
