### ISSUE TITLE
Error: ReferenceError: Can't find variable: angular when running code coverage

### ISSUE THREAD

**Issue by evgeny78** [mmanela/chutzpah#504]
Using Chutzpah with angular+typescript+jasmine
Works fine, but when trying to exclude angular from coverage report using line:
"CodeCoverageExcludes": ["Scripts\\*.js"]
in Chuzpah.json
coverage stops working with error: ReferenceError: Can't find variable: angular

**Comment by mmanela** [comment]
I think you need to either escape your backslash or use a forward slash:

```
"CodeCoverageExcludes": ["Scripts/*.js"]
```

**Comment by evgeny78** [comment]
Tried both options, but still has the same error :(

**Comment by mmanela** [comment]
Are you using the minified version of angular?

**Comment by evgeny78** [comment]
Yes, I use minified version

**Comment by mmanela** [comment]
Can you provide a full repro that I can download and run?

**Comment by evgeny78** [comment]
Project uploaded to here: http://s000.tinyupload.com/index.php?file_id=21750872046932823366
Thank you for the help

**Comment by mmanela** [comment]
Try this chutzpah.json:

```
{
    "Compile": {
        "Mode": "External",
        "Extensions": [ ".ts" ],
        "ExtensionsWithNoOutput": [ ".d.ts" ]
    },
    "References": [
        { "Path": "Scripts/angular.min.js", "IsTestFrameworkFile": true },
        { "Path": "Scripts/angular-mocks.js", "IsTestFrameworkFile": true },
        { "Path": "passwordvalidator.js" }
    ],
    "Tests": [
        { "Path": "Tests", "Includes": [ "*.ts" ] }
    ],
    "CodeCoverageExcludes": ["Scripts/*.js"]
}
```

**Comment by evgeny78** [comment]
Works fine! :)
Thank you.
