### ISSUE TITLE
xUnit style output support?

### ISSUE THREAD

**Issue by justinyoo** [mmanela/chutzpah#505]
Hi, Team.

Thanks for this great tools! I'm more than happy to use it. By the way, I wonder if Chutzpah supports xUnit style output or not. In the command line option, it supports NUnit2 by providing the `/nunit2` option, but I couldn't find the xUnit support option.

**Comment by mmanela** [comment]
Is there specific documentation on this format? It would be easy to add if you are interested.

**Comment by justinyoo** [comment]
@mmanela Yep, there's a document for the XML output format. https://xunit.github.io/docs/format-xml-v2.html It would be great if you can add it.

**Comment by mmanela** [comment]
I probably wouldn't be able to get to it for a bit but if you are interested PR's are welcome :)

**Comment by justinyoo** [comment]
@mmanela Oh, I'll try it. :-)

**Comment by mmanela** [comment]
Take a look at https://github.com/mmanela/chutzpah/blob/master/Chutzpah/Transformers/NUnitXmlTransformer.cs for an example.
