### ISSUE TITLE
Chutzpah returning exit code 0 even with failed builds

### ISSUE THREAD

**Issue by emi662002** [mmanela/chutzpah#507]
I'm running some Jasmine tests with Chutzpah on the test console (intended to be used in TFS build) vstest.console.exe "MySpecFile" /UseVsixExtensions:true

As you can see, the visual studio extension is being used. The tests run fine, and though I have some failing tests, the process always ends with error code 0, which is not good for my TFS build integration where I want the test step to fail when jasmine tests fail.

**Comment by mmanela** [comment]
I am not sure what Chutzpah would need to do to make vstest.console.exe return false. In that case Chutzpah is loaded as a dll and it just reports test failures. It has no control over what exit code vstest.console uses.

**Comment by emi662002** [comment]
Well I suppose that when the tests arent successfully run, a return exit code <> 0 should be enough (that's what the test console forwards).

Or just make the vsix component create a trx file with the test results, to be published in tfs, but thats not the case either.

**Comment by mmanela** [comment]
Chutzpah cannot return an exit code since it is not the exe running. It just reports failures and it is up to vstest.console.exe to decide what to return.

As for TRX, you can configure Chutzpah to generate that file. Please [read here](https://github.com/mmanela/chutzpah/wiki/Transforms-Setting)

**Comment by emi662002** [comment]
I've managed to use the chutzpah.json file but there seems to be an issue (or not):
When I run the test against a .html file (test harnass?):
vstest.console.exe "MySpecFile**.html**" /UseVsixExtensions:true
the transform is not executed.
When I run against a .js file:
vstest.console.exe "MyTest**.js**" /UseVsixExtensions:true
the transform is executed and I get my trx as expected.

**Comment by mmanela** [comment]
What does your chutzpah.json look like?

**Comment by emi662002** [comment]
{
    "Transforms": [
        { "Name": "trx", "Path": "trx.trx" }
    ]
}

btw, I've managed to use chutzpah.console.exe from the tfs build installing the package on the solution and using a custom tfs build task with a powershell that searches for the chutzpah console and the test harnass.

here the code for future reference:
param(
 )

if(-not ($Env:BUILD_SOURCESDIRECTORY))
{
    Write-Error "You must set the following variables"
    Write-Host 'BUILD_SOURCESDIRECTORY - TFS environment variable'
    exit 1
}
$Env:BUILD_SOURCESDIRECTORY
$chutzpah = Get-ChildItem -Path $Env:BUILD_SOURCESDIRECTORY -Filter chutzpah.console.exe -Recurse
if(-not $chutzpah)
{
	Write-Error "Chutzpah.console.exe not found, is the Chutzpah nuget package installed in the solution?"
	exit 1
}
foreach ($item in Get-ChildItem -Path $Env:BUILD_SOURCESDIRECTORY -Filter SpecRunner.html -Recurse)
    {
		& $chutzpah[0].FullName $item.FullName

		if($LASTEXITCODE -ne 0)
		{
			exit $LASTEXITCODE
		}
    }

**Comment by mmanela** [comment]
I am glad you got it to work! Is it generating the trx for you with that?

**Comment by emi662002** [comment]
I didn't configure the trx for this setup with powershell + chutzpah.console. because for the time being it's just enought to know red/green tests and not the stats of the run.

**Comment by mmanela** [comment]
Cool, glad you got it working
