### ISSUE TITLE
Can't run chutzpah.

### ISSUE THREAD

**Issue by CarbonMan** [mmanela/chutzpah#512]
Under tools -> Options Chutzpah is there.
I have installed the command line tool via nuget
So what do I do now?

If I open the Developer Command Prompt for VS2015 and run 
.\chutzpah.console.exe 
I get "not recognized ..."

Within VS2015 I don't see an option for the "Unit test explorer", that is shown in the docs here;
https://visualstudiogallery.msdn.microsoft.com/f8741f04-bae4-4900-81c7-7c9bfb9ed1fe

What am I doing wrong?

**Comment by mmanela** [comment]
The Visual Studio extension does not install the chutzpah.console.exe, it just add VS integration in unit test explorer (or if you install the other context menu extension in the context menu). 

You can launch the test explorer this way:
![image](https://cloud.githubusercontent.com/assets/304410/14763123/5d94276e-0941-11e6-850c-8726bcd68783.png)


Or if you install the [context menu extension](https://visualstudiogallery.msdn.microsoft.com/71a4e9bd-f660-448f-bd92-f5a65d39b7f0) you will see this:
![image](https://cloud.githubusercontent.com/assets/304410/14763126/81590be2-0941-11e6-9bfe-5134443eb939.png)

**Comment by mmanela** [comment]
Closing issue since I have not head back
