### ISSUE TITLE
Test duplication in Test Explorer with Typescript combined source file and combined tests file

### ISSUE THREAD

**Issue by jr01** [mmanela/chutzpah#513]
Hi,

I'm trying to use Chutzpah test adapter in a project where I have the following set-up:
- All typescript files are combined into a single javascript output file (code.js).
- All typescript test files are combined into another javascript output file (tests.js).

I notice that the test explorer displays each typescript unit-test multiplied by the number of typescript test files.
![image](https://cloud.githubusercontent.com/assets/2624681/14821569/86218a28-0bcb-11e6-9def-ad58aab5efae.png)

If I don't combine the tests into a single output file, like in the samples (https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation) then I don't have the problem, but that option I cannot use.

I have created a github repo for reproducing the problem: https://github.com/jr01/chutzpahtypescript

**Comment by mmanela** [comment]
Please take a look at [this sample](https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation/TypeScriptToSingleFile). It showed combining *all* scripts  into a single file but is able to get around the duplicate test issue by providing this setting in the chutzpah.json file:

```
"EnableTestFileBatching": true,
```

**Comment by jr01** [comment]
Yes, that works and I already had that working, however I still prefer to have the tests separate from the source.

**Comment by mmanela** [comment]
You should be able to do that. You can extend that sample and just configure a seond compilation path. I have not tried this but it could look something like:


```
{  
  "EnableTestFileBatching": true,
  "Compile": {
    "Extensions": [".ts"],
    "ExtensionsWithNoOutput": [".d.ts"],
    "Executable": "compile.bat",
    "Paths" : [

      // Merge all files in the source folder to a single merged js file
      { "SourcePath": "src", "OutputPath": "_out/_mergedSources.js" },

      // Map all test files in the test folder 1-1 to their corresponding js files
      { "SourcePath": "test", "OutputPath": "_out/_mergedTests.js" }
    ]
   },
  "References": [
    {"Includes": ["*/src/*.ts"], "Excludes": ["*/src/*.d.ts"] }
  ],
  "Tests": [
    { "Includes": ["*/test/*.ts"], "Excludes": ["*/test/*.d.ts"] }
  ]
}
```

**Comment by jr01** [comment]
That's exactly the config I tried and leads to duplication. See the config in my repo: https://github.com/jr01/chutzpahtypescript/blob/master/Chutzpah.Test/chutzpah.json

**Comment by mmanela** [comment]
I dug into it and this is because of a bug in the Visual Studio Test Adapter framework. I filed a bug about this and they are tracking the work. They are planning to fix it in the next major release of Visual Studio

**Comment by mmanela** [comment]
This will be fixed in next major version of VS so not point in tracking as open here.
