### ISSUE TITLE
vsix installers don't recognise VS 14.0.25+ update 2

### ISSUE THREAD

**Issue by Deracination** [mmanela/chutzpah#514]
The installers offer 2012 and 2013 as installer options, but don't support latest 2015

**Comment by mmanela** [comment]
I am not able to reproduce this issue. I have the latest VS 2015 installed and when I launch the installer I see:
![image](https://cloud.githubusercontent.com/assets/304410/14888281/63922122-0d0e-11e6-831b-4410fdb5d39b.png)



Here is my VS version:
![image](https://cloud.githubusercontent.com/assets/304410/14888293/74126520-0d0e-11e6-9f5a-765ad8460a27.png)

**Comment by mmanela** [comment]
Can you try clearing your package cache maybe and see if that helps? Also, ensure you do not already have it installed in your VS

**Comment by Deracination** [comment]
No change unfortunately. I see the same screen in the VSIX installer but without the 2015 line.

I managed to install by using the nuget package instead of running the VSIX files. One trap for the inexperienced is that the nuget package installs the extensions as disabled, so it took a while and several unnecessary install/uninstalls of the nuget package before I finally discovered that the extensions needed to be enabled in the 'Tools/Extensions and updates' list

This is not a complaint, simply an observation - perhaps the docs could be updated so it's easier for newcomers?

I very much appreciate your making this software available

**Comment by mmanela** [comment]
I don't think the nuget install will work correctly. Is it for you?

**Comment by Deracination** [comment]
This is a local install for myself. It seems to be working ok. Chutzpah Context menu and Test Explorer both run tests

**Comment by mmanela** [comment]
I am surprised. This has not worked properly in the past

**Comment by Deracination** [comment]
This isn't a totally clean install. Maybe some remnants lying around allowed it to work?

I had previously installed to 2015, updated Chutzpah extensions, used for some months, upgraded 2015, experimented with typescript tests and couldn't get them working so uninstalled the Chutzpah extensions and tried to reinstall with latest VSIX downloads. Then discovered that the VSIX didn't give 2015 as an option. Hence the issue...

**Comment by mmanela** [comment]
Hmm, have you tried clearing your extension cache?

**Comment by Deracination** [comment]
What's the best way to do this? The option for clearing the cache in the Nuget settings seems to have gone away.

**Comment by Deracination** [comment]
I used the instructions for NCrunch for manual install which detailed clearing the cache as follows:
``
"Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" /setup /nosetupvstemplates
``
After uninstall of the nuget packages and clearing the cache then VS 2015 shows up as an install option in the VSIX files.

Thanks!

**Comment by mmanela** [comment]
Great!
