### ISSUE TITLE
Chutzpah + RequireJS + jasmine + Typescript couldn't run Test

### ISSUE THREAD

**Issue by em-rkumar** [mmanela/chutzpah#515]
I am working with unit test part of project , could not mock module in jasmine spec file as it is using requirejs. please  help me to resolve . also sharing test project

[TestCore.zip](https://github.com/mmanela/chutzpah/files/246856/TestCore.zip)

**Comment by em-rkumar** [comment]
Hi @mmanela  ,

Why have you been not giving any response this issue.. I have not yet got any solution please response

**Comment by mmanela** [comment]
I have not had time to investigate you issue yet. Have you looked at the Chutzpah typescript sample and compared? https://github.com/mmanela/chutzpah/tree/master/Samples/RequireJS/TypeScript

**Comment by mmanela** [comment]
@em-rkumar Have you looked at my sample, have you resolved your issue?

**Comment by mmanela** [comment]
Closing as I have not heard back in a long time. Please re-open if needed.
