### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by em-rkumar** [mmanela/chutzpah#516]
When debug then giving error window.chutzpah is undefined
my env

visual studio 2015
windows 10

**Comment by mmanela** [comment]
Can you provide more details? The call stack? A repro?

**Comment by em-rkumar** [comment]
Yes ,I am getting window.chutzpah undefined error 

in chutzpah...........html file generated while debug test. file script generated below-

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Jasmine Spec Runner</title>
    <script type="text/javascript" src="file:///C:/USERS/KUMARRAJ/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/14.0/EXTENSIONS/0BBYIVGB.PAE/TestFiles/chutzpah_boot.js"></script>
<link rel="stylesheet" type="text/css" href="file:///C:/USERS/KUMARRAJ/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/14.0/EXTENSIONS/0BBYIVGB.PAE/TestFiles/jasmine/v2/jasmine.css"/>
<script type="text/javascript" src="file:///C:/USERS/KUMARRAJ/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/14.0/EXTENSIONS/0BBYIVGB.PAE/TestFiles/jasmine/v2/jasmine.js"></script>
<script type="text/javascript" src="file:///C:/USERS/KUMARRAJ/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/14.0/EXTENSIONS/0BBYIVGB.PAE/TestFiles/jasmine/v2/jasmine-html.js"></script>
<script type="text/javascript" src="file:///C:/USERS/KUMARRAJ/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/14.0/EXTENSIONS/0BBYIVGB.PAE/TestFiles/jasmine/v2/boot.js"></script>
<link rel="shortcut icon" type="image/png" href="file:///C:/USERS/KUMARRAJ/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/14.0/EXTENSIONS/0BBYIVGB.PAE/TestFiles/jasmine/v2/jasmine_favicon.png"/>

    
    
    <script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/ExtLib/lib/requirejs/require.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/ExtLib/lib/angular/angular.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/ExtLib/lib/angular-mocks/angular-mocks.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core.ut/config.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Core.App.js"></script>

<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/BaseController.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/BaseService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/Interface/IBaseMedHttpService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/Interface/IController.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/Interface/IIdentifier.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/Interface/IInject.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/Interface/IScope.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Base/Interface/IService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Controllers/FormController.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Interface/IBaseMedHttpService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Interface/IMedHttpService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Interface/IUrlBuildService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/Model/APIActionResult.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/services/BaseMedHttpService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/services/MedHttpService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Common/services/UrlBuilderService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Base/IBaseScopeControl.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Button/i1Button.directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Checkbox/i1checkbox-Directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Checkbox/IScopeCheckBox.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/DatePicker/i1datepicker.constants.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/DatePicker/i1datepicker.controller.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/DatePicker/i1datepicker.directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Form/i1form.directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Label/i1label.directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/NumberBox/i1Number.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/NumberBox/i1numberbox-Directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/NumberBox/IScopeNumberBox.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/RadioButton/i1radiobutton-Directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/RadioButton/IScopeRadioButton.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Textbox/i1textbox-Directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Textbox/IScopeTextBox.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/TimePicker/i1timepicker.constants.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/TimePicker/i1timepicker.controller.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/TimePicker/i1timepicker.directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Controls/Toolbar/i1toolbar.directive.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/dashboard/DashboardController.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/dashboard/DashboardService.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Test/ConsumerForm/consumer.controller.js"></script>
<script type="text/javascript" src="file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core/Test/LandingPage/landing.controller.js"></script>

    
    <script type="text/javascript">

        (function () {

            var amdTestPaths = ["checkboxspec",];
            window.chutzpah.boot(amdTestPaths);  //here  i am getting error

            if (window.chutzpah.usingModuleLoader) {
                if("file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core.ut/controls/checkbox") {
                    window.chutzpah.amdConfig({
                        baseUrl: "file:///c:/tfsimedone/imedone.trunk/current%20release/webbasis/apps/medcore/core.ut/controls/checkbox"
                    });
                }

                window.chutzpah.amdConfig({
                    map: {
                        '*': {
                            
                            }
                    }
                });

                window.chutzpah.amdStart = function() {
                    window.chutzpah.amdImport(amdTestPaths, function () {

                        console.log("!!_!! Stating Jasmine from AMD callback...");
                        window.initializeJasmine();
                    });
                };

                if(window.chutzpah.amdAutoStart) {
                    window.chutzpah.amdStart();
                }

            }
            else {
                var currentWindowOnload = window.onload;

                window.onload = function() {
                    if (currentWindowOnload) {
                        currentWindowOnload();
                    }
                    window.initializeJasmine();
                };
            }

        })();
    </script>
</head>
<body>
    
</body>
</html>

**Comment by mmanela** [comment]
Can you give me a full repro that I can run locally to see the error?

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
