### ISSUE TITLE
Having the chutzpah test adapter active keeps open handles to target files

### ISSUE THREAD

**Issue by brphelps** [mmanela/chutzpah#517]
I'm still trying to debug exactly what's going on here, but I noticed the issue dissipate when I disabled the Chutzpah VS Test Adapter extension (along with VS2015 Update 2). 

My team uses a standard gulp workflow to build files into an output directory (i.e. dist), and chutzpah.json to set references and test locations. However, our clean step frequently fails if a developer is using visual studio + chutzpah test adapter plugin, and running handle on our dist/ folder shows pretty much every referenced file as being open by visual studio. After disabling the Chutzpah plugin, this behavior dissipates.

Is there any way to prevent this aggressive locking behavior? 

Also, any recommendations you have for the traditional gulp/grunt flows would be helpful-- Running tests out of our output folder and cleaning the output folder every time we build is the standard practice.

**Comment by mmanela** [comment]
Chutzpah is just having a file watcher on those files and isn't usually locking them. That surprises me if it is. Is it all files?

**Comment by brphelps** [comment]
Actually, I think the reason I was seeing this originally was that Chutzpah itself may have been bootstrapping the Test Explorer window-- It seems like the first time this window loads itself in VS that it's opening file handles on a bunch of my files. This issue may be specific to VS Update 2, but I'm guessing it's not a chutzpah issue at this point. I'm continuing to dig, feel free to close :).

**Comment by mmanela** [comment]
Let me know if you learn more

**Comment by brphelps** [comment]
Added a repo with a repro here, I think I am able to see a causation between the chutzpah test adapter specifically and this phenomenon.

https://github.com/brphelps/chutzpah_repro

**Comment by brphelps** [comment]
@mmanela Any info? I don't mind contrib'ing but I'm not sure where to start.

**Comment by mmanela** [comment]
@brphelps Sorry, I have been swamped and have not had time to get to this to try to repro and investigate.

**Comment by mmanela** [comment]
I looked into this a big and I don't have a 100% smoking gun I do have a good idea of multiple things going on that cause this issue. 

1. You have configured Chutzpah to run tests from the "generated" directory. Instead, you should configure chutzpah to run off of the "source" directory. This way you won't ever have Chutzpah trying to read files while you are blowing them away. 

2. If you do need Chutzpah running off of a generated dir (like when using babel or typescript) you can configure this using Chutzpah's compile options. 

3. DNX file system is making matters worse. Even if you had Chutzpah running on a source dir but put the generated dir in your project it seems to cause issues with the file watcher. I have no root caused exactly why but it seems wrong either way that your generated folder is returned to VS as "project files".


That all said I was able to make a couple changes to make it work well. Assuming you needed to map source files to generated files (like when using babel), I set up compile options and I moved the generated dir above the project json so VS doesn't want to assume they are project files:

```
{
  "EnableCodeCoverage": "false",
  "Framework": "jasmine",
    "Compile": {
    "Mode": "External",
    "Extensions": [".js"],
    "IgnoreMissingFiles": true,
    "Paths" : [

      { "SourcePath": "wwwroot/js", "OutputPath": "../bin/dist-output" }
    ]
   },


  "Tests": [
    {
      "Path": "wwwroot/js",
      "Includes": [ "*.spec.js" ]
    }
  ]
}
```


In addition, there is a property you can add to your chutzpah.json that will dramatically speed up the test exection. 

```

    "EnableTestFileBatching": true,
```

The one catch is VS 2015 has a bug in it that make it not work well with this when using the Test Adapter plugin :(. They are planning to fix it for the next major release though. I am still looking for a way to work around their bug.

**Comment by brphelps** [comment]
Thanks for digging into this, @mmanela! 

Something that's not captured in this repro is that we're using an extensive set of gulp tasks to build JS output in a format that looks very different than its original source. It's these tasks that we want use to build, not rely on the functionality that's built into chutzpah (from my POV this is very similar to how a test runner like Karma would work-- i.e. there is no association between a test runner and your JS build chain, just that it runs on the output).

Just to be clear on what you listed in #3: In our normal projects I've been adding "DnxFolderIgnore" and an exclude in our project.json to attempt to hide our output folder from the DNX folder system. Is it DNX that's causing the problem in this case, or watchers opened by Chuztpah? From what I saw in my tests this issue didn't happen when the Chutzpah Test Adapter was disabled, so I thought we had accounted for all the DNX specific "stuff".

And, I think you mentioned in an earlier discussion that the watchers Chutzpah is opening should not be preventing deletion, is there anything that can be done to address that, even an additional configuration setting? At this point, this issue is severe enough that people are mitigating the issue by jumping through some very significant hoops (like having multiple repos for the same codebase so they can use VS in one place while it's locking files), and my primary interest is in reducing the crazy mitigations people are doing to accommodate this behavior. Even turning of automatic file watching in a chutzpah.json setting and deferring to the "refresh" button in VS would be preferable to some of the workflows people are using right now.

**Comment by mmanela** [comment]
So problem is two fold. 
1. You are having Chutzpah run tests (in your sample at least) on a directory that you want to blow away at any moment. This will cause problems since Chutzpah may be accessing a file at any give moment because of the file watcher (or even because of a existing test run). In my chutzpah.json above I showed one way to avoid this.

2. DNX file system integration in VS is telling my plugin that dist-output is part of the project files so my Chutzpah will watch them. When you go to blow that folder away Chutzpah start to react to it and some file locking is happening. I cannot pinpoint where (my guess it is something to do deep in file watcher and not chutzpah itself but I didn't get good evidence either way)

**Comment by brphelps** [comment]
I think I understand suggested fix, but this is a significant departure from how modern web build systems work-- I know it makes a lot of sense for the VS centric case, but I'm trying to figure out a clean way for chutzpah to live side-by-side with a gulp build flow.

What i'm really interested in is a path forward that doesn't involve a tighter coupling of chutzpah to our actual build process -- i don't see a good reason that we should be pointing at our source instead of our build output, so this feels like something I want to avoid. 

This is also typical of most other test runners-- they run on build output. Is there some way the chutzpah test adapter could function without file watchers? I think the C# test adapter is more of a "refresh tests after build" workflow, is that something that could be done? I don't mind getting a PR together, but I'm interested to know of this is a sensible way forward.

**Comment by mmanela** [comment]
Chutzpah supports exactly what you say it is just the test adapter plugin that seems to disagree with this pattern (combined with DNX telling it your output folder is project files).
