### ISSUE TITLE
Detecting Tests outside of configured test paths + angular not found

### ISSUE THREAD

**Issue by youngaj** [mmanela/chutzpah#518]
I have the following file structure with my spec files embedded with my application files.
|-Todo
|----ToDo.controller.js
|----ToDo.controller.spec.js
|----ToDo.service.js
|----ToDo.service.spec.js

I then combine/concat my application files using gulp into an app.js file.  I also have a few other vendor files that I include into a build folder.  Included in my vendor.js files are things like angular

Build
|--- vendor.js
|--- vendor.datatables.js
|--- app.js
|--- app.spec.js

**My problem is that the files in my source folders (ex. ToDo.service.spec.js) files are being picked up by the test runner then I'm getting errors about "angular" not being found.**

Here is my chulzpath.json

``` json
{
  "Framework": "jasmine",
  "References": [
    { "Path": "build/vendor.js" },
    { "Path": "build/vendor.datatables.js" },
    { "Path": "build/vendor.graph.js" },
    { "Path": "build/vendor.ui.js" },
    { "Path": "build/app.js" },
    { "Path": "build/angular-mocks/angular-mocks.js" },
    { "Path": "unit/SpecHelper.js" },
    {
      "Path": "../Scripts/jasmine-samples",
      "Include": "*.js"
    }
  ],
  "Tests": [
    { "Path": "unit" },
    {
      "Includes": [ "*.spec.js" ],
      "Path": "build"
    }
  ]
}

```

Here is my spec file

``` javascript
describe('Virtual Folders Module', function () {
    var ctrl;
    var scope;
    var rootScope;

    angular.module('SignalR', []);
    angular.module('common', []);
    beforeEach(module('app.modules.virtualFolders'));

    beforeEach(function () {
        inject(function ($rootScope) {
            scope = $rootScope.$new();
            rootScope = $rootScope;
        })
    });

    describe("virtualFolderService", function () {
        var virtualFolderService, httpBackend;

        beforeEach(inject(function (_virtualFolderService_, $httpBackend, $q) {
            // Service instance and dependencies
            virtualFolderService = _virtualFolderService_;
            httpBackend = $httpBackend;
            q = $q;
        }));

        describe("isFileUploadType", function () {
            it("with VirtualTree parameter", function () {
                var result = virtualFolderService.isFileUploadType('VirtualTree')
                expect(result).toBeFalsy();
            });

            it("with VirtualPhoto", function () {
                var result = virtualFolderService.isFileUploadType('VirtualPhoto')
                expect(result).toBe(true);
            });

            it("with VirtualSharedFile", function () {
                var result = virtualFolderService.isFileUploadType('VirtualPhoto')
                expect(result).toBe(true);
            });
        });

    });
});
```

Any help would be greatly appreciated.  Thanks!

**Comment by mmanela** [comment]
Do you not want your individual test files to be run?

**Comment by youngaj** [comment]
I am OK with the individual files running if I can resolve the "angular not found" error.  That error doesn't seem to appear in the concatenated app.spec.js file in the build folder.  Also I thought (but could be wrong) that the chutzpath.json "Tests" setting determined the files/paths to pull the test from?  Seems that those references are being ignored and all the describe functions regardless of location are pulled in.  Personally I would prefer to run the test in place but that would require resolving why I get the "angular not found error" although angular is included in my "References".

Thanks for responding so quickly!!

**Comment by mmanela** [comment]
@youngaj Do you still have this issuse?

**Comment by youngaj** [comment]
@mmanela. Yes.

**Comment by mmanela** [comment]
Can you provide a full repro I can run locally?

**Comment by mmanela** [comment]
Have not heard back, closing for now but will re-open when repro given

**Comment by youngaj** [comment]
@mmanela I have created a repo (below) with the code that I'm having a problem with.  The spec file I'm targeting is "app.spec.js" in the test folder.  Those are being rightfully pulled in but their source files under client/app are also being pulled in.  Not sure what I'm doing wrong.  Thanks again for this awesome tool and for your help.

https://github.com/youngaj/chutzpahRepo
