### ISSUE TITLE
Tests not found: Total Tests: 0 passed, 0 failed, 0 total 

### ISSUE THREAD

**Issue by pgarge** [mmanela/chutzpah#519]
I am using angular 2 and generating js files from ts files via VS 2015:

Here is the chutzpah.config file:

`{
  "Framework": "jasmine",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "Tests": [
    {
      "Path": "Tests/test.js"
    }
  ],
  "References": [   
    { "Path": "../node_modules/es6-shim/es6-shim.js" },
    { "Path": "../node_modules/zone.js/dist/zone.min.js" },
    { "Path": "../node_modules/reflect-metadata/Reflect.js" },
    { "Path": "../node_modules/systemjs/dist/system-polyfills.src.js" },
    { "Path": "../node_modules/systemjs/dist/system.src.js" },
    { "Path": "../node_modules/rxjs/bundles/Rx.js" },
    { "Path": "Tests/system-config.js" }
  ]
}`

In System-config I have:

`(function (global) {
    //map tells the System loader where to look for things
    var map = {
        'app': 'app', // 'dist',
        'rxjs': 'node_modules/rxjs'//,
        //'angular2-in-memory-web-api': 'https://npmcdn.com/angular2-in-memory-web-api' // get latest
    };

```
//packages tells the System loader how to load when no filename and/or no extension
var packages = {
    'app': { defaultExtension: 'js' },
    'rxjs': { defaultExtension: 'js' }//,
    //'angular2-in-memory-web-api': { defaultExtension: 'js' },
};

var packageNames = [
    '@angular/common',
    '@angular/compiler',
    '@angular/core',
    '@angular/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    //'@angular/router-deprecated',
    //'@angular/testing',
    //'@angular/upgrade',
];

packageNames.forEach(function (pkgName) {
    map[pkgName] = '../../node_modules/' + pkgName;
});

packageNames.forEach(function (pkgName) {
    packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
});

var config = {
    defaultJSExtensions: true,
    map: map,
    packages: packages
}

// filterSystemConfig - index.html's chance to modify config before we register it.
//if (global.filterSystemConfig) { global.filterSystemConfig(config); }

System.config(config);
```

})(this);`

When I run the simple test i.e.

`describe("Hello world", function () {
    it("says hello", function () {
        expect(helloWorld()).toEqual("Hello world!");
    });
});
function helloWorld() {
    return "Hello world!";
}`

I get this in VS and console app:
========== Total Tests: 0 passed, 0 failed, 0 total ==========

With /trace i get this
`chutzpah.console Information: 0 : Time:13:39:09.1259946; Thread:1; Message:Using Chutzpah.json files to find tests
chutzpah.console Information: 0 : Time:13:39:09.1349946; Thread:1; Message:Chutzpah run started in mode Execution with parallelism set to 8
chutzpah.console Information: 0 : Time:13:39:09.1439946; Thread:1; Message:Chutzpah.json file cache cleared
chutzpah.console Information: 0 : Time:13:39:09.1459946; Thread:1; Message:Chutzpah run finished with 0 passed, 0 failed and 0 errors`

With /debug I don't get any html file.

Any help with this will be appreciated.

**Comment by pgarge** [comment]
I was able to run a simple version but when it run this js file which was compiled via commonjs i get errors:
`"use strict";
var node_component_1 = require('./node.component');
describe('Node', function () {
    var menuItem = new node_component_1.Node('Node1');
    it('does not have children if it does not contain sub-nodes.', function () {
        expect(menuItem.hasChildren()).toBeFalsy();
    });
    it('has children if it contains sub-nodes.', function () {
        menuItem.children.push(new node_component_1.Node('ChildNode1'));
        expect(menuItem.hasChildren()).toBeTruthy();
    });
});`

I get Error: ReferenceError: Can't find variable: require

When I reference requirejs

`{
  "Framework": "jasmine",
  //"TestHarnessReferenceMode": "Normal",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TypeScriptModuleKind": "CommonJS",
 
  "References": [
    //{ "Path": "require.js" },
    //{ "Path": "../node_modules/es6-shim/es6-shim.js" },
    //{ "Path": "../node_modules/systemjs/dist/system-polyfills.src.js" },
    //{ "Path": "../node_modules/angular2/bundles/angular2-polyfills.js" },
    { "Path": "../node_modules/systemjs/dist/system.src.js" },
    //{ "Path": "../node_modules/rxjs/bundles/Rx.js" },
    //{ "Path": "../node_modules/angular2/bundles/angular2.dev.js" },
    { "Path": "scripts/system-config.js" },
    //{
    //  "Includes": [ "*/scripts/*.js", "../node_modules/angular2/*.js" ],
    //  "Excludes": [ "*/scripts/*.d.ts" ]
    //}
  ]
}`

I get Error: Error: Module name "node.component" has not been loaded yet for context: _. Use require([])

**Comment by mmanela** [comment]
I have not played with Angular2 and SystemJS much yet with Chutzpah but I have heard others report issue too. Can you provide a minimal sample that runs in a manual setup browser test harness but does not run in Chutzpah?

**Comment by pgarge** [comment]
I am using Angular 2 RC1 and SytemJS

Here is the browser harness (testrunner.html)

`<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />

    <title>Testing with jasmine</title>
    <link rel="stylesheet" href="node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
    
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
    
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/zone.js/dist/zone.min.js"></script>
    <script src="node_modules/zone.js/dist/async-test.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
</head>
<body>
<script>
    var map = {
        'app': 'app',
        'rxjs': 'node_modules/rxjs'
    };

    //packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' }
    };

    var packageNames = [
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/http',
        '@angular/platform-browser',
        '@angular/platform-browser-dynamic',
        '@angular/testing',
    ];

    packageNames.forEach(function(pkgName) {
        map[pkgName] = 'node_modules/' + pkgName;
    });

    packageNames.forEach(function(pkgName) {
        packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
    });

    var config = {
        defaultJSExtensions: true,
        map: map,
        packages: packages,
        paths: {
            'rxjs/observable/*': './node_modules/rxjs/add/observable/*.js',
            'rxjs/operator/*': './node_modules/rxjs/add/operator/*.js',
            'rxjs/*': './node_modules/rxjs/*.js'
        }
    }

    System.config(config);  
  
    System.import('app/tests/scripts/node.component.spec')
        .then(window.onload)
        .catch(console.error.bind(console));

</script>
</body>
</html>
`
**node.component.spec:**

`"use strict";
var node_component_1 = require('./node.component');
var testing_1 = require("@angular/core/testing");
testing_1.describe('Node', function () {
    var menuItem = new node_component_1.Node('Node1');
    testing_1.it('does not have children if it does not contain sub-nodes.', function () {
        testing_1.expect(menuItem.hasChildren()).toBeFalsy();
    });
    testing_1.it('has children if it contains sub-nodes.', function () {
        menuItem.children.push(new node_component_1.Node('ChildNode1'));
        testing_1.expect(menuItem.hasChildren()).toBeTruthy();
    });
});
//# sourceMappingURL=node.component.spec.js.map`


**node.component:**

`"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
var core_1 = require('@angular/core');
var NodeComponent = (function () {
    function NodeComponent() {
        this.nodes = new Array();
        this.nodes.push(new Node('Home'));
        var node = new Node('About Us');
        node.children.push(new Node('Careers'));
        this.nodes.push(node);
    }
    NodeComponent = __decorate([
        core_1.Component({ selector: 'node', templateUrl: 'views/node.component.html' }), 
        __metadata('design:paramtypes', [])
    ], NodeComponent);
    return NodeComponent;
}());
exports.NodeComponent = NodeComponent;
var Node = (function () {
    function Node(text) {
        this.children = new Array();
        this.text = text;
    }
    Node.prototype.hasChildren = function () {
        return this.children.length > 0;
    };
    return Node;
}());
exports.Node = Node;
//# sourceMappingURL=node.component.js.map`

**node.component.html**

`<nav>
    <ul>
        <li *ngFor="#node of nodes">
            <a href="#">
                {{node.text}}
            </a>
            <ul>
                <li *ngFor="#childNode of node.children">
                    <a href="#">{{childNode.text}}</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>`


This works fine in browser context but gives all sorts of errors with Chutzpah, any help in this will be appreciated. We are using Chutzpah in other products but if it won't work with Angular 2 then we will have to explore other options. Thanks !!

**Comment by pgarge** [comment]
html file didn't post right, trying again:

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />

    <title>Testing with jasmine</title>
    <link rel="stylesheet" href="node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
    
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
    <script src="node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
    
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/zone.js/dist/zone.min.js"></script>
    <script src="node_modules/zone.js/dist/async-test.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
</head>
<body>
<script>
    var map = {
        'app': 'app',
        'rxjs': 'node_modules/rxjs'
    };

    //packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app': { defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' }
    };

    var packageNames = [
        '@angular/common',
        '@angular/compiler',
        '@angular/core',
        '@angular/http',
        '@angular/platform-browser',
        '@angular/platform-browser-dynamic',
        '@angular/testing',
    ];

    packageNames.forEach(function(pkgName) {
        map[pkgName] = 'node_modules/' + pkgName;
    });

    packageNames.forEach(function(pkgName) {
        packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
    });

    var config = {
        defaultJSExtensions: true,
        map: map,
        packages: packages,
        paths: {
            'rxjs/observable/*': './node_modules/rxjs/add/observable/*.js',
            'rxjs/operator/*': './node_modules/rxjs/add/operator/*.js',
            'rxjs/*': './node_modules/rxjs/*.js'
        }
    }

    System.config(config);
    
    //System.import('app/tests/longprofile/longprofile.typescr.spec')
    //System.import('app/tests/longprofile/longprofile.svc.spec')
    System.import('app/tests/scripts/node.component.spec')
        .then(window.onload)
        .catch(console.error.bind(console));

</script>
</body>
</html>

**Comment by pgarge** [comment]
Adding the whole code folder as zip file(Angular files includes as well)

[testrunner.zip](https://github.com/mmanela/chutzpah/files/263861/testrunner.zip)

**Comment by brphelps** [comment]
On this topic, I think part of the issue is that file level (e.g. beforeeach ) issues are suppressed from XML output and the only place you can see them is stdout -- Could these be reported in a better way?

**Comment by mmanela** [comment]
I added better support for Angular2 in the 4.3.0 release. Please take a look at the [Angular2 sample](https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic) and see if it helps.

Will close for now but re-open if this doesn't solve the problem.
