### ISSUE TITLE
Test output file shows 0 tests when using openInBrowser

### ISSUE THREAD

**Issue by DanTup** [mmanela/chutzpah#520]
If I run:

```
PS C:\Thing> .\packages\Chutzpah.4.2.1\tools\chutzpah.console.exe "$testFile" /failOnError
/nunit2 "TestResults\$name.xml"
```

Then I get a test results file as expected. However, if I try running in a browser:

```
PS C:\Thing> .\packages\Chutzpah.4.2.1\tools\chutzpah.console.exe "$testFile" /failOnError
/nunit2 "TestResults\$name.xml" /openInBrowser chrome
```

Now I get an output file that says 0 tests were run:

```
<?xml version="1.0" encoding="us-ascii"?>
<test-results name="Chutzpah Test Results" total="0" errors="0" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2016-05-23" time="16:21:41" />
```

I can't find any info on whether this is intended to be supported. Is the a mechanism to report the tests back from the browser to the process? (If not, is it worth adding a warning if you use `openInBrowser` and an output flag?)

**Comment by mmanela** [comment]
When you open in browser the reporting will not work. I should throw or just not generate in this case (will look into this)

**Comment by DanTup** [comment]
Thanks for confirming. I had a quick dig through the code and came to this conclusion today (the browsers are just spawned with no further interaction).

We've got a mostly-working prototype tool that does this we can fall back to; just wanted to be sure we hadn't overlooked support for it here (since we already had some tests using Chutzpah).

Maybe something to consider as a feature for the future - we're probably not the only ones wanting to run automated tests across all browsers are part of the build :-)

**Comment by mmanela** [comment]
Would you expect it to generate the file based on running in the browser? Currently, chutzpah can only generate data from running against Phantom

**Comment by DanTup** [comment]
That's what we hoped for, yes :)

It's non-trivial to do (which is why we weren't all that surprised it's not there in chutzpah), but it's great functionality! It needs some test-framework-specific code but I guess that might already be the case for your Phantom integration?

We stole the idea from Dart (`pub test`) when we evaluated Dart but chose not to use it. The idea is basically to create an HTTP Listener, spawn each browser pointing back at it and serve a host page that runs the tests inside an iframe, collecting the results and sending them back to the server over a web socket.

**Comment by mmanela** [comment]
Yep, that is what Karma does. Definitely sounds good but I don't have the time to do that in the near term unless I get an PR from someone else.
