### ISSUE TITLE
chutzpah not loading the tests with import statements

### ISSUE THREAD

**Issue by avalinasab** [mmanela/chutzpah#521]
Hi,

Thanks for the tool, it's great however I'm experiencing issues with tests with import statements on top of the tests. My .ts tests are getting compiled using commonjs. I'm setting up my project based on angular2 webpack starter kit and I'm not able to run any of the existing tests in that project using chutzpah. It can't discover them.

Below is the repo:

https://github.com/AngularClass/angular2-webpack-starter.git

I'm using: 

- VS 2015 update 2. I use VS to build the project and compile the .ts files.
- Chutzpah 4.2.2
- No Resharper (I've seen other posts where Resharper was causing issues, so I'm trying to avoid it)

Here's the output window text:

------ Discover test started ------
Error: Timeout occurred when executing test file
While Running:c:\tfs\professional_services\tools\uitechstackseed\uitechstackseed\src\app\about\about.spec.ts

========== Discover test finished: 0 found (0:00:10.5995398) ==========
------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.0149985) ==========

Can you please let me know if you're able to run any of the tests under the repo provided?

https://github.com/AngularClass/angular2-webpack-starter.git

I've created a VS project (HTML with TypeScript template) so I can have a solution file and use VS.

I'm trying to keep my chutzpah.json file simple to narrow down the issue, here's what I currently have:

{
  "Compile": {"Mode": "External"},
  "Tests": [
    { "Include": "*spec*" },
    { "Path": "./*.js" }
  ]
}

I've added the chutzpah.json file under the "about" directory in the webpack project so I can just focus on one test (about.spec.ts) and get it to work.

Also here is my tsconfig

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true
  },
  "exclude": [
    "node_modules"
  ],
  "awesomeTypescriptLoaderOptions": {
    "resolveGlobs": true,
    "forkChecker": true
  },
  "compileOnSave": true,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}

Thanks
Ali

**Comment by mmanela** [comment]
Usually people use AMD not CommonJS when running in browser. What are you using that will run the CommonJS modules?

**Comment by avalinasab** [comment]
Thanks for your response. I get the same results with AMD. I'm not trying to run the tests using browser, I need to have the tests listed on the "Test Explorer" window in Visual Studio.

Thanks
Ali

**Comment by mmanela** [comment]
My general guidance when people hit issues is to first make it work manually by creating your own test harness (this removes Chutzpah from the equation) and see what Chutzpah is doing differently. Sometimes doing this makes you realize what you are forgetting to tell Chutzpah to do.

**Comment by avalinasab** [comment]
That's a good tip, I think I've already done that, I'm able to run the tests using the WebPack test task that uses PhantomJS and Karma to run the tests and I can see the tests are getting passed. 

Do you think you can take a look at the WebPack repository I provided above and let me know if you can get the tests loaded in the Test Explorer window?

Below is the output window from Task Runner Explorer when running the tests using the test task.

30 05 2016 16:49:01.846:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
30 05 2016 16:49:01.856:INFO [launcher]: Starting browser PhantomJS
30 05 2016 16:49:07.779:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#vSPpX7NhyaXzYwQ9AAAA with id 16260753
PhantomJS 2.1.1 (Windows 7 0.0.0) LOG: '`About` component loaded asynchronously'
  About
    √ should log ngOnInit
  App
    √ should have a url
  Home
    √ should have default data
    √ should have a title
    √ should log ngOnInit
  Title
    √ should have http
    √ should get data from the server
  x-large directive
    √ should sent font-size to x-large
Finished in 0.584 secs / 0.356 secs
SUMMARY:
√ 8 tests completed

===============================================================================Process terminated with code 0.

Thanks,
Ali

**Comment by avalinasab** [comment]
More info:

I tried running the tests using chutzpah.console with /trace flag, here is the error I get:

Error: ReferenceError: Can't find variable: require

"Require" is the code in the .js file, that's the commonjs compiled code for import statements.

**Comment by avalinasab** [comment]
More info:

I tried running one of the tests using chutzpah.console with /trace flag, here is the error I get:

Error: ReferenceError: Can't find variable: require

"Require" is the code in the .js file, that's the commonjs compiled code for import statements.

Here's my chutzpah.json file:

{
  "Compile": {
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "Executable": "compile.bat",
    "UseSourceMaps": true
  },
  "TestHarnessReferenceMode": "Normal",
  "Tests": [
    { "Include": "*spec*" },
    { "Path": "./*.js" }
  ]
}

The compile.bat file compiles the about.spec.ts file that I'm trying to run.

**Comment by mmanela** [comment]
Are you including the amd loader in chutzpah.json?

**Comment by avalinasab** [comment]
No here's all I have in the chutzpah.json file when using compile.bat. Can you please provide the chutzpah.json file that you think will work so I can test that?

{
"Compile": {
"Extensions": [ ".ts" ],
"ExtensionsWithNoOutput": [ ".d.ts" ],
"Executable": "compile.bat",
"UseSourceMaps": true
},
"TestHarnessReferenceMode": "Normal",
"Tests": [
{ "Include": "spec" },
{ "Path": "./*.js" }
]
}

**Comment by mmanela** [comment]
I do not know your setup but you need to list all the files that are needed to run your application in a references section. For example, when you run in Karma what does the HTML file look like, what dependencies is it using.

**Comment by avalinasab** [comment]
Can you please take a look at this repo? That's the setup I'm using:

https://github.com/AngularClass/angular2-webpack-starter

You can see the karma.conf.js under /config directory.

I'm using the exact same setup, I just added chutzpah.json under /src/app/about/ directory as below so I can run the tests in about.spec.ts. (Trying to narrow down to one test to troubleshoot easier)

{
  "Compile": {"Mode": "External"},
  "Tests": [
    { "Include": "*spec*" },
    { "Path": "./*.js" }
  ]
}

**Comment by mmanela** [comment]
You are not doing the same thing. In that karma config it is loading a bundle: ```files: [ { pattern: './config/spec-bundle.js', watched: false } ],``` but not in the chutzpah.json.

**Comment by avalinasab** [comment]
Thanks for your helps. I'm closing this issue since it's not an issue with Chutzpah.
