### ISSUE TITLE
Possibility to run external script before/after

### ISSUE THREAD

**Issue by johnBim** [mmanela/chutzpah#522]
Hello,
I would like to know if there is there the possibility to run an external script file before/after Chutzpah runs the test file script?
e.g run a bat file to execute some task automatically when in Visual studio Chutzpah starts and just before it starts to run effectively the test script.
- It is possible to capture the moment it start/end to run test files? 

Thanks for help

**Comment by mmanela** [comment]
There is not current feature like this but if you are interested I would be open to see it added.

**Comment by johnBim** [comment]
Hello, 
Yes please since chutzpah a great tool. That will extend it for good.
Do you have any estimation time?

**Comment by mmanela** [comment]
I will not be able to get to this any time soon. The best approach is if you would send a PR and I can aid with that.
