### ISSUE TITLE
just can't get it working

### ISSUE THREAD

**Issue by gregveres** [mmanela/chutzpah#524]
Hi

I believe I have read everything but I must be missing something fundamental. I will start by saying I have an ASP.Net MVC Solution with three projects: 

- CommonResources - just an resx file
- App - the MVC project
- App.Tests - a unit test project that contains a bunch of c# unit tests. 

To prepare my project for js unit testing, I have done the following things:

- pm Install-Package Chutzpah
- installed the Extensions: Chutzpah Test Adaptor for the Test Explorer & Chutzpah Test Runner Context Menu Extension

BTW, it is unclear to me that I needed to run pm Install-Package Chutzpah. There really aren't any installation instructions. 

I have also installed via NuGet: 

- jasmine
- jasmine.TypeScript.DefinitelyTyped

my intention is to write Typescript, not javascript, but since I am stuck, I am starting with just javascript.

At this point, I can verify that I have chutzpah.console.exe on the filesystem. I have the context menu when I right click on solution explorer items. So it would seem to me that I have everything installed properly. 

I know that I don't have a SpecRunner.html file. Do I need one? I was under the impression that Chutzpah will create one for me. 

I will say that chutzpah seems to run but it doesn't find any tests to run. So ...

I have added a javascript file to the App/Scripts/App directory called CourtGroups.js. It contains: 

```
var CourtGroups = (function () {
    function CourtGroups(firstName, lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    CourtGroups.prototype.FullName = function () {
        return this.firstName + " " + this.lastName;
    };
    return CourtGroups;
}());
//# sourceMappingURL=CourtGroups.js.map
```
I have the unit test file in the App.Tests/Scripts-Src directory. It contains: 

```
/// <reference path="../../app/scripts/app/courtgroups.js" />

describe("Court Groups tests", function () {
    var cg = new CourtGroups("fred", "flintstone");
    it("returns full name", function () {
        var fullName = cg.FullName();
        expect(fullName).toEqual("fred flintstone");
    });
});
//# sourceMappingURL=CourtGroupsTests.js.map

```

The source mapping is from the typescript compiler. These were originally TS files. 

When I right click on the CourtGroupTests.js file and select Run JS Tests, I get this for output:

> ========== Total Tests: 0 passed, 0 failed, 0 total ==========

Any suggestions of what I am doing wrong? 

Thanks
Greg

**Comment by gregveres** [comment]
I have enabled logging in the settings and this is all that is output:

> devenv.exe Information: 0 : Time:16:46:26.2401142; Thread:8; Message:Chutzpah.json file found at C:\Users\gregv\Source\Repos\App\App\App.Tests\chutzpah.json given starting directory C:\Users\gregv\Source\Repos\App\App\App.Tests\Scripts-Src

And here is what I have for the chutzpah.json file:

```
{
  "Framework": "jasmine",
  "References": [
    {
      "Exclude": "*.d.ts"
    },
    {
      "Path": "Scripts/jasmine",
      "Include": "*.js"
    },
    {
      "Path": "../Scripts/App",
      "Include": "*.js"
    }
  ],
  "Tests": [
    {
      "Path": "Scripts-Src",
      "Include": "*Tests.ts",
      "Exclude": "*.d.ts"
    }
  ],
  "EnableCodeCoverage": "false",

  "TypeScriptCodeGenTarget": "ES5",
  "Compile": {
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "Executable": "compile.bat",
    "UseSourceMaps": true
  }
}

```

**Comment by gregveres** [comment]
I just put a break point in the unit test code and tried to run Chutzpah in the debugger (context menu) and it did not stop at the break point.

**Comment by mmanela** [comment]
And you said nothing else is including in the trace file?
Can you create a repo with your sample and I can take a quick look

**Comment by gregveres** [comment]
Thanks. In creating the project, I realized that my one reference directory was wrong. I fixed that and I started to include the CourtGroups.js file. 

But in my real project, I have bootstrap, jQuery and knockout installed in the unit test project. The problem is that it is including it in the wrong order. I am trying to use the reference section to exclude those files. I thought this would do it but it isn't changing any behaviour in the way that Chutzpah is creating the spec.html file. 

```
{
  "Framework": "jasmine",
  "References": [
    {
      "Exclude": "*.d.ts"
    },
    {
 // this is the path that I thought would exclude all the bootstrap, jQuery and knockout files in App.Test/Scripts
     "Path": "Scripts",
      "Exclude":  "*.js"
    },
    {
      "Path": "Scripts/jasmine",
      "Include": "*.js"
    },
    {
// this is what I needed to change to reference the CourtGroups.js file.
      "Path": "../SquashSpider/Scripts/App",
      "Include": "*.js"
    }
  ],
  "Tests": [
    {
      "Path": "Scripts-Src",
      "Include": "*Tests.js",
      "Exclude": "*.d.ts"
    }
  ],
```

**Comment by gregveres** [comment]
Ok I have a new project working now. Here are the two mistakes that I made:
- I installed jasmine through NuGet, but it seems that I don't need to. I assume that Chutzpah installs a copy (I deduced this through looking at the spec.html that was automatically created)
- I specified the reference path incorrectly

Now I have the new project detecting and running and passing the test. 

BTW, when I install Chutzpah, do I need to install the NuGet package as well as the two extensions? I know what the two extensions do, but I don't really know why I would need the NuGet package. 

I would be happy to update the Readme..md file with installation instructions if you want.

**Comment by mmanela** [comment]
The nuget package is not for Visual Studio integration, it is intended if you want to integrate Chutzpah into your build process.

I am glad to hear you got it working and I would love suggestions/edits to make this easier for future people.

**Comment by gregveres** [comment]
Ok that makes sense for the NuGet package. 

I was noticing that there is only an "open in browser" option when right clicking on an individual file. Is that the only place where it should show up? I created an html file that works when I open it. But the integration still only shows the open in browser option on individual tests. 

And to create the html file so that it would work on my team mate's computers, I had to install jasmine in the project. That made chutzpah pickup the jasmine files. I thought that I was ignoring the files in the .json file but ...

 I created a GitHub for the example. it is here:

https://github.com/gregveres/ChutzpahSample

with the sample, it no longer recognizes the unit test. I think all because jasmine is installed in the unit test project.

**Comment by gregveres** [comment]
@mmanela You can ignore this. 
I started from scratch and now have a typescript file being tested with a typescript based unit test within VS2015. 

I still have to switch from QUnit to Jasmine but I don't think that will be an issue. 

I did have to give up on the idea of having Chutzpah include all my files_to_be_tested.ts. I am now specifying each ts file explicitly with a References.Path line. I am ok with this. I was hoping to not have to do that, but I read another person talking about classes and subclasses and the order of includes being wrong. At that point I figured that specifying each file was the best way to go. I seem to be able to specify the tests with a glob pattern. And I don't care which order they are executed in. 

I am also using Complie.Mode = external since I couldn't get the compile.bat to work. There was always a funky character being inserted before the first line of the bat file so the compile command wasn't working. I was also expecting the compile command to be something that was run on each file that Chutzpah found, rather than it being a command that is called once and leaves the compilation up to me as the bat file writer to include every single file that needs compiling. I am hoping the external mode works fine in the long run and on the CI server. I haven't tackled the CI server yet. But I have to get written my code and stop playing with the infrastructure. 

Thanks for your great tool. I really do appreciate it!

Greg

**Comment by mmanela** [comment]
Sure, is it ok if I close this item then?

And as for the compile.bat, the idea is that most people already have a compile process that handles all files and this mechanism lets you plug into that. But to be honest almost everyone does and should use external and let your existing build process compile your files and not have Chutzpah coordinate it
