### ISSUE TITLE
Dead links on the wiki

### ISSUE THREAD

**Issue by WrathZA** [mmanela/chutzpah#526]
On page: https://github.com/mmanela/chutzpah/wiki/Running-JavaScript-tests-with-chutzpah
On line: Chutzpah support QUnit, **Jasmine** and **Mocha** unit tests.

The Jasmine and Mocha links are dead.

For easy ref the working links are:

https://mochajs.org/

https://jasmine.github.io/

**Comment by mmanela** [comment]
Thanks, update.
