### ISSUE TITLE
Coverage and requrejs

### ISSUE THREAD

**Issue by casperno** [mmanela/chutzpah#528]
Hi,

I have problems getting code coverage tests to run from Visual Studio 2015.

Normal run of test is ok, but when running 'coverage', I get Erros of this type:
`Error: Error opening C:/Users/casper/Documents/Visual Studio 2015/Projects/Html5EditorProto/webapp/js/createjs.js: No such file or directory`

It seems to be caused by config.js either not running, or that it runs too late. 

I've tried to 'EnableTracing', which shows config.js being loaded, but right below, loading "createjs" fails ("createjs" has a path set in config.js)

```
devenv.exe Information: 0 : Time:13:13:19.0509301; Thread:104; Message:Phantom Log - Resource Recieved: file:///C:/Users/casper/Documents/Visual%20Studio%202015/Projects/Html5EditorProto/webapp/js/pfEditor/view/Image.js
devenv.exe Error: 0 : Time:13:13:19.0821803; Thread:104; Message:Eror recieved from Phantom Error opening C:/Users/casper/Documents/Visual Studio 2015/Projects/Html5EditorProto/webapp/js/createjs.js: No such file or directory
devenv.exe Information: 0 : Time:13:13:19.0821803; Thread:104; Message:Phantom Log - Resource Error for file:///C:/Users/casper/Documents/Visual%20Studio%202015/Projects/Html5EditorProto/webapp/js/createjs.js with error Error opening C:/Users/casper/Documents/Visual Studio 2015/Projects/Html5EditorProto/webapp/js/createjs.js: No such file or directory
```

Any pointers would be appreciated, I'd really like to have control over coverage. 

And thanks for all the hard work developing chutzpah!

**Comment by mmanela** [comment]
Can you show me your chutzpah.json? Or upload a git repo showing a minimal repro

**Comment by casperno** [comment]
Thanks for responding. Here's mye chutzpah.json:

```
{
  "Framework": "qunit",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "AMDBaseUrl": "js",
  "AMDAppDirectory": "./",
  "Compile": {
    "Mode": "External",
    "Paths": [
      {
        "OutputPath": "./js",
        "SourcePath": "./"
      }
    ],
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    {
      "Path": "Scripts/typings",
      "Include": "*d.ts",
      "IncludeInTestHarness": false
    },
    { "Path": "config.js" },
    { "Path": "Scripts/require.js" }
  ],
  "Tests": [
    {
      "Path": "tests",
      "Includes": [ "*/*tests.ts" ],
      "Excludes": [ "*/*.d.ts" ]
    }
  ]
}
```

**Comment by mmanela** [comment]
You config doesn't look right to me. Can you give a full repo that I can play with?

**Comment by casperno** [comment]
Some of the code in the project cannot be made public, but I'll try to build a version that's ok to show which still fails in the same way.

What looks wrong with the config? Anything I can fiddle with right away?

**Comment by mmanela** [comment]
This part of the Compile section seems odd to me

```
"Paths": [
      {
        "OutputPath": "./js",
        "SourcePath": "./"
      }
    ],
```

Not sure what you are trying to do there

**Comment by casperno** [comment]
There's a lot in that chutzpah.json that has just been left after I first got test running to work  :-)
I fiddled around some more with it now and found a solution.
The sourcePath & output path made little difference. Adding  "IsTestFrameworkFile": true to the Path: "config.js" made the difference. Unit tests worked with and without it, coverage works with it.

Found a possible bug in a samle while debugging my chutzpah.json: https://github.com/mmanela/chutzpah/blob/master/Samples/RequireJS/QUnit/chutzpah.json
```
   "References" : [
        {"Path" : "require-2.1.8.js" }, 
        {"Path" : "config.js" }
    ]
```
My test indicate that 'config' must be placed before 'require'

Here's the working chutzpah.json:
```
{
  "Framework": "qunit",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "AMDBaseUrl": "js",
  "AMDAppDirectory": "./",
  "Compile": {
    "Mode": "External",
    "OutDirectory": "js",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    {
      "Path": "config.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/require.js"
    
    },
    {
      "Path": "Scripts/typings"
    }
  ],
  "Tests": [
    {
      "Path": "tests",
      "Includes": [ "*/*tests.ts" ],
      "Excludes": [ "*/*.d.ts" ]
    }
  ],

  "CodeCoverageExcludes": [ "*Scripts*" ]
}
```
My test indicate that 'config' must be placed before 'require'

Here's the working chutzpah.json:

{
  "Framework": "qunit",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "AMDBaseUrl": "js",
  "AMDAppDirectory": "./",
  "Compile": {
    "Mode": "External",
    "OutDirectory": "js",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    {
      "Path": "config.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/require.js"
    
    },
    {
      "Path": "Scripts/typings"
    }
  ],
  "Tests": [
    {
      "Path": "tests",
      "Includes": [ "*/*tests.ts" ],
      "Excludes": [ "*/*.d.ts" ]
    }
  ],

  "CodeCoverageExcludes": [ "*Scripts*" ]
}

```

**Comment by mmanela** [comment]
Awesome I am glad you got it to work. I will look to update the samples to be better. It is odd since I do run coverage on that one but I wonder if something else is different.

**Comment by mmanela** [comment]
Can we close this now?

**Comment by casperno** [comment]
Indeed we can
