### ISSUE TITLE
Skipped tests are marked as passed in TRX output

### ISSUE THREAD

**Issue by Blackbaud-ChristineViets** [mmanela/chutzpah#529]
I have an `xit` Jasmine 2 test that should be skipped. The test is skipped and shows in the skipped count when running my tests. When I apply the TRX transform, the skipped test is reported in my .trx file and, when opening the file with Visual Studio, the test is marked as passed.

If I use mstest to run .NET tests and generate a TRX file, any ignored tests are not reported in the TRX file, but are listed as warnings in the console output:

```
Starting execution...
Warning: The disabled test 'IgnoredTest' was removed from the test run.
```

**Comment by mmanela** [comment]
Thanks for reporting this. I will take a look.

**Comment by mmanela** [comment]
Fixed will be in next release. I now mark them as Not Executed.
