### ISSUE TITLE
Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by IEvangelist** [mmanela/chutzpah#530]
IDE: **Microsoft Visual Studio Enterprise 2015, Version 14.0.25420.01 Update 3**

There seems to be an issue with `Chutzpah`. When I have the `Chutzpah Test Adapter for Test Explorer` enabled, **Visual Studio** becomes unresponsive and only "Tests" output, in the `Output Window` are available as it is so busy trying to "discover" tests. It might be related to this [open issue](https://github.com/aspnet/Tooling/issues/604#issuecomment-229097213). It immediately re-attempts to discover them again after it fails with the following message:

> '1.0.0-*' is not a valid version string.
> Parameter name: value

The process simply gets bogged down and after enough time, the **IDE** is so sluggish that you need to kill in from _Task Manager_. It took me a while, but I have isolated the issue to this current install of the **IDE** and `Chutzpah Test Adapter for Test Explorer, version 4.2.3`. When I disable that extension the symptom goes away. There is no longer an infinite loop and the **IDE** is responsive but there is still the error mentioned above.

**Comment by mmanela** [comment]
Do you see because of that other error that VS runs discovery again and re-kicks off chutzpah?

**Comment by IEvangelist** [comment]
I honestly have no idea, I was hoping you might have some additional insights. I just know that when I disable the extension that **Visual Studio 2015** only displays the error message once and doesn't get stuck in an infinite loop.

**Comment by mmanela** [comment]
I will investigate

**Comment by IEvangelist** [comment]
Did you find anything at all yet that might be related to this?

**Comment by mmanela** [comment]
I have not yet had a chance to look into it.

**Comment by GeorgDangl** [comment]
FYI, the same looping behavior also happens with the Karma Test Runner AddIn.

**Comment by IEvangelist** [comment]
I guess we could close this, but it is nice to leave it open to track the issue somehow? @mmanela & @GeorgDangl what do you think? Is there a way to move this issue to the tooling team somehow, I'm not that familiar with the capabilities?

**Comment by bootrider** [comment]
I am suffering the same symphtom

**Comment by mmanela** [comment]
There is nothing I can tell Chutzpah is doing here. And since it happens with other adapters tells me it is a framework issue. I will try to follow up with team who owns this feature.

**Comment by GeorgDangl** [comment]
I did actually only experience this issue with the sample project that @bravemav provided in another issue ([his repo is here](https://github.com/bravemav/Chutzpah-Angular2-SystemJS)), but didn't have this issue in my own project which I built from scratch. I looked but didn't see any obvious differences there except that the sample is for an older Angular 2 release.

**Comment by IEvangelist** [comment]
@bootrider, @GeorgDangl  and @mmanela this is definitely a framework issue, or perhaps more appropriately a tooling issue? There is nothing that `Chutzpah` is doing wrong. Thank you @mmanela for following up with the team who owns this feature.

**Comment by mayabans** [comment]
@IEvangelist , would it possible for you to share a possible repro or logs for vstest.discoveryengine.exe, & vstest.executionengine.exe regarding this issue
Please follow [here ](https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/)on how to enable these logs.

**Comment by chokaa** [comment]
My friends, i encountered same problem, i am currently testing some typescript code with jasmine and i added a simple .json file in your project, somewhere in app or your test folder, name it chutzpah.json and add this code (this works for me because i'm testing typescript, you can try and add something like this in your .json project file)

{
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    {
      "Includes": [ "*../Engine/*.ts" ],
      "Excludes": [ "*../Engine/*.d.ts" ]
    }
  ],
  "Tests": [
    {
      "Includes": [ "*/Unit/*.ts" ],
      "Excludes": [ "*/Unit/*.d.ts" ]
    }
  ]
}
just hit folder which contains your files you want to test (References) and your tests and that is it. Maybe @mmanela this is because your .json file is not doing the job, good luck in fixing this ! :)

**Comment by IEvangelist** [comment]
I'm sorry that I have been slacking on this thread. I was actually asked to remove **chutzpah** all together and instead utilize **[karma](https://github.com/karma-runner/karma)**, that is what we have done.
