### ISSUE TITLE
Blank Test Explorer pane after installing

### ISSUE THREAD

**Issue by yaakov-h** [mmanela/chutzpah#532]
**IDE:** Microsoft Visual Studio 2015 Enterprise, 14.0.25421.03 Update 3
**Extension:** Chutzpah Test Adapter for the Test Explorer, 4.2.3

After installing the test adapter and restarting Visual Studio, the Test Explorer pane was completely blank.

After disabling the Chutzpah adapter and restarting Visual Studio, the Test Explorer showed up again as expected.

Strangely, after re-enabling the Chutzpah adapter and restarting Visual Studio, the Test Explorer continued to show up again as expected, and my Jasmine tests are showing in the Test Explorer.

**Comment by mmanela** [comment]
Thanks for reporting. I will take a look

**Comment by mmanela** [comment]
Can not repro, @yaakov-h do you still hit this?

**Comment by yaakov-h** [comment]
I haven't seen this since I opened the issue. Could have been a once-off bug inside VS itself.

**Comment by mmanela** [comment]
Thanks, will close for now but please re-open if you hit again
