### ISSUE TITLE
References Glob Pattern in JSON Settings

### ISSUE THREAD

**Issue by GreenC90** [mmanela/chutzpah#533]
Hi Matthew (and anyone else willing to help!),

I'm having some trouble working with references in the chutzpah.json file. I have tests that work when I use the "/// <reference..." syntax, but would ideally like to use a glob pattern in the settings file.

My current understanding suggests that this should work...
```json
{
  "References": [
    {
      "Path": "../scripts/jasmine",
      "Includes": [ "*.js" ]
    },

    {
      "Path": "../../applicationdistributiontool2016.web/scripts",
      "Includes": [ "*.js" ]
    },

    {
      "Path": "../../applicationdistributiontool2016.web/scripts/pluggins",
      "Includes": [ "*.js" ]
    },

    {
      "Path": "../../applicationdistributiontool2016.web/app",
      "Includes": [ "*.js" ]
    },

    {
      "Path": "../../applicationdistributiontool2016.web/app/common",
      "Includes": [ "*.js" ]
    }
  ]
}
```

...where the top three references are to framework JavaScript and the bottom two are app specific.

However, Jasmine seems to load without issue, but the .js files in the following two paths do not. I've run the command line executable with the above settings file and hit several errors such as, "Error: ReferenceError: Can't find variable: angular"; I'm using Angular and it's source is in the .web/scripts folder.

My initial thought was just that I wasn't navigating to the folder properly. But if I put a specific reference to the angular.js file using the same path with no glob pattern, then the error for Angular disappears (I still have other errors that I think come from missing references)...

```json
{
  "References": [
    {
      "Path": "../scripts/jasmine",
      "Includes": [ "*.js" ]
    },

    {
      "Path": "../../applicationdistributiontool2016.web/scripts/angular.js"
    }

```

I feel like it's one of two issues, either I'm not navigating to the folder properly and Chutzpah is clever enough to find angular.js when given a filename, or I'm not using the glob pattern correctly.

Thanks for any help, I'm going to stick to the original "/// <referenece..." approach until I/we can solve this.
Chris.

**Comment by mmanela** [comment]
The key is the order matters. When you glob a folder you need to be ok with the files being added in whatever order the OS chooses. If you have dependencies that must be loaded first you should directly reference them and glob the rest.

**Comment by GreenC90** [comment]
OK, thanks Matthew. Apologies if that was referenced in the docs somewhere, I thought it would be simple in the end.

I won't get to look at the settings file until next week at least, but we'll assume this answer will sort my issue.
