### ISSUE TITLE
Systemjs.config.js Issue for Angular2

### ISSUE THREAD

**Issue by angDakila** [mmanela/chutzpah#534]
Hi Matthew, I am currently having an issue with Chutzpah, here are details of the tools that I am using:
1. Visual Studio 2015 with Update 3 (I am running Angular2 using ASPCore)
2. Chutzpah 4.2.3
3. systemjs.config.js

```
    {
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TestHarnessDirectory": "wwwroot",
  "EnableTestFileBatching": true,
  "BrowserArguments": {
    "chrome": "--allow-file-access-from-files"
  },
  "Tests": [
    {
      "Path": "app.test/",
      "Includes": [ "*.ts" ]
    }
  ],
  "References": [
    { "Path": "node_modules/es6-shim/es6-shim.js" },
    { "Path": "node_modules/@angular/core/bundles/core.umd.js" },
    { "Path": "node_modules/systemjs/dist/system.js" },
    { "Path": "node_modules/systemjs/dist/system-polyfills.js" },
    { "Path": "node_modules/rxjs/bundles/Rx.js" },
    { "Path": "node_modules/typescript/lib/typescript.js" },
    { "Path": "node_modules/zone.js/dist/zone.js" },
    { "Path": "node_modules/reflect-metadata/Reflect.js" },
    { "Path": "systemjs.config.js" }
  ],
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  }
}
```

For some reasone everytime that I run chutzpah I am getting the error below. I have tried everything based from the the forums in your site. I will really appreciate your help on this one. Thanks in advance

Error: ReferenceError: Can't find variable: System
in file:///C:/Git/Web/wwwroot/systemjs.config.js (line 78)
While Running:C:\Git\Web\wwwroot\app.test\userAccount\login.component.test.ts
------ Test started: File: C:\Git\Web\wwwroot\app.test\userAccount\login.component.test.ts ------
0 passed, 0 failed, 0 total (chutzpah).

**Comment by bootrider** [comment]
try to move the order in your references, the system.js should be the first:

```
"References": [
    { "Path": "node_modules/systemjs/dist/system.js" },
    { "Path": "node_modules/es6-shim/es6-shim.js" },
    { "Path": "node_modules/@angular/core/bundles/core.umd.js" },    
    { "Path": "node_modules/systemjs/dist/system-polyfills.js" },
    { "Path": "node_modules/rxjs/bundles/Rx.js" },
    { "Path": "node_modules/typescript/lib/typescript.js" },
    { "Path": "node_modules/zone.js/dist/zone.js" },
    { "Path": "node_modules/reflect-metadata/Reflect.js" },
    { "Path": "systemjs.config.js" }
  ],
```
It works for me

**Comment by angDakila** [comment]
Thanks for the tip! I will try your suggestion.

**Comment by angDakila** [comment]
@bootrider I got it working, though making the whole order thing did not solved my problem, currently the 2 important issues that I did not able to solve is running the unit tests in chrome, wherein the 
"BrowserArguments": {
  "chrome": "--allow-file-access-from-files"
}

did not work, and getting the code coverage to work, I hope @mmanela have suggestions on this one.

**Comment by mmanela** [comment]
@angDakila This is the chutzpah.json from @bootrider that works for him. Does this help you?


```
{
  "Framework": "jasmine",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TestHarnessReferenceMode": "AMD",
  "Compile": {
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "Executable": "compile.bat",
    "UseSourceMaps": false
  },

  "References": [

    { "Path": "node_modules/es6-shim/es6-shim.min.js" },
    { "Path": "node_modules/zone.js/dist/zone.min.js" },
    { "Path": "node_modules/reflect-metadata/Reflect.js" },
    {
      "Path": "node_modules/systemjs/dist/system.js",
      "IsTestFrameworkFile": true
    },

    {
      "Path": "wwwroot/system-config.js"
    },
    { "Path": "code.ts" }
  ],

  "CodeCoverageExcludes": [ "*node_modules\\*.ts", "*tests\\*.spec.ts" ],
  "CodeCoverageIncludes": [ "*code.ts" ],

  "Tests": [
    {
      "Path": "tests",
      "Includes": [ "*.spec.ts" ]
    }
  ]

} 
```

**Comment by angDakila** [comment]
Hi @mmanela below is the exact chutzpah.json that is working for me when I am running a headless test:

{
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "UseSourceMaps": false
  },
  "Framework": "jasmine",
  "BrowserArguments": {
    "chrome": "--allow-file-access-from-files"
  },
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TypeScriptModuleKind": "AMD",
  "References": [
    { "Path": "../node_modules/es6-shim/es6-shim.js" },
    { "Path": "../node_modules/reflect-metadata/Reflect.js" },
    { "Path": "../node_modules/systemjs/dist/system.src.js" },
    { "Path": "../node_modules/zone.js/dist/zone.js" },
    { "Path": "../node_modules/zone.js/dist/jasmine-patch.js" },
    { "Path": "../node_modules/zone.js/dist/async-test.js" },
    { "Path": "../node_modules/zone.js/dist/fake-async-test.js" },
    { "Path": "../node_modules/core-js/client/shim.min.js" },
    { "Path": "systemjs.config.js" }
  ],

  "Tests": [
    {
      "Path": "app.test/",
      "Includes": [ "*.ts" ],
      "Excludes": [ "node_modules" ]

    }
  ]
}



Browser Arguments is not working for me in Chrome and IE though testing in Browser using firefox is fine. That is my observation. 

Code coverage is also is not working. Below is what I am getting:
Error: Error opening C:/MyWeb/node_modules/zone/dist/zone.js.js: The system cannot find the path specified.
While Running:C:\MyWeb\wwwroot\app.test\common\validators\emailValidator.directive.spec.ts
Error: Error opening C:/MyWeb/node_modules/zone/dist/jasmine-patch.js.js: The system cannot find the path specified.
While Running:C:\MyWeb\wwwroot\app.test\common\validators\emailValidator.directive.spec.ts
Error: Error opening C:/MyWeb/node_modules/zone/dist/async-test.js.js: The system cannot find the path specified.
While Running:C:\Git\CustomerServiceWeb\CustomerServiceWeb.Web\wwwroot\app.test\common\validators\emailValidator.directive.spec.ts
Error: Error opening C:/MyWeb/node_modules/zone/dist/fake-async-test.js.js: The system cannot find the path specified.
While Running:C:\MyWeb\wwwroot\app.test\common\validators\emailValidator.directive.spec.ts
Error: Timeout occurred when executing test file
While Running: C:\MyWeb\wwwroot\app.test\common\validators\emailValidator.directive.spec.ts


I tried @bootrider's config and its not working for me. I am not also sure how to use the 'compile.bat'. If that is significant.

**Comment by mmanela** [comment]
For code coverage, please add CodeCoverageIncludes/Excludes like @bootrider 

```
  "CodeCoverageExcludes": [ "*node_modules\\*.ts", "*tests\\*.spec.ts" ],
  "CodeCoverageIncludes": [ "*code.ts" ],
```

**Comment by mmanela** [comment]
Closing as I have not heard back in a long time. Please re-open if needed.

**Comment by harvester-software** [comment]
Unnecessarily complicated crap

**Comment by harvester-software** [comment]
Adding my config in case it helps anyone and just generally sharing the pain of getting this working.

My set-up is similar to @angDakila 

- IDE is Visual Studio 2015 U3.
- The application is Angular2 delivered via ASP.NET Core 1.0.
- Application and Jasmine tests written in TypeScript.
- Module loading with systemjs.config.js (which didn't need to be modified to get the tests running).
- I have installed in VS Chutzpah Test Adapter for the Test Explorer and Chutzpah Test Runner Context Menu Extension, version 4.2.4 for both.

The chutzpah.json looks like this
```
{
  "Framework": "jasmine",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [

    { "Path": "../../node_modules/systemjs/dist/system.js" },
    { "Path": "../../node_modules/es6-shim/es6-shim.js" },
    { "Path": "../../node_modules/systemjs/dist/system-polyfills.js" },
    { "Path": "../../node_modules/rxjs/bundles/Rx.js" },
    { "Path": "../../node_modules/typescript/lib/typescript.js" },
    { "Path": "../../node_modules/zone.js/dist/zone.js" },
    { "Path": "../../node_modules/reflect-metadata/Reflect.js" },
    { "Path": "../../systemjs.config.js" }

  ],
  "Tests": [
    {
      "Includes": [ "*.spec.ts" ]
    }
  ]
}
```

Here's the test itself. I'll not post the code for the method under test and you can guess the implementation yourselves.

```
///<reference path="../../node_modules/@types/jasmine/index.d.ts"/>

import { ShapeShifterComponent } from "../app/shape-shifter.component";

describe("adding 2 and 7", () => {

    // Arrange
    let sut = new ShapeShifterComponent();

    // Act
    let result = sut.addTwoNumbers(2, 7);

    // Assert
    it("should equal 9", () => {
        expect(result).toEqual(9);
    });

});
```
This got Chutzpah successfully marshalling Jasmine tests for a simple method on an Angular2 component.

**Comment by laxmandasari** [comment]
@harvester-software - Will you able to share the working repo of your setup. I have followed the same things which have mentioned but its not working. Appreciate any help!
