### ISSUE TITLE
Visual Studio Contradiction

### ISSUE THREAD

**Issue by ricksmt** [mmanela/chutzpah#535]
I posted [my problem on StackOverflow](http://stackoverflow.com/q/38491238/1680677), but I'm hoping you can offer some insight. I can try putting together a repro if you need one, but the major details are in the post, so hopefully that can get us a little way on it's own.

In summary, Chutzpah works for a simple JavaScript test, but all my AngularJS tests (using the Jasmine) fail. It's as if the dependencies aren't fully defined, and I'm not sure why. Visual Studio seems split between it's Locals tab saying the dependencies are fully defined and the Watch tab saying properties are undefined.

**Comment by mmanela** [comment]
Have you looked at the Chutzpah samples for Angular JS and see if those work for you?

**Comment by ricksmt** [comment]
The AngularJS TemplateDirective sample works for me. Ran it successfully from the command line. Retried my project from the command line, but got the same error.

**Comment by mmanela** [comment]
So what is that sample doing that works that is different than your code? (I am not an angular expert, many times people hit issues with Angular and not Chutzpah but the key is getting them to understand each other)

**Comment by ricksmt** [comment]
I'm not sure. The sample test has a reference comment, but that shouldn't be an issue if I'm running the test with chutzpah.json. My JSON is below:
```
{
	"Framework": "jasmine",
	"References": [
		// Base setup
		{ // Include jQuery
			"Path": "../MyProject/Scripts",
			"Includes": [ "jquery-*.js" ],
			"Excludes": [ "*.intellisense.js" ],
			"IsTestFrameworkFile": true
		},
		{ // Include AngularJS
			"Path": "../MyProject/Scripts/angular.js",
			"IsTestFrameworkFile": true
		},
		{ // Include AngularJS Mocks
			"Path": "../MyProject/Scripts/angular-mocks.js",
			"IsTestFrameworkFile": true
		},

		// Project setup
		{ // Include all 3rd party scripts
			"Path": "../MyProject/Scripts",
			"Excludes": [
				"*/jquery*.js",
				"*/angular.*js",
				"*/_references.js"
			]
		},
		{ // Include all Views scripts
			"Path": "../MyProject/Views",
			"Includes": [ "*.js" ]
		},

		// Mock setup
		{ // Custom mocks
			"Path": "Scripts/Mocks",
			"Includes": [ "*.mock.js" ]
		},
		{ // Fallback mocks
			"Path": "Scripts/Mocks",
			"Includes": [ "*.default.js" ]
		}
	],
	"Tests": [
		{
			"Includes": [
				"*.unit.js",
				"*.integration.js"
			]
		}
	],
	"RootReferencePathMode": "SettingsFileDirectory",
	"CodeCoverageIncludes": [
		"../MyProject/Scripts/MyProject*.js",
		"../MyProject/Scripts/Services/*.js",
		"../MyProject/Views/*.js"
	]
}
```
It has more than the sample does, but I don't see how they'd mess up the tests like this. I've wrapped my tests in self-executing anonymous functions with "use strict";, but I've tried without those and it's still the same.

**Comment by mmanela** [comment]
Are you able to make your tests run in a vanilla jasmine setup (not using Chutzpah) and then compare the Chutzpah generated HTML to your own?

**Comment by ricksmt** [comment]
Finally figured it out. Simple mistype.

**Comment by mmanela** [comment]
@ricksmt For any other users who view this can you share what the typo was and the final solution?

**Comment by ricksmt** [comment]
The StackOverflow Q&A illustrates the problem (and consequently the fix) better, but I'll surmise here:

I was testing some SSN validation, but I had named the field "snn" instead of "ssn". My test, which was written correctly, never found "ssn", but I could always find (and misread) "snn" in the Watch or Locals. Simply renaming the field to "ssn" resolved the problem.
