### ISSUE TITLE
can't find variable : require - Chutzpah is not recognizing my tests

### ISSUE THREAD

**Issue by sujaykodamala** [mmanela/chutzpah#536]
I'm really new to Churtzpah and Jasmine. I have been trying to run tests using Chutzpah. I'm using Jasmine, Typescript , Chutzpah , angular2 to write unit tests. Whenever i try to run the tests , I see that my tests are being detected . My chutzpah.json file is as follows :

```
{
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    {
      "Path": "../app/ ",
      "Includes": [ "*.ts" ],
      "Excludes": [ "*.d.ts" ]
    }
  ],
  "Tests": [
    {
      "Includes": [ "*.spec.ts" ],
      "Excludes": [ "*.d.ts" ]
    }
  ]
}`
```

I had compile.bat before. I removed as i'm not sure of how .bat file should looks like .
My test file look like 

`/// <reference path="../../require.d.ts" />
// <reference path="../typings/jasmine/jasmine.d.ts" >

import {it, describe, beforeEach, inject, beforeEachProviders} from "@angular/core/testing";
import {HTTP_PROVIDERS} from "@angular/http";
import {LoginService} from "./login.service";

describe("testing LoginService", () => {
    let Myservice: LoginService = new LoginService();
    it("Should return true", () => {
        expect(Myservice.validateUser("test", "test")).toBe(true);
    });
        it("validateUser should fail if input values are null", () => {
            expect(Myservice.validateUser(null, null)).toBe(false);
        });
    });`

and I see following errors in my console:

Error: ReferenceError: Can't find variable: require
at global code in file:"path"/login.service.spec.js (line 2)
While Running:"path"\app\login\login.service.spec.ts
------ Test started: File: "path"\login\login.service.spec.ts ------
0 passed, 0 failed, 0 total (chutzpah).

Please let me know what I should do and what files I still need

**Comment by GeorgDangl** [comment]
You need to include some more references to your `chutzpah.json`. Here's an example that works for me with Angular 2:

    {
      "Framework": "jasmine",
      "TestHarnessReferenceMode": "AMD",
      "TestHarnessLocationMode": "SettingsFileAdjacent",
      "Tests": [
        {
          "Includes": [ "*.spec.ts" ],
          "Excludes": [ "node_modules" ]
        }
      ],
      "References": [
        { "Path": "../node_modules/es6-shim/es6-shim.js" },
        { "Path": "../node_modules/reflect-metadata/Reflect.js" },
        { "Path": "../node_modules/systemjs/dist/system.src.js" },
        { "Path": "../node_modules/zone.js/dist/zone.js" },
        { "Path": "../node_modules/zone.js/dist/jasmine-patch.js" },
        { "Path": "../node_modules/zone.js/dist/async-test.js" },
        { "Path": "../node_modules/zone.js/dist/fake-async-test.js" },
        { "Path": "../node_modules/core-js/client/shim.min.js" },
        { "Path": "testSetup.js" },
        { "Path": "systemjs.config.js" }
      ]
    }

**Comment by sujaykodamala** [comment]
Do you have a testSetup file ? could you please post that. I'm just wondering how it would look like.
Also, don't we need compile.bat file ?

**Comment by mmanela** [comment]
Take a look at the Typescript angualr sample (https://github.com/mmanela/chutzpah/tree/master/Samples/Angular/Basic_TypeScript) to hopefully hepl you get started.

**Comment by GeorgDangl** [comment]
@sujaykodamala the testSetup.js is just for systemjs to not use umd packages since that caused a bug for me with Angular 2. I've got a Visual Studio / Angular 2 TypeScript example repository where you could also take a look at: https://github.com/GeorgDangl/NetCoreHeroes

**Comment by sujaykodamala** [comment]
Thank you for your responses @mmanela and @GeorgDangl

**Comment by sujaykodamala** [comment]
`{
  "Framework": "jasmine",

  "Compile": {
    "Mode": "Executable",
    "Executable": "../compile.bat",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "UseSourceMaps": true,
    "Paths": [
      {
        "SourcePath": "../",
        "OutputPath": "../tests"
      }
    ]
  },
  "References": [
   { "Path": "../node_modules/es6-shim/es6-shim.js" },
    { "Path": "../node_modules/reflect-metadata/Reflect.js" },
    { "Path": "../node_modules/systemjs/dist/system.src.js" },
    { "Path": "../node_modules/zone.js/dist/zone.js" },
    { "Path": "../node_modules/zone.js/dist/jasmine-patch.js" },
    { "Path": "../node_modules/zone.js/dist/async-test.js" },
    { "Path": "../node_modules/zone.js/dist/fake-async-test.js" },
    { "Path": "../node_modules/core-js/client/shim.min.js" },
    {
      "Path": "app",
      "Includes": [ "*.ts" ],
      "Excludes": [ "*.d.ts" ]
    }
  ],
  "Tests": [
    { "Include": "app/tests/*.spec.ts" }

  ]
}`

**Comment by bootrider** [comment]
Hello guys,  in your configuration file  I see that you state:

```
"Tests": [
    { "Include": "*.spec.ts" }

  ]

```
should it be **Include** or **Includes** ?

**Comment by GeorgDangl** [comment]
It should be `Includes`. That's in the wiki here on GitHub and also in the [Json schema](http://json.schemastore.org/chutzpah):

		"testSettings": {
			"properties": {
				"Path": {
					"description": "The path to either a file or a folder. If given a folder, it will be scanned recursively. This path can be relative to the location of the chutzpah.json file.",
					"type": "string"
				},
				"Includes": {
					"description": "This is an optional array of include glob patterns. Only files matching the Include pattern will be added.",
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"Excludes": {
					"description": "This is an optional array of exclude glob patterns.  Only files not matching the Exclude patterns will be added.",
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			}
		},

**Comment by sujaykodamala** [comment]
changing Include to Includes isn't helping me . The console displays the following error:
"Total Tests: 0 passed, 0 failed, 0 total"

**Comment by mmanela** [comment]
Can you provide a runnable repro that I can test locally?

**Comment by sujaykodamala** [comment]
Hey @mmanela , here is the repo https://github.com/sujaykodamala/ChutzpahUnitTesting-

**Comment by mmanela** [comment]
Ok so can you make test html file that works without chutzpah? That would eliminate chutzpah from the equation and ensure you have all your dependencies working correctly. I have a sample of Angualr2 test in the current build of Chutzpah (although I think it requires the new build I am working on to run).

https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic

**Comment by sujaykodamala** [comment]
Are you talking about running the tests by some other means other than Chutzpah ? I had my tests running with Karma .

**Comment by llefkowitz** [comment]
This looks similar to #519 with error we were getting with chutzah /angular 2

**Comment by mmanela** [comment]
I added better support for Angular2 in the 4.3.0 release. Please take a look at the [Angular2 sample](https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic) and see if it helps.

Will close for now but re-open if this doesn't solve the problem.

**Comment by sujaykodamala** [comment]
Thanks, I Haven't worked on unit testing for  a while. I will update you if I run into any issues.
