### ISSUE TITLE
"False positive" chutzpah is detecting tests in files that don't contain tests

### ISSUE THREAD

**Issue by glenserraview** [mmanela/chutzpah#537]
Hi,

I'm trying to get Chutzpah working on a project that has formerly been working with Karma. I've added a chutzpah.json file and got my references working. The tests now run, but there are thousands of tests run that don't actually refer to a test file.

See Chutzpah.json here:
![chutzpah json](https://cloud.githubusercontent.com/assets/20766217/17285404/c8ace6b8-5805-11e6-8cf6-efea357bc32e.png)

Here is an example of a 'test' that isn't really a test, it's the source file.
![image](https://cloud.githubusercontent.com/assets/20766217/17285475/43de6f28-5806-11e6-9839-cb38da48b899.png)

Is there a reason that chutzpah is detecting code files as tests?

Thanks!

**Comment by mmanela** [comment]
Can you share your full Chutzpah.json file?

**Comment by mmanela** [comment]
Closing since I never got a repro / more info. Please reopen when ready
