### ISSUE TITLE
Test explorer does not recognizes all the tests

### ISSUE THREAD

**Issue by bootrider** [mmanela/chutzpah#539]
I have a project with the following chutzpah.json: 

```
{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  
  "References": [
    { "Path": "node_modules/es6-shim/es6-shim.min.js" },
    { "Path": "node_modules/zone.js/dist/zone.min.js" },
    { "Path": "node_modules/reflect-metadata/Reflect.js" },
    { "Path": "node_modules/systemjs/dist/system.js" },
    { "Path": "system-config.js" }
  ],
  "CodeCoverageExcludes": ["node_modules/*"],
  "Tests": [
    { "Path": "app", "Includes": [ "*.spec.ts" ] }
  ]
}
```

and the following tests files

![2016-08-05_13-54-34](https://cloud.githubusercontent.com/assets/11464233/17447495/4d6521e8-5b14-11e6-8cd6-c7bb5d079c54.jpg)

Test explorer just shows tests stored in the first file
![2016-08-05_13-56-33](https://cloud.githubusercontent.com/assets/11464233/17447573/c208a100-5b14-11e6-9220-a96787a82907.jpg)

If I try to run the the command  of the VSTest I get the same result:
![2016-08-05_13-57-21](https://cloud.githubusercontent.com/assets/11464233/17447771/0dbe5f9e-5b16-11e6-80c6-50c92a40826f.jpg)

If I call the command setting the name of the file (e.g. ` "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" app\InspectionDataView.spec.ts  /UseVsixExtensions:true` ), the tests in the file run.

Extra point:

I tried to run the test directly with Chutzpah.console.exe, this is what I got:

![2016-08-05_14-05-58](https://cloud.githubusercontent.com/assets/11464233/17447759/f1462694-5b15-11e6-8083-5025956253f4.jpg)

What am I missing here ?

Note: Using VS 2015 Update 3

**Comment by mmanela** [comment]
Can you provide a repro I can run? 
Also, the command line version of Chutzpah you are running is VERY old. Please try with the most recent version and see if it gives an error.

**Comment by HarelM** [comment]
Hi, I have just updated my entire development work space and the tests are no longer visible in the test explorer window.
Tests can be ran manually using right click but not from test explorer window - I have only C# tests there.
This is using VS 2015 update 3.

**Comment by HarelM** [comment]
Ignore my last comment, the tests are back, not sure what I did...

**Comment by bootrider** [comment]
I update chutzpah to version 4.2.3.0, now the test runs with the chutzpah console. but the VSRunner still does not recognize tests in all files, just in the first one.

**Comment by mmanela** [comment]
Not sure why VS would run different than client. Can you turn on Chutzpah tracing and share? (You can configure it in your [chutzpah.json](https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File) file)

**Comment by bootrider** [comment]
@mmanela If I want to run all the tests with the Chutzpah console, how should I setup the command line?
e.g.
`chutzpah.console.exe *.spec.ts`

**Comment by bootrider** [comment]
I ran the tests from the solution explorer pointing to the chutzpah.json, and I got this log. Line 4 shows the files that are going to be processed, but only run the test in the first one. this log end at Line 118.

I ran the test selecting each one of the files, the log of this activities are from Line 118.

[chutzpah.txt](https://github.com/mmanela/chutzpah/files/407280/chutzpah.txt)

**Comment by bootrider** [comment]
Trying to generate a small example to reproduce the behavior: in a small environment it works perfectly :(

**Comment by bootrider** [comment]
There is something in this haunted legacy code that I have to test, sorry to waste your time.

**Comment by mmanela** [comment]
@bootrider From the console exe you can just point it at your chutzpah.json file to run all files.

If you could share your full repo with me privately I can try. But this seems odd.
