### ISSUE TITLE
code coverage does not generate result

### ISSUE THREAD

**Issue by bootrider** [mmanela/chutzpah#540]
I follow the instructions to setup the use of chutzpah in one project, the test ran successfully, now I want to get the coverage. 

I installed the package blanket.js, and run the chutzpah console

![2016-08-08_16-32-39](https://cloud.githubusercontent.com/assets/11464233/17497103/ce9fd37a-5d85-11e6-8505-18aaec74123e.jpg)

If I run the tests from the VS Test runner I get:

![2016-08-08_16-33-45](https://cloud.githubusercontent.com/assets/11464233/17497180/31885d4a-5d86-11e6-8b40-33d1a7fb243d.jpg)

I know that I am missing something, could you give me a hand to  discover my mistake?

[WebSite1.zip](https://github.com/mmanela/chutzpah/files/407779/WebSite1.zip)

**Comment by mmanela** [comment]
It worked ok for me:
![image](https://cloud.githubusercontent.com/assets/304410/17531206/c2ad3256-5e2f-11e6-9d03-b6124c5d7bed.png)

I just unziped and run the following command:

chutzpah.console.exe .\chutzpah.json /coverage

**Comment by bootrider** [comment]
Is there a special configuration for blanket that I should perform? I am really lost about this.

**Comment by bootrider** [comment]
This is the debug log:
[coverageLogChutzpah.txt](https://github.com/mmanela/chutzpah/files/411029/coverageLogChutzpah.txt)

**Comment by mmanela** [comment]
I think I figured it out. The issue is with using SourceMaps for code coverage when you have spaces in your path. If you either

1. Put your project in a path with no spaces
2. Disable SourceMaps in the compile options for chutzpah  ```"UseSourceMaps": false``` it will work.

@Pablissimo Can you take a look at the spaces issue?

**Comment by bootrider** [comment]
Thanks a lot!!! 
Just disable the use source map, and it works perfectly, I did not change the folder structure.

**Comment by Pablissimo** [comment]
Any chance we can reopen this? Would like to take a look but can't currently build either, may raise an issue for that...

**Comment by bootrider** [comment]
Reopen by request of @Pablissimo

**Comment by Pablissimo** [comment]
Hmm, noticing this in a deployment I've got with 4.2.4 which is disappointing - looks like I didn't quite kill it off. Will try to find time to investigate...
