### ISSUE TITLE
Does not run in browser, Code coverage does not appear in console  & it is shown in NAN

### ISSUE THREAD

**Issue by bootrider** [mmanela/chutzpah#541]
I have this typescript project in VS 2015, with some test that run either from VS or from Chutzpah console:
![2016-08-12_10-58-55](https://cloud.githubusercontent.com/assets/11464233/17628665/1924e1c6-607c-11e6-998f-465df88405a3.jpg)
![2016-08-12_11-00-10](https://cloud.githubusercontent.com/assets/11464233/17628666/1c3841a0-607c-11e6-833b-83e62a489501.jpg)

If I run a test to the browser
![2016-08-12_11-02-30](https://cloud.githubusercontent.com/assets/11464233/17628698/516a34a0-607c-11e6-9e8c-d685e2c7a8bf.jpg)

I get this "empty" webpage:
![2016-08-12_11-03-26](https://cloud.githubusercontent.com/assets/11464233/17628732/77edf4e0-607c-11e6-9cee-6a9ed2139d11.jpg)

If I run Chutzpah with coverage

![2016-08-12_11-04-21](https://cloud.githubusercontent.com/assets/11464233/17628782/9e9d8844-607c-11e6-9098-91bb0b7eaac3.jpg)

the result is this:
![2016-08-12_11-06-04](https://cloud.githubusercontent.com/assets/11464233/17628842/e0aeaaec-607c-11e6-8804-d1de2a33522a.jpg)

if I try to do it with the console I do not even get a result of the coverage process.

![2016-08-12_11-07-43](https://cloud.githubusercontent.com/assets/11464233/17629043/044bfe36-607e-11e6-9369-6b69230dc601.jpg)

this is my current configuraiton

```

{
  "Framework": "jasmine",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TestHarnessReferenceMode": "AMD",
  "Compile": {
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "Executable": "compile.bat",
    "UseSourceMaps": false
  },

  "References": [

    { "Path": "node_modules/es6-shim/es6-shim.min.js" },
    { "Path": "node_modules/zone.js/dist/zone.min.js" },
    { "Path": "node_modules/reflect-metadata/Reflect.js" },
    {
      "Path": "node_modules/systemjs/dist/system.js",
      "IsTestFrameworkFile": true
    },

    {
      "Path": "wwwroot/system-config.js"
    },
    { "Path": "code.ts" }
  ],

  "CodeCoverageExcludes": [ "node_modules\\*.ts", "tests\\*.spec.ts" ],
  "CodeCoverageIncludes": [ "code.ts" ],

  "Tests": [
    {
      "Path": "tests",
      "Includes": [ "*.spec.ts" ]
    }
  ]

}
```

[chutzpahASP.NETCore.zip](https://github.com/mmanela/chutzpah/files/415710/chutzpahASP.NETCore.zip)

If I change the TestHarnessReferenceMode to false, then the test does not even run.

**Comment by mmanela** [comment]
Can you try to change your setting to this

```
  "CodeCoverageExcludes": [ "*node_modules\\*.ts", "*tests\\*.spec.ts" ],
  "CodeCoverageIncludes": [ "*code.ts" ],
```

**Comment by bootrider** [comment]
I tried the change that you proposed, and it works for my example project.

I mimic the configuration in a bigger project but it still fails...any other hint?

thanks for your help!!

**Comment by mmanela** [comment]
I made the same setting change I suggested in your project and the coverage ran fine:

```
{
  "Framework": "jasmine",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TestHarnessReferenceMode": "AMD",
  "Compile": {
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "Executable": "compile.bat",
    "UseSourceMaps": false
  },

  "References": [

    { "Path": "node_modules/es6-shim/es6-shim.min.js" },
    { "Path": "node_modules/zone.js/dist/zone.min.js" },
    { "Path": "node_modules/reflect-metadata/Reflect.js" },
    {
      "Path": "node_modules/systemjs/dist/system.js",
      "IsTestFrameworkFile": true
    },

    {
      "Path": "wwwroot/system-config.js"
    },
    { "Path": "code.ts" }
  ],

  "CodeCoverageExcludes": [ "*node_modules\\*.ts", "*tests\\*.spec.ts" ],
  "CodeCoverageIncludes": [ "*code.ts" ],

  "Tests": [
    {
      "Path": "tests",
      "Includes": [ "*.spec.ts" ]
    }
  ]

} 
```

![image](https://cloud.githubusercontent.com/assets/304410/17916041/8f2d197e-6964-11e6-97c7-8b4e4ed39231.png)

**Comment by bootrider** [comment]
You are correct, in the project that I share to you, it works pretty good!!!!

Trying to perform the same configuration in a little bigger project it fails. may you could give another points to check? 

thanks

**Comment by mmanela** [comment]
So can you show me the difference? I am not sure what is the difference in your bigger project

**Comment by bootrider** [comment]
well, lets say that it has more dependencies to npm modules:
the chutzpah conf file is here:
```

{
  "Framework": "jasmine",

  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TestHarnessReferenceMode": "AMD",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "UseSourceMaps": true,
    "Paths": [
      {
        "SourcePath": "app",
        "OutputPath": "wwwroot"
      }
    ]

  },

  "EnableTracing": true,
  "TraceFilePath": "chutzpah.log",

  "References": [
    { "Path": "node_modules/es6-shim/es6-shim.min.js" },
    { "Path": "node_modules/zone.js/dist/zone.min.js" },
    { "Path": "node_modules/reflect-metadata/Reflect.js" },
    {
      "Path": "node_modules/rxjs/Rx.js",
      "IncludeInTestHarness": false
    },
    {
      "Path": "node_modules/systemjs/dist/system.src.js",
      "IsTestFrameworkFile": true
    },

    { "Path": "node_modules/systemjs/system-polyfills.src.js" },

    {
      "Path": "node_modules/@ngular/common/index.js",
      "IncludeInTestHarness": false
    },
    {
      "Path": "node_modules/@ngular/compiler/index.js",
      "IncludeInTestHarness": false
    },
    {
      "Path": "node_modules/@ngular/core/index.js",
      "IncludeInTestHarness": false
    },
    {
      "Path": "node_modules/@ngular/router/index.js",
      "IncludeInTestHarness": false
    },
    {
      "Path": "node_modules/@ngular/http/index.js",
      "IncludeInTestHarness": false
    },
    {
      "Path": "node_modules/@ngular/platfomr-browser/index.js",
      "IncludeInTestHarness": false
    },

    {
      "Path": "node_modules/three-js/three.js",
      "IncludeInTestHarness": false
    },

    {
      "Path": "node_modules/papaparse/papaparse.js",
      "IncludeInTestHarness": false
    },

    {
      "Path": "node_modules/handsontable/dist/handsontable.full.min.js",
      "IncludeInTestHarness": false
    },

    {
      "Path": "wwwroot/system-config.js"
    },
    {
      "Path": "app",
      "Includes": [ "*.ts" ],
      "IncludeInTestHarness": false
    }
  ],

  "CodeCoverageExcludes": [ "*node_modules\\*.js", "*tests\\*.spec.ts" ],
  "CodeCoverageIncludes": [ "*\\app\\*.ts" ],

  "Tests": [
    {
      "Path": "tests",
      "Includes": [ "*.spec.ts" ]
    }
  ]
}
```

it allows me to execute the tests but does not show any coverage :(

**Comment by mmanela** [comment]
Can you provide me a repro project for the more complicated setup?

**Comment by bootrider** [comment]
@mmanela thanks for your offer, but I cannot share the code beyond  this point, I know that it is like walking in the darkness, but thanks anyway

**Comment by mmanela** [comment]
@bootrider Well, if you can create a repro that is more indicative of your more complicated setup then I can debug that.

**Comment by mmanela** [comment]
Closing as I have not heard back in a long time. Please re-open if needed.
