### ISSUE TITLE
Console runner takes very long to start

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#543]
Running the following line feels like the process is stuck as it doesn't output anything to the console...
(I thought it was really stuck until I accidentally left it running).
Might be related to the fact that I use windows 10?
```
chutzpah.console.exe .\chutzpah.json /junit .\chutzpah-results.xml
```
the following part just stays on the screen for about 3 minutes before writing the tests results.
```
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.2.3.0
Copyright (C) 2015 Matthew Manela (http://matthewmanela.com).

```

**Comment by mmanela** [comment]
Some questions
1. If you run it a second time is it faster?
2. Can you run with /log and share the log file?

**Comment by HarelM** [comment]
Added /log flag but I don't see a log file, do I need to pass the log file name?
Second time doesn't run faster.

**Comment by mmanela** [comment]
Figured it out. Your chutzpah.json line describing where your tests are is too broad. If you change it too this:

``` 
  "Tests": [{ "Path": "tests", "Include": "*\\**\\*Tests.ts" }],
 ```

it will run __MUCH__ faster. What you had before was scanning all folders and turned out to be very inefficient.

**Comment by HarelM** [comment]
I see. Thanks for taking the time to look into it.
I think that a short message to the console saying "looking for test files" or "discovering ..." could help in the future in this case to let the user know the runner is busy and not stuck.
I'll fix my json file nonetheless.
Thanks again!

**Comment by mmanela** [comment]
Thanks for the feedback. I appreciate you taking the time to report this.
