### ISSUE TITLE
Lcov file is created empty

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#544]
Hi,

I'm using the console runner to run my typescript tests.
The tests runs locally just fine from visual studio and I even get the nice html coverage report.
Now I want to publish this report to coveralls.io.
I know that coveralls doesn't support the format chutzpah writes but I found a way to convert the lcov file to what coveralls process.
unfortunately I can't get the lcov file to have any data in it when running from command line:
```chutzpah.console.exe .\chutzpah.json /converage /lcov .\chutzpah-results-lcov.xml```
am I doing something wrong?
Also tried junit, but got only tests report without coverage:
```chutzpah.console.exe .\chutzpah.json /converage /junit .\chutzpah-results-junit.xml```
Tried coveragejson flag which didn't create a file (I believe that when a user adds the /coveragejson flag it means he wants to get coverage report...)
```chutzpah.console.exe .\chutzpah.json /coveragejson .\chutzpah-results-junit.xml```
This is the only thing that created a report file, I'm still trying to figure out how to read it:
```chutzpah.console.exe .\chutzpah.json /coverage /coveragejson .\chutzpah-results-junit.xml```

**Comment by mmanela** [comment]
You have a typo in your first line. You wrote converage instead of coverage. Can you try

``` chutzpah.console.exe .\chutzpah.json /coverage /lcov .\chutzpah-results-lcov.xml ```

**Comment by HarelM** [comment]
hmm... shouldn't the runner inform me then? I'll give it another try soon.

**Comment by HarelM** [comment]
Ran it again, file is now full, the typo was the issue.
I think that chutzpah runner should at least warn me about typos if not stop the process all together.
See other issues I experienced above.

**Comment by mmanela** [comment]
Sure, I will make that change
