### ISSUE TITLE
Chutzpahjson coverage file - different number of sizes for the arrays

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#545]
Hi,

I'm looking into parsing the chutzpah json coverage file in order to be able to send it to coveralls.io site.
See below, the number of items in the LineExecutionCounts array and the SourceLines array do not match, it is by design? which line should I ignore the first? the last?

```
{"D:\\Github\\IsraelHikingMap\\Site\\isrealhiking.web\\services\\mapService.ts":
{"FilePath":"D:\\Github\\IsraelHikingMap\\Site\\isrealhiking.web\\services\\mapService.ts",
"LineExecutionCounts":[
null,
36,
18,
null,
null,
9,
10,
null,
null,
null,
null,
null,
null,
18,
18,
null
],
"SourceLines":[
"namespace IsraelHiking.Services {",
"    export class MapService {",
"        public map: L.Map;",
"",
"        constructor() {",
"            this.map = L.map(\"map\", {",
"                center: L.latLng(31.773, 35.12),",
"                zoom: 13,",
"                doubleClickZoom: false,",
"                zoomControl: false",
"            } as L.Map.MapOptions);",
"        }",
"    }",
"}",
" "
],
```

**Comment by mmanela** [comment]
Can you share the repro that I can run locally? And what is your chutzpah.json file?

**Comment by HarelM** [comment]
Sure, same as always:
https://github.com/IsraelHikingMap/Site
Chutzpah.json file is there in the root folder.

**Comment by mmanela** [comment]
I am not sure why it does this sometimes. I was able to replicate (and I also was able to not have it happen sometimes). But I think it will leave off a final curly bracket in some cases. This is coming from the Blanket library chutzpah uses so it may be a bug in that. However, it seems the coverage is still right.

**Comment by HarelM** [comment]
I figured out that in case it happens the first line if courage should be ignored, maybe you could open a bug for blanket.js, meanwhile fix this locally? I added a nasty "if" in my parsing code but I would very much like to remove it.

**Comment by mmanela** [comment]
Are you sure it's the first line? In my one test it looked like the last
line.

**Comment by HarelM** [comment]
Pretty sure, I skip the first line and use all the rest.
Results for ts files can be seen in the project's coveralls.io.
This is an example of one file:
https://coveralls.io/builds/7476068/source?filename=%2FIsrealHiking.Web%2Fservices%2FSnappingService.ts

you can run my project and inspect this file, the red lines should be inside the "if" statement as far as I can understand.
