### ISSUE TITLE
Coverage json file - file names are converted to lower cases

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#546]
The file path in the coverage json file have partial lower case characters, this presents a problem in something I'm working on...
for example below, the first part is correct, the lower case start after the "site" and the file name is correct...: 

```
{"D:\\Github\\IsraelHikingMap\\Site\\isrealhiking.web\\services\\mapService.ts"
...
```

**Comment by mmanela** [comment]
I tried a simple repro but it worked fine for me. I created a folder called CATS and put a test file in their. I then generated code coverage and the rests correctly contained the casing CATS. 

Can you provide me a more detailed repro that I can run locally?

Thanks!

**Comment by HarelM** [comment]
I think the problem is when setting in the chutzpah.json file the references without proper casing.
I can keep my current repository with the issue in case you want to look at it anytime soon, or you can get the following commit and run coverage using my chutzpah json file:
https://github.com/IsraelHikingMap/Site/commit/c9ab9e9ac4401eecb2a8bb6ba3c313765425c04c
Let me know...
