### ISSUE TITLE
Coverage of .js files containing arrow functions ( => )

### ISSUE THREAD

**Issue by GreenC90** [mmanela/chutzpah#547]
Hi Matthew,

Not entirely sure if this falls under your project, given it seems to be a blanket.js issue but...

When code coverage includes a file for coverage featuring an arrow function then blanket_jasmine_v2.js throws an "unexpected token" error when parsing the ">".

My particular stack trace begins:

`Error:Error: Line 46: Unexpected token >
at throwError in file:///C:/Program%20Files/chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js (line 1171)
at throwUnexpected in file:///C:/Program%20Files/chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js (line 1217)
at parsePrimaryExpression in file:///C:/Program%20Files/chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js (line 1563)
in file:///C:/Program%20Files/chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js (line 3600)
at trackLeftHandSideExpressionAllowCall in file:///C:/Program%20Files/chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js (line 3495)
at parsePostfixExpression in file:///C:/Program%20Files/chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js (line 1699)
in file:///C:/Program%20Files/chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js (line 3600)`
...

Where line 46 happens to be a line in one of my application files using an arrow function. If I comment that line out, the line error changes to 50, where the second and last arrow function is. Commenting both out means the coverage runs. The two troublesome lines in my application are:

`Line 46: var productRoleId = vm.roleTypes.findIndex((el) => el.roleId === roleId);`
`Line 50: var index = vm.rolesToUpdate.findIndex((el) => el.Hash === userId + roleId);`

I'm currently working around this using the "CodeCoverageExcludes" option in chutzpah.json, but would like to know if there's anyway I'll be able to run coverage on code containing this syntax in the future.

Thanks in advance,
Chris.

**Comment by GreenC90** [comment]
I should also mention that I haven't actually written any tests for this code yet, the only time Chutzpah would currently encounter it is during coverage.

**Comment by mmanela** [comment]
Yes this sounds like a blanket js bug. Please file it on them. Longer term I am considering changing coverage engines to a more active project to help mitigate this kind of issue.

**Comment by GreenC90** [comment]
OK, thanks Matthew, I'll let them know.

Chris.
