### ISSUE TITLE
Error: Timeout occurred when executing test file

### ISSUE THREAD

**Issue by areel** [mmanela/chutzpah#548]
Using VS 2015 Professional Update 3, Chutzpan Test Runner Context Menu 4.2.3

Intermittently I am having the following issue: 
When using the menu command

> Run JS Tests

on a folder containing all my tests, some tests may run and then the remaining tests report the following message, or all tests report the following message:

> `Error: Timeout occurred when executing test file`

If I then chose an individual file and use the menu command

> Open In Browser

that individual test file is executed correctly.
If I return to using

> Run JS Tests

it will fail.

The timeouts may go away by restarting VS or rebooting the OS, but not consistently.

I installed a separate installation using chocolatey. 
Created a dummy test file that contains only

> `console.log("I was executed");`

and is outside any VS solution, I executed with

> chutzpah.console.exe .\dummyTest.js /debug

which results in the following

> Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
> Version 4.2.3.0
> Copyright (C) 2015 Matthew Manela (http://matthewmanela.com).
> 
> Error: Timeout occurred when executing test file
> While Running:F:\dummyTest.js
> 
> === 0 total, 0 failed, took 15.06 seconds ===

Any suggestions as to what I can do to narrow down what is causing the timeouts.

Regards

Aidan

**Comment by mmanela** [comment]
Can you share a repro of this? I can test locally

**Comment by areel** [comment]
Unfortunately I cannot share our application's repo.
No other member of my team is experiencing this issue and it is intermittent on mine, so I am not sure even if I could share the repo it would help. I am assuming some kind of file locking is occurring.
Once the issue occurs within VS, I can replicate it using the chocolately installation.
Is there any mechanism where logging can be activated? I notice that even with /debug on the command line, no logging is displayed, only the header info, does that provide any clue?

**Comment by areel** [comment]
This morning, after starting my machine the tests all run, no issue.
Below is the output from running the chocolately install

`chutzpah.console.exe .\dummyTest.js /debug`

> Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
> Version 4.2.3.0
> Copyright (C) 2015 Matthew Manela (http://matthewmanela.com).
> 
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///F:/_Chutzpah.004346edf98d91cc3b46d2a3b8491e3a.test.html"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! onInitialized  Jasmine - v2"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Url Change file:///F:/_Chutzpah.004346edf98d91cc3b46d2a3b8491e3a.test.html"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! onInitialized  Jasmine - v2"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///F:/_Chutzpah.004346edf98d91cc3b46d2a3b8491e3a.test.html"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/chutzpah_boot.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/chutzpah_boot.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/jasmine.css"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/jasmine.css"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/jasmine.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/jasmine.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/jasmine-html.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/jasmine-html.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/boot.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///C:/ProgramData/chocolatey/lib/Chutzpah/TestFiles/jasmine/v2/boot.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///F:/dummyTest.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! isJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! onJasmineLoaded"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Resource Recieved: file:///F:/dummyTest.js"}}
> #_#Log#_# {"type":"Log","log":{"message":"I was executed"}}
> 
> Log Message: I was executed from F:\dummyTest.js
> 
> #_#FileStart#_# {"type":"FileStart"}
> #_#FileDone#_# {"type":"FileDone","timetaken":2,"passed":0,"failed":0}
> 
> File: F:\dummyTest.js
>      0 total, 0 failed, took 0.00 seconds
> 
> Tests complete: 0#_#Log#_# {"type":"Log","log":{"message":"!!_!! onInitialized  Jasmine - v2"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! Url Change about:blank"}}
> #_#Log#_# {"type":"Log","log":{"message":"!!_!! onInitialized  Jasmine - v2"}}
> 
> === 0 total, 0 failed, took 6.14 seconds ===

**Comment by mmanela** [comment]
Hmm, I am not sure. If you can get a minimal repro I can test it would be helpful. It is very odd that co-workers don't get the issue but you do

**Comment by areel** [comment]
I am ruling out VS because it has exactly the same plugins, extensions, updates as another team member (who never had this issue), I am ruling out the repo since  when the issue occurs it can be replicated in the chocalately installation on a single test file that has no relationship to the repo, (this is also another reason to rule out VS).

Perhaps a third party application has locked a file?
I think looking at what resources are touched before the /debug logging gets executed might help. When the issue is occurring the /debug produces no output so the issue must be occurring before the very first debug log gets executed. Do you agree?

**Comment by mmanela** [comment]
@areel No sure. Are you still having this issue?

**Comment by areel** [comment]
Did you meant to type "Not Sure." ?
Yes, the issue still occurs periodically, happened this morning, sometimes a reboot resolves it, but this morning that did not help, and since I really needed to confirm all tests were still working I spend some more time investigating, I searched for recently created files, looking to see if any thing looked like something that might represent a lock file. Nothing. But I did notice that Visual Studio on startup had installed the Web Compiler extension, the config for this extension was to automatically update. So I deleted the folders, restarted Visual Studio, it (not surprisingly) complained about a corrupt extension while restarting, I then explicitly chose uninstall from the extension dialog, restarted (no complaints this time) and the tests executed correctly. I then reinstalled the webcompiler extension, configured all extensions NOT to auto update, in the "hope" that perhaps VS doing occasional auto updates of other extensions may have been a factor.

**Comment by mmanela** [comment]
Hmm that is interesting. Let me know if that helps

**Comment by mmanela** [comment]
@areel Are you still having the issue?

**Comment by areel** [comment]
Not since I disabled all extensions from auto updating.

I may switch back to auto update and see if issue reoccurs

**Comment by mmanela** [comment]
I will close for now then.

**Comment by Radon222** [comment]
Maybe you can try using the config in chutzpah.json
"TestFileTimeout": "<Timeout in milliseconds>"

**Comment by bkwdesign** [comment]
I would turn the parallelism down to 1 in the chutzpah.json - for me, I found the test output to the command window seems to "step on each other" as if multiple tests are running concurrently and writing to stdout haphazardly as the various async tests complete.

 I also read somewhere that chutzpah is designed to randomize the test order.. and so, if your tests are depending on each other for some shared state (which is a no-no, obviously). Nevertheless, you might not be getting the same routine on every test run
