### ISSUE TITLE
Load file references not in HEAD but closing BODY tag

### ISSUE THREAD

**Issue by WouterBos** [mmanela/chutzpah#549]
Hi,

I'm trying to run automated tests for Angular2/TypeScript with Chutzpah in VS2015. I don't use seperate HTML files, but use the automatically generated HTML harness for it. Unfortunately, Angular2 requires to have the test files being loaded before the closing body tag. Adding the library references in the HEAD will generate an error. I could not find an option in chutzpah.json to get around that, or am I mistaking?

Thanks in advance!

**Comment by mmanela** [comment]
Does it really require this? I have a basic angular2 tests running fine currently (https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic).

**Comment by WouterBos** [comment]
Hmmm. I'll dig up what was the library that expects it.

**Comment by mmanela** [comment]
@WouterBos Any update?

**Comment by mmanela** [comment]
Closing as I have not heard back in a long time. Please re-open if needed.
