### ISSUE TITLE
Visual Studio Duration Sometimes Empty

### ISSUE THREAD

**Issue by spottedmahn** [mmanela/chutzpah#550]
I have 5 JS tests currently and some have the duration and some don't.  The behavior seems inconsistent.

![image](https://cloud.githubusercontent.com/assets/14079228/18056939/0039fe0e-6ddc-11e6-95f6-96990728bf75.png)

Regards,
Mike DePouw

**Comment by gsmeets** [comment]
That's sub 1ms, it's not a problem.

**Comment by mmanela** [comment]
@spottedmahn If @gsmeets is correct then this is not a chutzpah problem but a VS UI issue...

**Comment by spottedmahn** [comment]
![image](https://cloud.githubusercontent.com/assets/14079228/18323810/4bf20d1e-7507-11e6-989b-e23dda6f86c5.png)

FYI, from https://github.com/JoshClose/CsvHelper/tree/master/src/CsvHelper.Example tests.  < 1ms not blanks.

Regards,
Mike DePouw

**Comment by mmanela** [comment]
@spottedmahn Can you provide a repro for me to run locally?

**Comment by mmanela** [comment]
Have not heard back, closing for now but will re-open when repro given
