### ISSUE TITLE
Visual Studio Debug Selected Test(s) Runs All Tests

### ISSUE THREAD

**Issue by spottedmahn** [mmanela/chutzpah#551]
When I select a single test to debug it is running all tests not just the selected one.

Regards,
Mike DePouw

**Comment by mmanela** [comment]
The granularity Chutzpah works at is the whole file.

**Comment by spottedmahn** [comment]
Hi @mmanela,

I see.  It sure would be helpful to make it more granular.  If I make a pull request for such would it get approved?

**Comment by mmanela** [comment]
I would consider it but the tricky thing is Chutzpah unit of execution is a JS file so if you want to scope to a single file there are two options

1. Still execute full file but just report the one test
2. Pass the test name to the framework (qunit, jasmine and mocha) and see if they are able to filter to just one test.

I am curious how you would approach this.

**Comment by gsmeets** [comment]
Mocha's grep feature actually also runs all tests and just filters what you requested.

**Comment by spottedmahn** [comment]
I don't know how I would do it, I just know I can do it with c# so vs supports it, atleast for their stuff.  Thanks for the info.  Maybe one day I will have some time to research it.

Also, I can run one test now, the issue is debugging.  During testing, it can fake it, which it sounds like it already is, but when debugging break points on common methods are troublesome.

Cheers
