### ISSUE TITLE
TFS Build with Typescript, chutzpah.json, AMD, requirejs

### ISSUE THREAD

**Issue by aaronloe** [mmanela/chutzpah#553]
Hello,

First off, Chutzpah is awesome. We used it in our Javascript app with TFS and everything worked wonderfully. Really impressive.

Unfortunately, I haven't been able to get it to work in our new Typescript project. We have a TypeScript app that uses jspm for package management and transpiles all the TS to systemjs. For what it's worth, I originally tried to get Chutzpah to work with systemjs and combed through [this issue](https://github.com/mmanela/chutzpah/issues/534) , but couldn't get that working quite right either, so I decided to add an extra gulp task and transpile all of our TypeScript into AMD modules that requirejs can use and got Chutzpah to work great with some tweaks to the chutzpah.json file when running from Visual Studio. This is our current chutzpah.json file:

```
{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "AMDBaseUrl": "Tests/", 
  "AMDAppDirectory": "App/", 
  "Compile": {
    "Mode": "External"
  },
  "References": [
    {
      "Path": "tests/vendor/require.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "tests/vendor/config.js"
    }
  ],
  "Tests": [
    {
      "Path": "App/",
      "Includes": [ "*.spec.ts" ]
    }
  ]
}
```

Now, I'm trying to get our gated check-in to run the Jasmine tests. I think I've poured over every blog post & thread here and haven't found a working solution. In Summary, here's what I have tried so far:
- Copied the latest Chutzpah.vsix contents to our build controller's custom assemblies directories
- Installed Chutzpah Nuget Package to the project
- Added custom Pre-Build task to the project that Transpiles all of the TS into AMD javascript into the AMDBaseUrl (Tests/) directory, then copies the entire App and Tests directories to the Output Directory used by the build
- Specified custom runSettings.xml file with: 
    TestingMode = All
   EnabledTracing = true
  This causes the build to at least acknowledge that the chutzpah.json file is present. But this is the only thing that gets logged to the %temp% log file:
  Chutzpah.json file found at D:\Builds\9386...\bin\chutzpah.json given starting directory D:\Builds\9386...\bin
- I logged into the build server's source directory where it copies all of the files to before building, and manually ran chutzpah.console.exe from the packages folder with the path to the chutzpah.json file, and it's able to run the all the tests without any issues. I noticed that none of the chutzpah Nuget dlls are copied to the bin folder where TFS compiles the project into. Should they? 

Any help would be so greatly appreciated. Thank you!

**Comment by mmanela** [comment]
Not sure what the issue is but try to not install the nuget in the project but instead add the nuget as the custom assemblies directories instead of the vsix.

**Comment by aaronloe** [comment]
So I'm pretty sure I found the issue. We don't include any of the .js files in our project, so I was missing the step in the instructions that says to set all your files to "Copy Always". My PostBuild event must have been happening too slowly or just after Chutzpah was initialized or something.

Anyways, now I'm working with moving my PostBuild Events to a custom target in the project file & making the entire build process depend on running these scripts first. I had some luck with this in a different project earlier this morning, but it was just a little tricky nailing down the output directory to copy to. I'll report back once I have it totally working. Thanks anyways...

**Comment by mmanela** [comment]
Ok great. Thanks for the update. This is much easier in the new non-xml based TFS build system

**Comment by aaronloe** [comment]
OK, so I got it working. Here's what I had to do:
I updated my Chutzpah.json file to this:

`{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "AMDBaseUrl": "Tests/", // where the TS files get transpiled to under AMD Context
  "AMDAppDirectory": "App/", // where the TS source & spec files live
  "Compile": {
    "Mode": "External"
  },
  "TestFileTimeout": 600000, // <-- avoid Timeout error
  "EnableCodeCoverage": false, // <-- get a bad performance if true
  "EnableTracing": true,
  "References": [
    {
      "Path": "tests/vendor/require.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "tests/vendor/config.js"
    }
  ],
  "Tests": [
    {
      "Path": "App/",
      "Includes": [ "*.spec.ts" ]
    },
    {
      "Path": "Tests/",
      "Includes": ["*.spec.js"]
    }
  ]
}`


I added a custom build step to my project.csproj file to get it to first Transpile my app (using a separate Gulp task that transpiles into AMD modules, since we have to use requireJS as I could not get Chutzpah to work with SystemJS). After Transpiling, I copy both the App and Tests directories to the output folder. This is because in my Chutzpah.json file I'm specifying these two params:
  "AMDBaseUrl": "Tests/", 
  "AMDAppDirectory": "App/", 

The reason I'm doing that, is because we use jspm to manage our packages, which configures our dependencies as SystemJS modules. So we use SystemJS in Development & Production (bundle), and we use requireJS for writing unit tests that will work with Chutzpah and not have to mess with XSS Browser settings (I never actually got passed that. Using SystemJS with Chutzpah seems like it won't work for this reason).

Anyways, Here's the custom build step I appended to my .csproj file:

` 
<PropertyGroup>
    <BuildDependsOn>
      GulpBuild;
      $(BuildDependsOn);
    </BuildDependsOn>
  </PropertyGroup>
  <Target Name="GulpBuild">
    <Exec Command="cd &quot;$(ProjectDir)&quot;">
    </Exec>
    <Exec Command="call npm install">
    </Exec>
    <Exec Command="call jspm install">
    </Exec>
    <Exec Command="call gulp TranspileAMD">
    </Exec>
    <Exec Command="XCOPY &quot;$(ProjectDir)App&quot; &quot;$(TargetDir)App&quot; /s /i /y">
    </Exec>
    <Exec Command="XCOPY &quot;$(ProjectDir)Tests&quot; &quot;$(TargetDir)Tests&quot; /s /i /y">
    </Exec>
  </Target>
`

my TranspileAMD gulp task transpiles my App folder into itself, and then copies that into the Tests directory. I was unable to get it to run on the build machine without transpiling both the AMDAppDirectory and AMDBaseUrl into AMD modules for requireJS to use.

At this point, Chutzpah began to at least recognize my tests, but kept failing with "Timeout occurred when executing test file..." errors. After searching a bit more on these forums I found some people had success by tweaking the Chutzpah.json file to include these params:

  "TestFileTimeout": 600000,
  "EnableCodeCoverage": false, 

After doing this, I finally got it working. Although my last problem is that I had to specify both 
` {
      "Path": "App/",
      "Includes": [ "*.spec.ts" ]
    },
    {
      "Path": "Tests/",
      "Includes": ["*.spec.js"]
    }`

in my Chutzpah.json file. When developing locally, my tests all run twice. If I omit the latter Tests path, the TFS Build server doesn't find any tests at all (it currently only runs the tests once). 

Any suggestions to solve this last issue would be awesome, but if not no worries. Hopefully this'll be of some use to others trying to use TypeScript, SystemJS, and jspm with Chutzpah.

**Comment by mmanela** [comment]
Are your tests in both Tests and App? Are those the same tests? You should not reference them both. I think you just need the App but you need to set up a compile configuration to tell chutzpah where to find the compiled version. For example something similar to this might work:

```
  "Compile": {
    "Mode": "External",
    "Extensions": [".ts"],
    "ExtensionsWithNoOutput": [".d.ts"],
    "Paths": [
       { "SourcePath": "App", "OutputPath": "Tests" } 
    ],
   },
```

**Comment by mmanela** [comment]
Closing for now since have not heard back. Please re-open if issue persists.
