### ISSUE TITLE
Chutzpah Visual Studio test runner failing tests that pass in browser/ReSharper

### ISSUE THREAD

**Issue by glenatron** [mmanela/chutzpah#554]
I have a service that I am testing in Visual Studio and I'm having trouble with the injector running into "unknown provider" errors, but only when the tests are run by Chutzpah directly- if they are run from a browser or from ReSharper they pass successfully.

I'm doing things the Visual Studio way so I have a references.js that contains lots of `/// <reference path="" />` statements pointing at my JavaScript resources, I haven't done any manual configuration for Chutzpah. 
When I attempt to inject my services in the "beforeEach" part of my describe test, I get a message like this:

`Error: [$injector:unpr] Unknown provider: apiRequestServiceProvider <- apiRequestService <- newChannelsApi <- newChannelsService`

The code looks a bit like this:

```
describe( "New Channels Service", function() {
 var newChannelsService, newChannelsApi, $q, $rootScope, $filter;
        beforeEach(module("myapp.channels"));
        beforeEach( inject(function (_newlChannelsService_, _newChannelsApi_,  _$q_, _$rootScope_, _$filter_) {
            $filter = _$filter_;
            $rootScope = _$rootScope_;
            $q = _$q_;

            newChannelsApi = _newChannelsApi_;
            newChannelsService = _newChannelsService_;
        }));
       
       it("doesn't matter what goes here because the runner will crash", function() {
            expect( true ).toBeTrue();
        }
}
```

As I understand it, the "newChannelsApi" should be arriving as a mock, so there should be no need for the underlying dependency chain, but for some reason when I run the code from Chutzpah it is throwing the above message. 

I'm relatively new to testing in Angular so I could well be doing something weird but it looks to me as though the mocking process is somehow failing or something about the dependency tree here is causing Chutzpah to get confused. Unfortunately my app is pretty complex and I don't have time to put together a light reproduction case.

**Comment by mmanela** [comment]
1. Do you have a chutzpah.json file, if so can you share?
2. Did you ask Chutzpah to open the file in the browser? Does it pass there and if not can you debug why?
3. Can you provide a full repro?

**Comment by glenatron** [comment]
1. I haven't done any custom configuration, everything is directly out of the box.
2. It passes perfectly in the browser ( Chrome ) opened from Chutzpah, it only seems to be in the headerless environment that there is a problem.
3. I'm afraid I don't have the resources to try to create a simple reproduction step for you right now - trying to troubleshoot this already cost me quite a bit of time.

I think that the problem arises from something to do with multiple layers of service - as described above we have the `apiRequestService <- newChannelsApi <- newChannelsService` chain. It is perhaps relevant that the `apiRequestServiceProvider` that Chutzpah is asking about does not exist. The `apiRequestService` just uses $http and $q. 

It makes me wonder whether Jasmine in the browser is mocking out the newChannelsApi object but for some reason Chutzpah is trying to instantiate the whole stack. As you can see I'm not mocking in any provision calls.

**Comment by mmanela** [comment]
Chutzpah just runs the same HTML page in a headless browser but some differences that occur in the two environments are
1. Different JS engines. Phantom is not on ES6 and has some different behavior
2. Timing. Things move much faster in Phantom sometimes exposing bugs

**Comment by glenatron** [comment]
I can't figure out what is going on here, although it does seem like it could be some ES6 related stuff and Phantom related ( so probably not a Chutzpah problem ) but if I mock out my api service instead of injecting it, that seems to work alright:

```
describe( "New Channels Service", function() {
 var newChannelsService, newChannelsApi, $q, $rootScope, $filter;
        beforeEach(module("myapp.channels"));
        module(function($provide) { 
                newChannelsApi = { myFunction: function() {} );
                $provide('newChannelsApi', newChannelsApi);
        });
        beforeEach( inject(function (_newlChannelsService_, _newChannelsApi_,  _$q_, _$rootScope_, _$filter_) {
            $filter = _$filter_;
            $rootScope = _$rootScope_;
            $q = _$q_;
            newChannelsService = _newChannelsService_;
        }));

       it("doesn't matter what goes here because the runner will crash", function() {
            expect( true ).toBeTrue();
        }
}
```
Thanks for the assistance!
