### ISSUE TITLE
multi-file source isn't working for me

### ISSUE THREAD

**Issue by gregveres** [mmanela/chutzpah#555]
Hi

I have a problem where, when I try to run a test, I get a ReferenceError: Can't find variable: KnockoutCourt. This is one of my typescript classes. 

I think I am missing some high level knowledge about how to set this up. So please indulge me as I try to describe my setup from the top. 

I am trying to test a ViewModel class for a page that uses knockout. The page loads data from a WebService written in C#. I am using an excellent tool called typewriter that will turn C# model/view model definitions into typescript files. I then include them on the page and I have easy access to the webservice. 

What this does, is it creates a number of files though. So my file structure looks like this: (and this is the order that I include them on my html page)

ApiCourtGroupsViewModel.ts
ApiCourtsViewModel.ts
CourtGroupsController.ts

of course I include the .js files in the html file. 

I then include:
messenger.js (for page level alerts)
CourtGroups.ts

It is CourtGroups.ts that is my typescript viewmodel that I want to test. 

My first question:
Do I have to include "References" to the first three files (ApiCourtGroupsViewModel.ts, ApiCourtsViewModel.ts and CourtGroupsController.ts) in my Chutzpah.json file? 

Do I need to have CourtGroups.ts included in the reference section of the Chutzpah.json file?

Oh, these files also reference Knockout since a bunch of the variables are knockout observables. So do I need to include knockout in the reference section of my Chutzpah.json file? 

Each time I add a new file like CourtGroups.ts, it is going to have an accompanying few .ts files in this similar structure. Am I going to have to add all of these to the Chutzpah.json file each time I want to test this new typescript viewmodel file? 

I think I need to see the answer to these questions before I proceed with asking my next question. Because right now I have all of these in my Chutzpah.json file and I am getting this ReferenceError when I try to run a simple unit test (jasmine). It says it cant find a variable that is a class defined in ApiCourtsViewModel.ts.

BTW, all of these files are embedded in a namespace of Api.Courtbooking. I was wondering if that is screwing it up. All this works fine on the applications page, I am just coming back to it to setup unit testing. 

Here is what my current Chutzpah.json file looks like:

```
{
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "UseSourceMaps": true
  },
  "References": [
    { "Path": "../scripts/knockout-3.4.0.js", "IsTestFrameworkFile": true },
    { "Path": "../Scripts/App/CourtBooking/ApiCourtGroupsViewModel.ts" },
    { "Path": "../Scripts/App/CourtBooking/ApiCourtsViewModel.ts" },
    { "Path": "../Scripts/App/CourtBooking/CourtGroupsController.ts" },
    {
      "Path": "../Scripts/App/CourtBooking/CourtGroups.js"
    }
  ],
  "Tests": [
    {
      "Includes": [ "*/Scripts/*.ts" ],
      "Excludes": [ "*/Scripts/*.d.ts" ]
    }
  ],
  "CodeCoverageExecutionMode": "Always",
  "CodeCoverageIncludes": [
    "../Scripts/App/CourtGroups.*"
  ]
}


```

I am not sure if I got it right.

thanks
Greg

**Comment by gregveres** [comment]
Maybe it would help to show my unit test:

```
/// <reference path="../../../scripts/app/courtbooking/courtgroups.ts" />
/// <reference path="../typings/jasmine/jasmine.d.ts" />

describe("CourtGroupTests", (): void => {
    let model: Api.CourtBooking.CourtModel;

    beforeEach(() => {
        model = new Api.CourtBooking.CourtModel({
            CourtId: 1,
            Name: "Court 1",
            ShortName: "C1",
            OffsetMinutes: 20,
        });
    });

    it("constructor sets isEditing to false", (): void => {
        expect(model.isEditing()).toBeFalsy();     
    });
});

```

The files like CourtGroups.ts don't have any references at the top for my code, just for things like jquery and knockout. And Visual Studio and the compiler find the references just fine. 
I did have to put the reference at the top of the test file because it is in a different project in my solution file.

**Comment by gregveres** [comment]
Ok I made a little progress. I think my problem is probably with the way my code is structured rather than Chutzpah. However, can you please answer my questions about the Chutzpah config file above? I would like to know if I have to specify things like I have in the .json file or if there is someway that I can specify things in the .json file that new test files get picked up automatically and all the dependencies get figured out automatically. I can see the .json file getting very full and unwieldy.

Now for a quick explanation of what I changed to get this working. 

In my unit test, I was trying to test a class called Api.CourtBooking.CourtModel that extends Api.CourtBooking.KnockoutCourt. The browser was complaining that it didn't know what a KnockoutCourt was when it hit the definition of the CourtModel class. Specifically I defined the class like this:

`export class CourtModel extends KnockoutCourt`

since they were both in the same namespace, this worked. Well, it worked most of the time. Sometimes VS would go nuts and flag a million errors in my .ts file. I would quit VS and reload and the errors would go away. So I figured it was a bug in VS. 

But now I am wondering if I need to define the full name of KnockoutCourt like this:

`export class CourtModel extends Api.CourtBooking.KnockoutCourt`

When I did this, the unit test now compiles and runs properly in the browser. (after I specified all the framework files like jquery, knockout etc, and all the program .ts files as reference files). 

So at this point I am unstuck for now. 

Any suggestions would be very welcome.

**Comment by gregveres** [comment]
following up now that I have found my problem:

Please do respond to the original question about the .json config file. 

But for the problem I was having, I re-read this typescript docs page:
http://www.typescriptlang.org/docs/handbook/namespaces.html

and realized that I wasn't including the proper references to the other parts of my namespace. Since my namespace was split across multiple files, I really should have put /// reference path directives into any ts file that used parts of the namespace defined in those other files. Once I fixed that up, everything started working properly in the tests.

**Comment by mmanela** [comment]
For the file management you have a few options.

1. Use a AMD like system to manage dependencies for you
2. You reference comments (/// <reference ) to manage your graph (there is a setting to tell chutzpah to look for these
3. Add the required files to chutzpah.json (you can use wildcards if you want)

**Comment by mmanela** [comment]
Closing as I have not heard back in a long time. Please re-open if needed.

**Comment by gregveres** [comment]
Sorry for not getting back to you. I missed the email that you had responded. 

I have gone with listing all the files in the Chutzpah.json file. However, I am moving to RequireJS for my app so I will be moving to RequireJS / AMD soon.

**Comment by akanieski** [comment]
@mmanela 

> You reference comments (/// <reference ) to manage your graph (there is a setting to tell chutzpah to look for these

Where is this setting?

**Comment by mmanela** [comment]
On [this page](https://github.com/mmanela/chutzpah/wiki/references-setting) called **ExpandReferenceComments**
