### ISSUE TITLE
Tests not being discovered unless file edited.

### ISSUE THREAD

**Issue by ChocoMachine** [mmanela/chutzpah#557]
Hi, 

great work with chutzpah by the way, love it... :-)

We have an issue where tests stop being discovered by the test explorer in VS2015 U3. with TFS source control.

To force discovery we have to cause an edit in a test file (a space will do) and save. Then it detects, however we have a lot of files...
I was thinking maybe a force scan option on the context menu or something... ?

anyways apart from this, it's working great.

**Comment by ChocoMachine** [comment]
Actually could be caused by other plugins we have installed. not sure...

**Comment by mmanela** [comment]
Can you uninstall the other extension and see if it repros?
Can you share your chutzpah.json file?

**Comment by ChocoMachine** [comment]
I will disable all the extensions I can and report on the result. In the mean time here is our chutzpah.json:
`{
  "Framework": "jasmine",
  "References": [
    {
      "Path": "Scripts/jquery-2.1.3.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/kendo/kendo.all.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular-route.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/bootstrap.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular-ui/ui-bootstrap.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular-ui/ui-bootstrap-tpls.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular-animate.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular-cookies.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular-chosen.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/angular-mocks.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/jasmine/jasmine-jquery.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Scripts/underscore.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "startup.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "../SBS.Web/SbsApp",
      "Includes": [ "*.js" ]
    },
    {
      "Path": "SbsAppTests/baseTest.js",
      "IsTestFrameworkFile": true
    }
  ],
  "Tests": [
    {
      "Path": "SbsAppTests",
      "Includes": [ "*.js" ],
      "Excludes": [ "SbsAppTests/baseTest.js" ],
      "ExpandReferenceComments": false
    }
  ],
  "CodeCoverageExcludes": [ "*\\SbsAppTests\\*" ]
}`

**Comment by ChocoMachine** [comment]
I disabled as many extensions as I could and the effect did persist. However we can get around the issue by cleaning and then rebuilding the solution whilst the test explorer window closed.
