### ISSUE TITLE
Exception occurred while using ChutzpahAdapterSettings

### ISSUE THREAD

**Issue by ryanvgates** [mmanela/chutzpah#558]
I was following the instructions on the [wiki ](https://github.com/mmanela/chutzpah/wiki/Running-Unit-Tests-in-a-TFS-Build) to enable tracing for Chutzpah. When I run the build, I get the following error.

`An exception occurred while invoking executor 'executor://chutzpah-js/': An error occurred while initializing the settings provider named 'ChutzpahAdapterSettings'. Error: There is an error in XML document (4, 5).
There is an error in XML document (4, 5).
The string 'True' is not a valid Boolean value.`

It is similar to #443, but I am not getting an error about the headless browser phantomjs.exe. Where will the trace files be produced?

**Comment by mmanela** [comment]
Are you trying to run tests in VS or in a TFS build?

**Comment by ryanvgates** [comment]
@mmanela TFS build. Everything works great in VS when I right click and run the tests.

**Comment by ryanvgates** [comment]
@mmanela is there any way that I can simulate the process locally even if only for troubleshooting?

**Comment by ryanvgates** [comment]
@mmanela I was able to get beyond the error mentioned above by changing the following configuration from `True` to `true` so that it reads like the following.

    <?xml version="1.0" encoding="utf-8"?>
    <RunSettings>
        <ChutzpahAdapterSettings>
            <EnabledTracing>true</EnabledTracing>
        </ChutzpahAdapterSettings>
    </RunSettings>

Can you please update the wiki to reflect that this is the correct configuration? And then I'll close this issue.

**Comment by mmanela** [comment]
Thanks @ryanvgates , I updated the wiki. Also, you can enable tracing with just the chutzpah.json file now too. It will let you even choose where to put the trace file.

**Comment by ryanvgates** [comment]
@mmanela Thank you for updating it. I see what you mean about using [the chutzpah.json settings file](https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File). Thank you for pointing that out.
