### ISSUE TITLE
Chutzpah should allow debugging using PhantomJS instead of IE browser

### ISSUE THREAD

**Issue by junalmeida** [mmanela/chutzpah#560]
Its a must have to Run headless and debug using the same backend engine, in this case PhantomJS.

As a plus, be able to choose engine between Webkit PhamtomJS or headless Trident IE (IE without a window popping up).

**Comment by mmanela** [comment]
@junalmeida These are both great suggestions and I would love to get to them but I will not have any time in the near term. If you are interested I would work with you to contribute these changes :)

**Comment by mozts2005** [comment]
I think I can make debug of test work for many browsers, not just PhantomJS and IE. Like Chrome and Firefox and even Edge.  I no one else wants to do the work. I would like to.

**Comment by mmanela** [comment]
@mozts2005 I would love to see that :)

**Comment by mmanela** [comment]
@junalmeida  @mozts2005 I added support for [JsDom and Chrome](https://github.com/mmanela/chutzpah/wiki/Browser-Engines) in version 4.4. This is still a beta feature but feedback is welcome.

Please let me if it works for you

**Comment by ovirovkin** [comment]
@mmanela I tried Chrome on Windows 10, Visual Studio version: 15.7.4, but it doesn't work for me. I have specified `Engine` and `EngineOptions` with path to `chrome.exe`, but it still using IE to debug and execute tests. Hoping to make it work in chrome, so that I can use es6 syntax like `import` in chrome. If you need any help debugging this please let me know, it would be nice to have it working in Chrome.

**Comment by mmanela** [comment]
You should check the chutzpah.log from /trace command line flag. It will tell you if the chrome instance is not found

**Comment by ovirovkin** [comment]
Output: ``` chutzpah.console.exe Information: 0 : Time:16:58:02.9626973; Thread:1; Message:Chutzpah.json file found at C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\chutzpah.json given starting directory C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor
chutzpah.console.exe Information: 0 : Time:16:58:03.0237346; Thread:1; Message:Defaulting the RootPath to the drive root of the chutzpah.json file
chutzpah.console.exe Information: 0 : Time:16:58:03.0337359; Thread:1; Message:Chutzpah run started in mode Execution with parallelism set to 8
chutzpah.console.exe Information: 0 : Time:16:58:03.0407001; Thread:1; Message:Trying to build test context for C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js
chutzpah.console.exe Information: 0 : Time:16:58:03.0507006; Thread:1; Message:Building test context for C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js
chutzpah.console.exe Information: 0 : Time:16:58:03.0627341; Thread:1; Message:Test file c:\kneat\kneat.gx.web.app\javascript\kneatmodules\identifierincrementor\identifierincrementor.tests.js matched folder c:\kneat\kneat.gx.web.app\javascript\kneatmodules\identifierincrementor with includes *.tests.js and excludes  patterns from settings file
chutzpah.console.exe Information: 0 : Time:16:58:03.0717023; Thread:1; Message:Investigating reference file path '../../../../node_modules/should/should.js'
chutzpah.console.exe Information: 0 : Time:16:58:03.0757022; Thread:1; Message:Added file 'C:\Kneat\node_modules\should\should.js' to referenced files. Local: True, IncludeInTestHarness: True
chutzpah.console.exe Information: 0 : Time:16:58:03.0777154; Thread:1; Message:Processing referenced file 'C:\Kneat\node_modules\should\should.js' for expanded references
chutzpah.console.exe Information: 0 : Time:16:58:03.0937046; Thread:1; Message:Added framework dependency 'C:\Kneat\packages\Chutzpah.4.4.2\tools\ChutzpahTestHarnessFiles\mocha\mocha.js' to referenced files
chutzpah.console.exe Information: 0 : Time:16:58:03.0957032; Thread:1; Message:Added framework dependency 'C:\Kneat\packages\Chutzpah.4.4.2\tools\ChutzpahTestHarnessFiles\mocha\mocha.css' to referenced files
chutzpah.console.exe Information: 0 : Time:16:58:03.0977045; Thread:1; Message:Added framework dependency 'C:\Kneat\packages\Chutzpah.4.4.2\tools\ChutzpahTestHarnessFiles\chutzpah_boot.js' to referenced files
chutzpah.console.exe Information: 0 : Time:16:58:03.1017040; Thread:1; Message:Finished building test context for C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js
chutzpah.console.exe Information: 0 : Time:16:58:03.1347061; Thread:1; Message:Creating Web Server Host at path C:\ and port 59760
chutzpah.console.exe Information: 0 : Time:16:58:03.3887203; Thread:1; Message:Start test run for C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js in Execution mode
chutzpah.console.exe Information: 0 : Time:16:58:03.4027605; Thread:1; Message:Using builtin Test Harness from C:\Kneat\packages\Chutzpah.4.4.2\tools\ChutzpahTestHarnessFiles\mocha\mocha.html
chutzpah.console.exe Information: 0 : Time:16:58:03.4257242; Thread:1; Message:Invoking headless browser on test harness 'C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\_Chutzpah.e2aa50ef2f5f4bab6bc5cd8de8b5b3efccccf39d.test.html' for file 'C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js'
chutzpah.console.exe Information: 0 : Time:16:58:03.4367248; Thread:1; Message:Started headless browser: C:\Kneat\packages\Chutzpah.4.4.2\tools\Node\x64\node.exe with PID: 20016 using args: C:\Kneat\packages\Chutzpah.4.4.2\tools\ChutzpahJSRunners\Chrome\mochaRunner.js "http://localhost:59760/Kneat/Kneat.Gx.Web.App/JavaScript/KneatModules/IdentifierIncrementor/_Chutzpah.e2aa50ef2f5f4bab6bc5cd8de8b5b3efccccf39d.test.html" execution 10000 True False "C:\Kneat\node_modules\puppeteer\.local-chromium\win64-594312\chrome-win\chrome.exe" 
chutzpah.console.exe Information: 0 : Time:16:58:03.9477534; Thread:4; Message:Phantom Log - Using Chrome Install : C:\Kneat\node_modules\puppeteer\.local-chromium\win64-594312\chrome-win\chrome.exe
chutzpah.console.exe Information: 0 : Time:16:58:04.4577844; Thread:3; Message:Phantom Log - Resource Received: http://localhost:59760/Kneat/Kneat.Gx.Web.App/JavaScript/KneatModules/IdentifierIncrementor/_Chutzpah.e2aa50ef2f5f4bab6bc5cd8de8b5b3efccccf39d.test.html
chutzpah.console.exe Information: 0 : Time:16:58:04.4657818; Thread:5; Message:Phantom Log - isMochaLoaded
chutzpah.console.exe Information: 0 : Time:16:58:04.4867851; Thread:5; Message:Phantom Log - Resource Received: http://localhost:59760/Kneat/Kneat.Gx.Web.App/JavaScript/KneatModules/IdentifierIncrementor/IdentifierIncrementor.tests.js?sha=8d225d57ae8facab17778d4a5a12f1e4bc3cbc53
chutzpah.console.exe Information: 0 : Time:16:58:04.4897859; Thread:3; Message:Phantom Log - Resource Received: http://localhost:59760/__chutzpah__/mocha/mocha.css?sha=564143ed9c48e31f5066da8564b3e5842d71baca
chutzpah.console.exe Information: 0 : Time:16:58:04.4917870; Thread:3; Message:Phantom Log - Resource Received: http://localhost:59760/__chutzpah__/chutzpah_boot.js?sha=f14c307536e4a640962b815797388690fc596588
chutzpah.console.exe Information: 0 : Time:16:58:04.4947866; Thread:17; Message:Phantom Log - isMochaLoaded
chutzpah.console.exe Information: 0 : Time:16:58:04.4968021; Thread:17; Message:Phantom Log - Resource Received: http://localhost:59760/Kneat/node_modules/should/should.js?sha=77529663f0eb3f431a50acbcc6aa81cc4f355b30
chutzpah.console.exe Information: 0 : Time:16:58:04.4977850; Thread:17; Message:Phantom Log - Resource Received: http://localhost:59760/__chutzpah__/mocha/mocha.js?sha=e38d5343621c61202e2edf97d80f3539f06f69f1
chutzpah.console.exe Information: 0 : Time:16:58:04.4997864; Thread:10; Message:Phantom Log - isMochaLoaded
chutzpah.console.exe Error: 0 : Time:16:58:04.5868057; Thread:10; Message:Error received from Phantom SyntaxError: Unexpected identifier
chutzpah.console.exe Information: 0 : Time:16:58:04.5887908; Thread:15; Message:Phantom Log - onInitialized
chutzpah.console.exe Information: 0 : Time:16:58:04.5918042; Thread:15; Message:Phantom Log - isMochaLoaded
chutzpah.console.exe Information: 0 : Time:16:58:04.5937908; Thread:15; Message:Phantom Log - onMochaLoaded
chutzpah.console.exe Information: 0 : Time:16:58:04.5967929; Thread:15; Message:Phantom Log - onPageLoaded
chutzpah.console.exe Information: 0 : Time:16:58:04.5987929; Thread:15; Message:Phantom Log - Starting Mocha ...
chutzpah.console.exe Information: 0 : Time:16:58:04.7598002; Thread:1; Message:Finished reading stream from test file 'C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js'
chutzpah.console.exe Information: 0 : Time:16:58:04.7648002; Thread:1; Message:Ended headless browser: C:\Kneat\packages\Chutzpah.4.4.2\tools\Node\x64\node.exe with PID: 20016 using args: C:\Kneat\packages\Chutzpah.4.4.2\tools\ChutzpahJSRunners\Chrome\mochaRunner.js "http://localhost:59760/Kneat/Kneat.Gx.Web.App/JavaScript/KneatModules/IdentifierIncrementor/_Chutzpah.e2aa50ef2f5f4bab6bc5cd8de8b5b3efccccf39d.test.html" execution 10000 True False "C:\Kneat\node_modules\puppeteer\.local-chromium\win64-594312\chrome-win\chrome.exe" 
chutzpah.console.exe Information: 0 : Time:16:58:04.7688012; Thread:1; Message:Test harness 'C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\_Chutzpah.e2aa50ef2f5f4bab6bc5cd8de8b5b3efccccf39d.test.html' for file 'C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js' finished with 0 passed, 0 failed and 1 errors
chutzpah.console.exe Information: 0 : Time:16:58:04.7708027; Thread:1; Message:Finished running headless browser on test harness 'C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\_Chutzpah.e2aa50ef2f5f4bab6bc5cd8de8b5b3efccccf39d.test.html' for file 'C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js'
chutzpah.console.exe Information: 0 : Time:16:58:04.7728015; Thread:1; Message:Finished test run for C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js in Execution mode
chutzpah.console.exe Information: 0 : Time:16:58:04.7738041; Thread:1; Message:Cleaning up test context for C:\Kneat\Kneat.Gx.Web.App\JavaScript\KneatModules\IdentifierIncrementor\IdentifierIncrementor.tests.js
chutzpah.console.exe Information: 0 : Time:16:58:04.7778023; Thread:1; Message:Tearing down Web Server Host at path C:\ and port 59760
chutzpah.console.exe Information: 0 : Time:16:58:04.8108025; Thread:1; Message:Chutzpah run finished with 0 passed, 0 failed and 1 errors
chutzpah.console.exe Information: 0 : Time:16:58:04.8138036; Thread:1; Message:Chutzpah.json file cache cleared
 ```

**Comment by mmanela** [comment]
Are you sure its using Phantom? The output saying phantom is actually a logging error.

**Comment by ovirovkin** [comment]
Yes, it's configured to use Chrome in config, but it appears that it still used Phantom for some reason.

**Comment by mmanela** [comment]
Besides the log message saying phantom (which is just a bug) what tells you it is using phantom?

**Comment by ovirovkin** [comment]
I was expecting ES6 import statement `import {detectCats} from "kittydar.js";` to work, but it's failing with syntax error (unfortunately, I can attach exact error only tomorrow), it doesn't recognize import statement. Also when running tests in debug mode, it still uses IE browser. Shall it use Chrome when debugging too?

**Comment by mmanela** [comment]
Debugging from the ide? That only uses IE. 
But besides that it will honor your engine. Can you give me a small repro for not running in chrome ?

**Comment by ovirovkin** [comment]
I am using `Mocha` and `Should` to run tests and ES6 syntax in tests and in javascript files. Hopefully, you will be able to reproduce that with this example: `test` => https://github.com/ruanyf/mocha-demos/blob/master/demo04/test/add.test.js `js` => https://github.com/ruanyf/mocha-demos/blob/master/demo04/src/add.js

**Comment by mmanela** [comment]
Chutzpah is using the LTS version of Node and that syntax is not support in it.

**Comment by ovirovkin** [comment]
@mmanela sorry for a long delay and thank you for your help, if `import` is not supported in Node LTS, should I be able to use `require` instead? It for some reason doesn't work for me, error: ``` chutzpah.console.exe Information: 0 : Time:11:04:15.4865443; Thread:11; Message:Phantom Log - jsdomError: Error: Uncaught [ReferenceError: require is not defined]
chutzpah.console.exe Error: 0 : Time:11:04:15.5505460; Thread:11; Message:Error received from Phantom Uncaught [ReferenceError: require is not defined] ```

**Comment by ovirovkin** [comment]
@mmanela if you will have a chance to look at the question above, i will appreciate that, thank you :)

**Comment by mmanela** [comment]
Chutzpah supports what JsDom or Chromium supports here. Remember, Chutzpah is not Node. Chutzpah is just using node to run chromium or jsdom.
