### ISSUE TITLE
Timeout waiting for Internet Explorer child process to start.

### ISSUE THREAD

**Issue by spottedmahn** [mmanela/chutzpah#561]
When I try to debug tests I get 'Timeout waiting for Internet Explorer child process to start.'

This has worked in the past.  I am unable to run them just not debug them.  Any ideas or things I can try?

**Comment by jebrosac** [comment]
I'm also suffering from this issue. Started after the Windows 10 update (now on 10.0.14393 build 14393) but also updated Visual Studio 2015 at the same time to Version 14.0.25431.01 Update 3.

**Comment by spottedmahn** [comment]
I was able to fix my issue.  I switched my tests to run under X64 for another project.

VS2015 -> Menu Bar -> Test -> Test Settings -> Default Processor Architecture

**Comment by jebrosac** [comment]
Thanks @spottedmahn  changing mine to x86 has made the debug start working (it was set to x64). It now launches the browser ok and runs the tests but if I just choose to run the tests I get a lot of reference errors where it basically seems to not be picking up the referenced files from the chutzpah.json settings.  This all works fine when I use debug

**Comment by mmanela** [comment]
@jebrosac So just running tests gives you errors? What are the errors, can you open a new issue.

And @spottedmahn Thanks for figuring it out. that is good to know
