### ISSUE TITLE
Running test fails with JS referenced errors

### ISSUE THREAD

**Issue by jebrosac** [mmanela/chutzpah#562]
As requested from #561- When running the tests from either within visual studio or from the dos prompt they fail with JS reference errors.  The referenced errors indicate that the test is failing to pick up the files specified in the references section of the chutzpah.json file.  Running the test generates a .html file and if this is browsed independently all the tests successfully run.  Also using the debug option from the VS test runner results in the tests successfully passing!  I've compared the html generated by a debug run and a normal run and they are the same.  I've attached the chutzpah log file from a failing run. And the output from the cmd window with the failures.
[testfailoutput.txt](https://github.com/mmanela/chutzpah/files/519226/testfailoutput.txt)

[chutzpah log.zip](https://github.com/mmanela/chutzpah/files/519183/chutzpah.log.zip)

**Comment by mmanela** [comment]
Can you give me a repro that I can run locally?

**Comment by mmanela** [comment]
Have not heard back, closing for now but will re-open when repro given
