### ISSUE TITLE
FormData support

### ISSUE THREAD

**Issue by alexbryukhanova** [mmanela/chutzpah#563]
Are there plans to support FormData objects in the future? The new version of Phantom.JS (2.5) will support it after the release (https://github.com/ariya/phantomjs/issues/14464) so I'm wondering if there's been any thoughts on the timeline of incorporating this into Chutzpah.

**Comment by mmanela** [comment]
Once PhantomJS supports it I will upgrade to it. Is there other work Chutzpah would need to do besdies that?
