### ISSUE TITLE
What's the version of integrated Mocha?

### ISSUE THREAD

**Issue by thomasqu** [mmanela/chutzpah#564]
As the title, I am trying to find some libraries to use Mocha in Chutzpah, and the version info of Mocha is very helpful.

Thanks!

**Comment by mmanela** [comment]
Mocha comes package with a version of Mocha which in the last public release was 2.4.5. In the next release coming soon it will be 3.1.2.

**Comment by thomasqu** [comment]
Looking forward to the new release. Thanks!

**Comment by tansongyang** [comment]
In the future, how do we find this information ourselves? Can it be published on the Wiki somewhere?

**Comment by mmanela** [comment]
That is a good idea. I will get that set up soon.
