### ISSUE TITLE
Unknown Error occurs while running tests on server

### ISSUE THREAD

**Issue by 9-9-0** [mmanela/chutzpah#565]
Hi there,

I'm trying to run Chutzpah 4.2.3 with Microsoft's VSTest.console.exe through their Visual Studio Team Service's build manager.

Every test errors out with the following error:
https://s14.postimg.org/g4opp6ajl/Chutzpah_Errors.png

I've looked at related issues and it seems like it was due to bugs within VS' testing framework itself. I believe the version I'm running is the latest. Older versions also result in these errors.

I can post the chutzpah settings if needed. Currently they specify that code coverage should be enabled, the references, and the output file should be a LCOV.

Thanks!

**Comment by mmanela** [comment]
Does it also error out if you run directly using the chutzpah.console.exe?
Does it error if you turn off code coverage?

**Comment by 9-9-0** [comment]
Does not error out when I turn off code coverage. As a note, when I had code coverage turned on while including a reference to Angular.js it threw this: http://aidanreel.me/2014/03/angularjs-jasmine-chutzpah/.After replacing the reference to Angular.js with Angular.min.js, the error mentioned in the OP occurred. Don't know if they're related in some way.

I will get back to you Monday on whether or not the errors occur from using chutzpah.console.exe to test on the build machine. As a note, running the tests locally through VS with Chutzpah ran clean.

**Comment by 9-9-0** [comment]
Hey mmanela,

I can confirm that these errors do not occur when calling chutzpah.console.exe from a script (which is a fine alternative for now).

They have only occurred when the VS testing tool was run with the chutzpah custom adapters.

**Comment by mmanela** [comment]
Can you provide me with a repro I can run?
