### ISSUE TITLE
tfs build 2015 agent getting error when chutzpah test adapter references includes .js in path name 

### ISSUE THREAD

**Issue by RussKahler** [mmanela/chutzpah#567]
Our solution which includes a number of JS test projects using the chutzpah adapter for tests.   Everything works fine in VS but the same tests on our build server are resulting in errors.   Here is the error: 

Error: Error: Error opening C:/Builds/vsAgent/1/s/BaseApp/Script.Core/wwwroot/lib/bower/postal/lib/postal.js.js: The system cannot find the path specified.
While Running:C:\Builds\vsAgent\1\s\BaseApp\Tests.JS.Script.Core\scripts\core\definitions\controls\html-text-editor-definition.tests.js

Notice the path to postal.js in our chutzpah.json file is:
    "Path": "../../Script.Core/wwwroot/lib/bower/postal.js/lib/postal.js"

It appears the adapter is removing the .js in the path (folder) and reading an additional one at the end of the file.

I see a commit on 9/27/2016 don't know if that is the same issue.   How do we get a build that includes this or will there be another release out soon that would include this?

**Comment by mmanela** [comment]
This issue is fixed in the commit you mention, I am tying to get the time to wrap up a release and push it public. Hopefully within 2 weeks

**Comment by RussKahler** [comment]
Thanks



Sent from my U.S. Cellular® Smartphone


-------- Original message --------
