### ISSUE TITLE
Jasmine, RequireJs, Knockout, chutzpah.json - setting "EnableCodeCoverage": true causes "Open in browser" to show spec fails

### ISSUE THREAD

**Issue by danjackknife** [mmanela/chutzpah#570]
Hi Matthew,

I'm loving _Chutzpah_ right now! It's so nice to test run Jasmine tests with it. Aside, from the pros, it seems the current version, 4.2.4, has a bug with setting the _EnableCodeCoverage_ to true in the _chutzpah.json_.

**EnableCodeCoverage = false**
With _EnableCodeCoverage_ set as false, I click on _Run JS Tests_, my tests results show they passed:-

![image](https://cloud.githubusercontent.com/assets/12166958/19933652/0abaa334-a10c-11e6-9af8-6a13301113c2.png)

When I click on Open in browser, the spec runner also shows passed:-

![image](https://cloud.githubusercontent.com/assets/12166958/19933723/47238eda-a10c-11e6-8e17-1c04ccabd205.png)

**EnableCodeCoverage = true**
With _EnableCodeCoverage_ set as false, I click on _Run JS Tests_, my tests results show they passed:-

![image](https://cloud.githubusercontent.com/assets/12166958/19933652/0abaa334-a10c-11e6-9af8-6a13301113c2.png)

Plus the code coverage page:-

![image](https://cloud.githubusercontent.com/assets/12166958/19933840/a7ee860c-a10c-11e6-9ea7-0a1b693b1a2d.png)

When I click on Open in browser, the spec runner shows failed:-

![image](https://cloud.githubusercontent.com/assets/12166958/19933869/bddeb824-a10c-11e6-95b8-956c238f0d7d.png)

i'm presuming, the spec runner harness page is the issue? Or should I set something in the  _chutzpah.json_? 

Many thanks,

danjackknife

**Comment by mmanela** [comment]
First off EnableCodeCoverage is a deprecated property (it was always a bad name). The correct property is

``` "CodeCoverageExecutionMode": "Manual|Always|Never", ```

Most people set to manual which means to run coverage only when you ask and Always means run regardless of if you ask for coverage or not.

Can you try that with Manual and see how it works for you?

**Comment by danjackknife** [comment]
Hi @mmanela ,

Thank you for your response. I've tried both _Manual_ and _Always_ and it seems only _Manual_ works...

**Comment by mmanela** [comment]
Can you provide a repro so I can run locally?

**Comment by mmanela** [comment]
Have not heard back. Closing for now and can re-open once repro ggiven
