### ISSUE TITLE
Error: Line 42: Unexpected token (

### ISSUE THREAD

**Issue by silentbobbert** [mmanela/chutzpah#571]
Hi @mmanela 

I built a custom VSTS build step based on Chutzpah. During our automated builds I wanted not only to run the Jasmine tests we had, but also establish the code coverage and fail a build if coverage drops below a threshold set by the team.

This was working for a few weeks. We are using the /coverage flag on the command line.

Now, even in VS on a dev machine using the Chutzpah plugins we see lots of timeouts. Increasing the time out to"TestFileTimeout": 200000 in the chutzpah.json file does not improve this.

I checked out the git repo for Chutzpah to see if I could see what was going wrong.

I thought I tracked it down to blanket_jasmine_v2.js ~ line 5473

var timeout = _blanket.options("timeout") || 3000;

I tried overriding this and manually setting the timeout to 200000 also. 

var timeout = _blanket.options("timeout") || 3000;
timeout = 200000;

The error message being reported was being generated just beneath by

`throw new Error("error (timeout=" + timeout + ") loading source script: " + options.url);`

But the timeout was reported as 180, not 200000 or 3000. I might be getting my timeouts muddled up, so please bear with me.

If I turn coverage off, everything works again. It doesn't seem intermittent, every test run now has timeout issues. This used to work just fine on my project so I am not ruling out a problem in either our JS or our Jasmine tests. Line 42: Unexpected token (

I don't know which file it it referring to, so its hard to figure it out.

Any ideas?

Cheers,
Ian

**Comment by mmanela** [comment]
That is odd. I would assume upping the timeout would work but it seems to not matter in this case. Where are you editing this timeout variable?

BTW: I am about to commit a change to let you configure that variable in the chutzpah.json file.

**Comment by silentbobbert** [comment]
Thanks for the response. I tried setting in the chutzpah.json file which is in the root of the path I specified for the tests. I then tracked down the settings in the blanket_jasmine_v2.js file which is in your tools folder I believe and modified it directly. It was a bit hacky but I just wanted to see if it had a positive effect or not. 

Any idea if the error message about the "(" on line 42 could refer to one of our code files or our tests?

**Comment by silentbobbert** [comment]
I tracked down the file causing unexpected token ( on line 42. It was in one of our JS tests, and the result of a merge conflict resolved incorrectly.

![image](https://cloud.githubusercontent.com/assets/3257988/20350002/ceb60988-ac04-11e6-84ab-1a0494e4c09e.png)

Oddly enough, none of the test runners picks this up! Not VS Test, ReSharper Test runner or Chutzpah. When the tests are just simply run they all seem to run OK with no complaints! Only when turning coverage on does the problem manifest itself.
