### ISSUE TITLE
No tests appear in test explorer

### ISSUE THREAD

**Issue by FilippoPolo** [mmanela/chutzpah#572]
Hi all,

I'm trying to use Chutzpah to run some Typescript unit tests in VS2015, and I'm encountering several problems. The most severe is as follows:
![ct](https://cloud.githubusercontent.com/assets/9450467/20302976/29670c7c-ab21-11e6-8d13-479d266f1480.png)
No tests appear in test explorer. There is a timeout error, but the test is trivial and should take no time at all to complete. If I run the test in an HTML page, it runs correctly. If I run the test from chutzpah.console, it runs correctly. I have installed Chutzpah both as a VS extension, and as a NuGet package within the project.

The log file for vstest.discoveryengine.x86 follows.

[vstest.discoveryengine.x86.TpTrace.txt](https://github.com/mmanela/chutzpah/files/591720/vstest.discoveryengine.x86.TpTrace.txt)

**Comment by mmanela** [comment]
I don't see a chutzpah.json file there so Chutzpah will not know what to do with a TS file. Please look at this sample to help: https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation/ExternalCompile

**Comment by FilippoPolo** [comment]
Thanks, that seems to work. I expected it to ignore the .TS file altogether, and just find the test in the generated .JS file. Why is this not the case? Is it because it only looks at files that are part of the project?

**Comment by mmanela** [comment]
Chutzpah needs to know where to look for those generated files. That is the the compile configuration tells it.
