### ISSUE TITLE
Runing via console coverage file is generated in cwd

### ISSUE THREAD

**Issue by JuliusSenkus** [mmanela/chutzpah#573]
Actual: While running tests via console with coverage html file set to "coverage.html", I get two coverage files: "coverage.html" and "_Chutzpah.coverage.html".
Expected: If option "coveragehtml" is used only one coverage file should be generated to specified path.

Attached example how to reproduce.
[test.zip](https://github.com/mmanela/chutzpah/files/594592/test.zip)

**Comment by mmanela** [comment]
Thanks, I removed the default one that Chutzpah generates since that is a relic of before I had the transformers.
