### ISSUE TITLE
No coverage generated using SystemJS + import statements

### ISSUE THREAD

**Issue by devedse** [mmanela/chutzpah#576]
I've currently got a solution setup using SystemJS and TypeScript 2.0.x.

I have written my tests in the following format:

```
import { Core } from '../blah/file1';
describe('Test123',
    () => {
        describe('function getConfigurationValue',
            () => {
            });
    });
```

This all works great, except the code coverage part.

After doing some JavaScript debugging it seems that Blanket only supports RequireJS. (See line 5660-5688 in the following file:
https://github.com/mmanela/chutzpah/blob/master/Chutzpah/TestFiles/Coverage/blanket_jasmine_v2.js)

Next to that, it also seems that SystemJS is being loaded too late. When I look at the generated HTML file in the browser, SystemJS is being loaded after all the Chutzpah/Blanket js files. I think this might also need to be resolved on the Chutzpah part.
(SystemJS is being included as the first js file in my References in the chutzpah.json file)

**Comment by mmanela** [comment]
@devedse Yes, it is a known issue that Blanket does not support anything but require. I think Chutzpah needs to move away from Blanket but that is a large change so for now coverage won't work with SystemJS.

But is the later loading of SystemJS causing a separate issue for you?

**Comment by devedse** [comment]
Thanks for the fast response :). Too bad that that's not support for now.

Regarding your second question, no, that was the main thing I was running into when trying to do some internal debugging of the Chutzpah/Blanket JavaScript.

**Comment by gregveres** [comment]
There is also #503 that means your code coverage is going to be logged against the JS files, not the TS files. I can't tell if you got far enough that this is the issue. #503 lists some proposed changes that would potentially fix the issue.
