### ISSUE TITLE
how to define requireJS paths for 3rd party libraries?

### ISSUE THREAD

**Issue by gregveres** [mmanela/chutzpah#577]
Hi @mmanela 

I just finished moving my source over to use requireJS, so now I have to move my tests to use requireJS too. I got this working in a simple sample project first and I have Chutzpah performing brilliantly there. 

However, in my real project I quickly ran into a snag. How do I define the path to the third party  libraries that my code is "requiring"? 

For instance, in my typescript code that requires moment.js, I would do this at the top of the file:

import moment = require('moment');

Then in a js file I configure requireJS to know where moment is located: 
```
requirejs.config({
    baseUrl: 'Scripts',
    paths: {
        "jquery": "libs/jquery-3.1.1",
        "moment": "libs/moment",
    },
});
```

I don't see anything in the documentation of where to put this type of configuration for Chutzpah. And if I define a JS file with this requirejs.config in it, then everything breaks. 

Right now I am working around it by using the References section of the Chutzpah.json file:

```
  "References": [
    {
      "Path": "../squashspider/scripts/jquery-1.10.2.js",
      "IsTestFrameworkFile": true
    },
```

But that is not ideal because this kills my ability to ensure that I am requiring the right package dependencies in my code. 

Is there a way to inject these requireJS path definitions?

Thanks
Greg

**Comment by mmanela** [comment]
Using a require.js config us the right approach. We should investigate why
"everything broke". What happened? Did you configure the same base URL in
chutzpah?

**Comment by gregveres** [comment]
Ah ok. I will go back and do a proper investigation of why it broke then. When it broke, I assumed that Chutzpah was using the configuration and I overwrote it with my stuff. 

Now that i know that is the right way to go, I will go back and investigate it deeper. 

Thanks for getting back so quickly. Oh and 4.3 looks very interesting. I am going to have to check it out as soon as I get this task done. The jacoco.xml output to integrate with Visual Studio team services should be very handy.

**Comment by gregveres** [comment]
HI @mmanela 

You were correct. By defining a requireConfig.js and putting requireJS's configuration in that file and including it after including requireJS, everything works. I must have had the BaseURL set to something different when I first tried it. 

I now have finished transitioning to requireJS and everything is working great. The only outstanding issue is code coverage because I am using TS and there is an open issue that code coverage using requireJS doesn't load the map files. I am going to take a look at the original set of changes that were posted for this and see if I can provide you with a cleaned up PR. You had asked the original author to do it but I guess it didn't get done. 

Thanks for the great tool. 
Greg

**Comment by mmanela** [comment]
Sounds great 😀
