### ISSUE TITLE
Global Error

### ISSUE THREAD

**Issue by dedogs** [mmanela/chutzpah#578]
Something changed with Test Runner 4.3.1. Visula Studio 2015 or 2013. Qunit. Running simple test code below will throw a Global Error, and specifying jquery.3.1.1 is the file where error was thrown. Playing with finding a reason, I noticed removing QUnit.start() solved where now all tests pass with no Global Error. 

This had worked previously, but I must have updated. I don't understand why all test pass, cause I'm setting QUnit.config.autostart = false, so nothing should be tested until QUnit.start().
```
/// <reference path="../Application/Libraries/jquery-3.1.1.min.js" />
QUnit.config.autostart = false;

QUnit.module("Group is of type", {
    beforeEach: function () {
    },
    afterEach: function () {
    }
});

$(function () {
    QUnit.test("Test Message", function (assert) {
        assert.ok(true, "assertMessage");
    })
    QUnit.start();
})
```

**Comment by mmanela** [comment]
@dedogs What version did you update from?

**Comment by dedogs** [comment]
I believe that it wasn't an update. I just figured something had to change, because of the global error that I'm now receiving magically appeared. I was surprised noticing the error. Before all tests passed, and still all tests pass except a global failure test failing is thrown when running tests in browser. 

When removing QUnit.start() no global error failure occurs.
Versions:
IE11
Test Runner 4.3.1
Visual Studio 2015 or 2013 (global error happens in both versions)
jquery.3.1.1

Thank you,
Kirk deDoes

**Comment by dedogs** [comment]
If you can successfully run the code that I supplied above, then it  must be something on my end. I guess I will look at it more closely, however I'm need to think on where to start.

Thank you,
Kirk deDoes

**Comment by mmanela** [comment]
If you want to delay when Chutzpah starts to run please use the built in Chutzpah functions for this. I added these recently to address this problem (however, in most cases you shouldn't need this and just let Chutzpah run normally and not use Qunit.autoStart):

```
/// <reference path="jquery-3.1.1.min.js" />


window.chutzpah.preventAutoStart();

QUnit.module("Group is of type", {
    beforeEach: function () {
    },
    afterEach: function () {
    }
});

$(function () {
    QUnit.test("Test Message", function (assert) {
        assert.ok(true, "assertMessage");
    })
    window.chutzpah.start();
})
```

See [this page](https://github.com/mmanela/chutzpah/wiki/Controlling-when-Chutzpah-runs)

**Comment by mmanela** [comment]
I have no heard back. Closing for now, please re-open if needed
