### ISSUE TITLE
Visual Studio 2017 RC support

### ISSUE THREAD

**Issue by Valchris** [mmanela/chutzpah#579]
I opened a VS 2015 project in the new VS 2017 RC and while the project ran + C# tests executed the JS tests seem to be missing. Is there a scheduled timeline for VS 2017 to have Chutzpah support?

Also VS 2017 has a "Live unit testing" feature that seems pretty awesome, is there a roadmap for JS tests to also be available. (Ref: https://blogs.msdn.microsoft.com/visualstudio/2016/11/18/live-unit-testing-visual-studio-2017-rc/)

**Comment by mmanela** [comment]
Chutzpah works  in VS 2017 as of version 4.3. Are you sure your chutzpah version got updated?

And the live unit testing feature does not cooperate with file based editors like Chutzpah unfortunately. I plan to follow up with the team who built it to see if there are options to add in the future.
