### ISSUE TITLE
Code Coverage Function Declaration not covered

### ISSUE THREAD

**Issue by pittmaca** [mmanela/chutzpah#580]
I am trying to obtain 100% code coverage, but am having an issue with coverage on the function declaration when declaring the function as a member variable to hide the implementation of the function.  I would like to follow industry best practices as well as obtain 100% coverage.  Are there any suggestions on how to accomplish this?

![image](https://cloud.githubusercontent.com/assets/11183493/20891424/89cc7108-bad8-11e6-8860-76b5e6e6863b.png)

**Comment by mmanela** [comment]
Unfortunately, Chutzpah makes use of Blanket.js (another library) and is subject to its output here. I am planning in the future of switching libraries to one that is better and more actively maintained but for now we are subject to the good and the bad of that library and what it reports for coverage.

**Comment by devkeydet** [comment]
Any news on this front?

**Comment by mmanela** [comment]
Sorry but no. This would be a big effort and I don't have the time to investigate this as of now.
