### ISSUE TITLE
Test Discovery with webpack generated test.bundle.js

### ISSUE THREAD

**Issue by jekelhart** [mmanela/chutzpah#582]
Hello,

i use webpack to generate a bundled test.bundle.js file. I want to use this test.bundle.js with chutzpah.

My chutzpah.json:
```
{
  "Framework": "mocha",
  "Compile": {
    "Mode": "External"
  },
  "Tests": [
    { "Path": "tests/test.bundle.js" }
  ]
}
```

After i run my gulp task to generate the bundle, no tests are discoverd.
If I open test.bundle.js and simply save the file, the tests get discoverd.

Can anyone please help? :)

**Comment by mmanela** [comment]
Please take a look at [this sample](https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation/TypeScriptToSingleFile) which is the closet thing I have to what you are doing. It shows configuration Chutzpah to map compilation of TypeScript files to a single out file.

Let me know if you have questions after looking at that.
