### ISSUE TITLE
FrameworkVersion: Add support for choosing QUnit version

### ISSUE THREAD

**Issue by leeran88** [mmanela/chutzpah#583]
Hi,
Is there any plan to add support for QUnit versions to the FrameworkVersion setting (in the chutzpah.json file)?
I encountered this need lately... How difficult this should be to implement? Maybe I can help with this.

**Comment by mmanela** [comment]
So it wouldn't be too difficult to add, the only catch is if that version of QUnit changed their reporting api (which ideally is not often) it could break Chutzpah. But as long as we document that the one Chutzpah ships with is officially supported but you can grab any other then it sounds fine

**Comment by leeran88** [comment]
Great, thanks for the response.
This ability is kinda important to me, so I'm thinking about start working on this..
Is it cool?

**Comment by mmanela** [comment]
@leeran88 Did you ever start work on this?
