### ISSUE TITLE
VSTS build error problem with references

### ISSUE THREAD

**Issue by bartoszbr** [mmanela/chutzpah#584]
I configured VSTS build to run tests, but I had problem with references to js files.

chuzpah.json (F:\vsts-build-02-02\_work\58\s\01-Applications\MyAppName\UnitTests\MyAppName.JSUnitTests\chuzpah.json)

```
{
 "RootReferencePathMode": "SettingsFileDirectory",
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": false,
  "References": [
    ...
    {
      "Path": "../../MyAppName/UI",
      "Includes": [
        "*/*.js"
      ]
    }
  ],
  "Tests": [
    {
      "Path": "Tests"
    }
  ]
}
```

And I got this error for every my tests:

> 
> Error: Error: Error opening F:/vsts-build-02-02/_work/58/s/01-Applications/MyAppName/UnitTests/MyAppName.JSUnitTests/configuration.manager.config.module.js: No such file or directory
> While Running:F:\vsts-build-02-02\_work\58\s\01-Applications\MyAppName\UnitTests\MyAppName.JSUnitTests\Tests\ConfigurationManager\configuration.manager.config.module.spec.js
> 

File which is needed to run test is in location:
F:/vsts-build-02-02/_work/58/s/01-Applications/MyAppName/MyAppName/UI/ConfigurationManager/configuration.manager.config.module.js

When I run tests with the same configuration from Visual Studio 2015 everything works fine, problem is with VSTS build.
It looks like VSTS wants to have references to libraries in the same catalog where is chutzpah.json file, but in reference definitions I typed "../../MyAppName/UI" and RootReferencePathMode is set to SettingsFileDirectory.

**Comment by mmanela** [comment]
Are you sure your folder structure in the build output directory is the same as locally? Typically, this error occurs when they are not the same

**Comment by bartoszbr** [comment]
I have checked it by adding PowerShell script to my build configuration and output directory are the same as locally. Proof:

> 2017-01-09T14:18:04.3573737Z     Directory: F:\vsts-build-01-01\_work\77\s\01-Applications\MyAppName\MyAppName\UI\Configur
2017-01-09T14:18:04.3573737Z     ationManager
2017-01-09T14:18:04.3573737Z 
2017-01-09T14:18:04.3573737Z 
2017-01-09T14:18:04.3573737Z Mode                LastWriteTime     Length Name                                                                      
2017-01-09T14:18:04.3573737Z ----                -------------     ------ ----                                                                      
2017-01-09T14:18:04.3573737Z d----          1/9/2017   2:09 PM            Create                                                                    
2017-01-09T14:18:04.3573737Z d----          1/9/2017   2:09 PM            List                                                                      
2017-01-09T14:18:04.3573737Z -a---          1/9/2017   2:09 PM       1098 configuration.manager.config.module.js                                    
2017-01-09T14:18:04.3573737Z -a---          1/9/2017   2:09 PM        948 configuration.manager.css                                                 
2017-01-09T14:18:04.3573737Z -a---          1/9/2017   2:09 PM        367 configuration.manager.events.module.js                                    
2017-01-09T14:18:04.3573737Z -a---          1/9/2017   2:09 PM       2237 configuration.manager.module.js                                           
2017-01-09T14:18:04.3573737Z -a---          1/9/2017   2:09 PM       2682 configuration.manager.service.module.js                                   
2017-01-09T14:18:04.3573737Z -a---          1/9/2017   2:09 PM        869 configuration.manager.view.model.module.js

**Comment by bartoszbr** [comment]
Inspired by this article: http://newsweb.se/how-to-configure-chutzpah-paths-to-find-the-files-in-a-different-project-than-your-test-project/
I changed path in chutzpah.json to direct file, like this:

>     {
>       "Path": "../../MyAppName/UI/ConfigurationManager/Create/upload.configuration.config.module.js"
>     },

And again it works locally, but on VSTS build test fails.
I looked at locations after build and in my opinion everything should be ok, look:

chutzpah.json file:
> F:\vsts-build-01-02\_work\77\s\01-Applications\MyAppName\UnitTests\MyAppName.JSUnitTests\chutzpah.json 
Test file:
> F:\vsts-build-01-02\_work\77\s\01-Applications\MyAppName\UnitTests\MyAppName.JSUnitTests\Tests\ConfigurationUpload\upload.configuration.config.module.spec.js 
Referenced file:
> F:\vsts-build-01-02\_work\77\s\01-Applications\MyAppName\MyAppName\UI\ConfigurationManager\Create\upload.configuration.config.module.js 

And my local directory looks the same:
> C:\GIT\ProjectName\01-Applications\MyAppName\MyAppName\UI\ConfigurationManager\Create\upload.configuration.config.module.js
> C:\GIT\ProjectName\01-Applications\MyAppName\UnitTests\MyAppName.JSUnitTests\Tests\ConfigurationUpload\upload.configuration.config.module.spec.js
> C:\GIT\ProjectName\01-Applications\MyAppName\UnitTests\MyAppName.JSUnitTests\chutzpah.json  
>

**Comment by mmanela** [comment]
Can you turn on [chutzpah tracing ](https://github.com/mmanela/chutzpah/wiki/Chutzpah.json-Settings-File)and compare the trace files from where it works and where it doesnt?

**Comment by bartoszbr** [comment]
Thanks for reply. I turned on chutzpah tracing and I have problem with interprate it. Logs from build machine:

> 2017-01-16T11:34:46.0707713Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:26.1326680; Thread:8; Message:Phantom Log - Resource Recieved: file:///F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/MyAppName/UI/ConfigurationManager/Create/upload.configuration.config.module.js
> 2017-01-16T11:34:46.0707713Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:26.1482931; Thread:8; Message:Phantom Log - Resource Recieved: file:///F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/MyAppName/UI/ConfigurationManager/Create/upload.configuration.config.module.js
> ............
> 2017-01-16T11:34:46.0707713Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:26.4154799; Thread:8; Message:Phantom Log - Resource Recieved: file:///F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/UnitTests/MyAppName.JSUnitTests/upload.configuration.service.module.js
> 2017-01-16T11:34:46.0707713Z vstest.executionengine.x86.exe Error: 0 : Time:11:34:26.4234789; Thread:8; Message:Eror recieved from Phantom Error opening F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/UnitTests/MyAppName.JSUnitTests/upload.configuration.config.module.js: No such file or directory
> 2017-01-16T11:34:46.0707713Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:26.4304800; Thread:8; Message:Phantom Log - Resource Error for file:///F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/UnitTests/MyAppName.JSUnitTests/upload.configuration.config.module.js with error Error opening F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/UnitTests/MyAppName.JSUnitTests/upload.configuration.config.module.js: No such file or directory
> ............
> 2017-01-16T11:34:46.0707713Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:26.6964764; Thread:6; Message:Phantom Log - Resource Recieved: file:///F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/MyAppName/UI/ConfigurationManager/Create/upload.configuration.config.module.js
> 2017-01-16T11:34:46.0707713Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:26.6964764; Thread:6; Message:Phantom Log - Resource Recieved: file:///F:/vsts-build-01-01/_work/77/s/01-Applications/MyAppName/MyAppName/UI/ConfigurationManager/Create/upload.configuration.config.module.js
> ............
> 2017-01-16T11:34:46.0863963Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:27.7510918; Thread:13; Message:Investigating reference file path '../../MyAppName/UI/ConfigurationManager/Create/upload.configuration.config.module.js'
> 2017-01-16T11:34:46.0863963Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:27.7510918; Thread:13; Message:Added file 'F:\vsts-build-01-01\_work\77\s\01-Applications\MyAppName\MyAppName\UI\ConfigurationManager\Create\upload.configuration.config.module.js' to referenced files. Local: True, IncludeInTestHarness: True
> 2017-01-16T11:34:46.0863963Z vstest.executionengine.x86.exe Information: 0 : Time:11:34:27.7658427; Thread:13; Message:Processing referenced file 'F:\vsts-build-01-01\_work\77\s\01-Applications\MyAppName\MyAppName\UI\ConfigurationManager\Create\upload.configuration.config.module.js' for expanded references

So it could find file upload.configuration.config.module.js in path (...01-Applications/MyAppName/MyAppName/UI/ConfigurationManager/Create/) but it is also looking for it in location with chutzpah.json file and it crashes.

**Comment by mmanela** [comment]
What do you mean in crashes? Can you attach both good and bad full logs files?
