### ISSUE TITLE
Angular2 with Chutzpah

### ISSUE THREAD

**Issue by laxmandasari** [mmanela/chutzpah#586]
Can anyone share sample code of Angular2 with Chutzpah? I have gone through sample available in samples folder but it seems that is based on the beta version of Angular. It would be helpful if I can get quick info or samples on how to setup Chutzpah with Angular2 and system.js as module loader.

**Comment by mmanela** [comment]
Yea I see that my sample got outdated. I am not an Angular2 dev so can you share me a simple example with a test that you would like to work and I can base a new sample off of it

**Comment by laxmandasari** [comment]
@mmanela - I have uploaded an example project at below repo. 

https://github.com/laxmandasari/ChutzpahAngular

This repo contains 2 test files viz. "app.component.spec.ts" (this file contains angular component specific tests) and "demo.spec.ts" (this file contains plain jasmine test cases). 

After loading this solution I can see only plain jasmine test cases and test explorer window and other angular test cases are not loading and throwing following error in output window.

**Error: TypeError: Invalid System.register call. Anonymous System.register calls can only be made by modules loaded by SystemJS.import and not via script tags.**
in file:///c:/laxman/my.github.com/chutzpahangular/chutzpahangular/node_modules/systemjs/dist/system.js (line 5)
in file:///c:/laxman/my.github.com/chutzpahangular/chutzpahangular/node_modules/systemjs/dist/system.js (line 5)
in file:///c:/laxman/my.github.com/chutzpahangular/chutzpahangular/node_modules/systemjs/dist/system.js (line 5)
in file:///c:/laxman/my.github.com/chutzpahangular/chutzpahangular/node_modules/systemjs/dist/system.js (line 5)
at register in file:///c:/laxman/my.github.com/chutzpahangular/chutzpahangular/node_modules/systemjs/dist/system.js (line 5)
While Running:c:\laxman\my.github.com\chutzpahangular\chutzpahangular\angular_code\app\main.ts

**Comment by laxmandasari** [comment]
@mmanela - Did you get any chance to look into repo?

**Comment by mmanela** [comment]
Sorry, been busy I haven't had a chance to get to this yet.

**Comment by GeorgDangl** [comment]
I've created a [sample project](https://github.com/GeorgDangl/NetCoreHeroes) that has unit tests for Angular 2 with system.js. It's still on 2.0 because of a limitation in Asp.Net Cores server side prerendering, but it should still be valid.

**Comment by mmanela** [comment]
@laxmandasari This should work. https://github.com/laxmandasari/ChutzpahAngular/pull/1

**Comment by mmanela** [comment]
I also update the angualr2 sample to be the same. Thanks for the help
