### ISSUE TITLE
Running batch scripts is part of this workflow?

### ISSUE THREAD

**Issue by PandaWood** [mmanela/chutzpah#588]
I was interested in using Chutzpah, and I don't want to be too critical...
But I see the example to get my scenario working is relying on batch files!

This seems backward to me. I'm looking for a test runner, in order to avoid things like .bat files (being os-specific etc)

Would everyone agree that this should be changed?

examples is here in branch -> chutzpah/Samples/Compilation/TypeScript/

**Comment by mmanela** [comment]
That is just an example, most people do not use that.  This is the common workflow people use for TypeScript: https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation/ExternalCompile
