### ISSUE TITLE
Coverage works with OpenInBrowser but not with PhantomJS

### ISSUE THREAD

**Issue by davidjamartin** [mmanela/chutzpah#589]
I wonder if you could help me diagnose an issue I am having? I can successfully produce code coverage when running chutzpah.console.exe /openinbrowser option, however if I omit this it produces empty coverage files.

I've managed to do a little debugging and can see that the CoverageObject data appears to be empty, here's an extract of what I'm seeing:

```
#_#TestDone#_# {"type":"TestDone","testCase":{"moduleName":"Basic Assumptions:","testName":"has loaded application","testResults":[],"timetaken":42}}
#_#CoverageObject#_# {"type":"CoverageObject","object":"{\"http://localhost:9876/app/Application.js\":[null,1,null,null,null,0,null,0,0],\"http://localhost:9876/app/Helper/CommonMethods.js\":[null,1,null,null,null,null,0,0,0,0,0,0,null,0,0,null,null,null,0,0,0,0,0,0,null,null,null,null,0,0,0,0,null,null,0,0,null,null,0,null,0,null,null,null,0,0,0,0,0,0

```
This is the command line I am using:

`chutzpah.console.exe chutzpah.json /coverage /lcov ResultsCoverage.lcov`

This is my configuration file:

```
{
  "References": [
    {
      "Path": "ext/build/ext-all.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "app-test.js",
      "IsTestFrameworkFile": true
    }
  ],
  "Tests": [
    { "Path": "app-test/specs/application.js" }
  ],
  "Server": {
    "Enabled": true
  },
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "RootReferencePathMode": "SettingsFileDirectory",
  "CodeCoverageIncludes": [ "app" ],
  "EnableTestFileBatching": true
}

```

I'm not sure how to debug this further, or whether you may have seen this issue before? I'm not seeing any errors when running with either the trace and/or debug flags.

For information this is a ExtJS application, in case it is relevant.

Any advice would be appreciated.

**Comment by mmanela** [comment]
Can you give me a full repro I can run?

**Comment by davidjamartin** [comment]
I'm not sure that is going to be possible, ExtJS is a licensed product and the code is commercially sensitive.

I know that is not very helpful as I'm actually asking you to help me without much detail and I apologise for that,

What I'm really after is some guidance as to how to debug this issue. I have stepped through the c# code and that is not doing anything due to the null objects, I've run the PhantomJS command line (taken from the logs) and can reproduce the issue, for which I've attempted to debug using the remote debugging capability of PhantomJS.

So at this stage its advice that I'm after, failing that I'll see if I can reduce the code down to something that I can actually share with you.

**Comment by davidjamartin** [comment]
I have managed to reproduce the issue with all of the private code removed and just a single file from ExtJS which maintains the licence information.
 
If you run the attached batch file with the following command:
 
`chutzpahlocal.bat /openinbrowser`
 
Running without any options it produces the issue, in both cases the files created in the testresults folder are empty.

**Note:** Place a copy of Chutzpah.4.3.3 in the same folder, or update the path in the batch file to your copy.

[TestCoverage.zip](https://github.com/mmanela/chutzpah/files/701646/TestCoverage.zip)

**Comment by mmanela** [comment]
There was a bug I fixed recently that I think was the cause of this. With my updated code it runs with this output:
![image](https://cloud.githubusercontent.com/assets/304410/22945435/14342126-f2a9-11e6-8fa6-92c7b7d291c8.png)

**Comment by mmanela** [comment]
I will release the new version soon.
