### ISSUE TITLE
Running chutzpah.console.exe Fails w/ TypeInitializationException b/c Unable to load libuv.dll

### ISSUE THREAD

**Issue by FGS-BMarkham** [mmanela/chutzpah#590]
Running Chutzpah from command line on a 64-bit machine:
`..\packages\Chutzpah.4.3.3\tools\chutzpah.console.exe /path .`

Fails:

```
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.3.3.0
Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).
System.TypeInitializationException: The type initializer for 'Chutzpah.ChutzpahContainer' threw an exception. ---> Chutzpah.Exceptions.ChutzpahException: Unable to load libuv.dll
   at Chutzpah.ChutzpahContainer..cctor()
   --- End of inner exception stack trace ---
   at Chutzpah.ChutzpahContainer.get_Current()
   at Chutzpah.TestRunner.Create(Boolean debugEnabled)
   at Chutzpah.Program.RunTests(CommandLine commandLine, IEnumerable`1 transformers)
   at Chutzpah.Program.Main(String[] args)
```

This is apparently due to bitness of `libuv.dll`. This can be worked around by doing a `corflags chutzpah.console.exe /32bitreq+`, but it is clunky and the Chutzpah compile should likely be updated to reflect bitness requirement of dependencies.

**Comment by mmanela** [comment]
That seems odd. All the machines I ever work on are 64bit and I have not ever run into this problem. Why would it be different?

**Comment by FGS-BMarkham** [comment]
All I know is that the CLR will consistently use x64 if nothing explicitly prevents it, with complete disregard to native libraries in use. This has bitten me in my own work in the past, which is why I know about the `corflags` tool.

I notice that `libuv.dll` is in an `x86` folder. However, the Chutzpah addin for Visual Studio (which duplicates much of the NuGet package) also has a `x64` folder with `libuv.dll` in it. I'm not sure if that has significance (because Visual Studio would never run it as x64) but it seems to indicate a divergence in the build/package/deploy process. /shrug

**Comment by mmanela** [comment]
That is by design. Chutzpah ships both native libs and chooses the right one at runtime. This works on all machines I have tested so far:

```
        private static bool TryLoadLibuv(string folder)
        {
            var path = Path.Combine(folder, Environment.Is64BitProcess ? "x64" : "x86", "libuv.dll");
            bool ok = File.Exists(path) &&  NativeImports.LoadLibrary(path) != IntPtr.Zero;
            return ok;
        }
```

I am curious what is different about your environment that it doesn't work.

**Comment by FGS-BMarkham** [comment]
Herpderp. User error.

Turns out my tooling had excised the x64 folder. `nuget restore` fixed me right up.

Thanks…

**Comment by roopkt** [comment]
Hi
Could you please explain how did u solve this error. Since I am also getting the same error. 
My Build machine is 64 bit also.  Here is the error that I am getting.

An exception occurred while invoking executor 'executor://chutzpah-js/': Exception has been thrown by the target of an invocation.
The type initializer for 'Chutzpah.ChutzpahContainer' threw an exception.
Unable to load libuv.dll 
See [http://go.microsoft.com/fwlink/?LinkId=254169] (http://go.microsoft.com/fwlink/?LinkId=254169)

**Comment by roopkt** [comment]
Hi after restarting build controller it resolved and now working. Thanks !
