### ISSUE TITLE
No tests found

### ISSUE THREAD

**Issue by killjoy71** [mmanela/chutzpah#591]
I have an odd issue that I am looking for any advice on.

I am running Chutzpah 4.3.3 and have Jasmine 2.5.2 installed. I wrote a bunch of unit tests in Jasmine months ago and was able to run them fine with Chutzpah then (including code coverage). I have not run these tests in a few months not but needed to update some of them so I tried running them again yesterday and nothing happens. When I use Chutzpah to run the tests (any of them) it just shows "0 passed, 0 failed, 0 total".

The important thing to note here is that nothing has really changed. We didn't update or change anything besides some code files in our project. It is possible that Chutzpah updated since the last time I ran them since it is set to automatically update. I did manually update Jasmine in case that was the issue but that doesn't appear to have helped.

My Chutzpah config is pretty simple and hasn't changed:
```
{
  "Framework": "jasmine",
  "RootReferencePathMode":  "SettingsFileDirectory", 
  "EnableCodeCoverage ": "false",
  "CodeCoverageIncludes": [
    "*/App/Controllers/*.js",
    "*/App/Directives/*.js",
    "*/App/Service/*.js",
    "*/App/*.js",
    "*.spec.js"
  ],
  "CodeCoverageExcludes": [
    "*/scripts/*.*",
    "*/templates/*.html"
  ],
  "TestFileTimeout":200000
}
```
I set reference paths directly in each of my spec files. I have like 20 spec files and this was all working fine previously. I can't figure out why it suddenly isn't finding my tests. The spec files have no changed since the last time I ran them.

**Comment by mmanela** [comment]
If you upgrading from a very old version of Chutzpah I may know what you are hitting. In version 4.1 chutzpah made a [breaking change](https://github.com/mmanela/chutzpah/wiki/Breaking-change-to-nested-reference-comments-in-version-4.1). Let me know if that helps you...

**Comment by mmanela** [comment]
I havent heard back, closing for now
