### ISSUE TITLE
Error 404 for unknown file types

### ISSUE THREAD

**Issue by Danielku15** [mmanela/chutzpah#595]
I loading certain test data via AJAX from a test files directory. In general this works fine as long I use the server mode. But it seems for all file types that are not known to the system, the web server returns an error 404.  

For example: If you have a .txt file, it is properly provided via the HTTP server and therefore also via Ajax. But if you have an unknown file type like .abc or .xyz the server always returns error 404 even though the file is on the file system. This is a bit annoying since I now need to rename all my test files to something like .txt to get them in my tests.

 This error happens in both the VS Test Explorer extension and the console runner of the latest released version 4.3.3.

**Comment by mmanela** [comment]
Thanks for the issue. I was missing a simple setting to allow this. I have it fixed now and will include in next release.
