### ISSUE TITLE
No Tests will be shown

### ISSUE THREAD

**Issue by N3uR02812** [mmanela/chutzpah#597]
Hey there, i have an problem with chutzpah. None of my Test will be shown in the Test Explorer.
I have 2 Tests. One simple and one with references to Angular 2. When i run chutzpah.exe the simple one will be tested and the other one gets Errors:

Error: Error opening .../clientapp/app/components/counter/counter.component.spec: No such file or directory
While Running: ...\clientapp\app\components\counter\counter.component.spec.ts

Error: Unhandled Promise rejection: XHR error loading file:///.../clientapp/app/components/counter/counter.component.spec

Error loading file:///.../clientapp/app/components/counter/counter.component.spec ; Zone: <root> ; Task: Promise.then ; Value: Error: XHR error loading file:///.../clientapp/app/components/counter/counter.component.spec

Error loading file:///.../clientapp/app/components/counter/counter.component.spec null
at consoleError in file:///.../node_modules/zone.js/dist/zone.js (line 388)
While Running: ...\clientapp\app\components\counter\counter.component.spec.ts

and so on.

My chutzpah.json (in project root):

```
{
	"Framework": "jasmine",
	"TestHarnessReferenceMode": "AMD",
	"TestHarnessLocationMode": "SettingsFileAdjacent",
	"Tests": [
		{
			"Includes": [ "*.spec.ts" ]
		}
	],
	"TestFileTimeout": "20000",
	"References": [
		{ "Path": "node_modules/es6-shim/es6-shim.js" },
		{ "Path": "node_modules/core-js/client/shim.min.js" },
		{ "Path": "node_modules/reflect-metadata/Reflect.js" },
		{ "Path": "node_modules/systemjs/dist/system.src.js" },
		{ "Path": "node_modules/zone.js/dist/zone.js" },
		{ "Path": "node_modules/zone.js/dist/async-test.js" },
		{ "Path": "node_modules/zone.js/dist/fake-async-test.js" },
		{ "Path": "node_modules/zone.js/dist/sync-test.js" },
		{ "Path": "node_modules/zone.js/dist/proxy.js" },
		{ "Path": "node_modules/zone.js/dist/jasmine-patch.js" },
		{ "Path": "systemjs.config.js" }
	]
}
```

My systemjs.config.js (also root):

```
/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
	System.config({
		paths: {
			// paths serve as alias
			'npm:': 'node_modules/'
		},
		// map tells the System loader where to look for things
		map: {
			// our app is within the app folder
			app: 'ClientApp/app',
			// angular bundles
			'@angular/core': 'npm:@angular/core/bundles/core.umd.js',
			'@angular/core/testing': 'npm:@angular/core/bundles/core-testing.umd.js',
			'@angular/common': 'npm:@angular/common/bundles/common.umd.js',
			'@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
			'@angular/compiler/testing': 'npm:@angular/compiler/bundles/compiler-testing.umd.js',
			'@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
			'@angular/platform-browser/testing': 'npm:@angular/platform-browser/bundles/platform-browser-testing.umd.js',
			'@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
			'@angular/platform-browser-dynamic/testing': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js',
			'@angular/http': 'npm:@angular/http/bundles/http.umd.js',
			'@angular/http/testing': 'npm:@angular/http/bundles/http-testing.umd.js',
			'@angular/router': 'npm:@angular/router/bundles/router.umd.js',
			'@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
			// other libraries
			'rxjs': 'npm:rxjs'
		},
		// packages tells the System loader how to load when no filename and/or no extension
		packages: {
			app: {
				main: './main.js',
				defaultExtension: 'js'
			},
			rxjs: {
				defaultExtension: 'js'
			}
		}
	});
})(this);
```
I checked the references multiple times but didn't found any problem. I will post later the repo down her.

Thanks,
N3uR02812

**Comment by N3uR02812** [comment]
Here is my Repo: https://github.com/N3uR02812/Angular2App.git

**Comment by mmanela** [comment]
@N3uR02812 
A couple tips to help you debug
1. Check out the official Chutzpah Angular2 sample and see how it is different: [https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic](https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic)

2. Using Chutzpah command line (or context menu extension) have Chutzpah try to open the test in the browser. This will often yield more info and better error messages in the console as the why it is not work and can lead you to fixes.

Please try those and if you still have trouble I can look deeper at your sample.

**Comment by talelamira** [comment]
I'm having the same issue with a simple HelloWorld example

**HelloWorld.spec.js**:
`import './hello-world.js';

describe('Hello World', function() {
  var helloWorld = new HelloWorld();

  it('says hello world with no name', function() {
    expect(helloWorld.hello('')).toEqual('Hello, World!');
  });

  xit('says hello to bob', function() {
    expect(helloWorld.hello('Bob')).toEqual('Hello, Bob!');
  });

  xit('says hello to sally', function() {
    expect(helloWorld.hello('Sally')).toEqual('Hello, Sally!');
  });
});`

**Chutzpah.json** :
`{        
    "Framework": "jasmine",


    "TestFileTimeout": 15000,

    "RootReferencePathMode":"SettingsFileDirectory",
	
	"Tests": [{ "Path": "./"}],

    "References": [{ "Path": "hello-world.js" }],

    "Transforms": [],

    "EnableTracing": true
}`

**Output** :
Tests complete: 0
=== 0 total, 0 failed, took 3.20 seconds ===

**Command** :
`chutzpah.console.exe HelloWorld.spec.js /openInBrowser`

In the browser, there's nothing: No specs found

Any help please?

**Comment by N3uR02812** [comment]
Ok, i've tried this example https://blog.dangl.me/archive/netcoreheroes-angular2-with-net-core-in-visual-studio-2015-part-i and this worked. I think it wasn't working because in my example i use webpack and system.js at the same time. In this Blog example it runs only with system.js and the .ts files are in the wwwroot. But i am not really sure if this was the reason.

**Comment by GeorgDangl** [comment]
@N3uR02812, the `.ts` files being in the `wwwroot` folder was just because of my inexperience with TypeScript and web development. I've updated [the repository](https://github.com/GeorgDangl/NetCoreHeroes) and moved the TypeScript files to the `App` folder.
(The project now also uses webpack for bundling, but chutzpah tests are still being executed with system.js).

The important point here is that you need to be sure to set up files and references, both in `chutzpah.json` and `systemjs.config.js`, to correctly match your modules and test files.
