### ISSUE TITLE
Add support for proxy servers 

### ISSUE THREAD

**Issue by sunnyy999** [mmanela/chutzpah#598]
I have been struggled in trying to get Chutzpah working for a couple of days, and in the end, I found that the issue is due to the fact that it doesn't support proxy. the Unit test i am trying to test has a external reference to a cdn url, obviously it stop the test runner from discover the test or run the test, with error like "connection timeout". I have a look at the source code, and notice that the proxy server setting is disabled.
Can a option be provided to allow turn the proxy setting on? and allow to pass in the proxy server/port from json config file? Thanks

**Comment by mmanela** [comment]
That seems like a good feature. Would this be something you are interested in adding? (Always looking for new contributors :) )

**Comment by sunnyy999** [comment]
Yeah why not? I will look into it.
How to become a contributor?

**Comment by mmanela** [comment]
Send me a PR :)  And if you have questions on how to implement or build please let me know here and I can guide you

**Comment by sunnyy02** [comment]
Anyway to debug the test adapter thru visual studio?

**Comment by mmanela** [comment]
Yea, you don't need to test the VS integration just the command line client. This makes it easier to develop. So just launch the ConsoleRunner project under the debugger

**Comment by mmanela** [comment]
This is now released
