### ISSUE TITLE
Chutzpah Console incorrectly reports test results when run in parallel

### ISSUE THREAD

**Issue by kharabasz** [mmanela/chutzpah#602]
We recently upgraded from v.4.0.3 to v4.3.4 to see if there were any performance gains available. We have around 1600 javascript tests in our project.

The performance increase looks great (4 mins down to 50 seconds) but we are worried as the console runner is reporting a different test count after each run.

I realize this is not the best issue report - please let me know what I can provide to help debug the issue.

**Comment by kharabasz** [comment]
As a follow-up: I traced the issue to how Chutzpah discovers tests. (using the /discover option on the console runner). It seems to be finding different numbers of tests with each run, but never the full amount.

**Comment by mmanela** [comment]
Can you share your Chutzpah.json file? Also, do you see different results when running tests like this?

> chutzpah.console.exe path/to/Chutzpah.json

**Comment by kharabasz** [comment]
Here is my chutzpah.json - https://gist.github.com/kharabasz/3a31a20eaf2da64f861281363b4f2936

We run tests this way:
`chutzpah.console.exe path/to/tests/`

I will try with:
` chutzpah.console.exe path/to/tests/Chutzpah.json`
and post back the results

**Comment by kharabasz** [comment]
Running with the path to the chutzpah.json file produces consistent counts for the /discovery command - but incorrect when compared to the expected number of tests (there are too many tests discovered)

Executing tests with the path to the chutzpah.json file produces different test counts with each run (less tests then expected)

**Comment by mmanela** [comment]
Lets ignore the /discovery option for now. Lets focus on executing tests using chutzpah.json file. You are saying that gives different results each time you run in? How different? Do you see errors?

**Comment by kharabasz** [comment]
Per v.4.0.3, I am expecting 1576 tests

Here are the last 10 runs under v4.3.4: 1519, 1505, 1457, 1435, 1491, 1499, 1481, 1495, 1489, 1496

The output does not contain any error messages.

The behavior is also consistent when tests are run on a teamcity agent.

**Comment by mmanela** [comment]
Can you run /trace from the command line on version 4.3.4 and and in a different folder run /trace on 4.0.3 and attach both logs. (NOTE: Chutzpah will append to the same log file if it is there, so make sure you either rename after running once or copy to a different folder)

**Comment by kharabasz** [comment]
I changed some project folders around in the meantime, so I also included the new chutzpah.json. There are 2 v4.3.4 logs from separate runs and 1 v4.0.3 run.

https://drive.google.com/drive/folders/0B85IxhePcfkZVE1BdlBkb1NKc28?usp=sharing

**Comment by mmanela** [comment]
I will take a look but at first glance of your chutzpah.json file I have some suggestions to change and then test again. Can you change that entire first section where you have  ```"IsTestFrameworkFile": false``` with  ```"IsTestFrameworkFile": true```. This is good to set for any of the framework level files like angualr or jasmine.

**Comment by kharabasz** [comment]
I made this change and still see the same behavior (different number of tests reported between different runs). A small number of tests are failing due to what looks like bad imports around moment.js

**Comment by mmanela** [comment]
Can you provide a repro I can run locally?

**Comment by kharabasz** [comment]
Sorry, I can't do that. I can try to debug through the runner, if given some pointers on what to look for. I tested switching to karma over the weekend and that runner ties out w/ the expected results from chutzpah v.4.0.3

**Comment by SCMorgan** [comment]
I'm experiencing the same issue.
I only use Chutzpah through the console in Teamcity. Whenever I see this issue the number of tests I appear to be short is offset by the number of tests are being reported as running more than once.
**i.e. "OK (2 runs)"**

**Comment by mmanela** [comment]
No resolution yet, @SCMorgan do you have a repro I can run and test with?

**Comment by kharabasz** [comment]
@mmanela What is the default behavior of the runner when a test file times out? Is it supposed to re-run the test file, or is it supposed to come up as a failure in the summary?

**Comment by mmanela** [comment]
It will come as failure.

**Comment by zrajnai** [comment]
We are also experiencing this, and have tracked it down to being due to testStarted and testFinished messages being interleaved.
Appearantly, TeamCity can use a flowId, to identify messages belonging to the same 'flow.
see here:
[How to use flowId? ](https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206692465-How-to-use-flowId-)

**Comment by zrajnai** [comment]
I think the solutions:
* set an Id in ```TestContext`` to ```Task.CurrentId``` inside the ```Parallel.ForEach``` of ```Task.CurrentIdExecuteTestContexts```
* pass the ```TestContext``` to the methods of ```ITestMethodRunnerCallback```
* modify ```TeamCityConsoleRunnerCallback`` to include the Id of the ```TestContext``` as the flowId value in all TeamCity messages.

**Comment by zrajnai** [comment]
I just created a [Pull request ](https://github.com/mmanela/chutzpah/pull/738)to fix this issue :)
