### ISSUE TITLE
TypeError: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by a2nmous** [mmanela/chutzpah#605]
When run test my project I met this error:
"Error: TypeError: Attempted to assign to readonly property.
in file:///D:/Admi21/03.UnitTest/04.TestProject/SAMPortal/SAMPortalSite/src/app/scripts/angular-mocks.js (line 18)"
but all test case done.
Can you give me a suggess to fix this problem?
Thanks!

**Comment by mmanela** [comment]
Can you please give a small minimal repro that I can run locally?

**Comment by a2nmous** [comment]
Hi mmanela.
Sorry, i'm reply late. I create a repo here [https://github.com/a2nmous/04.TestProject](url)
Please check, thanks.

**Comment by SCMorgan** [comment]
I'm not sure how similar your case is to mine, but I found that asking Chutzpah to find all tests within my project caused it to load angular-mocks twice: It loaded it once when it found the file, presumably picking up the describes in it and assuming it was a file that needed to be loaded, then a second time when it was referenced in a given test file.

I've not found a sensible way to exclude this from the command line, but if you're using chutzpah.json then you might have an easier time about it :)

**Comment by mmanela** [comment]
@SCMorgan I recommend you always use chutzpah.json to have most control over how things load. That said, chutzpah should never load the same file twice. Do you have a repro I can run that shows this?

**Comment by SCMorgan** [comment]
Hi @mmanela , Since I made my post this morning I've started using chutzpah.json and my issue is solved. If you're interested in the problem I'll see if I can put something together a little later on.

Would you still like to see it?

**Comment by mmanela** [comment]
Sure doesnt hurt to see but in general chutzpah.json cure problems :)
