### ISSUE TITLE
Chutzpah Module dependencies not working

### ISSUE THREAD

**Issue by rahulsahay19** [mmanela/chutzpah#606]
Hi Team,

Same test is getting passed from Resharper Javascript test runner, but when i run the same using chutpah test runner either with menu option or with command line, it failed with a reason that angular module is not getting loaded. Although all references are pretty much there. I have attached the screenshots for your reference. This usually happens, when my module names and other dependencies follow namespace kind of structure like shown in the snippet attached. Similar issue was earlier reported. http://stackoverflow.com/questions/36733738/cannot-get-simple-angularjs-jasmine-test-to-pass-with-chutzpah

```
`'use strict';

/* Header Controller */

gcs.portal.headerController = ["$scope", "corp", function ($scope, corp) {
    $scope.iframeSource = Common.Settings.ExternalUIRoot + "/Samples/Content/Examples#/Dashboard";

    // Navigate to samples features
    $scope.NavigateToSamples = function () {
        location.href = corp.settings.UiRoot + "/Content/Samples#/home";
    };

    // Navigate to support features
    $scope.NavigateToSupport = function () {
        location.href = corp.settings.UiRoot + "/Content/Support#/home";
    };

    //
    $scope.LogOff = function () {
        //clear the dashboard peer panel session storage
        //TODO we need to re-look on this
        var userId = corp.user !== null ? corp.user.UserId : -1;
        //Clearing local storage for selected MyCompany relative ticker.
        location.href = corp.settings.UiRoot + "/Home/LogOff" + "?userId=" + userId;
    };
}];
```

![gcs_not_defined](https://cloud.githubusercontent.com/assets/3886381/23458137/ee10356c-fea0-11e6-91fe-80ce6ea45948.png)
` 

Thanks,
Rahul
![failing_test](https://cloud.githubusercontent.com/assets/3886381/23453941/64228bc6-fe90-11e6-8a8d-1feff71eeffc.png)
![failing_test_reason](https://cloud.githubusercontent.com/assets/3886381/23453983/907fccce-fe90-11e6-8cef-a5e28f559fd4.png)

**Comment by mmanela** [comment]
Can you share your chutzpah.json and if possible a minimal repro I can run locally?

**Comment by rahulsahay19** [comment]
Hi,

I have installed Chutzpah from nuget as well just to get the cmd line tool. I already have chutzpah as extension as well. But, I no where saw chutzpah.json file as part of my project. Where it resides? 

Thanks,
Rahul

**Comment by mmanela** [comment]
In all but the most simple cases Chutzpah requires configuration. You must create a chutzpah.json file and place it in your tree and configure it for your tests. Chutzpah contains several [samples](https://github.com/mmanela/chutzpah/tree/master/Samples) to help get you started. Take a look at the Angular samples in there.

**Comment by rahulsahay19** [comment]
Thanks will apply and test the same, then let you know!

**Comment by rahulsahay19** [comment]
Hi,

Below is the sample of chutzpah.json.

`{
    "Framework": "jasmine",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "EnableTestFileBatching": true,
    "References": [
        {"Path" : "data/mockData.js" },
        { "Path": "../../jasmine-lib/lib/jasmine-2.3.4/boot.js" },
        { "Path": "../../jasmine-lib/lib/jasmine-2.3.4/jasmine.js" },
        { "Path": "../../jasmine-lib/lib/angular/angular.js" },
        { "Path": "../../jasmine-lib/lib/angular/angular-mocks.js" },
        { "Path": "~/Scripts/gcs-scripts/gcs-shell.js" },
        { "Path": "../directives/navbar.js" },
        { "Path": "../services/navigationDataService.js" },
        { "Path": "../controllers/headerController.js" },
        { "Path": "../headerModule.js" }
    ],

    // Tests do *not* get inherited.
    "Tests": [
        { "Includes": [ "*Tests.js" ] }
    ]
}
`

Then my folder structure as follow.
![1st](https://cloud.githubusercontent.com/assets/3886381/23577112/24db7c44-00dd-11e7-822a-e3df85bcd440.png)

Also, my module looks like 

![3rd](https://cloud.githubusercontent.com/assets/3886381/23577269/a6bef224-00e0-11e7-8f41-08cea07d54a5.png)

Now, I am running the same with cmd prompt via 
`C:\IRSuite\Features\Platform\src\Portal\Shell.UI>chutzpah.console.exe .\Apps\_header\_tests\headerControllerTests.js`

and getting below error.

![2nd](https://cloud.githubusercontent.com/assets/3886381/23577157/2e389ece-00de-11e7-8623-86d09c9d4ee0.png)

And, when I run the same in browser from command line, it gives me following error

![4th](https://cloud.githubusercontent.com/assets/3886381/23577276/e3a70564-00e0-11e7-88e5-55c33ce48aa0.png)

However, it looks like that gcs-shell.js is not loading, because I am referencing the same with ~ option as its part of different folder and with .. navigation its not resolving and when I am dragging and dropping the file its taking absolute path kind of structure. However, when I specify below chutzpah.json, my test case passes.

`{
    "Framework": "jasmine",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "EnableTestFileBatching": true,
    "References": [
        {"Path" : "data/mockData.js" },
        { "Path": "../../jasmine-lib/lib/jasmine-2.3.4/boot.js" },
        { "Path": "../../jasmine-lib/lib/jasmine-2.3.4/jasmine.js" },
        { "Path": "../../jasmine-lib/lib/angular/angular.js" },
        { "Path": "../../jasmine-lib/lib/angular/angular-mocks.js" },
        { "Path": "C:\\IRSuite\\Features\\Platform\\src\\Portal\\Shell.UI\\Scripts/gcs-scripts/gcs-shell.js" },
        { "Path": "../directives/navbar.js" },
        { "Path": "../services/navigationDataService.js" },
        { "Path": "../controllers/headerController.js" },
        { "Path": "../headerModule.js" }
    ],

    // Tests do *not* get inherited.
    "Tests": [
        { "Includes": [ "*Tests.js" ] }
    ]
}
`

My question is how to resolve absolute path here when main script is not part of test folder. Is there any way to resolve the same using ~ opeartor.

**Comment by rahulsahay19** [comment]
One more thing is for passing test, its coverage is failing like shown below.

![7th](https://cloud.githubusercontent.com/assets/3886381/23577407/593f5a3a-00e4-11e7-9c36-8b86d175a768.png)

![6th](https://cloud.githubusercontent.com/assets/3886381/23577403/36ce0a46-00e4-11e7-8830-d594d6de4ad4.png)

**Comment by rahulsahay19** [comment]
Closing the issue. Thanks for the help. Issue sorted.
