### ISSUE TITLE
chutzpah.json is not detecting the test files

### ISSUE THREAD

**Issue by vijayalakshmi13** [mmanela/chutzpah#609]
when i place the chutzpah.json inside test folder why js files are not getting detected

```
{
"AMDBaseUrl": "testjsfile",
"AMDAppDirectory": "./",

"Framework": "jasmine",
"Compile": {
"Mode": "External",
"Extensions": [ ".ts" ],
"ExtensionsWithNoOutput": [ ".d.ts" ],
"UseSourceMaps": true,

"Paths": [
  {
    "SourcePath": "source/file1/sourcein",
    "OutputPath": "testjsfile/sourcejs"
  }
]
},
"References": [
{
"Path": "source",
"Includes": [ ".ts" ]
}
],
"Tests": [
{
"Path": "testjsfile/testjs",
"Includes": [ ".js" ]
}
],
"EnableTracing": true,
"TraceFilePath": "E:/Vijayalakshmi/compile.log"
}
```

-source
--file1
---sourcein
----sourcefile.ts

-test
--testfile.ts
--chutzpah.json

it is not working for the above folder structure
but when i place the file outside that is at the root of the project it is working

**Comment by mmanela** [comment]
Can you provide a minimal repro/sample I can run to see what you are doing?

**Comment by vijayalakshmi13** [comment]
`



`

**Comment by vijayalakshmi13** [comment]
#508

**Comment by vijayalakshmi13** [comment]
is there any way to make chutzpah work by keeping the source.js files in a different folder rather than in the same folder where chutzpah.json resides

**Comment by vijayalakshmi13** [comment]
asa mentioned above i have placed chutzpah.json in test folder and the js files of test and source are kept in a different folder

**Comment by mmanela** [comment]
Yes, I have samples in the repos /Samples folder on this. Have you looked at those?

**Comment by RonNewcomb** [comment]
You have an extra closing } before "References"
