### ISSUE TITLE
Time occured when executing test file

### ISSUE THREAD

**Issue by krzysztofadamczak** [mmanela/chutzpah#611]
Hi,
I have a problem with executing javascript tests in Visual Studio 2015 with  Chutzpah version 4.3.4
When i'm running single test using 'Run JS Tests' file all works fine, if I run all tests in debugger mode 'Run Chutzpah with Debugger' on main folder it works too but when i run all tests without debug 'Run JS Tests' on main folder I'm getting:
`Error: Timeout occured when executing test file
While Running:<test-file-name>`
for all files.

Chutzpah configuration:
```
 "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "RootReferencePathMode": "SettingsFileDirectory",
  "EnableTestFileBatching": false,
  "EnableTracing": true,
  "TraceFilePath": "chutzpah.log",
```

**Comment by mmanela** [comment]
Can you clear the log file, then do this again and share it with me?

**Comment by krzysztofadamczak** [comment]
[Chutzpah.TXT](https://github.com/mmanela/chutzpah/files/840480/Chutzpah.TXT)

**Comment by mmanela** [comment]
Hmm I am not sure from the logs. Do you have a repro I can run?

Also, can you enable test file batching?

**Comment by krzysztofadamczak** [comment]
If i enable test file bathing some tests didn't pass.
Unfortunately i can't share any part of code.

**Comment by roopkt** [comment]
Hi, 
We were facing this issue in our project. It turned out that phantom.exe was timing out/out of memory. We had a large combined test file that we used to run and phantom was throwing exception. In order to fix that issue we did split our test files in to 4 parts and then all test run successfully.

**Comment by mmanela** [comment]
Chutzpah allows you to break down and parallelize multiple test harnesses by making a parent chutzpah.json and have child chutzpah.json files for each area to test.
