### ISSUE TITLE
VS2015 Instrumentation error, you cannot redefine the 'window' variable in  file: angular.js

### ISSUE THREAD

**Issue by raffaeu** [mmanela/chutzpah#612]
We have a set of Unit Tests built in Jasmine.
The version we are using right now is **2.5.3 of Jasmine**.

If I right click on my test project from **Solution Explorer** and choose "Run JS Tests" I get this output in the Output Window:

```
------ Test started: File: C:\DEV\xxx\unittests.js ------
35 passed, 0 failed, 35 total (chutzpah).

========== Total Tests: 35 passed, 0 failed, 35 total ==========
```

But, if I right click my Tests from **Test Explorer** and choose **Run Selected Tests**, after a while (about 1 minute) I get this error:

```
------ Run test started ------
Error: Error: Instrumentation error, you cannot redefine the 'window' variable in  file:///c:/xxx/angular.js:1876
in file:///C:/xxx/ChutzpahTestHarnessFiles/Coverage/blanket_jasmine_v2.js (line 4583)
at forEach  (line 0)
at _checkDefs in file:///C:/xxx/ChutzpahTestHarnessFiles/Coverage/blanket_jasmine_v2.js (line 4581)

While Running:c:\xxx\unittests.js

Error: Error: error (timeout=5000) loading source script: file:///c:/xxx/angular.js
in file:///C:/xxx/ChutzpahTestHarnessFiles/Coverage/blanket_jasmine_v2.js (line 5476)
While Running:c:\xxx\unittests.js

Error: Timeout occurred when executing test file
While Running:c:\xxx\unittests.js

========== Run test finished: 0 run (0:01:02.6401247) ==========
```

This problem seems to be due to the **Code Coverage** triggered by Test Explorer.
So, I tried to change the Chutzpah.json for the project in this way:

  "CodeCoverageExecutionMode": "Never",

And the tests are running as expected.

## Question
I am aware of the fact that Angular 2.0 has an issue with Phantom, used by Chutzpah, but what about using Istanbul instead? Also, I am on Angular 1.3 but still get the error

**Comment by mmanela** [comment]
Chutzpah's code coverage support can be tricky to get right with Angular but with Angular 1 at least its possible. Can you share your chutzpah.json file?

**Comment by raffaeu** [comment]
Hi @mmanela , so it looks like, by doing this, I can remove code coverage on Angular and get it done properly:

```
  "CodeCoverageExecutionMode": "Always",
  "CodeCoverageExcludes": [ "*jquery*", "*angular*" ],

```

**Comment by mmanela** [comment]
Ok cool, that worked?

**Comment by raffaeu** [comment]
Yes it did, it did the trick, actually I wasn't aware of this option and I can now execute Code Coverage only on specific files and it is quite cool. 
Kudo for the great job done so far 🥇
