### ISSUE TITLE
I want to disable chutzpah for one project.

### ISSUE THREAD

**Issue by sounik** [mmanela/chutzpah#613]
I like the chutzpah tool vary much and started using it in my projects but in one of the project i am using 
karma. Currently it is showing unit tests for all projects (also in the projects where i am planing to use karma) in my visual studio probably because i installed chutzpah tool. Now i want to disable it for one project. I am pretty new to this tool. Please let me know if there is a option to disable chutzpah for specific project and can use it in other. Is any configuration available ?

**Comment by mmanela** [comment]
You can add a chutzpah.json in a directory to say to not run any tests like this:

```
{
  "Tests": [
    { "Exclude": "*" }
  ]
}
```

**Comment by sounik** [comment]
Thanks for response, It works for me.
