### ISSUE TITLE
Cannot get Tests running from TFS 2013 Build

### ISSUE THREAD

**Issue by raffaeu** [mmanela/chutzpah#614]
So, I have created 3 different test projects (.dll), each one with its own Chutzpah.json configuration file.
They work just fine locally, I can run **Jasmine**, I can do **Code Coverage** and see the integration with Visual Studio 2015.

Now, I setup my Build Server as explained in the Documentation by following these steps:

1. Configured for the Build Controller a BIN folder using the content of this package: **Chutzpah.4.3.4**
2. Created a Test Settings file which contains the specified XML (see pic)
3. Include the .js and .json file marked as "Content Copy Always"

If I open the **"BIN"** result from TFS and Run Chutzpah via Console or using Visual Studio 2015 (of Build Controller) I can execute the tests.

But if I run the build I get this error, where no tests or test runner compatible were found:

```
Run VS Test Runner00:00:55
Inputs
TestSpecs: BuildParameter[] Array
Enabled: True
ConfigurationsToTest: String[] Array
OutDir:
Test Run Completed. 0 tests executed.
```

So TFS finds the projects specified by my pattern `**\*unittests*.js` but it doesn't understand that they need to be run using Chutzpah.
I am sure 100% sure I am missing something in the configuration of the Build Controller. Maybe I am using wrong version of Chutzpah, I need to install some else?

## Attachments

```
<RunSettings>
  <ChutzpahAdapterSettings>
    <EnabledTracing>true</EnabledTracing>
  </ChutzpahAdapterSettings>

```

![image](https://cloud.githubusercontent.com/assets/1304736/24045767/7e26ffa6-0b20-11e7-87b3-b336da10e173.png)

**Comment by raffaeu** [comment]
I found the reason of the problem, but not a proper solution yet.
In Chutzpah, we must use relative or absolute paths to reference a .JS file.
In Karma, I can use also Wildcards as following:

```
 "References": [
    { "Path": "../../../test/Client/**/*mockConfiguration.js" },
]
```

But Chutzpah doesn't like that, so I have a problem with TFS because all projects have a different output than what we have in source control.
I think I will create a **Chutzpah.json** specifically for TFS and one for local development, is this even possible?

**Comment by mmanela** [comment]
@raffaeu You can do this with Chutzpah:

 "References": [
    { "Include": "*/test/Client/*/*mockConfiguration.js" },
]

**Comment by raffaeu** [comment]
@mmanela What a great support you give!! 💯 
So I will do some experiments, if I understand it right, I have to _escape_ using `*/` ?
I will try, thank you again

**Comment by mmanela** [comment]
No need to escape, to Chutzpah * is wildcard for 0 or more characters

**Comment by raffaeu** [comment]
Very clear, so then I will try your suggestion and make some _paths_ experiments.
Thank you again for the quick reply, much appreciated

**Comment by raffaeu** [comment]
Just to update you @mmanela, it works.
I removed from each reference the "Path" and use only the "Includes" in this way:

**Before**
```
"References": [
    {
      "Path": "../../../test/Client/Module01/mockConfiguration.js" 
    }
]

```
**After**
```
"References": [
    {
      "Includes": [ "*/Module01/mockConfiguration.js" ] 
    }
]
```
