### ISSUE TITLE
VS 2017 is complaining about the plug-in's performance

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#616]
FYI:
![image](https://cloud.githubusercontent.com/assets/3269297/24070933/458f3a82-0bcf-11e7-9874-a2a0dccefd73.png)

**Comment by mmanela** [comment]
Is this always (even for super small projects that have just one file) or only on large projects?

**Comment by HarelM** [comment]
I've opened a relatively small project IMO.

**Comment by mbp** [comment]
I see the same problem. "Manage Visual Studio Performance" says that the extension adds 17 seconds to IDE startup on average.
