### ISSUE TITLE
VS2015 and Jasmine. If multiple tests and some fail, VS reports 0 tests found

### ISSUE THREAD

**Issue by raffaeu** [mmanela/chutzpah#617]
I have a project which has a structure as following:
```
+ Scripts
 + Module01
  - tests.js
 + Module02
  - tests.js
```

Now, if I configure Chutzpah.json as following:

```
  "Tests": [
    {
      "Path": "Scripts",
      "Includes": [ "*/*tests.js" ]
    }
  ]
```

I get back the following:

```
------ Test started: File: C:\DEV\Scripts\Module01\unittests.js, 
C:\DEV\Scripts\Module02\unittests.js ------
========== Total Tests: 0 passed, 0 failed, 0 total ==========

```
So, it finds all my test harnesses but actually it returns 0.
But, if I right click the project and choose "Debug in Browser", then IE opens and I can see Jasmine executing all my tests but some of them are failing:

![image](https://cloud.githubusercontent.com/assets/1304736/24104231/f9ae60c0-0d81-11e7-9711-b8cdd7e35c24.png)

I also set the tracing but VS 2015 doesn't show anything:

```
  "Framework": "jasmine",
  "FrameworkVersion": "2.5.2",
  "EnableTestFileBatching": true,
  "EnableTracing": true,
```

Surely there is something wrong, somewhere but in this way I really can't figure it out.
What am I suppose to do right now in order to understand why Chutzpah can't load my tests?

**Comment by raffaeu** [comment]
I also tried to execute the Console directly using this command:

`chutzpah.console.exe /path "C:\DEV\Scripts" /trace /openinbrowser`

and in this specific case, Chrome opens on my PC and I can see Jasmine and running all tests and only 3 (as expected) are failing.
But, if I remove `/openinbrowser` flag, I get 0 tests found:

```
C:\Users\raf\Downloads\Chutzpah.4.3.4>chutzpah.console.exe /path "C:\DEV\Scripts" /trace
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.3.4.0
Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).


=== 0 total, 0 failed, took 7.43 seconds ===

```

Very odd (I forgot, it's Windows 10 Ultimate)

**Comment by mmanela** [comment]
Can you share the repro so I can run locally?

**Comment by raffaeu** [comment]
It's part of a large project that I can't make public, can I send you the
repo via email zipped, is that an option for you?

**Comment by mmanela** [comment]
Totally. That would be great.

**Comment by raffaeu** [comment]
I sent you an e-mail from here http://matthewmanela.com/contact/
because I can't find your e-mail address. As soon as you reply to me I will send you the .zip project with instructions on how to replicate the bug of test runner.

**Comment by raffaeu** [comment]
Here you can find the project (_I just minimized the code in order to replicate the issue_)
 Link https://drive.google.com/open?id=0B2swh8i_YlPvVFUwTElQMVFfY3c

This is how I structured the project:
```
+ src
 + UI Project
+ test
 + UI Tests
 + UI Mocks
 + Chutzpah 4.3.4
```

Open `CMD` and get this path:
```
$ C:\ cd C:\[whatever]\Test_Investigations\test\Chutzpah.4.3.4
$ C:\[whatever]\Test_Investigations\test\Chutzpah.4.3.4>
```

Then try to execute the tests _"as is"_ and this is the result you will obtain:
```
C:\[whatever]\Test_Investigations\test\Chutzpah.4.3.4>chutzpah.console.exe ../Mproof.Caas.Ui.Tests
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.3.4.0
Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).


=== 0 total, 0 failed, took 3.31 seconds ===
```

Try to execute them with **Chrome** and **Jasmine** will open and all tests will execute correctly:
```
C:\[whatever]\Test_Investigations\test\Chutzpah.4.3.4>chutzpah.console.exe ../Mproof.Caas.Ui.Tests /openinbrowser Chrome
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.3.4.0
Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).
```

and voila':

![image](https://cloud.githubusercontent.com/assets/1304736/24138646/4d93849e-0e19-11e7-84cf-69395e8068ff.png)

In my opinion is a bug in Chutzpah.console.exe when executing tests using Chutzpah.json and pointing to a folder which contains the tests. That's the only time it happens, when I pass multiple .js files

**Comment by mmanela** [comment]
Thanks for providing all the info. I tracked down the issue to your Jasmine spy on console.log. You are basically stubbing out console.log so that it does not actually work. This breaks Chutzpah since it uses console.log to report the results out of the headless browser. Can you change the spy on console.log to still let the original method run?

**Comment by raffaeu** [comment]
Hi and thank you for the quick investigation. I will refactor the tests and
report the problem to the testers.
 I think we had around 3-400 tests wrote using log. I will go through the
Jasmine documentation and implement the assertions the way you mention and
be back here with the results.

**Comment by raffaeu** [comment]
All right, I will write down here the solution because it may help others.
So I can confirm, the problem was due to the "spy" being replaced by the developers.

They were using this at the beginning of each harness:
```
	beforeEach(inject(function ($injector) {
		$httpBackend = $injector.get("$httpBackend");
		$timeout = $injector.get("$timeout");

		console.log = jasmine.createSpy("console.log");
		console.warn = jasmine.createSpy("console.warn");
		console.error = jasmine.createSpy("console.error");
	}));
```

I removed this part and now I can see the tests executing correctly in Visual Studio and also in Team Foundation.

Kudo @mmanela 🥇
