### ISSUE TITLE
ECMA 6 not supported

### ISSUE THREAD

**Issue by ILoveITScience** [mmanela/chutzpah#618]
Hello,

I have the following test:

```
"use strict";

describe("let", function () {

    // let available in ECMA 6 and higher
    it("Let", function () {
        let result = sum(2, 3);
        expect(result).toBe(5);

        function sum(value1, value2) {
            return value1 + value2;
        };
    });
});
```

It's not recognized by Chutzpah in the test explorer. If I change the word "let" into "var" it's recognized and displayed in the Visual Studio Test-Explorer. It seems like ECMA 2015 is not supported, is it?

- Visual Studio 2017 Enterprise
- Latest update of chutzpah 
- jasmine 2.5.3

**Comment by mmanela** [comment]
Chutzpah is bound by the version of PhanomJs it uses (http://phantomjs.org/download.html). This will be resolved when version 2.5 comes out but I do not know when they plan to release.

**Comment by ILoveITScience** [comment]
Thank you. I'll use babel to transpile the ecma 6 code to ecma 5.1. You can close the ticket.

**Comment by saroj08** [comment]
i installed babel-cli but still i am getting error while inserting es6 syntax. Can you please share any config file or repo so that i can follow?

**Comment by Zelig880** [comment]
Saroj,

Chutzpah does not support ES6, so there is no config or anything that the
community can provide you.

The only thing that you have to do is to make sure is that your code is
actually ES5 before calling Chutzpah.

Something that may help in this case is to run Chutzpah in the browser (
like google chrome) that supports ES6 and see if it actually works.

I had your same issues, and the above steps helped me understand the real
issues.

Regards

Simone

**Comment by saroj08** [comment]
Thanks  Zelig

**Comment by mmanela** [comment]
@saroj08  @Zelig880 @ILoveITScience  In the latest release I added support for running Chutzpah using node with JsDom or Chrome. This is early integration but will work for many. [Learn more here](https://github.com/mmanela/chutzpah/wiki/Browser-Engines)
