### ISSUE TITLE
Use Chutzpah For different Browsers

### ISSUE THREAD

**Issue by jt4000** [mmanela/chutzpah#620]
Hello,

I'm newbie in chutzpah and I wonder if you can use unit test for different browsers?

The purpose is to test if the javascript code works well in different browsers.

Today, I'm using chutzpah in relation to Visual Studio 2013 by using Nuget.

Thank you!

**Comment by mmanela** [comment]
Chutzpah is for unit tests and not intended for cross-browser testing. For that I would suggest a tool like selenium.
