### ISSUE TITLE
Syntax “Number.isFinite” don't work with Chutzpah

### ISSUE THREAD

**Issue by jt4000** [mmanela/chutzpah#622]
Hello,

It doesn't work to use syntax code "Number.isFinite" in relation to Chutzpah.

Is it supposed to be?
![g1](https://cloud.githubusercontent.com/assets/14993569/24399621/9ef11c68-13ad-11e7-978e-27b932c2eeba.png)

Thank you!

**Comment by mmanela** [comment]
Chutzpah is using PhanomJS and the new version should support this but I am waiting for version 2.5 to be released to resolve this
