### ISSUE TITLE
Test Explorer not populating after install of ContextMenu addin

### ISSUE THREAD

**Issue by ryanpete** [mmanela/chutzpah#626]
I'd been running tests just fine with just the VS testing adapter and wanted to get the added ability to generate CodeCoverage so I installed the ContextMenu addin too.  After installing the second addin I'm no longer able to see any tests in the test explorer window:

- Restarted VS (yes) (VS2017 Pro) **did not resolve problem**
- Execution appears to be fine, it's the discovery and push to TestExplorer that has the issue.
- I've tried uninstall/reinstall of the adapter plugin **did not resolve problem**
-I've since tried uninstalling the ContextMenu plugin, restarting still **did not resolve problem**
- %temp%\chutzpah.txt/log
devenv.exe Information: 0 : Time:10:17:55.3763754; Thread:53; Message:Begin OnProjectItemChanged
devenv.exe Information: 0 : Time:10:17:55.3983910; Thread:53; Message:Determining if D:\src\DSSInsight1\UnitTest\insightUserTest.js might be a test file
devenv.exe Information: 0 : Time:10:17:55.3993915; Thread:53; Message:Assuming 'D:\src\DSSInsight1\UnitTest\insightUserTest.js' is a test file
devenv.exe Information: 0 : Time:10:17:55.3993915; Thread:53; Message:Removed test container for 'D:\src\DSSInsight1\UnitTest\insightUserTest.js'
devenv.exe Information: 0 : Time:10:17:55.4003916; Thread:53; Message:Added test container for 'D:\src\DSSInsight1\UnitTest\insightUserTest.js'
devenv.exe Information: 0 : Time:10:17:55.4013925; Thread:53; Message:Begin OnTestContainersChanged
devenv.exe Information: 0 : Time:10:17:55.4088661; Thread:17; Message:Begin GetTestContainers
devenv.exe Information: 0 : Time:10:17:55.4093673; Thread:53; Message:End OnTestContainersChanged
devenv.exe Information: 0 : Time:10:17:55.4113712; Thread:53; Message:End OnProjectItemChanged
devenv.exe Information: 0 : Time:10:17:55.4187475; Thread:17; Message:End GetTestContainers
devenv.exe Information: 0 : Time:10:17:55.4187475; Thread:17; Message:Test container comparision 4/21/2017 10:13:49 AM vs 4/21/2017 10:17:55 AM for d:\src\foo\unittest\insightusertest.js
Informational: ------ Discover test started ------
vstest.discoveryengine.x86.exe Information: 0 : Time:10:17:55.4790975; Thread:15; Message:Sending discovered tests to test case discovery sink
vstest.discoveryengine.x86.exe Information: 0 : Time:10:17:55.4907434; Thread:15; Message:Chutzpah.json file not found given starting directory d:\src\foo\unittest
Informational: ========== Discover test finished: 1 found (0:00:01.7060302) ==========

- I am uninstalling both addins and will attempt reinstall just the Adapter addin to  see if that changes things. **Neither reinstall nor reboot fixed problem**

**Comment by mmanela** [comment]
Can you share your repo so I can see if it has something to do with it?
