### ISSUE TITLE
In Visual Studio 2017, when trying to run the tests (especially with code coverage) I get an InvalidOperationException

### ISSUE THREAD

**Issue by killyosaur** [mmanela/chutzpah#628]
The following error occurs when I try running tests in my project 
Error: System.InvalidOperationException: Cannot build a batch context for Url or Html test files
   at Chutzpah.TestContextBuilder.BuildContext(IEnumerable`1 files, TestOptions options)
   at Chutzpah.TestContextBuilder.TryBuildContext(IEnumerable`1 files, TestOptions options, TestContext& context)
   at Chutzpah.TestRunner.<>c__DisplayClass40_0.<BuildTestContexts>b__0(List`1 testFiles)

This occurs when I try to run against the project or the folder, both have an html file that is generated as an output for other tests. I tried updating the chutzpah.json to exclude html for tests but that doesn't appear to work.

**Comment by mmanela** [comment]
Can you share your chutzpah.json? And if possible a minimal repro ?

**Comment by killyosaur** [comment]
{
	"Framework": "jasmine",
	"RootReferencePathMode": "SettingsFileDirectory",
	"EnableTestFileBatching": true,
	"CodeCoverageExcludes": [ "*.config.js", "*.module.js", "*.spec.js", "files.js", "*\\bower_components\\", "*\\node_modules\\", "*\\[Ss]cripts\\", "\\Helpers\\" ],
	"CodeCoverageIncludes": [ "*\\actualProjectFolder\\Apps\\**\\*.js" ],
	"CodeCoverageExecutionMode": "Always",
	"CodeCoverageTimeout": 200000,
	"TestFileTimeout": 200000,
	"Tests": [
		{
			"Path": "Tests",
			"Includes": [ "*.spec.js" ],
			"Excludes": [ "*.html", "files.js" ],
			"ExpandReferenceComments": true
		}
	],
	"Transforms": [
		{
			"Name": "coveragehtml",
			"Path": "coverage.html"
		},
		{
			"Name": "lcov",
			"Path": "coverage.lcov.dat"
		}
	]
}

**Comment by killyosaur** [comment]
I'll see about getting a minimal repro as soon as I can...

**Comment by GerhardvanZyl** [comment]
I got the same issue when I right click on the project and run the tests. When I right click on the chutzpah.json file and run the tests or run from the console it works. Or Or if I delete the html files.
It seems Chutzpah doesn't ignore the html files in the same folder as the Chutzpah.json file.

**Comment by vishnurk** [comment]
Just hit the same problem. My chutzpah.json is not under project root. When I right click on the chutzpah.json and select 'Run JS Tests', tests run fine. When I right click on the project and select 'Run JS Tests', chutzpah displays the error below twice for two html files under the root folder.

> Error: System.InvalidOperationException: Cannot build a batch context for Url or Html test files
>    at Chutzpah.TestContextBuilder.BuildContext(IEnumerable`1 files, TestOptions options)
>    at Chutzpah.TestContextBuilder.TryBuildContext(IEnumerable`1 files, TestOptions options, TestContext& context)
>    at Chutzpah.TestRunner.<>c__DisplayClass40_0.<BuildTestContexts>b__0(List`1 testFiles)
>

**Comment by mmanela** [comment]
Can you share a sample project that repros this issue?

**Comment by gagangit** [comment]
Hi mmanela,

When I right click on a test case using chutpaz and run the same without coverage it runs well with passed test cases.
But when I right click on the same test case and now run with coverage then it gives me so many error like module $injector not found. 
Is there any difference  in above two cases????

**Comment by mmanela** [comment]
Honestly, the code coverage tool Chutzpah uses is deprecated and not in a good shape (the risk of building on other projects ;) ). It is possible to get it to work sometimes buts it can be a real battle

**Comment by serpenyx** [comment]
Hey mmanela,

Based on your last post, should we not be using Chutzpah for code coverage anymore?

**Comment by mmanela** [comment]
Honestly, I think so. It is very outdated right now.
