### ISSUE TITLE
Debug Throw Exception in Visual Studio 2015

### ISSUE THREAD

**Issue by huyjack178** [mmanela/chutzpah#629]
Hi, I use chutzpah for testing javascript in VS 2015, but when I use debugging, it throws exception in this file
Unhandled exception at line 4870, column 17 in file:///C:/Users/harrison.nguyen/AppData/Local/Microsoft/VisualStudio/14.0/Extensions/30rb1yrh.odo/ChutzpahTestHarnessFiles/Coverage/blanket_jasmine_v2.js

```0x800a138f - JavaScript runtime error: Unable to get property 'blanketSessionLoader' of undefined or null reference
 //check session state
if (sessionStorage["blanketSessionLoader"]) { ==> sessionStorage is Undefined
            _blanket.blanketSession = JSON.parse(sessionStorage["blanketSessionLoader"]);
}
```

**Comment by mmanela** [comment]
What browser and version is it using? sessionStorage has always been defined on the browsers I am testing.  For now you will need to disable code coverage to avoid the error.

**Comment by bootrider** [comment]
What if I need the coverage?

**Comment by devkeydet** [comment]
Any news on fixing this so that we can use code coverage?

**Comment by mmanela** [comment]
I have not been able to reproduce this issue. Above I asked "What browser and version is it using?"

**Comment by tamariz** [comment]
localStorage is only available on HTTP websites for IE, not on local files execution. That would explain why when debugging you get this exception on sessionStorage. I ran into this issue with Internet Explorer 11 and Visual Studio 2017. With coverage set, debugs fails. If I comment the coverage section of the chutzpah.json, it start working again.
