### ISSUE TITLE
Update Code Coverage Link

### ISSUE THREAD

**Issue by alarimer** [mmanela/chutzpah#630]
Currently the link to Chutzpah in the code coverage results is pointing to the old Codeplex site: http://chutzpah.codeplex.com/
It needs to be updated to GitHub: https://github.com/mmanela/chutzpah

"shutting it down completely on December 15th, 2017" https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/

**Comment by mmanela** [comment]
Thanks for the PR
