### ISSUE TITLE
angular-cli VS2017 and Chutzpah

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#632]
Hi again :-).
I hope you are happy to hear from me again (although all I do is open annoying bugs for you :-)).
I'm in the final stages of my migration from AngularJS to Angular.
I hope I would be able to convert my tests code easily.
In any case I was wondering if you were able to create a small test project to show how one can use chutzpah with Angular?
Previous version of angular was not using any compiling tools and so it was easier to understand how Chutzpah should be configured.
This is no longer the case I think (although I might be wrong).
would appreciate your input.
Here are a couple of articles on VS and angular-cli:
https://medium.com/@levifuller/building-an-angular-application-with-asp-net-core-in-visual-studio-2017-visualized-f4b163830eaa
http://candordeveloper.com/2017/04/12/how-to-use-angular-cli-with-visual-studio-2017/
As always and in contradiction to how the default angular tree looks like I would like the tests and the code to be in separate folders and projects.
I'm slowly building my `Angular4` branch to accommodate for all the changes - currently the compilation of the tests fail which is OK since I haven't got to them yet.
https://github.com/IsraelHikingMap/Site/
Would appreciate your thoughts.
Keep up the good work!

**Comment by mmanela** [comment]
The best I have right now is my Angular2 sample which is pretty basic but includes typescript compilation. https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic. Take a look and let me know if that helps.

**Comment by HarelM** [comment]
I'm migrating out of system.js due to too many issues. So the sample you sent me are not exactly what I'm looking for.
angular-cli compiles the typescript files and reference libraries to a few js files so it might be even easier than before since all the code sits in a few files which should make chutzpah.json file pretty short, not sure how coverage will work but one step at a time.
If you get to try it out before I do please let me know. BTW angular-cli is amazing, you should try it...

**Comment by HarelM** [comment]
I'm in a bit of a dilema.
the [angular style guide](https://angular.io/guide/styleguide) says that the spec files for the tests should be right next to the code itself.
I'm having a hard time letting go of the habit to split the code into production and tests (mainly due to C# and compiled languages I guess).
angular-cli is a command-line tool which I think is less productive than an IDE.
The problem is that due to how angular works and the fact that it compiles and bundles the code into a few files I have no clue how to test the source files with Chutzpah - your help would be greatly appreciated, I don't want to go back to command line test run, it's just counter productive...
My project can be found [here](https://github.com/IsraelHikingMap/Site) and the test folder with the web test belongs to the previous version of angular which could work.
The website can be compiled with `ng build` but after that I don't have a good idea how to make it work - especially with all the `import` that is being done in typescript now...
Thanks ahead.

**Comment by mmanela** [comment]
Does the angular build combine everything into one file? Couldn't you reference that from Chutzpah?

**Comment by HarelM** [comment]
I can, that what I thought about doing, but then I don't know how to write the test code itself since the import statement won't work and adding a reference causes compilation errors...

**Comment by mmanela** [comment]
If the combined file was referenced already, wouldn't the subsequent import/require statement automatically resolve to the already loaded file?

**Comment by HarelM** [comment]
I thought about adding the combined reference to chutzpah.json file.
But then chutzpah engine will need to know how to load this and I think the relevant path will cause issues.
If you could experiment with angular-cli and let me know of a working example I can probably continue from there - one that does not involve placing the test code next to production code.
My other option is to start learning how karma works as angular-cli is supporting this out of the box, but I don't really want to find out the quirks of another test harness...

**Comment by mmanela** [comment]
I can take a look but I wouldn't be surprised if Chutzpah would need some new logic. Angular has been changing pretty fast and Karma is built by the same people to be lock-step in sync.

**Comment by mmanela** [comment]
Which folder do I run ng build from?

**Comment by HarelM** [comment]
I would advise to follow angular guide and create a new project using ng new instead of using my project. Will be easier for you...

**Comment by mmanela** [comment]
Well, I want to make sure its replicating your setup. Can you provide me with a minimal repro of your setup?

**Comment by HarelM** [comment]
Basically this file (used ng new and copied the test file outside, original is still in original location):
[angular-cli-chutzpah.zip](https://github.com/mmanela/chutzpah/files/1100620/angular-cli-chutzpah.zip)
I have moved the test file where I would like the tests file to be.
