### ISSUE TITLE
Enable Chutzpah to run CasperJS tests

### ISSUE THREAD

**Issue by jon241** [mmanela/chutzpah#633]
I would like Chutzpah to run my CasperJS tests. I have not been able to find a workaround so far myself.
If you don't have time, I would be willing to get involved to add that functionality.
I should also say I am not a CasperJS developer, just a user of this great tool.

**Comment by mmanela** [comment]
Hmm interesting. This is not something I ever looked at but I am not against this. What are your thoughts for how it would work?

**Comment by jon241** [comment]
I don't know how the chutzpah internals work but I would see it working like the existing functionality.

Jon-Paul
