### ISSUE TITLE
Chutzpah removes .js extension

### ISSUE THREAD

**Issue by RonNewcomb** [mmanela/chutzpah#634]
I get a clear error:

```
Error: Error opening C:/code/_scratch/A2/hero/tests/hero.detail.spec: No such file or directory
While Running:c:\code\_scratch\a2\hero\tests\hero.detail.spec.js
```

No kidding it can't find the file.  It removed the .js extension.  

This is with "TestHarnessReferenceMode": "AMD"

**Comment by mmanela** [comment]
Can you give a full sample of what you are trying? One that I can download and run

**Comment by icnocop** [comment]
Did you ever find a solution for this issue?

Thank you.

**Comment by icnocop** [comment]
I've attached a sample Visual Studio 2019 solution that can reproduce this issue.

[ChutzpahTestProject.zip](https://github.com/mmanela/chutzpah/files/6513777/ChutzpahTestProject.zip)

Steps to reproduce:
1. Download and unzip attached file.
2. Open ChutzpahTestProject.sln in Visual Studio 2019
3. Right-click on the solution node in Solution Explorer and select "Restore Client-Side libraries"
4. Build the solution
5. Run `chutzpah.console.exe MyFileTests.ts /debug /trace /openInBrowser` and notice the network in the developer tools tries to fetch `MyFileTests` without a file extension.

Any ideas?

Thank you.

**Comment by icnocop** [comment]
I think it's a result of [this line](https://github.com/mmanela/chutzpah/blob/17a0898926b64ab68fac178dff495155455b92bf/Chutzpah/ReferenceProcessor.cs#L185):

`return Path.Combine(Path.GetDirectoryName(path), Path.GetFileNameWithoutExtension(path))`
