### ISSUE TITLE
Inline Reference Path Specification not working

### ISSUE THREAD

**Issue by Avinm** [mmanela/chutzpah#637]
I am using VS 2017 with Chutzpah test adapter and I have the following two files in the same directory:

**Function.js:**
```
const FOO= "BAR";
```

**Function.test.js**
```
/// <reference path="Function.js" />

describe('Tests', function ()
{
    describe('Function', function ()
    {
        it('should export variable', function ()
        {
            console.log(FOO);
            return "";
        });
    });
});
```

When running the test, it fails with the error : **can't find variable FOO**.
Anything I might be missing here?

**Comment by mmanela** [comment]
Chutzpah it still using PhantomJs which I don't believe support const keyword yet. I am looking into to switching off phantom but in the mean team You will need to transpile to a lower ES version.

**Comment by Avinm** [comment]
Const works in PhantomJs, only let doesn't. After a tedious search through the docs I found out you need
` "ExpandReferenceComments" : true` in chutzpah test path specification to get it work. I don't understand why it would be set as false by default. Meanwhile I guess this issue can be closed though

**Comment by mmanela** [comment]
From your post I didn't realize you have a chutzpah.json file. When you do I require you to opt-in to comment references since Chutzpah prefers you list your references explicit in the chutzpah.json file for performance reasons.

**Comment by Avinm** [comment]
Yeah, but It would be helpful to mention that somewhere in this page: https://github.com/mmanela/chutzpah/wiki/Chutzpah-File-References

**Comment by akanieski** [comment]
@mmanela How exactly do you "opt-in" to comment references when your already using chutzpah.json?

**Comment by mmanela** [comment]
On [this page](https://github.com/mmanela/chutzpah/wiki/references-setting) called **ExpandReferenceComments**

**Comment by akanieski** [comment]
Thanks for quick response!

**Comment by charliesibbach** [comment]
Just in case anybody else has trouble with this, I ran around and around with this, because "ExpandReferenceComments" is not in the schema Visual Studio pulls in (http://json.schemastore.org/chutzpah). You need to add "ExpandReferenceComments": true into one of your Tests path definitions. For example: ```"Tests": [
        {"Includes": ["**.test.ts"], "Excludes": [], "ExpandReferenceComments":  true }
    ]```

**Comment by PandaWood** [comment]
I must admit, ExpandReferenceComments took me a while to work out as well... I personally think it should be in by default and out by config - but too late now ;-)

**Comment by leodutra-aurea** [comment]
This should really be in the "File References" page.
Lost 4 hours and almost gave up.

The unique references would not work for legacy projects with bad code organization.

**Comment by leodutra-aurea** [comment]
This should really be in the "File References" page.
