### ISSUE TITLE
Use of location in code causing file not found in test runner.

### ISSUE THREAD

**Issue by SCMorgan** [mmanela/chutzpah#638]
Hi,

The following code causes problems when running chutzpah.
`       window.location.href = url;`

This is handled quietly in Reshaper's test runner, but in Chutzpah will cause the page to redirect to a file not found.

I've fixed it in my case by adding a spy on it's containing method and not calling location, this seems like something Chutzpah should be able to handle on our behalf by default, as I can't think of a scenario in which this wouldn't just break things.

**Comment by mmanela** [comment]
So, you think Chutzpah should stub this out for you by default?

**Comment by SCMorgan** [comment]
Yes that's right. Assuming I'm right about it _never_ being useful to leave the default behaviour.
