### ISSUE TITLE
codecoverageincludes not identifying filename with bootstrap or component

### ISSUE THREAD

**Issue by jish2512** [mmanela/chutzpah#639]
I am having a weird issue. I have a src file testBootstrap.js i have a spec for the same UTs are running fine
But when I am giving this file for codecoverage it doesn't works . If I am renaming the file to testBoot or testBoo anything its working fine codecoverage is coming.
Similar issue with one for src file which has a naming such as testComponent.js
Renaming is a concern as its an existing application and I need to give a solid explanation as why its needed.
if a file name is containing Bootstrap or component its not working
chutzpah.json 

```
{
  "Compile": {
    "Mode": "External"
  },
	"References": [
		{ "Path": "../../../../../src/scripts/wwwroot/lib/jquery/dist/jquery.js" },
		{ "Path": "../../../../../src/scripts/wwwroot/lib/angular/angular.js" },
		{ "Path": "../../../../../src/scripts/wwwroot/lib/angular-mocks/angular-mocks.js" },
		{ "Path": "../../../../../src/scripts/wwwroot/js/boot/testBootstrap.js" }

	],
  "Tests": [

    {
      "Path": "../../../../../Scripts/Tests/UnitTests/"
    }
  ],

  "CodeCoverageExcludes": [
    "*\\\\*.ts*"
  ],
	"CodeCoverageIncludes": [
		"*\\\\src\\\\scripts\\\\wwwroot\\\\js\\\\boot\\\\testBootstrap.js*"
	],
  "CodeCoverageExecutionMode": "Manual",
  "Framework": "jasmine",
  "TestFileTimeout": 20000
}

```

**Comment by mmanela** [comment]
Does this work?

```
"CodeCoverageIncludes": [
		"*testBootstrap.js"
	],
```

**Comment by jish2512** [comment]
Nope this doesn't works

**Comment by mmanela** [comment]
Can you provide a full repro I can run locally?
