### ISSUE TITLE
chutzpah open in browser does not work

### ISSUE THREAD

**Issue by a2nmous** [mmanela/chutzpah#642]
Hi,
I run "Open in browser" in menu context but a message "The requested operation is not allowed" was show in output panel.  Although the browser starts up, the homepage is displayed, but the test result is not displayed.
Any help in resolving this would be greatly appreciated.

chutzpah context menu 4.3.4
chutzpah test adapter 4.3.4

**Comment by mmanela** [comment]
Does it work when you run normally and not in browser?
What version of Windows and VS are you using?

**Comment by a2nmous** [comment]
Yes, it work normally when I run test, not in browser.
OS: Window 10 64bit
Visual studio 2015
type script 1.8.3.6.0
