### ISSUE TITLE
VS 2017 Test Explorer Not Recognising Tests

### ISSUE THREAD

**Issue by tdc-studio** [mmanela/chutzpah#643]
I have created a clean solution in VS 2017 by running `dotnet new angular`.
 See [https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/](url). I want to be able to write Unit Tests against my Angular code (Typescript) using Jasmine and have them appear in VS 2017 Test Explorer. I have installed Chutzpah Test Adapter 4.3.4.

The resulting Solution has a single Project and within that is a folder named 'ClientApp' which is where the Angular files are located. I have created a new file named 'simple-test.spec.ts' within the ClientApp folder. The test code is as follows:

```
describe('Simple Test', () => {
it("true is true", () => expect(true).toEqual(true));
});
```
I created a `chutzpah.json` file with the following code:
```
{
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    {
      "Path": "./ClientApp",
      "Includes": [ "**.ts" ],
      "Excludes": [ "**.d.ts" ]
    }
  ],
  "Tests": [
    {
      "Path": "./ClientApp",
      "Includes": [ "*spec.ts" ]
    }
  ]
}
```
The Project builds fine and runs fine, displaying the resulting website in Chrome. No matter what I try I cannot get my test to appear in Test Explorer or run.

**Comment by mmanela** [comment]
If you run with the command line client do you see errors?

**Comment by tdc-studio** [comment]
Thanks for the reply,

1. Are you referring to the Chutzpah command line client?
2. No, I meant that when I open my web application in Chrome it runs fine, in other words the Solution builds and runs with no errors.
3. My Angular code is written in Typescript. My tsconfig.json file is as follows:
`
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "lib": [ "es6", "dom" ],
    "types": [ "node", "jasmine" ]
  },
  "exclude": [ "bin", "node_modules", "core-js" ],
  "atom": { "rewriteTsconfig": false }
}
`
This is new to me, as you may tell, I just want some guidance to get VS2017 running Jasmine tests against my Typescript code.

**Comment by tdc-studio** [comment]
I tried a different approach this morning. I created a clean VS2017 Solution by running `dotnet new angular`. The default project has a `spec` folder and with this is a `support` folder and within that is a file named `jasmine.json`. The file is as follows:
`
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
`
There is also a folder at root level named `ClientApp` where the Angular files reside. Within this is a folder named `test` with the following 2 files within it: `boot-tests.ts` and `karma.conf.js`.

The `boot-tests.ts` file is as follows:
`
// Load required polyfills and testing libraries
import 'reflect-metadata';
import 'zone.js';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import * as testing from '@angular/core/testing';
import * as testingBrowser from '@angular/platform-browser-dynamic/testing';

// There's no typing for the `__karma__` variable. Just declare it as any
declare var __karma__: any;
declare var require: any;

// Prevent Karma from running prematurely
__karma__.loaded = function () {};

// First, initialize the Angular testing environment
testing.getTestBed().initTestEnvironment(
    testingBrowser.BrowserDynamicTestingModule,
    testingBrowser.platformBrowserDynamicTesting()
);

// Then we find all the tests
const context = require.context('../', true, /\.spec\.ts$/);

// And load the modules
context.keys().map(context);

// Finally, start Karma to run the tests
__karma__.start();
`
The `karma.conf.js` file is as follows:
`
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
    config.set({
        basePath: '.',
        frameworks: ['jasmine'],
        files: [
            '../../wwwroot/dist/vendor.js',
            './boot-tests.ts'
        ],
        preprocessors: {
            './boot-tests.ts': ['webpack']
        },
        reporters: ['progress'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        mime: { 'application/javascript': ['ts','tsx'] },
        singleRun: false,
        webpack: require('../../webpack.config.js')().filter(config => config.target !== 'node'), // Test against client bundle, because tests run in a browser
        webpackMiddleware: { stats: 'errors-only' }
    });
};
`
Using your sample code I created a new Javascript file named `chutzpah-code.js` and placed it within the `spec` folder. This contains your sample `stringlib`, `mathlib` and `log` functions. I then created a new file named `chutzpah-test.spec.js` within the `spec` folder. This contained your corresponding Jasmine test code. Finally I created a `chutzpah.json` file at root level and included the following code:
`
{
  "References": [
    {
      "Path": "spec/chutzpah-code.js"
    }
  ],
  "Tests": [
    {
      "Path": "spec/chutzpah-test.spec.js"
    }
  ]
}
`

I built the project and Test Explorer recognised the tests. Hooray.

Can you please explain the relationship between `chutzpah.json`, `karma.config.js` and jasmine.json`?

I now need to adjust the configuration to allow me to test my Typescript files which will reside within `ClientApp/app`, if you have any advise it would be very welcome.

Thank you.

**Comment by tdc-studio** [comment]
I have made some adjustments and now when I run `npm test` Karma is started and it reads my `karma.comf.js` file, next Webpack creates its bundles, Karma server is started, Chrome launches and all of my Typescript tests are found and run. Autowatch works fine but of course the results are sent to the command line.

I'm close, I now want to control and view the testing in Test Explorer.

Can you please advise me how I configure Chutzpah to move me on the last step.
