### ISSUE TITLE
Can't discover/run tests against Angular

### ISSUE THREAD

**Issue by bradley-dotnet** [mmanela/chutzpah#644]
Using VS 2017, Chutzpah 4.3.

I am trying to get a basic Angular test running using the sample (https://github.com/mmanela/chutzpah/tree/master/Samples/Angular2/Basic) as a guide. I have tried all the chutzpah.json files I could find; this one seems to get the closest:

```
{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },

  "Tests": [
    {
      "Includes": [ "*.spec.ts" ]
    }
  ],
  "References": [
    { "Path": "../node_modules/core-js/client/shim.min.js" },
    { "Path": "../node_modules/systemjs/dist/system.js" },
    { "Path": "../node_modules/zone.js/dist/zone.js" },
    { "Path": "../node_modules/zone.js/dist/long-stack-trace-zone.js" },
    { "Path": "../node_modules/zone.js/dist/proxy.js" },
    { "Path": "../node_modules/zone.js/dist/sync-test.js" },
    { "Path": "../node_modules/zone.js/dist/jasmine-patch.js" },
    { "Path": "../node_modules/zone.js/dist/async-test.js" },
    { "Path": "../node_modules/zone.js/dist/fake-async-test.js" },
    { "Path": "../node_modules/reflect-metadata/Reflect.js" },
    { "Path": "systemjs.config.js" }
  ],
  "Server": {
    "Enabled": true
  }
} 
```

However, this generates the following error:

> Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
> Version 4.3.0.0
> Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).
> 
>                                                                                                                                     Error: Unhandled Promise rejection: Unexpected token 'const'
>   Evaluating http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/wwwroot/src/General/data-status.component.spec.js
>   Loading src/General/data-status.component.spec ; Zone: <root> ; Task: Promise.then ; Value: Error: Unexpected token 'const'
>   Evaluating http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/wwwroot/src/General/data-status.component.spec.js
>   Loading src/General/data-status.component.spec eval@[native code]
> Re@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:25534
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:32670
> S@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:7553
> E@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:7050
> k@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:6049
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:39071
> invoke@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:391:31
> run@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:141:49
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:818:60
> invokeTask@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:424:36
> runTask@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:191:57
> drainMicroTaskQueue@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:584:42
> g@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/core-js/client/shim.min.js:8:19058
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/core-js/client/shim.min.js:8:19180
> k@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/core-js/client/shim.min.js:8:14294
> at onUnhandledError in http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js (line 643)
> While Running:D:\code\SaffariNet\SmartCandleServices\TechMenuService\wwwroot\src\General\data-status.component.spec.ts
>                                                                                                                                     Error: Error: Uncaught (in promise): Error: Unexpected token 'const'
>   Evaluating http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/wwwroot/src/General/data-status.component.spec.js
>   Loading src/General/data-status.component.spec
> eval@[native code]
> Re@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:25534
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:32670
> S@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:7553
> E@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:7050
> k@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:6049
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js:4:39071
> invoke@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:391:31
> run@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:141:49
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:818:60
> invokeTask@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:424:36
> runTask@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:191:57
> drainMicroTaskQueue@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js:584:42
> g@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/core-js/client/shim.min.js:8:19058
> http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/core-js/client/shim.min.js:8:19180
> k@http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/core-js/client/shim.min.js:8:14294
> at onUnhandledError in http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/zone.js/dist/zone.js (line 645)
> While Running:D:\code\SaffariNet\SmartCandleServices\TechMenuService\wwwroot\src\General\data-status.component.spec.ts
>                                                                                                                                     Error: Timeout occurred when executing test file
> While Running:D:\code\SaffariNet\SmartCandleServices\TechMenuService\wwwroot\src\General\data-status.component.spec.ts
> 
> === 0 total, 0 failed, took 11.62 seconds ===

If I put the "shim.min.js" at the bottom as in the sample I get:

> Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
> Version 4.3.0.0
> Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).
> 
>                                                                                                                                     Error: ReferenceError: Can't find variable: Promise
> in http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/node_modules/systemjs/dist/system.js (line 4)
> While Running:D:\code\SaffariNet\SmartCandleServices\TechMenuService\wwwroot\src\General\data-status.component.spec.ts
>                                                                                                                                     Error: TypeError: undefined is not a constructor (evaluating 'System.config')
> in http://localhost:9876/code/SaffariNet/SmartCandleServices/TechMenuService/wwwroot/systemjs.config.js (line 5)
> While Running:D:\code\SaffariNet\SmartCandleServices\TechMenuService\wwwroot\src\General\data-status.component.spec.ts
>                                                                                                                                     File: D:\code\SaffariNet\SmartCandleServices\TechMenuService\wwwroot\src\General\data-status.component.spec.ts
>      0 total, 0 failed, took 0.01 seconds
> 
> Tests complete: 0
> === 0 total, 0 failed, took 3.44 seconds ===

The error seems to occur regardless of what is in the actual test file. At no point have I actually suceeded in the console runner or VS discovering the test itself, let alone by directory (I am running via console and manually giving it my one test file); but I can't tell if that is related.

**Comment by bradley-dotnet** [comment]
Note that Karma has trouble if using the PhantomJS browser also; so it may just be related to that.

**Comment by mmanela** [comment]
PhantomJS is running older JS and needs to be replaced. But until then you may need to transpile to an older ECMA script version.
