### ISSUE TITLE
How to run unit test in Visual Studio 2015 Enterprise for Typescript in SharePoint application

### ISSUE THREAD

**Issue by spvjebaraj** [mmanela/chutzpah#645]
Team,
I'm working in SharePoint Office 365 project and I want to do the unit testing with Visual Studio 2015 Enterprise Edition. Can you please share the details how to do that?

Philip

**Comment by mmanela** [comment]
What specifically are you looking at. I have documentation and example on running JavaScript tests. Have you looked at those? Do you have a specific question about Sharepoint? If you share details I can try to help but don't know much about that
