### ISSUE TITLE
[Typescript,RequireJS,Jasmine] Jasmine tests are not found

### ISSUE THREAD

**Issue by MLangHSE** [mmanela/chutzpah#647]
Hello,

first i want to say thanks for this great plugin. I used it with pure JS and i was very satisfied with the results. Now i had to conver my project to TypeScript and i have problems with the correct setup in chutzpah.json.

I'm using VS 2017 15.2 (24630.16), chutzpah 4.3. For compiling i using the VS builtin process with a tsonfig.json file. For some reason the written tests are not found. I tried many configuration variants but with no effort. I created a sample project that have the same problem like my productive project.

The logfile says Message:Unable to build test context.
It would be nice, when you could have a look at settings. The destination path (dist) and all subfolders have to be unchanged. I want the compiled js files in the folder "/dist/source/*. In the folder core are the program files in tests sould be the test files.

Thanks in advance

Sample Project:
[TypeScriptHTMLApp1.zip](https://github.com/mmanela/chutzpah/files/1183093/TypeScriptHTMLApp1.zip)

**Comment by mmanela** [comment]
Your Chutzpah.json doesn't look correct. I think something like this should work. The key is to properly tell chutzpah how to map from source to output directory

```
{
	"Framework": "jasmine",
	"TestHarnessReferenceMode": "AMD",
	"TestHarnessLocationMode": "SettingsFileAdjacent",
	"AMDBaseUrl": "dist/source",
	"AMDAppDirectory": "source/TS",
	"References": [
		{
			"Path": "dist/source/require.js",
			"IsTestFrameworkFile": true
		}
	],
	"Tests": [
		{ "Path": "source/TS/tests" }
	],
	"Compile": {
		"Mode": "External",
		"Extensions": [ ".ts" ],
		"ExtensionsWithNoOutput": [ ".d.ts" ],
    "Paths": [
      {
        "SourcePath": "source/TS",
        "OutputPath": "dist/source"
      }
    ]
	},
	"EnableTracing": true,
	"TraceFilePath": "./trace.log"

}
```
