### ISSUE TITLE
Timeout occurred when executing test file

### ISSUE THREAD

**Issue by AlbertShamsiyan** [mmanela/chutzpah#652]
Hi, 

I'm trying to use the following command line: `..\..\Chutzpah.4.3.4\tools\chutzpah.console.exe SpecRunner.html /coverage /lcov coverage.dat` while using the following chutzpah.json
`{
   "Framework": "jasmine",
   "EnableTestFileBatching": true,
   "IgnoreResourceLoadingErrors": true,
   "EnableTracing": true,
   "TraceFilePath": "chutzpah.log"
}`
Yet, the following error being raised:

> Error: Timeout occurred when executing test file
While Running:e:\MyProj\Tests\spec\SpecRunner.html

Please note that I've TRIED adding  `"TestFileTimeout": 60000` (with \ without surrounding quotes), yet seems like it being ignored ...   

Your help is highly appropriated - THX

**Comment by mmanela** [comment]
What is in your HTML file? Typically Chutzpah works best when you configure it for running directly on JS files.

**Comment by AlbertShamsiyan** [comment]
Html file just include references to Jasmine files, MVS recorder files, and test files.
Is a standard specRunner.html of Jasmine.
Here is example: https://github.com/jasmine/jasmine/blob/master/grunt/templates/SpecRunner.html.jst
 
Thanks

**Comment by mmanela** [comment]
I know, and that is ok but Chutzpah provides the ability to generate that for you in most cases. If you give Chutzpah your own HTML there is often a few extra steps to make sure Chutzpah is hooked in properly to when it need to pick up the test cases
