### ISSUE TITLE
Code coverage results not appearing in VS 2013 using Chutzpah

### ISSUE THREAD

**Issue by sajesh1985** [mmanela/chutzpah#654]
I have configured Chutzpah nuget package in VS 2013 Premium. I am using jasmine to write my test cases, I am able to see the tests are running on the Unit test windows but I am not able to see the Code coverage results for my javascript code. The browser doesnt show the code coverage results.

My chutzpah.json file looks like this:

```
{
"Framework" : "jasmine",
"TestHarnessReferenceMode": "AMD",
"TestHarnessLocationMode": "SettingsFileAdjacent",
"References":[
    { "Path" : "../../Scripts/jasmine-2.5.2/jasmine_favicon.png"},
    { "Path" : "../../Scripts/jasmine-2.5.2/jasmine.css"},
    { "Path" : "../../Scripts/jasmine-2.5.2/jasmine.js" },
    { "Path" : "../../Scripts/jasmine-2.5.2/jasmine-html.js"},
    { "Path" : "../../Scripts/jasmine-2.5.2/boot.js" },
    { "Path" : "../../Scripts/jquery/1.10.2/jquery-1.10.2.js"},
    { "Path" : "../../Views/Claim/Startup/SpecHelper.js" }
],
"Tests": [
  { "Path" : "SpecHelper.spec.js"}
],
"CodeCoverageExecutionMode": "Always",
"EnableCodeCoverage": "true",
"CodeCoverageIncludes": ["../../Views/Claim/Startup/*"]
}
```

And this file I have placed under my tests folder where my spec files are present. Please let me know what I am missing to configure this properly.

**Comment by sajesh1985** [comment]
Even from command prompt I am not able to generate coverage report, the error it is showing is "Error: Timeout occurred when executing test file". I can see a temp file that is created under tests folder but it goes off, i tried seeing the html. I see something like this:  <script type="text/javascript" src="http://localhost:9876/__chutzpah__/chutzpah_boot.js?sha=53b2a50be82a9c5fa2f11ece83d3c3992d010769"></script>
<link rel="stylesheet" type="text/css" href="http://localhost:9876/__chutzpah__/jasmine/v2/jasmine.css?sha=35d04b846e8b6fa57d18fc41fa028f395e71175c"/>
<script type="text/javascript" src="http://localhost:9876/__chutzpah__/jasmine/v2/jasmine.js?sha=0a89603eaa502899263ddb6c621ac4859773ebc2"></script>
<script type="text/javascript" src="http://localhost:9876/__chutzpah__/jasmine/v2/jasmine-html.js?sha=a8cf2efb194b374bb0fad5c98b8764f81d592d49"></script>
<script type="text/javascript" src="http://localhost:9876/__chutzpah__/jasmine/v2/boot.js?sha=bb5b0b62a69f7bff78bac2d31712afdd74bacd15"></script>
<link rel="shortcut icon" type="image/png" href="http://localhost:9876/__chutzpah__/jasmine/v2/jasmine_favicon.png?sha=6d4877de949769bf6fba65c09c2acb0718b008a0"/>

    <script type="text/javascript" src="../../../packages/Chutzpah.4.3.4/tools/ChutzpahTestHarnessFiles/Coverage/blanket_jasmine_v2.js?sha=c4ae5e17696ac3606b474affbcb14199b1404ac8" data-cover-flags="ignoreError autoStart" data-cover-only="//.*/" data-cover-never="['http://localhost:9876/__chutzpah__/chutzpah_boot.js?sha=53b2a50be82a9c5fa2f11ece83d3c3992d010769','http://localhost:9876/__chutzpah__/jasmine/v2/jasmine.js?sha=0a89603eaa502899263ddb6c621ac4859773ebc2','http://localhost:9876/__chutzpah__/jasmine/v2/jasmine-html.js?sha=a8cf2efb194b374bb0fad5c98b8764f81d592d49','http://localhost:9876/__chutzpah__/jasmine/v2/boot.js?sha=bb5b0b62a69f7bff78bac2d31712afdd74bacd15','../../../packages/Chutzpah.4.3.4/tools/ChutzpahTestHarnessFiles/Coverage/blanket_jasmine_v2.js?sha=c4ae5e17696ac3606b474affbcb14199b1404ac8']" data-cover-timeout="5000"></script>

    
    <script type="text/blanket" src="../../Scripts/jquery/1.10.2/jquery-1.10.2.js?sha=b84283e6645110fd25d1e42c4f95114365700978"></script>
<script type="text/blanket" src="../../Views/Claim/Startup/SpecHelper.js?sha=9f76f83ae570b8cd0b2571449b5a4e6c3d77e923"></script>
<script type="text/javascript">window._Chutzpah_covobj_name='_$blanket';</script>

    
    <script type="text/javascript">

        (function () {

            var amdTestPaths = ["SpecHelper.spec",];
            window.chutzpah.boot(amdTestPaths);

            if (window.chutzpah.usingModuleLoader) {
                if("http://localhost:9876/TFS_DCF_FSE/DCF.BenefitRecovery/1.0.0/dev/DCF.BenefitRecovery.WebUI/Tests/Claim") {
                    window.chutzpah.amdConfig({
                        baseUrl: "http://localhost:9876/TFS_DCF_FSE/DCF.BenefitRecovery/1.0.0/dev/DCF.BenefitRecovery.WebUI/Tests/Claim"
                    });
                }

**Comment by mmanela** [comment]
I suggest you run chutzpah exe with /coverage and /openinbrowser and see why it is failing. 

But also try this as your chutzpah.json

```

"Framework" : "jasmine",
"TestHarnessReferenceMode": "AMD",
"TestHarnessLocationMode": "SettingsFileAdjacent",
"References":[
{ "Path" : "../../Scripts/jquery/1.10.2/jquery-1.10.2.js", "IsTestFrameworkFile": true},
{ "Path" : "../../Views/Claim/Startup/SpecHelper.js" }
],
"Tests": [
{ "Path" : "SpecHelper.spec.js"}
],
"CodeCoverageExecutionMode": "Always",
"EnableCodeCoverage": "true",
"CodeCoverageIncludes": ["../../Views/Claim/Startup/*"]
}
```

**Comment by sajesh1985** [comment]
Thanks for your reply, i tried with your suggestion but I see a blank browser window, when i debug I see the code inside initializeJasmine  doesnt executes, originalExecute == env.execute is false
window.initializeJasmine = function () {

        // [Chutzpah]: Guard against multiple initializations when running blanket
        if (!initialized && originalExecute == env.execute) {
            htmlReporter.initialize();
            env.execute();
            initialized = true;
        }
    };
Command i tried "C:\dev\packages\Chutzpah.4.3.4\tools>chutz
pah.console.exe /coverage /path C:\dev\Benefit\Tests\Claim\SpecHelper.spec.js /openInBrowser"...i also tried the trace..and i see this

chutzpah.console.exe Error: 0 : Time:08:51:42.6586292; Thread:1; Message:Test file 'C:\dev\Benefit\Tests\Claim\SpecHelper.spec.js' timed out after running for 10525.8853 milliseconds
chutzpah.console.exe Information: 0 : Time:08:51:42.6781599; Thread:1; Message:Ended headless browser: C:\dev\packages\Chutzpah.4.3.4\tools\phantomjs.exe with PID: 151576 using args: --ignore-ssl-errors=true --proxy-type=none --ssl-protocol=any "C:\dev\packages\Chutzpah.4.3.4\tools\ChutzpahJSRunners\jasmineRunnerV2.js" "file:///C:/dev/DCF.Benefit/Tests/Claim/_Chutzpah.dbd4211fc7383dd3de6ec5dcdfe4b6d761b8b667.test.html" execution 10000 False 
chutzpah.console.exe Error: 0 : Time:08:51:42.6937846; Thread:1; Message:Headless browser returned with an error: Timeout occurred when executing test file

**Comment by mmanela** [comment]
Can you send me a sample that I can test locally?

**Comment by sajesh1985** [comment]
I am using the sample codethat is under Samples/Basic.
I am attaching the structure of my project, the code is the same, i am trying to make the Basic code up and running on my VS 2013
[Chutzpah.docx](https://github.com/mmanela/chutzpah/files/1303299/Chutzpah.docx)

**Comment by sajesh1985** [comment]
Matthew just to let you know I dont have nodejs installed on my system, I believe there is something related to environment settings thats why I see Timeout error

**Comment by sajesh1985** [comment]
Hi Matthew, Did you get a chance to look into this issue?

**Comment by mmanela** [comment]
Can you give me a zip or a link to a repo that I can clone and run? That is best for me to debug and isolate your issue.

**Comment by sajesh1985** [comment]
Hi Matthew...sample application...https://github.com/sajesh1985/Sajesh/tree/Test_Git...Please Let me know if you are able to access it

**Comment by sajesh1985** [comment]
Were you able to look into the issue?

**Comment by mmanela** [comment]
I havent had a chance yet, will try to get to it tomorrow

**Comment by mmanela** [comment]
In your sample you had Chutzpah set to AMD mode but you are not using AMD. Removing this fixes your issue:

```

	"TestHarnessReferenceMode": "AMD",
```

**Comment by sajesh1985** [comment]
Awesome...thanks Matthew..it was so simple, my bad..small things are always difficult to find.
Appreciate your time for looking into this. I am closing this issue.
