### ISSUE TITLE
Version of QUnit is outdated

### ISSUE THREAD

**Issue by victor175** [mmanela/chutzpah#656]
Hello,

Is it possible for you to update the version of qunit once again to the latest (2.4.0)?
Some major changes to the API were introduced and it would be very helpful if you can do that, so we can benefit from them.

I already did some tests, just replacing the qunit files with the newest ones and everything seem to work without any problems, so it looks compatible (should be a straightforward replacement).

**Comment by mmanela** [comment]
Support was added in the last version for Qunit 2.4.0, to use it in your Chutzpah.json file set ```FrameworkVersion: "2"```
