### ISSUE TITLE
PhantomJS doesn't support ES6 

### ISSUE THREAD

**Issue by smilealdway** [mmanela/chutzpah#657]
Current PhantomJS in Chutzpah test running doesn't support ES6 functionality (including simple keywords like "let", "Const" etc.) This has basically rendered use of chutzpah in our project pointless. 

Is there plan to update to latest PhantomJS or instead migrate to GoogleChrome/puppeteer? Is there a fork one is aware of?

**Comment by mmanela** [comment]
I am working on switching to headless Chrome but blocked by a couple issues right now. I am working through it and hopefully will be able to get that done soon.
