### ISSUE TITLE
Issue with code coverage when using webpack build

### ISSUE THREAD

**Issue by sanjeet1827** [mmanela/chutzpah#658]
Hi,

I recently switched to webpack module loader/bundler and could manage all test cases to ve discover-able in test case explorer but not able to get the code coverage.

I tried Chtuzpah context menu option "Run chutzpah with>Coverage". 
Below is my Chutzpah.json

```
{
"Compile":{
"Mode":"External"
},
"References":[
{"Path":"common,bundle.js"}// framework
{"Path":"app,bundle.js"}// application code
],
"Tests":[
{"Path":"test.bundle.js"}// all test cases
],
"EnableCodeCoverage":"true",
"CodeCoverageExecutionMode":"Always",
"CodeCoverageIncludes":["app.bundle.js"]
}
```

I simply made right click on folder which contains all bundles and perform "Run chutzpahwith>Coverage"

I am using Chtuzpah 4.2.3

**Comment by mmanela** [comment]
What are the errors you are seeing? What does the test harness contain?

**Comment by sanjeet1827** [comment]
I can not see any error in output window. which are you saying test harness , temp .html files or Chutzpah.log ?

Does my Chutzpaj.json seems correct?

I am not able to get the hint why it can not get the coverage. I opens the browser displaying coverage report but It always shows 
Covered/Total Smts as 0/0 and Coverahe (%) as NaN%

**Comment by mmanela** [comment]
Can you provide a repro?

**Comment by sanjeet1827** [comment]
I can not provide the original repo as I am not allowed to do but will try to create a new sample.

**Comment by sanjeet1827** [comment]
Issue is resolved , Sorry for late reply, I had to made some config changes and it worked.

Thanks for patience.
