### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'window.mocha.reporter(chutzpahMochaReporter)'

### ISSUE THREAD

**Issue by PandaWood** [mmanela/chutzpah#659]
Hi
I can't get Chutzpah to work with Mocha HTML files

I've just installed  4.3.5
I've retried this using Mocha v3.5 (latest), 2.5 and 1.21.5 (years ago)
I have tried with config file and without - it is running the test because console.debug message are output

ran ```chutzpah.console.exe scripts/ts/tests/mocha/idify.mocha.html```
with config I run ```chutzpah.console.exe chutzpah.json```
The HTML files in question are Mocha tests that all work fine when opened in a browser

```
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.3.5.0
Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).

Error: TypeError: undefined is not a constructor (evaluating 'window.mocha.reporter(chutzpahMochaReporter)')
at onMochaLoaded in undefined (line 129)
 (line 130)
While Running:C:\code\src\Web.Site\scripts\ts\tests\mocha\idify.mocha.html

Error: Timeout occurred when executing test file
While Running:C:\code\src\Web.Site\scripts\ts\tests\mocha\idify.mocha.html
```

**Comment by PandaWood** [comment]
So the question is why window.mocha doesn't have a property called "reporter".
Without getting deep in Chutzpah code, I tried using an older version of Mocha (2.5.1) - still same error

**Comment by PandaWood** [comment]
I'll try using .js files directly and report back - otherwise I think we might just have to strictly point out that Chutzpah doesn't support Mocha HTML templates

**Comment by mmanela** [comment]
Thanks, can you give me a small repro I can run locally to debug?

**Comment by PandaWood** [comment]
See above, run command ```chutzpah.console test-mocha.html``` in dir ```Samples\Basic\Mocha```
