### ISSUE TITLE
chutzpah_reference work tandem with config References?

### ISSUE THREAD

**Issue by PandaWood** [mmanela/chutzpah#662]
I'll get you a repro for this if you think it should work.

I have a problem where I've set up chutzpah.json with various "References"
Then, in the test itself, I reference the file being tested (as below)

But the js errors I get and the debug output confirms that the chutzpah reference is not being included.

Do you know if in-file references and config references are designed to work together - ie could it be purposeful or accidental design that only one of them can be used? Or do I presume I'm doing something wrong...

**In test file**
```/// <chutzpah_reference path="../../core/core.util.js" />```

**In config**
```"References" :  [
    { "Path": "lib/core/jquery.js" },
    { "Path": "lib/core", "Includes": ["*.js"], "Excludes": ["jquery.js", "*.min.js"] },
    { "Path": "common" },
```

**Comment by mmanela** [comment]
If you are combining them you need to update the chutzpah.json file to have ExpandReferenceComments  set on the references.

See
https://github.com/mmanela/chutzpah/wiki/Breaking-change-to-nested-reference-comments-in-version-4.1

**Comment by PandaWood** [comment]
Thanks yes, that's it.
