### ISSUE TITLE
Want to use  ES6 code in  jasmine can you suggest me the process

### ISSUE THREAD

**Issue by saroj08** [mmanela/chutzpah#664]
what changes i have to make in chutzpah.json to run my jasmine-es6 code

**Comment by PandaWood** [comment]
You'll have to transpile es6 to es5 yourself (eg using Babel) before calling Chutzpah.

As per this issue https://github.com/mmanela/chutzpah/issues/618

**Comment by saroj08** [comment]
Thanks for your answer. i understood the points
