### ISSUE TITLE
chutzpah.json being ignored when running tests from the ReSharper test explorer

### ISSUE THREAD

**Issue by MrYossu** [mmanela/chutzpah#665]
Having struggled with my chutzpah.json file being ignored, I finally discovered that if I right-click on a test project in the Visual Studio Solution Explorer and choose "Run JS Tests" then the file is read, the tests pass, and I get the results in the Output window.

Similarly, if I use the VS Test Explorer, it works fine.

However, if I use the ReSharper Unit Tests Explorer window, the chutzpah.json file is ignored and the tests fail.

Given the number of developers that use R#, is there any way to have the R# Test Explorer to work with Chutzpah? It's a pain to have to use two different windows to run tests.

**Comment by mmanela** [comment]
I do not own the resharper client and have no context on it. You should follow up with JetBrains and see if there is an issue on their side...

**Comment by slawomir-brzezinski-at-interxion** [comment]
@MrYossu thanks for raising it with them.  

Is the ticket public, by any chance? If so, could you share a link?

**Comment by MrYossu** [comment]
The ticket isn't public unfortunately, but their response was that it was due to a bug in R# version 2017.1.2. They recommended using version 2017.2.2 or later, and that seems to have fixed the problem.

Hope this helps someone else.
