### ISSUE TITLE
/failOnError option for Chutzpah Test Runner

### ISSUE THREAD

**Issue by francittadini** [mmanela/chutzpah#667]
Hi!

It would be nice if there was a way to use the options described in https://github.com/mmanela/chutzpah/wiki/Command-Line-Options in the Test Runner Visual Studio extension.

For example, I could avoid the situation in which having no expectations shows an error but the test passes.

Thank you 😃

**Comment by mmanela** [comment]
Fail on error just tells chutzpah to return a non-zero exit code on the command line. It doesn't change what the test runner like Qunit reports. What are you looking for to happen in VS?

**Comment by francittadini** [comment]
I'm trying to avoid this situation:
![image](https://user-images.githubusercontent.com/5400670/32731634-218b62bc-c869-11e7-8057-2595f1973263.png)

I think the runner should say that the test failed in this case. What do you think?
