### ISSUE TITLE
75% of my tests fail, but only with chutzpah

### ISSUE THREAD

**Issue by brunis** [mmanela/chutzpah#669]
Hi, i have opened every test html file i have and they all succeed 100% in Edge, Chrome and Firefox, but with chutzpah, 75% fails. Not sure if it's just PhantomJS or what's causing this. Any way i can assist in debugging these failures?

**Comment by Zelig880** [comment]
Hi,

In many cases this kind of issues are related to phantomJs. One of the most
common issue is the lack of ES6 in chutzpah that will fail the test. ( for
example declaring the function with () => will break all tests).

When you run the test with Chutzpah, you can choose to run them in a
Browser. If by doing so, the test pass, it means that it is most probably
the Phantom issue. If on the other hand, they fail there too, then it will
be related to the config.

I hope the above message help.

Regards

**Comment by mmanela** [comment]
I am working on migrating Chutzpah to headless chrome which should hopefully help with this...

**Comment by Nagendracv** [comment]
until that time use es6 shim

**Comment by nm4568** [comment]
Hello,  I have a similar issue but mine isn't ES6 related.  In my case, I am asserting an element's style.left and style.width properties.  Oddly enough, my tests pass when running headless  if I use the left and width values from IE 9 (which leads me to believe that IE 9 is currently being used to run headless).  

Any ETA as to when I will be able to run headless chrome? 

I couldn't find any applicable settings to add within my Chutzpah.json config. I am executing the headless tests from within Visual Studio test explorer and I have both the "Chutzpah Test Adaptor for the Test Explorer" and "Chutzpah Test Runner Context Menu Extension" installed both version 4.3.6.  I did see there was a command line option /openInBrowser which is great if you are running in command line.

**Comment by mbp** [comment]
Do you need any help with getting Chrome headless working @mmanela? Hard to know what is the status/current issues.

**Comment by mmanela** [comment]
In master now I have the changes pushed to support both Headless chrome and JsDom. However, It needs testing, lots of it. And I just havent had the time to do that. If you are interested I would love some help. I tested it on a large code base and lots of tests failed BUT it could be because differences in PhantomJS versus JsDom and Chrome. I just need more testing.
