### ISSUE TITLE
Chutzpah is a great tool but very hard to get up and running

### ISSUE THREAD

**Issue by tarquinrex** [mmanela/chutzpah#670]
Hi MManela,
I appreciate all the time and effort you have taken in writing this great tool however after a day of trying to get it to work I've had to give up due to lack of time. I'm running VS 2017 Professional with an Angular 4 project and have tried:

1) Your sample angular 2 application (does to work when loading into VS 2017!)
2) Various other demos and samples in GitHub and the web (most also don't work in VS 2017)
3) Even tried to take a sample that does work (https://github.com/GeorgDangl/NetCoreHeroes) and them slowly migrate config files over to my non-working solution but still cannot get it to work.

The main problem is the chutzpah configuration and its interaction with the various testing frameworks such as karma and jasmine. Its really difficult to work it all out and some more guidance on the interactions between the various configs is needed. 

Tx

**Comment by PandaWood** [comment]
Just to be clear, are you saying the VS2017 extension is not working for you?

I use Chutzpah on the command line without the VS2017 plugin, so I'm probably of no help, but I would have thought you would get it working on the command line first and then check it in the extension - since the command line can give you tracing and ways of figuring out what's wrong

**Comment by tarquinrex** [comment]
I’m just saying that’s its very hard to get the tool up and running. If you are wanting a large uptake of the tool then the process needs to be made a bit clearer – there are a myriad of config files and the interaction between all of them is not easy to understand.

**Comment by mmanela** [comment]
@tarquinrex Thanks for the feedback, Is there a specific question/issue I can help you with?

**Comment by joeJazdzewski** [comment]
I am seemly having the same issue.

My System is 

- OS: Win10 Enterprise
- IDE: VS2017

I have downloaded the [NetCoreHeroes](https://github.com/GeorgDangl/NetCoreHeroes)  solution and opened it. 
I have installed the chutzpah test adapter and installed the chutzpah nuget package both of them are 4.3.6.

When I build I only see the tests for the NetCoreHeroes.Tests.Controllers.HeroesControllerTests+GetReturnResults

**Comment by GeorgDangl** [comment]
Hey @joeJazdzewski, I just re-checked [NetCoreHeroes](https://github.com/GeorgDangl/NetCoreHeroes) with the latest Chutzpah version 4.3.6, both in VS2017 and as NuGet package. Both the tests in Visual Studio 2017 as well as the CI scripts are running.

However, on a fresh clone of the project, I had to build the project in Visual Studio and then needed to restart it before any tests were picked up, so I guess there is something flaky.

NetCoreHeroes is still on TypeScript 2.4, do you have the appropriate SDK installed in Visual Studio?

**Comment by joeJazdzewski** [comment]
I have 2.3 and 2.5 installed but I started the project back up and built they are now appearing in the test explorer... Its working now

**Comment by ndhanh** [comment]
I have same issue.

I did the same steps that GeorgDangl mentioned, but unit tests does not appear in the Test Explorer

I'm using VS2017 Update 6 (15.6.4), and installed latest version of Chutzpah (4.3.6).
![image](https://user-images.githubusercontent.com/3151344/39398223-b5e83060-4abf-11e8-9ed5-7538842bfd64.png)
