### ISSUE TITLE
Using the test adapter without the vs extension

### ISSUE THREAD

**Issue by stavroskasidis** [mmanela/chutzpah#676]
The nuget package has to be changed to be able discover and run the tests without the extension (like xunit does). Also the new PackageReference nuget format should be supported to run seamlessly with CI tools like TFVC

See here (relative solutions)
https://github.com/NuGet/Home/issues/4837
https://github.com/NuGet/Home/issues/5803

**Comment by mmanela** [comment]
Historically, the test framework did *not* support running chutzpah without a vsix due to its needing to use a custom **ITestCaseContainerDiscoverer**. The team who owns the adapter framework in VS has talked about fixing this but I have no heard of any change yet.

**Comment by mmanela** [comment]
Historically, the test framework did *not* support running chutzpah without a vsix due to its needing to use a custom **ITestCaseContainerDiscoverer**. The team who owns the adapter framework in VS has talked about fixing this but I have no heard of any change yet.
