### ISSUE TITLE
VS2017 Test Explorer not discovering tests with variable declaration

### ISSUE THREAD

**Issue by Thaoden** [mmanela/chutzpah#677]
Hi,

I'm currently trying to get Chutzpah running with Visual Studio 15.5, Jasmine and TypeScript.

When I have a test written like this:

    describe("This", function () {
        it("is a test", function () {
            expect(true).toBe(false)
        });
    });

it is disovered and displayed in the Test Explorer.

However as soon as I introduce a variable declaration:

    describe("This", function () {
        it("is a test", function () {
            let test = "test";
            expect(true).toBe(false)
        });
    });

the test is no longer discovered and not displayed in the Test Explorer.

Any help is greatly appreciated!

**Comment by Thaoden** [comment]
Apparently it has to do with my TypeScript options that were set to transpile to ES2015. Setting this to ES5 discovers the test.

**Comment by mmanela** [comment]
Thanks for figuring it out
