### ISSUE TITLE
Coverage reported on generated js files instead of ts files.

### ISSUE THREAD

**Issue by vishnurk** [mmanela/chutzpah#679]
I recently started working on a typescript project that uses Chutzpah for running ts unit tests and for generating code coverage.

I restructured code to redirect generated js output to a separate folder (previously all the generated JS files were in the same location as the ts source files). So, the current folder structure is 

**ProjectRoot
--ts
----src
----typings
----unittests
--js
----generated
--------src
--------unittests
tsconfig.json
chutzpah.json**

After I made this restructuring, I included an _OutputPath_ setting in the chutzpah.json.
    _"Paths": [
      {
        "OutputPath": "../js/generated",
        "OutputPathType": "Folder"
      }_

I have all the UTs passing. But, my coverage (coverage html)  is now being reported on JS files as opposed to TS files. Before this restructuring, the coverage html would report coverage on TS files.

Why did this change? What am I missing?

**Comment by mmanela** [comment]
Not sure, I need to investigate. Can you provide a minimal repro I can clone and use?

**Comment by vishnurk** [comment]
Here's a public repo to reproduce the problem - 
[Click Here](https://github.com/vishnurk/ChutzpahProblems.git)

Folder "coverage1" has source files setup to output JS files to a separate folder.
Folder "coverage2" has source files setup to output JS files to the same folder as the ts files.

Run unit tests; They are all failing at the moment for some other reason; Look at the generated tsCoverageHtml.html; For Coverage1, coverage is shown on the generated JS file.
