### ISSUE TITLE
ReferenceErrors during Chutzpah+Jasmine+Ts+Angular test run

### ISSUE THREAD

**Issue by mihalycz** [mmanela/chutzpah#680]
Hello!

I'm trying to setup **Chutzpah** to run **Jasmine** Unit Tests with an **angular** and **typescript**.

And when I'm running test for the first time I receive errors like:

`ReferenceError: Can't find variable: SomeModule `

But .js usually generated and second test run goes ok.

repo:
[chutzpah-jasmine-angular](https://github.com/mihalycz/chutzpah-jasmine-angular)

Best Regards and Thank You!

**Comment by mmanela** [comment]
Where is that variable supposed to come from? Did you check the generated HTML file and see if it is referenced correctly?
