### ISSUE TITLE
Test adapter make 'Test Explorer' take too long to find all tests (more than 15 minutes)

### ISSUE THREAD

**Issue by WillRock19** [mmanela/chutzpah#681]
Good day,

I've created a test project using Jasmine and Chutzpah and added  the **'Chutzpah Test Adapter for the Test Explorer'** and the **Chutzpah Test Runner Context Menu Extention'**  extentions, following this tutorial (https://developers.veinteractive.com/tech-blog/testing-javascript-chutzpah-vsts/). I've done it two times: one of then in a solution with only my JS tests project, and other in a solution with my web app other tests projects (Integration, Acceptance and Unit tests projects that are using NUnit, OpenQA.Selenium, FluentAssertions, etc).

In the first solution (the one that contains only the JS tests project), it worked really well. But, when I've added a JS test project following the same logic to my other solution, the Visual Studio's Test Explorer got really, really slow (it spend more than 15 minutes to find my tests - have in mind that, before I've used the extensions and created the JS tests project, it took, in worst case scenario, 2 minutes to find all my tests) to finally find all tests, including the JS ones.

Do you guys have any ideia of what might be happening? 

P.S. I am using Visual Studio 2017 in an ASP.Net net45 web project, Chutzpah 4.3.6, Jasmine 2.6.4, FluentAssertions 3.0.107, NUnit 2.6.3, NUnitTestAdapter 1.0, SpecFlow 2.2.1, Selenium.WebDriver 3.6.0, Selenium.Support 3.6.0 and some others

**Comment by mmanela** [comment]
Do you have a Chutzpah.json file decalring which are your test files?
