### ISSUE TITLE
Jasmine browser is running in addition to VS Test Runner

### ISSUE THREAD

**Issue by mwpowellhtx** [mmanela/chutzpah#684]
I'm not sure how *Jasmine* is picking up on the test as well. Or at least is being reported via *Jasmine*. Is that the default? Is there a better way? Or to "ignore" that reporter altogether? The test runner is sufficient for my use. In addition to the *Gulp-Chutzpah*, which is invoking the ``chutzpah(...)`` with executable path.

A side note, *Jasmine* is reporting "SPEC HAS NO EXPECTATIONS", which I'm not sure what that means, per se. Do I need to call a method during the ``describe``, ``it``, or otherwise return a value? I am calling ``expect(...)``, and so on, during my unit tests.

Thanks!

**Comment by mmanela** [comment]
What do you mean "Jasmine" is picking it up? Where do you see this?

**Comment by mwpowellhtx** [comment]
I get a Jasmine browser window appear in addition to the test runner results. It is reporting the same details in a slightly different format, but it's just annoying. Not sure if that's a tooling issue, though, on the one hand. Or what constitutes a "spec", per se. The tests run, and run successfully. When there is something wrong, or "unexpected", they fail, as expected. So I'm not sure what is meant by that.

**Comment by mmanela** [comment]
Can you share your chutzpah.json config?

**Comment by mwpowellhtx** [comment]
It's fairly standard, as far as I can tell:

```JavaScript
{
    "Framework": "mocha",
    "MochaInterface": "bdd",
    "References": [
        { "Path": "./node_modules/chai/chai.js" },
        { "Path": "./path/to/module/under/test.js }
    ]
}
```

With the mocha dependency available by default from what I understand.

**Comment by mmanela** [comment]
Then its not Chutzpah running "Jasmine". Not sure if there is some other tool or something doing it.
