### ISSUE TITLE
Duplicate Run All et al are appearing

### ISSUE THREAD

**Issue by mwpowellhtx** [mmanela/chutzpah#685]
Uh oh. I am finding multiple duplicate *Run All* as well as for test cases appearing in the left hand margin context menu via the VS Test Runner Adapter. This after I've added some test cases, run, added some more test cases, re-run, and so on. Basically, rinse, repeat, and re-run, etc.

**Comment by mmanela** [comment]
What is your chutzpah.json file? People find dupes sometimes where their test definition is picking up multiple copies of the file that get laid down in the build process...

**Comment by mwpowellhtx** [comment]
I have one *chutzpah.json* per project in my solution at the moment. However, I sometimes shift gears from one project to the next during the course of troubleshooting.

**Comment by mwpowellhtx** [comment]
To follow up, the issue doesn't appear to be chutzpah.json related. Rather it seems to be related to test paths, describe/it names, as I'm adding new bits, elaborating, fleshing it out, etc. The runner "sees" this and adds the dupes.

**Comment by mmanela** [comment]
ok, do you have a repro I can run?

**Comment by mwpowellhtx** [comment]
No I really don't. From what I can tell, I see this when I am adding *describe* sections, *it* sections, etc. Perhaps also when shifting gears between projects, introducing test capability to the next project.

**Comment by mwpowellhtx** [comment]
@mmanela So, I'm just walking through another session this morning of "rinse and repeat", adding describe sections, it sections, beforeEach snippets, and so on, and observing the "Run All" entries, etc, piling up. At the moment I must have as many as half a dozen such entries. That's the best I can tell you as far as "repro". Short of diving into your code and analyzing for the same.
