### ISSUE TITLE
Changes to chutzpah.json aren't detected in VS 2017

### ISSUE THREAD

**Issue by jegarne** [mmanela/chutzpah#689]
Hi, when I make changes to the chutzpah.json file I can only get them to take effect in test explorer by restarting visual studio.  Am I missing something?

**Comment by mmanela** [comment]
That seems odd, I will need to take a look at that.

**Comment by rschiefer** [comment]
I've also noticed when "Run All" is clicked, JavaScript tests don't appear to be rerun after changes are made to the test files or referenced JS files.  They do rerun if I restart VS or explicitly run those tests.
