### ISSUE TITLE
Reports not generated When Using Html file as Tests path

### ISSUE THREAD

**Issue by MhdTlb** [mmanela/chutzpah#692]
I want to generate Jacoco report for code coverage so I can included in my TFS build as described here https://www.linkedin.com/pulse/enabling-javascripttypescript-code-coverage-brett-jacobson?trk=portfolio_article-card_title. 

For that, I used almost the same chutzpah.json file: 

```
{
	"Compile": {
		"Mode": "External",
		"Extensions": [ ".ts" ],
		"ExtensionsWithNoOutput": [ ".d.ts" ]
	},
	"CodeCoverageExecutionMode": "Always",
	"EnableCodeCoverage": "True",
	"CodeCoverageExcludes": [
		"node_modules/*"
	],
	"TestFileTimeout": 5000,
	"Tests": [
		{
			"Path": "test\\unittests\\index.html"
		}
	],
	"Transforms": [
		{
			"Name": "jacoco",
			"Path": "..\\TestResults\\ChutzpahJacoco.xml"
		},
		{
			"Name": "lcov",
			"Path": "..\\TestResults\\ChutzpahJS.lcov"
		},
		{
			"Name": "coveragehtml",
			"Path": "..\\TestResults\\ChutzpahJS.html"
		}
	]
}
```

Inside my index.html file, I have all my unit tests. Giving this config, if I run _chutzpah.console.exe chutzpah.json_ command, I get the result all total and failed tests. But the 3 transforms reports are not generated.

However, if I change Tests settings to use `Includes": [ "*Tests.ts" ]` instead of a path to html file, I will get reports generated but all tests failed (I assume some references are required like in index.html file???)

Is this bug or I'm doing something wrong?
How can I run all tests and generated the 3 reports both Visual Studio 2015 and TFS 2015 build?

**Comment by mmanela** [comment]
This is by design. If you want the integrated code coverage you must do the work to configure chutzpah to build the html harness. You need to configure the dependencies in the chutzpah.json file
