### ISSUE TITLE
Tests will not run in Edge browser

### ISSUE THREAD

**Issue by tyrielv** [mmanela/chutzpah#694]
All of the test harness templates start with
`<!-- saved from url=(0014)about:internet -->`

When this is present, Edge will not load any script files unless they also have the same tag present.

Is there a reason to have that tag?

**Comment by mmanela** [comment]
That is interesting, that was added to fix other issues. One mitigation is to run in Server mode, which I recommend regardless. Add this to your chutzpah.json:

```
   "Server": {
       "Enabled": true
    },

```
