### ISSUE TITLE
Chutzpah - PhantomJS memory leak causing time outs

### ISSUE THREAD

**Issue by vishnurk** [mmanela/chutzpah#695]
We are seeing PhantomJS memory consumption go past 600K on our build server causing chutzpah to time out when running tests.  

We ONLY have **130** unit tests spread across 10 files. 50 of the 130 are in one file. 
Chutzpah.json has the following settings - 
>   "TestFileTimeout": 30000,
>   "EnableTestFileBatching": true,
> 
> 

What are my options? 
Any suggestions? 
I noticed the reply below in a related issue  - Will this be of any use?

> Chutzpah allows you to break down and parallelize multiple test harnesses by making a parent chutzpah.json and have child chutzpah.json files for each area to test.

**Comment by mmanela** [comment]
Phantom has issues and I am working to move away from it. However, 130 tests shouldnt hit this issue. 600k is not that much though, why do you think memory is the issue?
