### ISSUE TITLE
PhantomJs Replacement

### ISSUE THREAD

**Issue by mfcastro** [mmanela/chutzpah#696]
I was wondering if there are plans to switch to a different headless browser now that it has been announced that PhantomJs will no longer be maintained.

[https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE)

**Comment by mmanela** [comment]
I have a branch where I have this mostly done. Just working through an issue with Google Chrome Launcher.
