### ISSUE TITLE
TypeScript coverage - only spec files are covered as TypeScript (VS test runner)

### ISSUE THREAD

**Issue by klylesatepic** [mmanela/chutzpah#697]
We use the [Chutzpah Test Runner Context Menu Extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-2795.ChutzpahTestRunnerContextMenuExtension).  It works great for JavaScript, and pretty well for TypeScript, but I've been unable to get TypeScript code coverage to work the way we want it to.  Specifically, I've been trying to set it up to show the coverage on the TypeScript files, instead of the generated JavaScript files.  I've even gotten it working for the spec files, but it seems pretty set on showing the JavaScript for the files under test:
![screenshot](https://user-images.githubusercontent.com/37372562/37405522-dae2c662-2762-11e8-8f22-48629f042ea8.png)

I've tried every combination of settings I can think of for the chutzpah.json file, with the results so far either being the same, or things just not working.  I also enabled tracing, but didn't see much that looked applicable to my (admittedly inexperienced at reading Chutzpah traces) eyes: [chutzpah.log](https://github.com/mmanela/chutzpah/files/1811336/chutzpah.log) However, I may still have missed some way to get things working.

I spent some time to come up with something close to the smallest possible project to reproduce the issue in Visual Studio 2017:
[Chutzpah Test.zip](https://github.com/mmanela/chutzpah/files/1811251/Chutzpah.Test.zip)
It also opens and shows the issue in 2015 -- let me know if it's not working in your preferred version and I'll see what I can do.

I'm hoping for one of two outcomes:
1. If there are changes we can make to any of the following files in that project to get things working, I should be able to apply that to our actual code:
- chutzpah.json (seems the most likely)
- tsconfig.json
- Toolbox.ts
- ToolboxSpec.ts
Changes to other files in the project are less certain to be directly applicable, but I'm willing to try them out.  We can't realistically stop using AMD modules or Jasmine.
2. If this is actually a bug in Chutzpah or the extension, hopefully the smallish test case helps it get reproduced and fixed.

Please let me know if I can provide any additional information.

**Comment by klylesatepic** [comment]
I was on vacation when this was flagged for inactivity.  It's still a bug we're running into, and I still don't have a good workaround.

**Comment by pushkin-** [comment]
I can still reproduce this with Visual Studio 2019 and Chutzpah 4.4.6. @mmanela Can this be reopened?
