### ISSUE TITLE
FileNotFoundException in VS2017 - Chutzpah.VS2012.TestAdapter.dll

### ISSUE THREAD

**Issue by rschiefer** [mmanela/chutzpah#698]
I receive the following error when VS starts up:

System.IO.FileNotFoundException: C:\Users\myUser\AppData\Local\Temp\VisualStudioTestExplorerExtensions\Chutzpah.4.3.6/tools/Chutzpah.VS2012.TestAdapter.dll
   at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.PerformShadowCopy(IEnumerable`1 testExtensions)

I am running VS Community 2017 15.6.2 and referenced the Chutzpah 4.3.6 Nuget package.  I'm running Windows 10.0.16299.248.

**Comment by rschiefer** [comment]
Not sure how but it looks like that folder lost a bunch of files while the root Chutzpah folder was still there which confused VS.  I deleted the root folder and VS recreated it with all the proper files.  Issue resolved.

**Comment by joel-mcbeth-impact** [comment]
I have not been able to find the cause of this but this issue has happened to me at least twice now. I wish the handling of the situation was better.

Chutzpah doesn't have control over the temp folder, I don't think it would be unreasonable for it to take extra care when expecting certain files to be there.

My most recent instance there was nothing in the VisualStudioTestExplorerExtensions folder. Deleting it did not solve the issue until I restarted Visual Studio.
