### ISSUE TITLE
run tests automatically in watch mode

### ISSUE THREAD

**Issue by roopkt** [mmanela/chutzpah#703]
Hi all,
This may not be an issue however more of questions. 
Can Chutzpah run in watch mode like whenever file changes and saved can chutzpah re-run test automatically ? Can someone point me to some config settings for that ?

**Comment by mmanela** [comment]
This is something I have wanted to get to for a long time but have not had the time.

**Comment by mmanela** [comment]
Cool ! Thanks for sharing

**Comment by roopkt** [comment]
Hi Matthew Manela @mmanela ,
I created [chutzpah-watch](https://www.npmjs.com/package/chutzpah-watch) npm module which does the same thing and it is working too. 
Here is the link for the npm package please provide your feedback. 
https://www.npmjs.com/package/chutzpah-watch

**Comment by mmanela** [comment]
I like that! Thanks for creating.
