### ISSUE TITLE
Allow wild card entries in path

### ISSUE THREAD

**Issue by roopkt** [mmanela/chutzpah#704]
Hi I am using chuzpah.console and want to pass the path when I give folder path it is very slow.
I wanted to pass wildcard path like below

```
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.3.3.0
```
chutzpah.console /path js\feature1\**\*.tests.ts

**Comment by mmanela** [comment]
That is a good suggestion. Chutzpah supports wild cards in the chutzpah.json file which I recommend using for now.
