### ISSUE TITLE
Unable to run tests with Chutzpah

### ISSUE THREAD

**Issue by ashwini-ms** [mmanela/chutzpah#706]
Hi 

I am writing tests using Chutzpah and facing issues with the tool. my test has dependencies on third party libs and I am using them with require('') to access them. I git following error

Error: ReferenceError: Can't find variable: require

Here is chutzpah.json
```
{
    "Framework": "mocha",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "References": [
        {
            "Path": "config.js"
        },
        {
            "Path": "app.js"
        }
    ],
    "Tests": [
        {
            "Includes": [
                "*test.js"
            ]
        }
    ],
    "Server": {
        "Enabled": true
    }
```
}

**Comment by mmanela** [comment]
You need to include require.js in your references.

**Comment by Nagendracv** [comment]
Suggest to close this
