### ISSUE TITLE
Chutzpah not recognizing typescript tests

### ISSUE THREAD

**Issue by Nagendracv** [mmanela/chutzpah#707]
Below is what I have in my Chuzpah.json.

{
	"Framework": "jasmine",
	"Compile": {
		"Mode": "External",
		"Extensions": [ "*.ts" ],
		"ExtensionsWithNoOutput": [ "*.d.ts" ]
	},
	"References": [
		{ "Path": "node_modules/promise-polyfill/dist", "Include": "*.js", "Exclude": "*.d.ts", "IsTestFrameworkFile": true },
		{ "Path": "node_modules/systemjs/dist", "Include": "*.js", "Exclude": "*.d.ts", "IsTestFrameworkFile": true  },
		{ "Path": "service/shared/impl", "Include": "*.ts", "Exclude": "*.d.ts" }
	],
	"Tests": [
		{ "Path": "unittests", "Includes": [ "*.spec.ts" ], "Excludes": [ "*.d.ts" ], "ExpandReferenceComments": "true" }
	]
}

And this doesn't seem to identify any of the unit tests unittests directory
sample test

/// &lt;reference path = "../Scripts/typings/jasmine/jasmine.d.ts" />
/// &lt;reference path = "../node_modules/@types/systemjs/index.d.ts" />
describe('Plain Simple Login Test', function () {
	it("Valid User With Valid Password Should Get Logged In", () => {
		expect(1).toBe(1);
	});
});

If I change "Includes": [ "*.spec.ts" ] to "Includes": [ "*.spec.js" ], it seems to work.
But then later it results in other issues like wherever there is an import needed from another *.ts file. Import statements dont work.
Please confirm if this is a still a supported feature.

**Comment by Nagendracv** [comment]
yay... finally got it working - 'sort of'. 
Enabled tracing and figured out that the issue was that system.js has this statement in it 
return e.startsWith("System.register",r)||e.startsWith("SystemJS.register",r)
and string.startsWith is not supported in PhantomJS!!! eeek. [Wonder when we will have support for chromeheadless]
after about another 8 hrs of struggling and almost deciding to go back to commonjs, with another stackoverflow suggestion to use an es6 Shim.
And that got it working!!!
(btw this is with "Includes": [ ".spec.js" ] in the chutzpah.json)

**Comment by mmanela** [comment]
I added support for [JsDom and Chrome](https://github.com/mmanela/chutzpah/wiki/Browser-Engines) in version 4.4. This is still a beta feature but feedback is welcome.
