### ISSUE TITLE
Cannot run tests react/mocha/chai

### ISSUE THREAD

**Issue by frederikstonge** [mmanela/chutzpah#714]
I'm trying to use chutzpah to run all my tests from the test explorer in visual studio.

I managed to configure it correctly (I believe) but unfortunately, it keeps saying that:
`Can't find variable: exports`.

Basically, we compile our ts tests to js in commonjs and the "import" declarations at the top gets translated to:
`Object.defineProperty(exports, "__esModule", { value: true });`.

here's my chutzpah.json:

```
{
  "Framework": "mocha",
  "Compile": {
    "Mode": "Executable",
    "Executable": "compile.bat",
    "Extensions": [ ".tsx", ".ts" ]
  },
  "Tests": [
    {
      "Path": "test",
      "Includes": [ "*.ts" ]
    }
  ],
  "References": [
    {
      "Path": "src",
      "Includes": [ "*.tsx" ]
    }
  ],
  "Server": {
    "Enabled": true
  }
}
```

and my compile.bat:
`tsc -p tsconfig.test.json`

I tried to add references to react, react-dom, chai and mocha in the chutzpah.json, but it never got me anywhere further. Adding `/// <reference/>` tags at the top fails to compile my typescripts.

Also, when i run the npm command : `mocha -r ts-node/register test/**/*.js`, everything works. What am I missing in my configuration?

Thank you

**Comment by mmanela** [comment]
Are you compiling your code to ES5? Chutzpah still uses phantomJS which requires you down-transpile the code.

**Comment by mmanela** [comment]
With latest version you can run under newer JS by targeting JSDom (https://github.com/mmanela/chutzpah/wiki/Browser-Engines)
