### ISSUE TITLE
Chutzpah Error: System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by sandeepnmenon** [mmanela/chutzpah#718]
Environment : VS 2017
Language : Typescript

While running a Chutzpah test, I am getting the following error
`Chutzpah Error: System.IO.FileNotFoundException: Couldn't find generated path for E:\repos\****************\***\****************\UnitTests\utils.spec.ts at e:\repos\***************\***\****************\UnitTests\utils.spec.js or at E:\repos\****************\***\**************\**********\utils.spec.js
File name: 'e:\repos\**********\***\**************\UnitTests\utils.spec.js'`

My chutzpah.json is as follows
```{
  "Framework": "jasmine",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "CodeCoverageExcludes": [ ".spec.ts" ],
  "References": [

  ],
  "Tests": [
    {
      "Path": "UnitTests",
      "Includes": [ "*/*.spec.ts" ],
      "Excludes": [ "*/*.d.ts", "*/**.spec.js" ],
      "ExpandReferenceComments": "true"
    }
  ]

}
```
Chutzpah.json is placed one directory level above utils.ts and utils.spec.ts

Is it required to build the .ts files to .js files before running the tests? If yes, then is there a workaround.
If no, then what is the issue?

**Comment by mmanela** [comment]
Yes, you need to compile your TS into JS. Chutzpah will not do that for you.
