### ISSUE TITLE
[Qunit JS] Failed to running tests from code editor

### ISSUE THREAD

**Issue by Chan-Zhang** [mmanela/chutzpah#719]
Affected Branch: rel/d15.8
Affected Build: 27916.00
Affected Product Language: javascript

Steps to reproduce:

1. Install VSIX: click "Tool" -> "Extensions and Updates", search "Chutzpah" in the tag "Online" to 
    install  it.( you need to close vs to finish installing) Reopen Vs to make sure installation is success.
2. Create a C# Console App project
3. Add file "JSSample.js":
    function isEven(val) {
     return val % 2 === 0;
     }
     test('TestMethodPass', function () {
     ok(isEven(2), 'Two is an even number');
     ok(!isEven(1), 'One is not an even number');
     });
     test('TestMethodFail', function () {
     ok(isEven(3));
     });
4. In code editor, right click inside one test-->Run Tests
Expected Result: For step4, the selected test will run.
Actual Result: For step4, Output will show an Warning:  Build failed or it was cancelled. No test will run.
Repro gif: \\mlangfs1\public\v-zchan\Qunit JS Issue.gif

**Comment by mmanela** [comment]
Closed as external
