### ISSUE TITLE
How to make chutzpah Parallelism more than number of CPUs?

### ISSUE THREAD

**Issue by memao** [mmanela/chutzpah#720]
We are currently running our js tests using vstest.console.exe, use chutzpah.json as test files. I found that the maximum parallel phantom.js sessions is the number of CPUs, no matter how high I set the number for parallelism in chutzpah.json. We have over 4000 tests to run, so this caused test run very slow. 

We also tried another approach - we run js tests using a c# wrapper, which call testRunner.RunTests() directly in an async method. The tests finish much faster. 

I think one reason for the speed difference is the number of maximum parallel sessions allowed in chutzpah.json. So I am wondering if it is possible to increase it instead of limited by the number of CPUs?

**Comment by mmanela** [comment]
Today it is not. I limit to number of CPUs based on past feedback but I am willing to re-consider.
