### ISSUE TITLE
Jasmine version

### ISSUE THREAD

**Issue by andrewgrahamorange** [mmanela/chutzpah#724]
The Jasmine version used in Chutzpah is now quite old and is missing some features we'd like to use.

Are there any plans for a new release of Chutzpah with an upgraded Jasmine version in the near future?

**Comment by mmanela** [comment]
Which version would you like?

**Comment by andrewgrahamorange** [comment]
Thanks for getting back to me.

As a minimum, we'd need Jasmine 2.6.0 but getting some of the features in later versions would also be great.

**Comment by mmanela** [comment]
Done, published 4.4

**Comment by andrewgrahamorange** [comment]
Excellent - much appreciated.

**Comment by NPC** [comment]
@mmanela Do you plan to update to Jasmine 3.x? (latest is 3.3, from Oct 2018)

**Comment by dogeth** [comment]
In case anyone is arriving from a google search, to update to use jasmine 3, add the following to your chutzpah.json configuration:

`    "Framework": "jasmine",
    "FrameworkVersion": "3",
    "Engine": "Chrome",
    "Server": {
         "Enabled": false
    }
`
