### ISSUE TITLE
`dotnet test` runner

### ISSUE THREAD

**Issue by mbp** [mmanela/chutzpah#730]
Is it possible to run Chutzpah using `dotnet test` instead of `vstest.console.exe`?

Currently vstest is invoked as follows:
vstest.console.exe /TestAdapterPath:Chutzpah/ chutzpah.json

It's possible to specify test adapter path for "dotnet test", but how can I specify chutzpah.json instead of a project file?

**Comment by mmanela** [comment]
I have not looked into this yet. I am not sure how or what it takes to integrate there.
