### ISSUE TITLE
jasmine - catchExceptions option is deprecated, replace with stopOnSpecFailure

### ISSUE THREAD

**Issue by IgorWolbers** [mmanela/chutzpah#731]
I am receiving the following errors in my execution of my unit tests. 

```
2018-10-12T02:17:55.9072112Z ##[error]Error: DEPRECATION: The catchExceptions option is deprecated and will be replaced with stopOnSpecFailure in Jasmine 3.0
2018-10-12T02:17:55.9072648Z ##[error]	[{file:http://localhost:9876/__chutzpah__/jasmine/v2/jasmine.js?sha=ff4fe8914c64182a8ad0e0810786acb0857fd35d,line:949,function:deprecated}]
2018-10-12T02:17:55.9072846Z ##[error]While Running:D:\myscript.spec.js
```

I am using the latest [NuGet package](https://www.nuget.org/packages/Chutzpah) and have `jasmine 2.9.0` referenced in my `package.json` file. Please let me know if there is something else I can provide.

**Comment by bravominski** [comment]
+1
Based on https://github.com/jasmine/jasmine/issues/1497, it looks like 2.99.1 should be consumed since that version has a fix.

**Comment by terrytsay** [comment]
although this is not a preferred solution, but we worked around this by
1. Bring down the jasmine-core npm/nuget for version 2.99.1
2. In build process, replace \packages\Chutzpah.4.4.2\tools\ChutzpahTestHarnessFiles\Jasmine\v2\jasmine.js with one from above.

The file diff between these 2 is simply 2-3 lines where the warnings dont show up anymore.

We also use VS extensions for chutzpah and the latest version will discover chutzpah in nuget packages and use that. So we just replace the chutzpah in nuget packages.

**Comment by jonathantwite** [comment]
This causes a issue when using Azure Build Pipelines / DevOps.  The standard build pipeline re-installs all NuGet packages so they do not have to be in source control and do not become accidentally broken.

The Test part of the build then sees this "error" and assumes that the tests have failed, even if all have passed (see [this question](https://stackoverflow.com/questions/53207656/chutzpah-jasmine-tests-in-azure-devops-build-pipeline-returning-failed-when-all/)).

Therefore it looks like the version in NuGet needs to be updated to use at least Jasmine 2.99.1, if not 3.* to allow any Jasmine tests to be run on DevOps - Note that Microsoft specifically state Chutzpah as a testing method to use with Build Pipelines.

**Comment by mmanela** [comment]
I updated in 4.4.3 to fix this issue
