### ISSUE TITLE
Chutzpah unit tests doesn't run in Chrome

### ISSUE THREAD

**Issue by anarchitect** [mmanela/chutzpah#737]
Hi, I tried to run chutzpah 4.4.2 in command line and it was good when run in PhantomJS, but when i use /engine Chrome option, it display 0 testes run and 0 tests failed.  The same repo on other machines work.  Chrome is version 70 which supports headless.  I have uninstalled Chrome and reinstalled Chrome and it still doesn't work.  Would you please help? Thanks.

**Comment by mmanela** [comment]
@anarchitect Run chutzpah with the /trace option and examine the chutzpah.log generated. Chutzpah will try to find chrome, but if it can't you need to configure where it is

**Comment by thcgit** [comment]
This looks like a bug. In chutzpahRunner.js, the value of chromePath is an empty string when EngineOptions is not specified. So it never gets into getChromePaths.

**Comment by mmanela** [comment]
Oh that is interesting. @thcgit  did you fix both in your PR?

**Comment by thcgit** [comment]
> Oh that is interesting. @thcgit did you fix both in your PR?

Not the Chrome issue, but I can fix it and submit another PR if you like.

**Comment by mmanela** [comment]
Sure if you can that would be great, or roll into the current PR too

**Comment by mmanela** [comment]
Published in v4.4.4
