### ISSUE TITLE
Code coverage not seem to cooperate with (Beta) engines

### ISSUE THREAD

**Issue by Nitakri** [mmanela/chutzpah#739]
Hi, we have an angularJS project with JasmineJS unit tests and we are using Chutzpah Test adapter in VS2017 to run them. We were utterly happy to see JSDom and Chrome engines as selectable options and we accepted, they're in a Beta state at the moment.

I just started to experiment with them and came to the conclusion that both JsDom and Chrome engines just work like a charm even with our ES6 snippets, but unfortunately code coverage runs only with PhantomJS, the other two just leaves an empty result html. :( 

I understood this is still a Beta, but I wanted to know whether it is a known thing, or I have just misconfigured something?

Here is our simple Chuzpah.json, which works for running tests, but not for code coverage. Are we missing something?

{
  "Engine": "JSDom",
  "Framework": "jasmine",
 
  "CodeCoverageExcludes": [ "*jquery*", "*angular*", "*bootstrap*", "*underscore*", "*moment*" ],
  "CodeCoverageIgnores": [ "*Mock.js", "*mocks.js", "*Test.js", "*Tests.js" ]
}

However, Your work is awesome, it makes our life so much easier!

**Comment by Nitakri** [comment]
Thanks for Your answer @mmanela and sorry for this late reply. What you mention is totally understandable, just focus on replacing the engine, it's a great step forward! We'll look for another JS code coverage solution then (we need to use it during VSTS builds anyways)!

**Comment by mmanela** [comment]
Thanks!

**Comment by siddharth4gupta** [comment]
Hi @Nitakri Wondering if you found any other coverage solutions ? I am in the same boat, most of my tests have ES6 code and need to run on Chrome. Any pointers would help.
