### ISSUE TITLE
Chrome and JSDom engines not working when Chutzpah path has a space

### ISSUE THREAD

**Issue by thcgit** [mmanela/chutzpah#742]
NodeTestExecutionProvider is not escaping the runnerPath, so it doesn't work when the path contains spaces. I've submitted a pull request for the fix : https://github.com/mmanela/chutzpah/pull/741

I also found another bug that I've commented on in https://github.com/mmanela/chutzpah/issues/737.

Can these be fixed for the next release?

Thanks.

**Comment by mmanela** [comment]
Published in v4.4.4
