### ISSUE TITLE
Error: ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by mgrowan** [mmanela/chutzpah#746]
Running locally everything is fine. 
Running on Azure Pipelines using VSTest Task version 1 or 2 passes all tests, but fails the overall task with:

`##[error]Error: The process 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe' failed with exit code 1`

Within the middle of a block of tests is the error:

`Passed   MembersController closes add member popup when a member is added
Error: ReferenceError: Can't find variable: require`
	`[{file:file:///d:/a/1/s/src/packages/Chutzpah.4.4.4/tools/Node/packages/node_modules/safer-buffer/tests.js,line:5,function:global code}]`
`While Running:d:\a\1\s\src\packages\Chutzpah.4.4.4\tools\Node\packages\node_modules\safer-buffer\tests.js`

`Error: ReferenceError: Can't find variable: require`
`While Running:d:\a\1\s\src\packages\Chutzpah.4.4.4\tools\Node\packages\node_modules\safer-buffer\tests.js`

Any ideas?

**Comment by sjtipton** [comment]
Getting this issue as well in Azure DevOps build only -- all tests pass however. Using Chutzpah 4.4.4. Have another app using Chutzpah 4.3.4, and the Azure DevOps build passes all tests without any issues.

Following this issue.
