### ISSUE TITLE
Chutzpah test explorer in VS 2017 cant find variable Promise

### ISSUE THREAD

**Issue by fahad-nadeem** [mmanela/chutzpah#749]
Hi, 

My tests are running fine in the browser but inside the test explorer or the console I get the error

**ReferenceError: Can't find variable: Promise** 

My code is as follows:

`/// <reference path="../lib/sinon-1.3.2.js"/>
/// <reference path="../lib/fn_xrmobjects.js" />
/// <reference path="../fos_dyn_core_crud.js" />

describe("Test Retrieve Call Accept", function () {
    

    afterEach(function () {
        Xrm.WebApi.RetrieveRecord = sinon.restore();
    });

    it("Should call succcess callback", function(done){
        var successCallback;
        var errorCallback;
        successCallback = sinon.spy();
        errorCallback = sinon.spy();

        Xrm.WebApi.RetrieveRecord = sinon.stub().callsFake(function () {
            return sinon.stub().resolves("DATA")().then(function (value) {
                successCallback();
                expect(successCallback.calledOnce).toBe(true);
            });
        });
        CRUD.RetrieveRecord("test", "test", "test", successCallback, errorCallback);
        done();
    });

    
});`

**Comment by mmanela** [comment]
Which browser engine for Chutzpah are you using?

**Comment by fahad-nadeem** [comment]
I am running the harness file in Google Chrome and it works. Using Chutzpah.Console fails.

**Comment by mmanela** [comment]
You can try running chutzpah using chrome or jsom to see if it helps
https://github.com/mmanela/chutzpah/wiki/Browser-Engines

**Comment by fahad-nadeem** [comment]
Thanks a lot Matthew! That did it.
