### ISSUE TITLE
<HintPath>..\packages_autosigned\ServiceStack.Text.dll</HintPath> does not exit?

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [mmanela/chutzpah#753]
Fresh download and opening SLN in VS2019, Chutzpah DLL does not build complaining about ServiceStack.Text. 
Upon closer look, the hint path in csproj:
<HintPath>..\packages_autosigned\ServiceStack.Text.dll</HintPath> does not exit.

Also since the project already loads newtonsoft.json, would it much easier to replace the only two reference to ServiceStack.Text with NewtonSoft? 

One less reference to keep track of. Thanks

**Comment by mmanela** [comment]
You need to run `./build install `from the command line before those dlls will exists.

The reason I used service stack originally was performance, when tested (this was years ago) it performed way better
