### ISSUE TITLE
Test runner reports "cannot find path" errors for ajax urls

### ISSUE THREAD

**Issue by bmmohanty** [mmanela/chutzpah#757]
I am trying to test my JS file using Chutzpah and QUnit and it is erroring out for the ajax calls.
The error line is as follows:

"Error: Error opening D:/xxxxx/xxxxx/UI/Tests/DummyController/DummyAction: The system cannot find the path specified."

My JS AJAX Section code is as below:

$.ajax({
            url: "/DummyController/DummyAction",
            type: "POST",
            data: SampleModelData,
            success: function (result) {                
            },
            error: function (err) {
                alert("Error Occured");
            }
        });

**Comment by mmanela** [comment]
Can you share your chutzpah.json file?

**Comment by bmmohanty** [comment]
> Can you share your chutzpah.json file?

Sure.. here it is...

{
  "Framework": "qunit",
  "RootReferencePathMode": "SettingsFileDirectory",
  "EnableTestFileBatching": true,
  "TestFileTimeout": 10000,
  "Compile": {
    "UseSourceMaps": true,
    "Paths": [
      {
        "SourcePath": "../",
        "OutputPath": "../"
      }
    ]
  },
  "References": [
    {
      "Path": "Tests/jquery.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "../../xxxxxxxxxxxxx/wwwroot/js",
      "Includes": [ "*.js" ],
      "Excludes": ["jquery.js"],
      "IsTestFrameworkFile": true
    }
  ],
  "Tests": [
    {
      "Path": "Tests",
      "Includes": [ "*_test.js" ]
    }
  ]
}

**Comment by mmanela** [comment]
Can you try turning on server mode by adding this

```

"Server" : {
  "Enabled": true
}

```

**Comment by bmmohanty** [comment]
Tried the same thing, but no lock. Still the error is running one.

**Comment by mmanela** [comment]
Can you run with the /trace flag and share the chutpah.log file?
