### ISSUE TITLE
Clean bulid of master fails 2 tests

### ISSUE THREAD

**Issue by matneyx** [mmanela/chutzpah#758]
Hey, I pulled the repo down over the weekend and when I run `.\build.bat` everything seems to run just fine, but I have 2 failing tests.  I'm not sure if the two tests are failing because my local setup is incorrect, or if two failing tests made it into master.

The failing tests messages (including the super brief traces) are:
```
Chutzpah.Facts.Integration.Execution.Will_run_tests_from_chutzpah_samples(scriptPath: "Samples\Angular2\Basic\chutzpah.json", count: 2) [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   0
      Stack Trace:
        Facts.Integration\Execution.cs(97,0): at Chutzpah.Facts.Integration.Execution.Will_run_tests_from_chutzpah_samples(String scriptPath, Int32 count)
```
and
```
 Chutzpah.Facts.Integration.Discovery.Will_discover_amd_tests_from_chutzpah_samples(scriptPath: "Samples\Angular2\Basic\chutzpah.json", count: 2) [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   0
      Stack Trace:
        Facts.Integration\Discovery.cs(75,0): at Chutzpah.Facts.Integration.Discovery.Will_discover_amd_tests_from_chutzpah_samples(String scriptPath, Int32 count)
```

And here's a gist with the entire output (at least I think it is... `.\build.bat >> text.txt`): https://gist.github.com/matneyx/f150d5a8dd759001dfc346d2b7fb1b1d

**Comment by mmanela** [comment]
Thanks for reporting this, I think there is a flaky test. I will investigate

**Comment by matneyx** [comment]
Thanks.  I didn't give it a ton of time, but I couldn't figure out how to debug through the failing tests (simply changing `Theory` to `Fact` wasn't the trick. :p).
