### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by francittadini** [mmanela/chutzpah#759]
With the last update of Chutzpah Test Runner Context Menu Extension (4.4.5), running tests is broken.

![image](https://user-images.githubusercontent.com/5400670/58038164-99fc1c00-7b05-11e9-8776-6736fe741d16.png)

**Comment by mmanela** [comment]
That is not good. Will take a look.

@zhangyiatmicrosoft  could this be a fallout of your recent change?

**Comment by mmanela** [comment]
@francittadini  Can you try out this vsix and see if it helps? If
 so I can publish it. 

https://github.com/mmanela/chutzpah/releases/download/v4.4.6/Chutzpah.VisualStudioContextMenu.vsix

**Comment by francittadini** [comment]
Nope, same error ☹

**Comment by mmanela** [comment]
@francittadini  Can you share your chutzpah.json file?

**Comment by francittadini** [comment]
@mmanela 
![image](https://user-images.githubusercontent.com/5400670/58194659-83d49400-7c9c-11e9-99d6-86f8a442b597.png)

**Comment by mmanela** [comment]
I found the issue and published a new version (4.4.6)

**Comment by francittadini** [comment]
Jewel, thank you!
