### ISSUE TITLE
Is it possible to associate chutzpah test with TFS/MTM Test case?

### ISSUE THREAD

**Issue by nramprakash88** [mmanela/chutzpah#763]
Is it possible to associate chutzpah test with TFS/MTM Test case by 
* Select the chutzpah test From Unit Test explorer, 
* Right click and select "Associate to Test Case" 

Reference link - https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops#test-types

**Comment by mmanela** [comment]
I have not looked into this but I don't think it is possible today
