### ISSUE TITLE
Chutzpah not detecting Chrome

### ISSUE THREAD

**Issue by ferrx** [mmanela/chutzpah#764]
I'm setting the chutzpah.json options for Engine and EngineOptions.ChromeBrowserPath to use chrome headless, but the trace logs indicate it's still trying to use PhantomJS. It gives me a "timeout occurred" error after about 10s. If I remove the engine properties (leaving it to default to PhantomJS), everything runs smoothly.

I don't see any reference to Chrome in the logs. I see my chutzpah.json references, but it doesn't seem to catch my engine properties.

Using chutzpah 4.4.5 and Chrome 74.0.3729.169.

```
{
  "Engine": "Chrome",
   "EngineOptions": {
        "ChromeBrowserPath": "C:\\yadayadayada\\chrome.exe"
   },
  "Framework": "jasmine",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "Tests": [
    { "Includes": [ "*.html" ] }
  ]
}
```

**Comment by ferrx** [comment]
This seems to be because I was using jasmine 2.99.

I used whichever version came with the chutzpah nuget package and it works fine.

**Comment by mmanela** [comment]
I am unable to repo this issue. I was able to specify the chrome path and it works with this json
```

{
  "Engine": "Chrome",
  "Framework": "Jasmine",   
   "EngineOptions": {
        "ChromeBrowserPath": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
   },
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "Tests": [
    { "Includes": [ "*test.js" ] }
  ]
}


```

![image](https://user-images.githubusercontent.com/304410/60112477-b56dce80-9724-11e9-8e10-d2d5dfd48bd0.png)


You can also try leaving off the engineOptions and see if it will find the chrome instance via its built in detection

**Comment by ferrx** [comment]
Thanks. Here's a hint -- I noticed you have a js file in your Tests.Includes, but I'm using *.html in mine.

If I switch to *.js it works, but using *.html does not work. Maybe there's some extra setup in the html harness to get chrome-headless working?

**Comment by mmanela** [comment]
I don't support directly running your own HTML test file under Chrome or JsDom.

**Comment by ferrx** [comment]
Any plans for that? I have a project that is jQuery heavy and needs that. I'll stick with Phantom for now.

**Comment by mmanela** [comment]
No plans, there are technical reasons why I don't support it. However, you can usually get chutzpah to work with jquery and let it generate the html file itself

**Comment by ferrx** [comment]
Can you provide an example w/ chutzpah running tests on JS files that have jQuery dependencies? I'm just a little lost, the idea is to be able to interact and manipulate with the "DOM" (whatever you want to call that within a headless browser) with jQuery.. meaning execute jQuery selectors, etc.

**Comment by mmanela** [comment]
Take a look at [this example](https://github.com/mmanela/chutzpah/blob/51e9eb968e987cd268becdd471e140a8340555a5/Facts.Integration/JS/Test/HtmlTemplate/template-jasmine.js)

It uses jquery and it also uses HTML files that get injected into the dom and then queried on.

**Comment by ferrx** [comment]
I duplicated that example, it didn't work for me until I took out this includes from chutzpah.json:
```
  "Tests": [
    { "Includes": [ "*.js" ] }
  ]
```

**Comment by mmanela** [comment]
Perfect!

**Comment by mmanela** [comment]
Are you unblocked now?

**Comment by ferrx** [comment]
Unblocked when using PhantomJS and html files as an entry point, yes. Definitely the "not detecting Chrome" issue is clarified and resolved.
