### ISSUE TITLE
Chutzpah tests trigger an endless discovery loop with CPS projects

### ISSUE THREAD

**Issue by AbhitejJohn** [mmanela/chutzpah#765]
Filed from [this](https://developercommunity.visualstudio.com/content/problem/639406/chutzpah-tests-added-to-projects-based-on-the-new.html) feedback issue. 

**Environment:** VS 2019 update 2 preview bits.

**Repro Steps:**
1. Create a new .Net Core Console application.
2. Add a .js file to the project.
3. Update its content to be the below:
```
function isEven(val) { 
    return val % 2 === 0; 
} 
  
test('TestMethodPass', function () {    
    ok(isEven(2), 'Two is an even number');    
    ok(!isEven(1), 'One is not an even number');         
}) 
  
test('TestMethodFail', function () {    
    ok(isEven(3));         
}) 
```
4. Open Test Explorer.

**Expected:**
2 tests are discovered.

**Observed:**
The test explorer does discover 2 tests but it endlessly performs discovery operations on the js file.

**Note:**
This is tied to the project being updated because of the temporary html file created during Chutzpah test discovery. This triggers a container changed event as part of every discovery which in turn triggers another discovery. 

**Workaround:**
Change the location of the temporary html file as stated in the linked feedback.

**Comment by djjohnjoseph** [comment]
Can this be reopened - I also get this issue. Disabling the Adapter is the only way to get rid of it.
