### ISSUE TITLE
10th test in spec seems to always fail

### ISSUE THREAD

**Issue by ferrx** [mmanela/chutzpah#766]
It seems like the 10th test in my spec fails consistently. I have replaced it with a simple jasmine test like `expect(1).toEqual(1)` and it still fails. Tests after that work fine.

Looking at the trace log, I see that something special occurs after the 9th test every time:

```
chutzpah.console.exe Information: 0 : Time:11:08:07.6439264; Thread:7; Message:Test Case Started:'Uploader:fake test'
**chutzpah.console.exe Information: 0 : Time:11:08:07.6518773; Thread:7; Message:Phantom Log - isTestingDone**
chutzpah.console.exe Information: 0 : Time:11:08:07.6618613; Thread:7; Message:File ******.spec.html, Test fake test failed
chutzpah.console.exe Information: 0 : Time:11:08:07.6783920; Thread:7; Message:Test Case Finished:'Uploader:fake test'
```

It seems like that `isTestingDone` may be corrupting the test that was just started.

The error I'm seeing:

```
Test 'Uploader:fake test' failed
        TypeError: undefined is not a constructor (evaluating '$("#testObj").validate') thrown
```

**Comment by mmanela** [comment]
That is odd, can you try with a different engine, not phantom and see if it goes away

**Comment by ferrx** [comment]
Strange that it was throwing that error after adding a certain amount of tests, but the underlying TypeError was that call to `validate` without including the jquery invalidate code within the test harness.
