### ISSUE TITLE
Set Arguments for Headless Chrome

### ISSUE THREAD

**Issue by foxable** [mmanela/chutzpah#775]
Since PhantomJS doesn't support ES6 features, I switched to Headless Chrome as testing engine. Since my tests are using AJAX requests, I need to disable CORS using the flag `--disable-web-security`. Unfortunately, the arguments defined in `BrowserArguments` are only passed when using the `/openInBrowser` switch and seem to be completely ignored for headless browsers. I think it would be useful if you could define arguments for headless browers as well, e.g. using the key `HeadlessChrome` or `JSDom` within `BrowserArguments`. An alternative would be to add a property like `Arguments` to the `EngineOptions` setting and pass them to the specified engine.

**Comment by mmanela** [comment]
Honestly, I think that flag should be passed by default always. I think that is what I did for Phantom, it may have just not been done in case of JSDom

**Comment by foxable** [comment]
This explains why the tests were running successfully in Phantom before running into problems with unsupported features. Actually, I patched my local `chutzpahRunner.js` for Chrome by adding the required flag. However, I would also need to patch the Visual Studio extension to run tests using the context menu. So setting the flag by default would help a lot.

**Comment by mmanela** [comment]
@foxable  Would you be interested in contributing the change?

**Comment by foxable** [comment]
Sure, I just created #776 which adds the required flag to the Chrome runner. If there are further changes needed just let me know.
