### ISSUE TITLE
Https-agent-proxy is vulnerable

### ISSUE THREAD

**Issue by antondats** [mmanela/chutzpah#779]
Hello!
The chutzpah uses some vulnerable https-agent-proxy package start from the 4.4.0 version. After some investigation, I have noticed that this package is used by other npm packages like "puppeteer" and "puppeteer-core"(chutzpah\Chutzpah\Node\packages and chutzpah\EdgeJsPackages). 
Please update the versions of these packages to make the chutzpah safe for using in projects. 

Thanks a lot)

**Comment by mmanela** [comment]
Should be fixed by b21cf9d581155e9926113a04be77078bb2f54346
