### ISSUE TITLE
Using a different engine with Chutzpah Test Adapter for the Test Explorer

### ISSUE THREAD

**Issue by JeffIDavies** [mmanela/chutzpah#788]
Is there any way to change the engine for the Test Adapter?  I am at present caught between a rock and a hard place.  My unit tests run fine using IE in debug mode and fine  in command mode using chutzpah.console.exe and the jsDom engine .  Unfortunately it fails when using 'run test' in Visual Studio and using phantomjs in command mode.  The script also works fine with a web page using Chrome browser.   Clearly a compatibility quirk.   I either need to somehow divine what is causing the problem that phantomjs is complaining about (it is an undefined object) or switch to a n engine that works.
Cheers
Jeff Davies

**Comment by mmanela** [comment]
You can customize the engine in your chutzpah.json file: https://github.com/mmanela/chutzpah/wiki/Browser-Engines

**Comment by JeffIDavies** [comment]
Hi Matthew

Thanks for that.  I had found the page before, but it wasn’t clear that it was for the chutzpah.json file.

I have run my tests from the command line using Chrome and JSDom and they work fine. They also work fine on our website.   However, they fail using Phantom.

I am experiencing a similar problem to one of your other users in that Visual Studio is not finding all my tests.  The ones that work with Phantom are fine, but the other tests appeared sporadically and now that I have changed the engine, they don’t appear at all.

It seems to me that the tests are parsed before they are displayed.  It seems that the parsing is failing silently and so the tests are not detected.  I wonder if the tests are being parsed by Phantom and failing which explains why they are not appearing in Visual Studio.

I have downloaded your code from GitHub and will have a go at debugging the problem when I find some time.

I have had trouble finding in code the messages appearing in the Output Window.  I guess they are stored away in a Resource File somewhere.

If you can give me any more guidance in tracking down the problem, I would appreciate it.  If I find a the problem, I am happy to post it back.

Thanks

Jeff Davies
