### ISSUE TITLE
ES6 syntax mixed in Js code fails chutzpah plugin to test

### ISSUE THREAD

**Issue by amanpreet-mymindinfotech** [mmanela/chutzpah#793]
Hi
I am using chutzpah with Qunit to test my js code in mvc project but it continuously fails for all tests which reference file containing es6 syntax like let/lambda etc.

I have tried Engine option but with that all test disappear from test explorer if I use option any other than Phantom.

My prime target is to test my js code in VS Test Explorer as well as CI/CD Pipeline.

**Comment by amanpreet-mymindinfotech** [comment]
I have also checked provided samples, but MVC related no sample is found.

**Comment by M0ns1gn0r** [comment]
In the default configuration, Chutzpah uses PhantomJS which doesn't support ES6. See https://github.com/mmanela/chutzpah/issues/618
