### ISSUE TITLE
Running Chutzpah on macOS from within VS Code?

### ISSUE THREAD

**Issue by ruffin--** [mmanela/chutzpah#796]
I've installed the Chutzpah Runner in VS Code on macOS, but I'm not sure how to tell it where the .exe lives -- or, more to the point, how to get a living .exe on my macOS box.

The settings seem to suggest Chutzpah is compatible with *NIX when it says `~/ChromeDevSession` may be used for the profile folder by default, but I wasn't able to figure out how to [install the nuget](https://www.nuget.org/packages/Chutzpah).

<img width="764" alt="chutzpahSettings" src="https://user-images.githubusercontent.com/5659878/108109135-81fd5780-705f-11eb-89f5-592e2c2aa905.png">

In my case, I'm just trying to edit the client-side code for an app with no csproj file. It doesn't look like (understandably) that nuget is happy with this situation -- that is, nuget seems to expect a csproj host [or equivalent].

```
projects/QuestionBuilder.Client $ dotnet add package Chutzpah --version 4.4.10
Could not find any project in `/Applications/projects/QuestionBuilder.Client/`.
```

Does Chutzpah run on macOS/Core? How would I install a copy to run outside of a csproj environment?

**NOTE:** Also posted on [the Chutzpah Runner repo](https://github.com/dfrencham/vscode-chutzpahrunner/issues/22) in case that's more appropriate.

**Comment by mmanela** [comment]
Chutzpah does not support anything but windows.

**Comment by ruffin--** [comment]
Just for fun, [here's a Chutzpah clone called khutzpa](https://github.com/ruffin--/khutzpa#vs-code-usage-with-chutzpah-runner) [that I wrote] that runs on macOS and essentially works with [Frencham](https://marketplace.visualstudio.com/publishers/dfrencham)'s [Chutzpah Runner](https://github.com/dfrencham/vscode-chutzpahrunner/issues/22).

I'm sure there are bugs, it's got a few rough edges (coverage with the VS Code Chutzpah Runner opens an extra browser tab/window atm & it can't only support one report at a time; you have kill a process to fire another), and it supports a pretty [stark subset of the full Chutzpah options so far](https://github.com/ruffin--/khutzpa#currently-supported-options), but not bad for a few weekends' of catch-as-catch-can spare time.

I haven't tested on Windows yet and suspect I'll have to set up a .bat file similar to the `macKhutzpa.sh` file I created for macOS. That is, right now Chutzpah Runner support is macOS only. Should have that fixed soon, though.

I've also updated the tools a little. Blanket has been replaced by Istanbul (via karma), which means coverage doesn't have [the PhantomJS issue](https://github.com/mmanela/chutzpah/issues/789) any more and can test modern code more easily.

I looked through the Chutzpah code a decent amount back in Feb/March. I was surprised to see how much of it was JS (not C#) and it was excellent! I thought about forking and gutting the tools, but after a while figured starting over in Node  would be easier. 

The Chutzpah.json file format is _very_ useful, which means my company's apps will move over easily and I have one less wheel to reinvent, which was a big help. The tool has worked very well for them for years, and I didn't want to rock the boat too much as we move away from an AngularJS heavy codebase [and need es6+ JavaScript testing support].

I'll try looking at stealing your Visual Studio Classic extension code once I get our builds swapped over (which use Chutzpah as part of the code's QA steps), which could take a little while. My code is also a[n almost] first-functioning mess right now. Don't look too closely. Need to refactor. A lot. It hurts me to look at it.

Anyhow, just fyi. If you're coding a project that relies on Chutzpah for testing & are using a Mac (or want to), you can now check tests and coverage. Bug reports more than welcome!

**Comment by mmanela** [comment]
@ruffin--  Super cool! Love seeing working around the nightmare of our old dependencies :)
