### ISSUE TITLE
Unable to build Chutzpah

### ISSUE THREAD

**Issue by ruffin--** [mmanela/chutzpah#801]
Cloned. Opened in Visual Studio 2019. F6.

```
Build started...
NuGet Package restore failed for project VS.Common: Unable to find version '9.0.4' of package 'VSSDK.IDE.9'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'VSSDK.IDE.9.9.0.4' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: 
  https://api.nuget.org/v3/index.json: 
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project VS.Common: Unable to find version '7.0.4' of package 'VSSDK.IDE'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'VSSDK.IDE.7.0.4' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: 
  https://api.nuget.org/v3/index.json: 
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project VS.Common: Unable to find version '8.0.4' of package 'VSSDK.IDE.8'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'VSSDK.IDE.8.8.0.4' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: 
  https://api.nuget.org/v3/index.json: 
. Please see Error List window for detailed warnings and errors
```

Etc, etc.

I've tried a few methods of debugging, including installing the nuget cli and trying `nuget restore -NoCache -NonInteractive .\Chutzpah.VS.sln`, but no dice yet; same error appears.

Is there something obvious that I'm doing incorrectly? Are these dated nuget packages that shouldn't be available now? Should those references be updated? I do have Visual Studio extension development installed in VS 2019. Is there something similar that needs installing?

**Comment by icnocop** [comment]
https://github.com/mmanela/chutzpah#building-the-code

> Building the code
> 
>     1. Clone the repo
>     2. One time run .\build.bat install - This will install all dependencies
>     3. Run .\build - This will build all the code and run tests.
>     4. Open solution Chutzpah.NoVS.sln for normal changes

**Comment by mmanela** [comment]
@ruffin--  Let me know if that helps

**Comment by F-Forget** [comment]
I tried building using @icnocop link, which is the official link for how to build the code. No luck. .bu/ild.bat resulted in this error : 

```
Import-Module : The specified module 'D:\Projects\chutzpah\packages\psake.4.6.0\Tools\psake.psm1' was not loaded
because no valid module file was found in any module directory.
```

When looking at the files, there's indeed to file named like this...

Could we get any help @mmanela?

**Comment by iprak** [comment]
The build command is case sensitive .. try `build Install`.
